ALTER TABLE IF EXISTS ONLY public."SNFClaims" DROP CONSTRAINT IF EXISTS "SNFClaims_beneficiaryId_to_Beneficiaries";
ALTER TABLE IF EXISTS ONLY public."SNFClaimLines" DROP CONSTRAINT IF EXISTS "SNFClaimLines_parentClaim_to_SNFClaims";
ALTER TABLE IF EXISTS ONLY public."PartDEvents" DROP CONSTRAINT IF EXISTS "PartDEvents_beneficiaryId_to_Beneficiaries";
ALTER TABLE IF EXISTS ONLY public."OutpatientClaims" DROP CONSTRAINT IF EXISTS "OutpatientClaims_beneficiaryId_to_Beneficiaries";
ALTER TABLE IF EXISTS ONLY public."OutpatientClaimLines" DROP CONSTRAINT IF EXISTS "OutpatientClaimLines_parentClaim_to_OutpatientClaims";
ALTER TABLE IF EXISTS ONLY public."MedicareBeneficiaryIdHistory" DROP CONSTRAINT IF EXISTS "MedicareBeneficiaryIdHistory_beneficiaryId_to_Beneficiary";
ALTER TABLE IF EXISTS ONLY public."InpatientClaims" DROP CONSTRAINT IF EXISTS "InpatientClaims_beneficiaryId_to_Beneficiaries";
ALTER TABLE IF EXISTS ONLY public."InpatientClaimLines" DROP CONSTRAINT IF EXISTS "InpatientClaimLines_parentClaim_to_InpatientClaims";
ALTER TABLE IF EXISTS ONLY public."HospiceClaims" DROP CONSTRAINT IF EXISTS "HospiceClaims_beneficiaryId_to_Beneficiaries";
ALTER TABLE IF EXISTS ONLY public."HospiceClaimLines" DROP CONSTRAINT IF EXISTS "HospiceClaimLines_parentClaim_to_HospiceClaims";
ALTER TABLE IF EXISTS ONLY public."HHAClaims" DROP CONSTRAINT IF EXISTS "HHAClaims_beneficiaryId_to_Beneficiaries";
ALTER TABLE IF EXISTS ONLY public."HHAClaimLines" DROP CONSTRAINT IF EXISTS "HHAClaimLines_parentClaim_to_HHAClaims";
ALTER TABLE IF EXISTS ONLY public."DMEClaims" DROP CONSTRAINT IF EXISTS "DMEClaims_beneficiaryId_to_Beneficiaries";
ALTER TABLE IF EXISTS ONLY public."DMEClaimLines" DROP CONSTRAINT IF EXISTS "DMEClaimLines_parentClaim_to_DMEClaims";
ALTER TABLE IF EXISTS ONLY public."CarrierClaims" DROP CONSTRAINT IF EXISTS "CarrierClaims_beneficiaryId_to_Beneficiaries";
ALTER TABLE IF EXISTS ONLY public."CarrierClaimLines" DROP CONSTRAINT IF EXISTS "CarrierClaimLines_parentClaim_to_CarrierClaims";
ALTER TABLE IF EXISTS ONLY public."BeneficiariesHistory" DROP CONSTRAINT IF EXISTS "BeneficiariesHistory_beneficiaryId_to_Beneficiary";
DROP INDEX IF EXISTS public.schema_version_s_idx;
DROP INDEX IF EXISTS public."SNFClaims_beneficiaryId_idx";
DROP INDEX IF EXISTS public."PartDEvents_beneficiaryId_idx";
DROP INDEX IF EXISTS public."OutpatientClaims_beneficiaryId_idx";
DROP INDEX IF EXISTS public."MedicareBeneficiaryIdHistory_beneficiaryId_idx";
DROP INDEX IF EXISTS public."InpatientClaims_beneficiaryId_idx";
DROP INDEX IF EXISTS public."HospiceClaims_beneficiaryId_idx";
DROP INDEX IF EXISTS public."HHAClaims_beneficiaryId_idx";
DROP INDEX IF EXISTS public."DMEClaims_beneficiaryId_idx";
DROP INDEX IF EXISTS public."CarrierClaims_beneficiaryId_idx";
DROP INDEX IF EXISTS public."Beneficiaries_hicn_idx";
DROP INDEX IF EXISTS public."BeneficiariesHistory_hicn_idx_old";
DROP INDEX IF EXISTS public."BeneficiariesHistory_hicn_idx";
DROP INDEX IF EXISTS public."BeneficiariesHistory_beneficiaryId_idx";
ALTER TABLE IF EXISTS ONLY public.schema_version DROP CONSTRAINT IF EXISTS schema_version_pk;
ALTER TABLE IF EXISTS ONLY public."SNFClaims" DROP CONSTRAINT IF EXISTS "SNFClaims_pkey";
ALTER TABLE IF EXISTS ONLY public."SNFClaimLines" DROP CONSTRAINT IF EXISTS "SNFClaimLines_pkey";
ALTER TABLE IF EXISTS ONLY public."PartDEvents" DROP CONSTRAINT IF EXISTS "PartDEvents_pkey";
ALTER TABLE IF EXISTS ONLY public."OutpatientClaims" DROP CONSTRAINT IF EXISTS "OutpatientClaims_pkey";
ALTER TABLE IF EXISTS ONLY public."OutpatientClaimLines" DROP CONSTRAINT IF EXISTS "OutpatientClaimLines_pkey";
ALTER TABLE IF EXISTS ONLY public."MedicareBeneficiaryIdHistory" DROP CONSTRAINT IF EXISTS "MedicareBeneficiaryIdHistory_pkey";
ALTER TABLE IF EXISTS ONLY public."MedicareBeneficiaryIdHistoryInvalidBeneficiaries" DROP CONSTRAINT IF EXISTS "MedicareBeneficiaryIdHistoryInvalidBeneficiaries_pkey";
ALTER TABLE IF EXISTS ONLY public."InpatientClaims" DROP CONSTRAINT IF EXISTS "InpatientClaims_pkey";
ALTER TABLE IF EXISTS ONLY public."InpatientClaimLines" DROP CONSTRAINT IF EXISTS "InpatientClaimLines_pkey";
ALTER TABLE IF EXISTS ONLY public."HospiceClaims" DROP CONSTRAINT IF EXISTS "HospiceClaims_pkey";
ALTER TABLE IF EXISTS ONLY public."HospiceClaimLines" DROP CONSTRAINT IF EXISTS "HospiceClaimLines_pkey";
ALTER TABLE IF EXISTS ONLY public."HHAClaims" DROP CONSTRAINT IF EXISTS "HHAClaims_pkey";
ALTER TABLE IF EXISTS ONLY public."HHAClaimLines" DROP CONSTRAINT IF EXISTS "HHAClaimLines_pkey";
ALTER TABLE IF EXISTS ONLY public."DMEClaims" DROP CONSTRAINT IF EXISTS "DMEClaims_pkey";
ALTER TABLE IF EXISTS ONLY public."DMEClaimLines" DROP CONSTRAINT IF EXISTS "DMEClaimLines_pkey";
ALTER TABLE IF EXISTS ONLY public."CarrierClaims" DROP CONSTRAINT IF EXISTS "CarrierClaims_pkey";
ALTER TABLE IF EXISTS ONLY public."CarrierClaimLines" DROP CONSTRAINT IF EXISTS "CarrierClaimLines_pkey";
ALTER TABLE IF EXISTS ONLY public."Beneficiaries" DROP CONSTRAINT IF EXISTS "Beneficiaries_pkey";
ALTER TABLE IF EXISTS ONLY public."BeneficiariesHistory_old" DROP CONSTRAINT IF EXISTS "BeneficiariesHistory_pkey_old";
ALTER TABLE IF EXISTS ONLY public."BeneficiariesHistory" DROP CONSTRAINT IF EXISTS "BeneficiariesHistory_pkey";
ALTER TABLE IF EXISTS ONLY public."BeneficiariesHistoryInvalidBeneficiaries" DROP CONSTRAINT IF EXISTS "BeneficiariesHistoryInvalidBeneficiaries_pkey";
DROP TABLE IF EXISTS public.schema_version;
DROP SEQUENCE IF EXISTS public.beneficiaryhistorytemp_beneficiaryhistoryid_seq;
DROP SEQUENCE IF EXISTS public.beneficiaryhistory_beneficiaryhistoryid_seq;
DROP TABLE IF EXISTS public."SNFClaims";
DROP TABLE IF EXISTS public."SNFClaimLines";
DROP TABLE IF EXISTS public."PartDEvents";
DROP TABLE IF EXISTS public."OutpatientClaims";
DROP TABLE IF EXISTS public."OutpatientClaimLines";
DROP TABLE IF EXISTS public."MedicareBeneficiaryIdHistoryInvalidBeneficiaries";
DROP TABLE IF EXISTS public."MedicareBeneficiaryIdHistory";
DROP TABLE IF EXISTS public."InpatientClaims";
DROP TABLE IF EXISTS public."InpatientClaimLines";
DROP TABLE IF EXISTS public."HospiceClaims";
DROP TABLE IF EXISTS public."HospiceClaimLines";
DROP TABLE IF EXISTS public."HHAClaims";
DROP TABLE IF EXISTS public."HHAClaimLines";
DROP TABLE IF EXISTS public."DMEClaims";
DROP TABLE IF EXISTS public."DMEClaimLines";
DROP TABLE IF EXISTS public."CarrierClaims";
DROP TABLE IF EXISTS public."CarrierClaimLines";
DROP TABLE IF EXISTS public."BeneficiariesHistory_old";
DROP TABLE IF EXISTS public."BeneficiariesHistoryInvalidBeneficiaries";
DROP TABLE IF EXISTS public."BeneficiariesHistory";
DROP TABLE IF EXISTS public."Beneficiaries";
DROP EXTENSION IF EXISTS plpgsql;
DROP SCHEMA IF EXISTS public;
