#!/usr/bin/env groovy

// These variables are accessible throughout this file (except inside methods and classes).
def verboseMaven
if (params.verbose_mvn_logging != null) {
    verboseMaven = params.verbose_mvn_logging
} else {
    verboseMaven = false
}

pipeline {
    agent {
        kubernetes {
            defaultContainer 'bfd-cbc-build'
            yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccount: bfd
  volumes:
  - name: docker-socket
    emptyDir: {}
  containers:
  - name: docker-daemon
    image: docker:20.10-dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    resources:
      requests:
        memory: '8192Mi'
        cpu: '4000m'
      limits:
        memory: '8192Mi'
        cpu: '4000m'
  - name: bfd-cbc-build
    image: 'public.ecr.aws/c2o1d8s9/bfd-cbc-build:jdk17-mvn3-tfenv3-latest'
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    command:
    - cat
    tty: true
    imagePullPolicy: Always
    resources:
      requests:
        memory: '8192Mi'
        cpu: '4000m'
      limits:
        memory: '8192Mi'
        cpu: '4000m'
"""
        }
    }
    parameters {
        booleanParam(name: 'verbose_mvn_logging',
        description: 'When true, `mvn` will produce verbose logs.',
        defaultValue: false)
    }
    environment {
        SONAR_TOKEN = credentials('svc-sonar-bfd')
        SONAR_PROJECT_KEY = 'bfd-parent'
        SONAR_HOST_URL = 'https://sonarqube.cloud.cms.gov'
    }
    stages {
        stage('Build Stage') {
            // Build Step
         steps {
                script {
                   // Load the child Jenkinsfiles.
                   scriptForApps = load('apps/build.groovy')
                   //Authentication of AWS to run Build.groovy
                   awsAuth.assumeRole()
                   // Perform Build steps
                   scriptForApps.build(verboseMaven, true)
                }
            }
        }
        stage ('SonarQube Analysis') {
            steps {
                script {
                    dir ('apps') {
                        sh "mvn sonar:sonar" +
                        " -Dsonar.projectKey=${SONAR_PROJECT_KEY}" +
                        " -Dsonar.host.url=${SONAR_HOST_URL}" +
                        " -Dsonar.login=${SONAR_TOKEN}" +
                        " -Dmaven.build.cache.enabled=false" +
                        " -DskipITs" +
                        " -DskipTests" +
                        " -Dsonar.exclusions='*.java'" +
                        " -Dsonar.coverage.jacoco.xmlReportPaths=target/coverage-reports/jacoco-it/jacoco.xml,target/coverage-reports/jacoco-ut/jacoco.xml"
			" -Dsonar.sources=/home/jenkins/agent/workspace/bfd-jenkins-sonarqube_master/apps/bfd-ops/pom.xml,/home/jenkins/agent/workspace/bfd-jenkins-sonarqube_master/apps/bfd-ops/ccs-ops-misc/**/*"
                    }
                }
            }
        }
    }
}
