
repos:
  #
  # pre-commit hooks
  #
- repo: local
  hooks:
    - id: pre-commit-check-sop-files-script
      name: Pre-commit Check SOP Files Script
      entry: ./.github/scripts/pre-commit-check-sop-files.sh
      language: script
      stages: [ pre-commit ]
      verbose: true
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
    - id: shellcheck
      args: ['-e', 'SC1071,SC2239', '-S', 'warning']
      stages: [ pre-commit ]
      verbose: true
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
    - id: gitleaks
      stages: [ pre-commit ]

  #
  # pre-push hooks
  #
- repo: local
  hooks:
    - id: pre-push-check-java-format
      stages: [ pre-push ]
      name: Pre-push Check Java Format
      entry: mvn -f apps/ com.spotify.fmt:fmt-maven-plugin:check
      language: system
      files: '\.java$'
      pass_filenames: false
      verbose: true
