
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
        stages: [ pre-push ]
        verbose: true
      # Run the formatter.
      - id: ruff-format
        stages: [ pre-push ]
        verbose: true
  - repo: local
    hooks:
      - id: run-uv-pyright
        name: UV Run Pyright
        stages: [ pre-push ]
        entry: uv run pyright
        language: system
        verbose: true
