/*
 * Table to hold known MBI and their hashed equivalents.
 */
CREATE TABLE "pre_adj"."MbiCache" (
    "mbiId"       bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "mbi"         VARCHAR(11) NOT NULL,
    "hash"        VARCHAR(64) NOT NULL,
    "oldHash"     VARCHAR(64),
    "lastUpdated" timestamp with time zone
);

/*
 * We need these indexes to support queries by mbi, hash, and oldHash.
 */
CREATE UNIQUE INDEX "MbiCache_mbi_idx" on "pre_adj"."MbiCache"("mbi");
CREATE UNIQUE INDEX "MbiCache_hash_idx" on "pre_adj"."MbiCache"("hash");
CREATE INDEX "MbiCache_oldHash_idx" on "pre_adj"."MbiCache"("oldHash");

/*
 * Add foreign key to reference MbiCache in claims tables.
 */
ALTER TABLE "pre_adj"."FissClaims"
    ADD "mbiId" bigint;
ALTER TABLE "pre_adj"."FissClaims"
    ADD CONSTRAINT "FK_FissClaims_mbiId" FOREIGN KEY ("mbiId") REFERENCES "pre_adj"."MbiCache"("mbiId");

ALTER TABLE "pre_adj"."McsClaims"
    ADD "mbiId" bigint;
ALTER TABLE "pre_adj"."McsClaims"
    ADD CONSTRAINT "FK_McsClaims_mbiId" FOREIGN KEY ("mbiId") REFERENCES "pre_adj"."MbiCache"("mbiId");

/*
 * We need these indexes to efficiently find claims using join from MbiCache.
 */
CREATE INDEX "FissClaims_mbiId_idx" on "pre_adj"."FissClaims"("mbiId");
CREATE INDEX "McsClaims_mbiId_idx" on "pre_adj"."McsClaims"("mbiId");
