/*
 * NOTE: This migration will fail if there are any claims in the FissClaims or McsClaims tables.
 */

/*
 * Table to hold known MBI and their hashed equivalents.
 */
CREATE TABLE "pre_adj"."MbiCache" (
    "mbiId"   bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "mbi"     VARCHAR(13) NOT NULL,
    "hash"    VARCHAR(64) NOT NULL,
    "oldHash" VARCHAR(64),
    "lastUpdated" timestamp with time zone
);

/*
 * We need these indexes to support queries by mbi, hash, and oldHash.  Note that oldHash
 * is usually null (only set to a value during hash rotation) so the index cannot be unique.
 */
CREATE UNIQUE INDEX "MbiCache_mbi_idx" on "pre_adj"."MbiCache"("mbi");
CREATE UNIQUE INDEX "MbiCache_hash_idx" on "pre_adj"."MbiCache"("hash");
CREATE INDEX "MbiCache_oldHash_idx" on "pre_adj"."MbiCache"("oldHash");

/*
 * Migrate all existing MBI values into the MbiCache table.
 */
INSERT INTO "pre_adj"."MbiCache"("mbi", "hash", "lastUpdated")
SELECT "mbi", "mbiHash" as "hash", CURRENT_TIMESTAMP as "lastUpdated"
FROM (
    SELECT DISTINCT "mbi", "mbiHash"
    FROM "pre_adj"."FissClaims"
    UNION
    SELECT DISTINCT "idrClaimMbi" AS "mbi", "idrClaimMbiHash" AS "mbiHash"
    FROM "pre_adj"."McsClaims"
) x
WHERE "mbi" IS NOT NULL AND "mbiHash" IS NOT NULL;

/*
 * Replace the mbi and mbiHash columns in FissClaims with a mbiId foreign key column.
 */
ALTER TABLE "pre_adj"."FissClaims"
    ADD "mbiId" bigint;
ALTER TABLE "pre_adj"."FissClaims"
    ADD CONSTRAINT "FK_FissClaims_mbiId" FOREIGN KEY ("mbiId") REFERENCES "pre_adj"."MbiCache"("mbiId");
UPDATE "pre_adj"."FissClaims"
SET "mbiId"=(SELECT "mbiId" FROM "pre_adj"."MbiCache" WHERE "hash" = "mbiHash");
ALTER TABLE "pre_adj"."FissClaims" DROP "mbi";
ALTER TABLE "pre_adj"."FissClaims" DROP "mbiHash";

/*
 * Replace the idrClaimMbi and idrClaimMbiHash columns in FissClaims with a mbiId foreign key column.
 */
ALTER TABLE "pre_adj"."McsClaims"
    ADD "mbiId" bigint;
ALTER TABLE "pre_adj"."McsClaims"
    ADD CONSTRAINT "FK_McsClaims_mbiId" FOREIGN KEY ("mbiId") REFERENCES "pre_adj"."MbiCache"("mbiId");

UPDATE "pre_adj"."McsClaims"
SET "mbiId"=(SELECT "mbiId" FROM "pre_adj"."MbiCache" WHERE "hash" = "idrClaimMbiHash");

ALTER TABLE "pre_adj"."McsClaims" DROP "idrClaimMbi";
ALTER TABLE "pre_adj"."McsClaims" DROP "idrClaimMbiHash";

/*
 * We need these indexes to efficiently find claims using join from MbiCache.
 */
CREATE INDEX "FissClaims_mbiId_idx" on "pre_adj"."FissClaims"("mbiId");
CREATE INDEX "McsClaims_mbiId_idx" on "pre_adj"."McsClaims"("mbiId");
