-- NEW_SCHEMA_SNF_CLAIMS_FIX.SQL
-- flyway migration for SNF_CLAIMS_NEW and SNF_CLAIM_LINES_NEW tables into
-- a new schema structure; previus flyway script, V63__nw_schema_snf_claims.sql
-- whcich erroneously defined columns in the snf_claim_lines_new table
-- as an integer. This script fixes that mistake and does a complete data
-- migration of SNF claims data because the _new tables would have missed
-- a weekend's ETL propcessing.
--
-- Once current table data is migrated to new table name/structtre,
-- a subsequent PR will be deployed that changes the ORM model(s)
-- for SNF table(s).

-- truncate _new SNF claims tables in order to reload
${logic.hsql-only}  TRUNCATE table snf_claim_lines_new;
${logic.hsql-only}  TRUNCATE table snf_claims_new;
${logic.psql-only}  TRUNCATE snf_claim_lines_new, snf_claims_new;

-- fix the columns that were erroneously defined
-- Values from Excel spreadsheet are:
-- carrier_claims table:
--     CLM_UTLZTN_DAY_CNT           NUM  *   *
--     BENE_TOT_COINSRNC_DAYS_CNT   NUM  *   *
--     CLM_NON_UTLZTN_DAYS_CNT      NUM  *   *
--     NCH_BLOOD_PNTS_FRNSHD_QTY    NUM  *   *
--
alter table snf_claims_new 
    alter column CLM_UTLZTN_DAY_CNT           ${logic.alter-column-type} numeric;
alter table snf_claims_new 
    alter column BENE_TOT_COINSRNC_DAYS_CNT   ${logic.alter-column-type} numeric;
alter table snf_claims_new 
    alter column CLM_NON_UTLZTN_DAYS_CNT      ${logic.alter-column-type} numeric;
alter table snf_claims_new 
    alter column NCH_BLOOD_PNTS_FRNSHD_QTY    ${logic.alter-column-type} numeric;

-- carrier_claim_lines table:
--     REV_CNTR_UNIT_CNT            NUM  *   *
--     REV_CNTR_NDC_QTY             NUM  *   *
--
alter table snf_claim_lines_new 
    alter column REV_CNTR_UNIT_CNT  ${logic.alter-column-type} numeric;
alter table snf_claim_lines_new     
    alter column REV_CNTR_NDC_QTY   ${logic.alter-column-type} numeric;

-- (re-) migrate snf_claims data to the snf_claims_new table.
insert into public.snf_claims_new (
                    clm_id,
                    bene_id,
                    clm_grp_id,
                    last_updated,
                    clm_from_dt,
                    clm_thru_dt,
                    claim_query_code,
                    clm_admsn_dt,
                    clm_fac_type_cd,
                    clm_freq_cd,
                    clm_ip_admsn_type_cd,
                    clm_non_utlztn_days_cnt,
                    clm_utlztn_day_cnt,
                    bene_tot_coinsrnc_days_cnt,
                    clm_srvc_clsfctn_type_cd,
                    final_action,
                    clm_tot_chrg_amt,
                    clm_pmt_amt,
                    clm_pps_ind_cd,
                    clm_pps_cptl_dsprprtnt_shr_amt,
                    clm_pps_cptl_excptn_amt,
                    clm_pps_cptl_fsp_amt,
                    clm_pps_cptl_ime_amt,
                    clm_pps_cptl_outlier_amt,
                    clm_pps_old_cptl_hld_hrmls_amt,
                    nch_clm_type_cd,
                    nch_near_line_rec_ident_cd,
                    nch_wkly_proc_dt,
                    nch_blood_pnts_frnshd_qty,
                    nch_prmry_pyr_cd,
                    nch_prmry_pyr_clm_pd_amt,
                    nch_bene_blood_ddctbl_lblty_am,
                    nch_bene_ip_ddctbl_amt,
                    nch_bene_pta_coinsrnc_lblty_am,
                    nch_ip_ncvrd_chrg_amt,
                    nch_ip_tot_ddctn_amt,
                    nch_vrfd_ncvrd_stay_from_dt,
                    nch_vrfd_ncvrd_stay_thru_dt,
                    nch_qlfyd_stay_from_dt,
                    nch_qlfyd_stay_thru_dt,
                    nch_actv_or_cvrd_lvl_care_thru,
                    nch_bene_dschrg_dt,
                    nch_bene_mdcr_bnfts_exhtd_dt_i,
                    nch_ptnt_status_ind_cd,
                    clm_drg_cd,
                    clm_mco_pd_sw,
                    clm_mdcr_non_pmt_rsn_cd,
                    clm_src_ip_admsn_cd,
                    admtg_dgns_cd,
                    admtg_dgns_vrsn_cd,
                    at_physn_npi,
                    at_physn_upin,
                    op_physn_npi,
                    op_physn_upin,
                    org_npi_num,
                    ot_physn_npi,
                    ot_physn_upin,
                    prncpal_dgns_cd,
                    prncpal_dgns_vrsn_cd,
                    prvdr_num,
                    prvdr_state_cd,
                    ptnt_dschrg_stus_cd,
                    fi_clm_actn_cd,
                    fi_clm_proc_dt,
                    fi_doc_clm_cntl_num,
                    fi_num,
                    fi_orig_clm_cntl_num,
                    fst_dgns_e_cd,
                    fst_dgns_e_vrsn_cd,
                    icd_dgns_cd1,
                    icd_dgns_cd2,
                    icd_dgns_cd3,
                    icd_dgns_cd4,
                    icd_dgns_cd5,
                    icd_dgns_cd6,
                    icd_dgns_cd7,
                    icd_dgns_cd8,
                    icd_dgns_cd9,
                    icd_dgns_cd10,
                    icd_dgns_cd11,
                    icd_dgns_cd12,
                    icd_dgns_cd13,
                    icd_dgns_cd14,
                    icd_dgns_cd15,
                    icd_dgns_cd16,
                    icd_dgns_cd17,
                    icd_dgns_cd18,
                    icd_dgns_cd19,
                    icd_dgns_cd20,
                    icd_dgns_cd21,
                    icd_dgns_cd22,
                    icd_dgns_cd23,
                    icd_dgns_cd24,
                    icd_dgns_cd25,
                    icd_dgns_e_cd1,
                    icd_dgns_e_cd2,
                    icd_dgns_e_cd3,
                    icd_dgns_e_cd4,
                    icd_dgns_e_cd5,
                    icd_dgns_e_cd6,
                    icd_dgns_e_cd7,
                    icd_dgns_e_cd8,
                    icd_dgns_e_cd9,
                    icd_dgns_e_cd10,
                    icd_dgns_e_cd11,
                    icd_dgns_e_cd12,
                    icd_dgns_e_vrsn_cd1,
                    icd_dgns_e_vrsn_cd2,
                    icd_dgns_e_vrsn_cd3,
                    icd_dgns_e_vrsn_cd4,
                    icd_dgns_e_vrsn_cd5,
                    icd_dgns_e_vrsn_cd6,
                    icd_dgns_e_vrsn_cd7,
                    icd_dgns_e_vrsn_cd8,
                    icd_dgns_e_vrsn_cd9,
                    icd_dgns_e_vrsn_cd10,
                    icd_dgns_e_vrsn_cd11,
                    icd_dgns_e_vrsn_cd12,
                    icd_dgns_vrsn_cd1,
                    icd_dgns_vrsn_cd2,
                    icd_dgns_vrsn_cd3,
                    icd_dgns_vrsn_cd4,
                    icd_dgns_vrsn_cd5,
                    icd_dgns_vrsn_cd6,
                    icd_dgns_vrsn_cd7,
                    icd_dgns_vrsn_cd8,
                    icd_dgns_vrsn_cd9,
                    icd_dgns_vrsn_cd10,
                    icd_dgns_vrsn_cd11,
                    icd_dgns_vrsn_cd12,
                    icd_dgns_vrsn_cd13,
                    icd_dgns_vrsn_cd14,
                    icd_dgns_vrsn_cd15,
                    icd_dgns_vrsn_cd16,
                    icd_dgns_vrsn_cd17,
                    icd_dgns_vrsn_cd18,
                    icd_dgns_vrsn_cd19,
                    icd_dgns_vrsn_cd20,
                    icd_dgns_vrsn_cd21,
                    icd_dgns_vrsn_cd22,
                    icd_dgns_vrsn_cd23,
                    icd_dgns_vrsn_cd24,
                    icd_dgns_vrsn_cd25,
                    icd_prcdr_cd1,
                    icd_prcdr_cd2,
                    icd_prcdr_cd3,
                    icd_prcdr_cd4,
                    icd_prcdr_cd5,
                    icd_prcdr_cd6,
                    icd_prcdr_cd7,
                    icd_prcdr_cd8,
                    icd_prcdr_cd9,
                    icd_prcdr_cd10,
                    icd_prcdr_cd11,
                    icd_prcdr_cd12,
                    icd_prcdr_cd13,
                    icd_prcdr_cd14,
                    icd_prcdr_cd15,
                    icd_prcdr_cd16,
                    icd_prcdr_cd17,
                    icd_prcdr_cd18,
                    icd_prcdr_cd19,
                    icd_prcdr_cd20,
                    icd_prcdr_cd21,
                    icd_prcdr_cd22,
                    icd_prcdr_cd23,
                    icd_prcdr_cd24,
                    icd_prcdr_cd25,
                    icd_prcdr_vrsn_cd1,
                    icd_prcdr_vrsn_cd2,
                    icd_prcdr_vrsn_cd3,
                    icd_prcdr_vrsn_cd4,
                    icd_prcdr_vrsn_cd5,
                    icd_prcdr_vrsn_cd6,
                    icd_prcdr_vrsn_cd7,
                    icd_prcdr_vrsn_cd8,
                    icd_prcdr_vrsn_cd9,
                    icd_prcdr_vrsn_cd10,
                    icd_prcdr_vrsn_cd11,
                    icd_prcdr_vrsn_cd12,
                    icd_prcdr_vrsn_cd13,
                    icd_prcdr_vrsn_cd14,
                    icd_prcdr_vrsn_cd15,
                    icd_prcdr_vrsn_cd16,
                    icd_prcdr_vrsn_cd17,
                    icd_prcdr_vrsn_cd18,
                    icd_prcdr_vrsn_cd19,
                    icd_prcdr_vrsn_cd20,
                    icd_prcdr_vrsn_cd21,
                    icd_prcdr_vrsn_cd22,
                    icd_prcdr_vrsn_cd23,
                    icd_prcdr_vrsn_cd24,
                    icd_prcdr_vrsn_cd25,
                    prcdr_dt1,
                    prcdr_dt2,
                    prcdr_dt3,
                    prcdr_dt4,
                    prcdr_dt5,
                    prcdr_dt6,
                    prcdr_dt7,
                    prcdr_dt8,
                    prcdr_dt9,
                    prcdr_dt10,
                    prcdr_dt11,
                    prcdr_dt12,
                    prcdr_dt13,
                    prcdr_dt14,
                    prcdr_dt15,
                    prcdr_dt16,
                    prcdr_dt17,
                    prcdr_dt18,
                    prcdr_dt19,
                    prcdr_dt20,
                    prcdr_dt21,
                    prcdr_dt22,
                    prcdr_dt23,
                    prcdr_dt24,
                    prcdr_dt25 )
select
${logic.psql-only}  cast(clm_id as bigint),
${logic.psql-only}  cast(bene_id as bigint),
${logic.psql-only}  cast(clm_grp_id as bigint),  
${logic.hsql-only}  convert(clm_id, SQL_BIGINT),
${logic.hsql-only}  convert(bene_id, SQL_BIGINT),
${logic.hsql-only}  convert(clm_grp_id, SQL_BIGINT),
                    last_updated,
                    clm_from_dt,
                    clm_thru_dt,
                    claim_query_code,
                    clm_admsn_dt,
                    clm_fac_type_cd,
                    clm_freq_cd,
                    clm_ip_admsn_type_cd,
                    clm_non_utlztn_days_cnt,
                    clm_utlztn_day_cnt,
                    bene_tot_coinsrnc_days_cnt,
                    clm_srvc_clsfctn_type_cd,
                    final_action,
                    clm_tot_chrg_amt,
                    clm_pmt_amt,
                    clm_pps_ind_cd,
                    clm_pps_cptl_dsprprtnt_shr_amt,
                    clm_pps_cptl_excptn_amt,
                    clm_pps_cptl_fsp_amt,    
                    clm_pps_cptl_ime_amt,
                    clm_pps_cptl_outlier_amt,
                    clm_pps_old_cptl_hld_hrmls_amt,    
                    nch_clm_type_cd,
                    nch_near_line_rec_ident_cd,
                    nch_wkly_proc_dt,
                    nch_blood_pnts_frnshd_qty,
                    nch_prmry_pyr_cd,
                    nch_prmry_pyr_clm_pd_amt,
                    nch_bene_blood_ddctbl_lblty_am,
                    nch_bene_ip_ddctbl_amt,
                    nch_bene_pta_coinsrnc_lblty_am,
                    nch_ip_ncvrd_chrg_amt,
                    nch_ip_tot_ddctn_amt,
                    nch_vrfd_ncvrd_stay_from_dt,
                    nch_vrfd_ncvrd_stay_thru_dt,
                    nch_qlfyd_stay_from_dt,
                    nch_qlfyd_stay_thru_dt,
                    nch_actv_or_cvrd_lvl_care_thru,
                    nch_bene_dschrg_dt,
                    nch_bene_mdcr_bnfts_exhtd_dt_i,
                    nch_ptnt_status_ind_cd,
                    clm_drg_cd,
                    clm_mco_pd_sw,
                    clm_mdcr_non_pmt_rsn_cd,
                    clm_src_ip_admsn_cd,
                    admtg_dgns_cd,
                    admtg_dgns_vrsn_cd,
                    at_physn_npi,
                    at_physn_upin,
                    op_physn_npi,
                    op_physn_upin,
                    org_npi_num,
                    ot_physn_npi,
                    ot_physn_upin,
                    prncpal_dgns_cd,
                    prncpal_dgns_vrsn_cd,
                    prvdr_num,
                    prvdr_state_cd,
                    ptnt_dschrg_stus_cd,
                    fi_clm_actn_cd,
                    fi_clm_proc_dt,
                    fi_doc_clm_cntl_num,
                    fi_num,
                    fi_orig_clm_cntl_num,
                    fst_dgns_e_cd,
                    fst_dgns_e_vrsn_cd,
                    icd_dgns_cd1,
                    icd_dgns_cd2,
                    icd_dgns_cd3,
                    icd_dgns_cd4,
                    icd_dgns_cd5,
                    icd_dgns_cd6,
                    icd_dgns_cd7,
                    icd_dgns_cd8,
                    icd_dgns_cd9,
                    icd_dgns_cd10,
                    icd_dgns_cd11,
                    icd_dgns_cd12,
                    icd_dgns_cd13,
                    icd_dgns_cd14,
                    icd_dgns_cd15,
                    icd_dgns_cd16,
                    icd_dgns_cd17,
                    icd_dgns_cd18,
                    icd_dgns_cd19,
                    icd_dgns_cd20,
                    icd_dgns_cd21,
                    icd_dgns_cd22,
                    icd_dgns_cd23,
                    icd_dgns_cd24,
                    icd_dgns_cd25,
                    icd_dgns_e_cd1,
                    icd_dgns_e_cd2,
                    icd_dgns_e_cd3,
                    icd_dgns_e_cd4,
                    icd_dgns_e_cd5,
                    icd_dgns_e_cd6,
                    icd_dgns_e_cd7,
                    icd_dgns_e_cd8,
                    icd_dgns_e_cd9,
                    icd_dgns_e_cd10,
                    icd_dgns_e_cd11,
                    icd_dgns_e_cd12,
                    icd_dgns_e_vrsn_cd1,
                    icd_dgns_e_vrsn_cd2,
                    icd_dgns_e_vrsn_cd3,
                    icd_dgns_e_vrsn_cd4,
                    icd_dgns_e_vrsn_cd5,
                    icd_dgns_e_vrsn_cd6,
                    icd_dgns_e_vrsn_cd7,
                    icd_dgns_e_vrsn_cd8,
                    icd_dgns_e_vrsn_cd9,
                    icd_dgns_e_vrsn_cd10,
                    icd_dgns_e_vrsn_cd11,
                    icd_dgns_e_vrsn_cd12,
                    icd_dgns_vrsn_cd1,
                    icd_dgns_vrsn_cd2,
                    icd_dgns_vrsn_cd3,
                    icd_dgns_vrsn_cd4,
                    icd_dgns_vrsn_cd5,
                    icd_dgns_vrsn_cd6,
                    icd_dgns_vrsn_cd7,
                    icd_dgns_vrsn_cd8,
                    icd_dgns_vrsn_cd9,
                    icd_dgns_vrsn_cd10,
                    icd_dgns_vrsn_cd11,
                    icd_dgns_vrsn_cd12,
                    icd_dgns_vrsn_cd13,
                    icd_dgns_vrsn_cd14,
                    icd_dgns_vrsn_cd15,
                    icd_dgns_vrsn_cd16,
                    icd_dgns_vrsn_cd17,
                    icd_dgns_vrsn_cd18,
                    icd_dgns_vrsn_cd19,
                    icd_dgns_vrsn_cd20,
                    icd_dgns_vrsn_cd21,
                    icd_dgns_vrsn_cd22,
                    icd_dgns_vrsn_cd23,
                    icd_dgns_vrsn_cd24,
                    icd_dgns_vrsn_cd25,
                    icd_prcdr_cd1,
                    icd_prcdr_cd2,
                    icd_prcdr_cd3,
                    icd_prcdr_cd4,
                    icd_prcdr_cd5,
                    icd_prcdr_cd6,
                    icd_prcdr_cd7,
                    icd_prcdr_cd8,
                    icd_prcdr_cd9,
                    icd_prcdr_cd10,
                    icd_prcdr_cd11,
                    icd_prcdr_cd12,
                    icd_prcdr_cd13,
                    icd_prcdr_cd14,
                    icd_prcdr_cd15,
                    icd_prcdr_cd16,
                    icd_prcdr_cd17,
                    icd_prcdr_cd18,
                    icd_prcdr_cd19,
                    icd_prcdr_cd20,
                    icd_prcdr_cd21,
                    icd_prcdr_cd22,
                    icd_prcdr_cd23,
                    icd_prcdr_cd24,
                    icd_prcdr_cd25,
                    icd_prcdr_vrsn_cd1,
                    icd_prcdr_vrsn_cd2,
                    icd_prcdr_vrsn_cd3,
                    icd_prcdr_vrsn_cd4,
                    icd_prcdr_vrsn_cd5,
                    icd_prcdr_vrsn_cd6,
                    icd_prcdr_vrsn_cd7,
                    icd_prcdr_vrsn_cd8,
                    icd_prcdr_vrsn_cd9,
                    icd_prcdr_vrsn_cd10,
                    icd_prcdr_vrsn_cd11,
                    icd_prcdr_vrsn_cd12,
                    icd_prcdr_vrsn_cd13,
                    icd_prcdr_vrsn_cd14,
                    icd_prcdr_vrsn_cd15,
                    icd_prcdr_vrsn_cd16,
                    icd_prcdr_vrsn_cd17,
                    icd_prcdr_vrsn_cd18,
                    icd_prcdr_vrsn_cd19,
                    icd_prcdr_vrsn_cd20,
                    icd_prcdr_vrsn_cd21,
                    icd_prcdr_vrsn_cd22,
                    icd_prcdr_vrsn_cd23,
                    icd_prcdr_vrsn_cd24,
                    icd_prcdr_vrsn_cd25,
                    prcdr_dt1,
                    prcdr_dt2,
                    prcdr_dt3,
                    prcdr_dt4,
                    prcdr_dt5,
                    prcdr_dt6,
                    prcdr_dt7,
                    prcdr_dt8,
                    prcdr_dt9,
                    prcdr_dt10,
                    prcdr_dt11,
                    prcdr_dt12,
                    prcdr_dt13,
                    prcdr_dt14,
                    prcdr_dt15,
                    prcdr_dt16,
                    prcdr_dt17,
                    prcdr_dt18,
                    prcdr_dt19,
                    prcdr_dt20,
                    prcdr_dt21,
                    prcdr_dt22,
                    prcdr_dt23,
                    prcdr_dt24,
                    prcdr_dt25
from
    public.snf_claims;

-- migrate data via INSERT from current SNF_CLAIM_LINES table to SNF_CLAIM_LINES_NEW table
--
 insert into public.snf_claim_lines_new (
                    clm_id,
                    clm_line_num,
                    rev_cntr,
                    rev_cntr_unit_cnt,
                    rev_cntr_tot_chrg_amt,
                    rev_cntr_rate_amt,
                    rev_cntr_ncvrd_chrg_amt,
                    rev_cntr_ddctbl_coinsrnc_cd,
                    rev_cntr_ndc_qty_qlfr_cd,
                    rev_cntr_ndc_qty,
                    hcpcs_cd,
                    rndrng_physn_npi,
                    rndrng_physn_upin )
select
${logic.psql-only}  cast(clm_id as bigint),
${logic.hsql-only}  convert(clm_id, SQL_BIGINT),
${logic.psql-only}  cast(clm_line_num as smallint),
${logic.hsql-only}  convert(clm_line_num, SQL_SMALLINT),
                    rev_cntr,
                    rev_cntr_unit_cnt,
                    rev_cntr_tot_chrg_amt,
                    rev_cntr_rate_amt,
                    rev_cntr_ncvrd_chrg_amt,
                    rev_cntr_ddctbl_coinsrnc_cd,
                    rev_cntr_ndc_qty_qlfr_cd,
                    rev_cntr_ndc_qty,
                    hcpcs_cd,
                    rndrng_physn_npi,
                    rndrng_physn_upin
from
    public.snf_claim_lines;