-- setup for parallel processing
SET max_parallel_workers = 6;
SET max_parallel_workers_per_gather = 6;
SET parallel_leader_participation = off;
SET parallel_tuple_cost = 0;
SET parallel_setup_cost = 0;
SET min_parallel_table_scan_size = 0;

insert into dme_claims(
	clm_id,
	bene_id,
	clm_grp_id,
	last_updated,
	clm_from_dt,
	clm_thru_dt,
	clm_disp_cd,
	clm_pmt_amt,
	clm_clncl_tril_num,
	carr_num,
	carr_clm_cntl_num,
	carr_clm_entry_cd,
	carr_clm_prvdr_asgnmt_ind_sw,
	carr_clm_hcpcs_yr_cd,
	carr_clm_pmt_dnl_cd,
	nch_carr_clm_alowd_amt,
	nch_carr_clm_sbmtd_chrg_amt,
	carr_clm_cash_ddctbl_apld_amt,
	nch_clm_bene_pmt_amt,
	nch_clm_type_cd,
	nch_near_line_rec_ident_cd,
	nch_wkly_proc_dt,
	carr_clm_prmry_pyr_pd_amt,
	prncpal_dgns_cd,
	prncpal_dgns_vrsn_cd,
	nch_clm_prvdr_pmt_amt,
	rfr_physn_npi,
	rfr_physn_upin,
	final_action,
	icd_dgns_cd1,
	icd_dgns_cd2,
	icd_dgns_cd3,
	icd_dgns_cd4,
	icd_dgns_cd5,
	icd_dgns_cd6,
	icd_dgns_cd7,
	icd_dgns_cd8,
	icd_dgns_cd9,
	icd_dgns_cd10,
	icd_dgns_cd11,
	icd_dgns_cd12,
	icd_dgns_vrsn_cd1,
	icd_dgns_vrsn_cd2,
	icd_dgns_vrsn_cd3,
	icd_dgns_vrsn_cd4,
	icd_dgns_vrsn_cd5,
	icd_dgns_vrsn_cd6,
	icd_dgns_vrsn_cd7,
	icd_dgns_vrsn_cd8,
	icd_dgns_vrsn_cd9,
	icd_dgns_vrsn_cd10,
	icd_dgns_vrsn_cd11,
	icd_dgns_vrsn_cd12
)
select
	cast("claimId" as bigint),
	cast("beneficiaryId" as bigint),
	cast("claimGroupId" as bigint),
	"lastupdated",
	"dateFrom",
	"dateThrough",
	"claimDispositionCode",
	"paymentAmount",
	"clinicalTrialNumber",
	"carrierNumber",
	"claimCarrierControlNumber",
	"claimEntryCode",
	"providerAssignmentIndicator",
	"hcpcsYearCode",
	"paymentDenialCode",
	"allowedChargeAmount",
	"submittedChargeAmount",
	"beneficiaryPartBDeductAmount",
	"beneficiaryPaymentAmount",
	"claimTypeCode",
	"nearLineRecordIdCode",
	"weeklyProcessDate",
	"primaryPayerPaidAmount",
	"diagnosisPrincipalCode",
	"diagnosisPrincipalCodeVersion",
	"providerPaymentAmount",
	"referringPhysicianNpi",
	"referringPhysicianUpin",
	"finalAction",
	"diagnosis1Code",
	"diagnosis2Code",
	"diagnosis3Code",
	"diagnosis4Code",
	"diagnosis5Code",
	"diagnosis6Code",
	"diagnosis7Code",
	"diagnosis8Code",
	"diagnosis9Code",
	"diagnosis10Code",
	"diagnosis11Code",
	"diagnosis12Code",
	"diagnosis1CodeVersion",
	"diagnosis2CodeVersion",
	"diagnosis3CodeVersion",
	"diagnosis4CodeVersion",
	"diagnosis5CodeVersion",
	"diagnosis6CodeVersion",
	"diagnosis7CodeVersion",
	"diagnosis8CodeVersion",
	"diagnosis9CodeVersion",
	"diagnosis10CodeVersion",
	"diagnosis11CodeVersion",
	"diagnosis12CodeVersion"	
from
	"DMEClaims";