-- setup for parallel processing
SET max_parallel_workers = 6;
SET max_parallel_workers_per_gather = 6;
SET parallel_leader_participation = off;
SET parallel_tuple_cost = 0;
SET parallel_setup_cost = 0;
SET min_parallel_table_scan_size = 0;

insert into partd_events (
	clm_id,
	bene_id,
	clm_grp_id,
	last_updated,
	adjstmt_dltn_cd,
	brnd_gnrc_cd,
	cmpnd_cd,
	ctstrphc_cvrg_cd,
	cvrd_d_plan_pd_amt,
	daw_prod_slctn_cd,
	days_suply_num,
	drug_cvrg_stus_cd,
	dspnsng_stus_cd,
	fill_num,
	final_action,
	gdc_abv_oopt_amt,
	gdc_blw_oopt_amt,
	lics_amt,
	prod_srvc_id,
	ncvrd_plan_pd_amt,
	nstd_frmt_cd,
	othr_troop_amt,
	pd_dt,
	phrmcy_srvc_type_cd,
	plan_cntrct_rec_id,
	plan_pbp_rec_num,
	plro_amt,
	prcng_excptn_cd,
	prscrbr_id,
	prscrbr_id_qlfyr_cd,
	ptnt_pay_amt,
	ptnt_rsdnc_cd,
	qty_dspnsd_num,
	rptd_gap_dscnt_num,
	rx_orgn_cd,
	rx_srvc_rfrnc_num,
	srvc_dt,
	srvc_prvdr_id,
	srvc_prvdr_id_qlfyr_cd,
	submsn_clr_cd,
	tot_rx_cst_amt
)
select
	cast("eventId" as bigint),
	cast("beneficiaryId" as bigint),
	cast("claimGroupId" as bigint),
	"lastupdated",
	"adjustmentDeletionCode",
	"brandGenericCode",
	"compoundCode",
	"catastrophicCoverageCode",
	"partDPlanCoveredPaidAmount",
	"dispenseAsWrittenProductSelectionCode",
	"daysSupply",
	"drugCoverageStatusCode",
	"dispensingStatusCode",
	"fillNumber",
	"finalAction",
	"grossCostAboveOutOfPocketThreshold",
	"grossCostBelowOutOfPocketThreshold",
	"lowIncomeSubsidyPaidAmount",
	"nationalDrugCode",
	"partDPlanNonCoveredPaidAmount",
	"nonstandardFormatCode",
	"otherTrueOutOfPocketPaidAmount",
	"paymentDate",
	"pharmacyTypeCode",
	"planContractId",
	"planBenefitPackageId",
	"patientLiabilityReductionOtherPaidAmount",
	"pricingExceptionCode",
	"prescriberId",
	"prescriberIdQualifierCode",
	"patientPaidAmount",
	"patientResidenceCode",
	"quantityDispensed",
	"gapDiscountAmount",
	"prescriptionOriginationCode",
	"prescriptionReferenceNumber",
	"prescriptionFillDate",
	"serviceProviderId",
	"serviceProviderIdQualiferCode",
	"submissionClarificationCode",
	"totalPrescriptionCost"
from
	"PartDEvents";