name: "Deploy Platform Terraservice"
description: "Composite action to deploy an account-specific Terraservice"
inputs:
  account-type:
    description: "The account type to deploy the given service to"
    required: false
  service-path:
    description: "The path to the Terraservice relative to the root of the repository"
    required: true
  cw-log-group:
    description: >-
      Name of CloudWatch Log Group to submit OpenTofu logs to; will be created if necessary
    required: true
  cw-log-stream:
    description: >-
      Name of CloudWatch Log Stream to submit OpenTofu logs to; will be created if necessary
    required: true
  skip-apply:
    description: >-
      Skip the apply of the given Terraservice. Useful for logging the plan without making any
      modifications
    default: "false" # Composite Action inputs must be strings
    required: false
  tofu-vars-json:
    description: "JSON object map of variables to their values"
    required: false
    default: "{}"
runs:
  using: "composite"
  steps:
    - name: Setup OpenTofu and shell environment
      id: setup-tofu
      uses: ./.github/actions/bfd-setup-tofu
      with:
        service-path: ${{ inputs.service-path }}
        cw-log-group: ${{ inputs.cw-log-group }}
        cw-log-stream: ${{ inputs.cw-log-stream }}
        tofu-vars-json: ${{ inputs.tofu-vars-json }}

    # This step is necessary as it seems that some objects (like "github" or "inputs") are
    # unavailable when the top-level "env" is evaluated for Composite Actions
    - name: Setup environment
      run: |
        echo "TOFU_CI_SCRIPT=${{ github.workspace }}/.github/scripts/tofu-ci.sh" >> $GITHUB_ENV
      shell: bash

    - name: OpenTofu init
      run: |
        tofu --version

        # Often OpenTofu stdout/stderr logs contain sensitive/private information. GHA logs are
        # available for anyone logged in with a GitHub account to view, and so this information must
        # be protected. Instead of logging to stdout, all potentially sensitive OpenTofu log output
        # is instead logged to CloudWatch
        TF_WORKSPACE=default tofu init \
          -var account_type="${{ inputs.account-type }}" \
          -reconfigure \
          -no-color 2>&1 | "$STDOUT_TO_CWLOGS_SCRIPT"
        echo "tofu init for \"${{ inputs.account-type }}\" completed"

        tofu workspace select \
          -no-color \
          -var account_type="${{ inputs.account-type }}" \
          -or-create "${{ inputs.account-type }}" 2>&1 | "$STDOUT_TO_CWLOGS_SCRIPT"
        echo "Selected workspace \"${{ inputs.account-type }}\""
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.service-path }}

      # We split Tofu steps into "start"/"do"/"end" steps in order to attempt to avoid GitHub
      # Actions' poor signaling behavior on exit.
      # See the README of https://github.com/ringerc/github-actions-signal-handling-demo and
      # https://github.com/orgs/community/discussions/26311
    - name: Start OpenTofu Plan
      run: |
        echo "Generating OpenTofu plan for ${{ inputs.service-path }}..."
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.service-path }}

      # Having this "exec ..." be the first command should ensure that the wrapper script is the
      # "leader" process
    - name: Do OpenTofu plan
      run: |
        exec "$TOFU_CI_SCRIPT" plan ${{ steps.setup-tofu.outputs.tf-vars-args }} -no-color \
          -out=tfplan 2>&1 | "$STDOUT_TO_CWLOGS_SCRIPT"
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.service-path }}

    - name: End OpenTofu plan
      run: |
        echo "Plan generated for ${{ inputs.service-path }} successfully"
      shell: bash

    - name: Start apply Terraservice
      if: ${{ inputs.skip-apply != 'true' }}
      run: |
        echo "Applying OpenTofu plan for ${{ inputs.service-path }}..."
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.service-path }}

    - name: Do apply Terraservice
      if: ${{ inputs.skip-apply != 'true' }}
      run: |
        exec "$TOFU_CI_SCRIPT" apply -no-color -input=false tfplan 2>&1 | "$STDOUT_TO_CWLOGS_SCRIPT"
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.service-path }}

    - name: End apply Terraservice
      if: ${{ inputs.skip-apply != 'true' }}
      run: |
        echo "OpenTofu plan for ${{ inputs.service-path }} applied"
      shell: bash

