/*
 * Creates the beneficiary and claim tables required by the application. This
 * schema is derived from the JPA metadata, via the 
 * gov.hhs.cms.bluebutton.data.pipeline.rif.schema.HibernateSchemaPrinter 
 * utility.
 */

${logic.tablespaces-escape} SET default_tablespace = fhirdb_ts2;

create table "Beneficiaries" (
   "beneficiaryId" varchar(15) not null,
    "birthDate" date not null,
    "countyCode" varchar(10) not null,
    "endStageRenalDiseaseCode" char(1),
    "entitlementCodeCurrent" char(1),
    "entitlementCodeOriginal" char(1),
    "hicn" varchar(64) not null,
    "medicareEnrollmentStatusCode" varchar(2),
    "nameGiven" varchar(15) not null,
    "nameMiddleInitial" char(1),
    "nameSurname" varchar(24) not null,
    "partATerminationCode" char(1),
    "partBTerminationCode" char(1),
    "postalCode" varchar(9) not null,
    "race" char(1),
    "sex" char(1) not null,
    "stateCode" varchar(2) not null,
    constraint "Beneficiaries_pkey" primary key ("beneficiaryId")
)
${logic.tablespaces-escape} tablespace "beneficiaries_ts"
;

create table "CarrierClaimLines" (
   "lineNumber" numeric not null,
    "parentClaim" varchar(255) not null,
    "allowedChargeAmount" numeric(12, 2) not null,
    "anesthesiaUnitCount" numeric not null,
    "beneficiaryPartBDeductAmount" numeric(12, 2) not null,
    "beneficiaryPaymentAmount" numeric(12, 2) not null,
    "betosCode" varchar(3),
    "cliaLabNumber" varchar(10),
    "cmsServiceTypeCode" char(1) not null,
    "coinsuranceAmount" numeric(12, 2) not null,
    "diagnosisCode" varchar(7),
    "diagnosisCodeVersion" char(1),
    "firstExpenseDate" date,
    "hcpcsCode" varchar(5),
    "hcpcsInitialModifierCode" varchar(5),
    "hcpcsSecondModifierCode" varchar(5),
    "hctHgbTestResult" numeric(4) not null,
    "hctHgbTestTypeCode" varchar(2),
    "hpsaScarcityCode" char(1),
    "lastExpenseDate" date,
    "linePricingLocalityCode" varchar(2) not null,
    "mtusCode" char(1),
    "mtusCount" numeric not null,
    "nationalDrugCode" varchar(11),
    "organizationNpi" varchar(10),
    "paymentAmount" numeric(12, 2) not null,
    "paymentCode" char(1),
    "performingPhysicianNpi" varchar(12),
    "performingPhysicianUpin" varchar(12),
    "performingProviderIdNumber" varchar(15) not null,
    "placeOfServiceCode" varchar(2) not null,
    "primaryPayerCode" char(1),
    "primaryPayerPaidAmount" numeric(12, 2) not null,
    "processingIndicatorCode" varchar(2),
    "providerParticipatingIndCode" char(1),
    "providerPaymentAmount" numeric(12, 2) not null,
    "providerSpecialityCode" varchar(3),
    "providerStateCode" varchar(2),
    "providerTaxNumber" varchar(10) not null,
    "providerTypeCode" char(1) not null,
    "providerZipCode" varchar(9),
    "reducedPaymentPhysicianAsstCode" char(1) not null,
    "rxNumber" varchar(30),
    "serviceCount" numeric not null,
    "serviceDeductibleCode" char(1),
    "submittedChargeAmount" numeric(12, 2) not null,
    constraint "CarrierClaimLines_pkey" primary key ("lineNumber", "parentClaim")
)
${logic.tablespaces-escape} tablespace "carrierclaimlines_ts"
;

create table "CarrierClaims" (
   "claimId" varchar(15) not null,
    "allowedChargeAmount" numeric(12, 2) not null,
    "beneficiaryId" varchar(15) not null,
    "beneficiaryPartBDeductAmount" numeric(12, 2) not null,
    "beneficiaryPaymentAmount" numeric(12, 2) not null,
    "carrierNumber" varchar(5) not null,
    "claimDispositionCode" varchar(2) not null,
    "claimEntryCode" char(1) not null,
    "claimGroupId" numeric(12) not null,
    "claimTypeCode" varchar(2) not null,
    "clinicalTrialNumber" varchar(8),
    "dateFrom" date not null,
    "dateThrough" date not null,
    "diagnosis10Code" varchar(7),
    "diagnosis10CodeVersion" char(1),
    "diagnosis11Code" varchar(7),
    "diagnosis11CodeVersion" char(1),
    "diagnosis12Code" varchar(7),
    "diagnosis12CodeVersion" char(1),
    "diagnosis1Code" varchar(7),
    "diagnosis1CodeVersion" char(1),
    "diagnosis2Code" varchar(7),
    "diagnosis2CodeVersion" char(1),
    "diagnosis3Code" varchar(7),
    "diagnosis3CodeVersion" char(1),
    "diagnosis4Code" varchar(7),
    "diagnosis4CodeVersion" char(1),
    "diagnosis5Code" varchar(7),
    "diagnosis5CodeVersion" char(1),
    "diagnosis6Code" varchar(7),
    "diagnosis6CodeVersion" char(1),
    "diagnosis7Code" varchar(7),
    "diagnosis7CodeVersion" char(1),
    "diagnosis8Code" varchar(7),
    "diagnosis8CodeVersion" char(1),
    "diagnosis9Code" varchar(7),
    "diagnosis9CodeVersion" char(1),
    "diagnosisPrincipalCode" varchar(7),
    "diagnosisPrincipalCodeVersion" char(1),
    "hcpcsYearCode" char(1),
    "nearLineRecordIdCode" char(1) not null,
    "paymentAmount" numeric(12, 2) not null,
    "paymentDenialCode" varchar(2) not null,
    "primaryPayerPaidAmount" numeric(12, 2) not null,
    "providerAssignmentIndicator" char(1),
    "providerPaymentAmount" numeric(12, 2) not null,
    "referringPhysicianNpi" varchar(12),
    "referringPhysicianUpin" varchar(12),
    "referringProviderIdNumber" varchar(14) not null,
    "submittedChargeAmount" numeric(12, 2) not null,
    "weeklyProcessDate" date not null,
    constraint "CarrierClaims_pkey" primary key ("claimId")
)
${logic.tablespaces-escape} tablespace "carrierclaims_ts"
;

create table "DMEClaimLines" (
   "lineNumber" numeric not null,
    "parentClaim" varchar(255) not null,
    "allowedChargeAmount" numeric(12, 2) not null,
    "beneficiaryPartBDeductAmount" numeric(12, 2) not null,
    "beneficiaryPaymentAmount" numeric(12, 2) not null,
    "betosCode" varchar(3),
    "cmsServiceTypeCode" char(1) not null,
    "coinsuranceAmount" numeric(12, 2) not null,
    "diagnosisCode" varchar(7),
    "diagnosisCodeVersion" char(1),
    "firstExpenseDate" date,
    "hcpcsCode" varchar(5),
    "hcpcsFourthModifierCode" varchar(5),
    "hcpcsInitialModifierCode" varchar(5),
    "hcpcsSecondModifierCode" varchar(5),
    "hcpcsThirdModifierCode" varchar(5),
    "hctHgbTestResult" numeric(3, 1) not null,
    "hctHgbTestTypeCode" varchar(2),
    "lastExpenseDate" date,
    "mtusCode" char(1),
    "mtusCount" numeric not null,
    "nationalDrugCode" varchar(11),
    "paymentAmount" numeric(12, 2) not null,
    "paymentCode" char(1),
    "placeOfServiceCode" varchar(2) not null,
    "pricingStateCode" varchar(2),
    "primaryPayerAllowedChargeAmount" numeric(12, 2) not null,
    "primaryPayerCode" char(1),
    "primaryPayerPaidAmount" numeric(12, 2) not null,
    "processingIndicatorCode" varchar(2),
    "providerBillingNumber" varchar(10),
    "providerNPI" varchar(12),
    "providerParticipatingIndCode" char(1),
    "providerPaymentAmount" numeric(12, 2) not null,
    "providerSpecialityCode" varchar(3),
    "providerStateCode" varchar(2) not null,
    "providerTaxNumber" varchar(10) not null,
    "purchasePriceAmount" numeric(12, 2) not null,
    "screenSavingsAmount" numeric(12, 2),
    "serviceCount" numeric not null,
    "serviceDeductibleCode" char(1),
    "submittedChargeAmount" numeric(12, 2) not null,
    "supplierTypeCode" char(1),
    constraint "DMEClaimLines_pkey" primary key ("lineNumber", "parentClaim")
)
${logic.tablespaces-escape} tablespace "dmeclaimlines_ts"
;

create table "DMEClaims" (
   "claimId" varchar(15) not null,
    "allowedChargeAmount" numeric(12, 2) not null,
    "beneficiaryId" varchar(15) not null,
    "beneficiaryPartBDeductAmount" numeric(12, 2) not null,
    "beneficiaryPaymentAmount" numeric(12, 2) not null,
    "carrierNumber" varchar(5) not null,
    "claimDispositionCode" varchar(2) not null,
    "claimEntryCode" char(1) not null,
    "claimGroupId" numeric(12) not null,
    "claimTypeCode" varchar(2) not null,
    "clinicalTrialNumber" varchar(8),
    "dateFrom" date not null,
    "dateThrough" date not null,
    "diagnosis10Code" varchar(7),
    "diagnosis10CodeVersion" char(1),
    "diagnosis11Code" varchar(7),
    "diagnosis11CodeVersion" char(1),
    "diagnosis12Code" varchar(7),
    "diagnosis12CodeVersion" char(1),
    "diagnosis1Code" varchar(7),
    "diagnosis1CodeVersion" char(1),
    "diagnosis2Code" varchar(7),
    "diagnosis2CodeVersion" char(1),
    "diagnosis3Code" varchar(7),
    "diagnosis3CodeVersion" char(1),
    "diagnosis4Code" varchar(7),
    "diagnosis4CodeVersion" char(1),
    "diagnosis5Code" varchar(7),
    "diagnosis5CodeVersion" char(1),
    "diagnosis6Code" varchar(7),
    "diagnosis6CodeVersion" char(1),
    "diagnosis7Code" varchar(7),
    "diagnosis7CodeVersion" char(1),
    "diagnosis8Code" varchar(7),
    "diagnosis8CodeVersion" char(1),
    "diagnosis9Code" varchar(7),
    "diagnosis9CodeVersion" char(1),
    "diagnosisPrincipalCode" varchar(7),
    "diagnosisPrincipalCodeVersion" char(1),
    "hcpcsYearCode" char(1),
    "nearLineRecordIdCode" char(1) not null,
    "paymentAmount" numeric(12, 2) not null,
    "paymentDenialCode" varchar(2) not null,
    "primaryPayerPaidAmount" numeric(12, 2) not null,
    "providerAssignmentIndicator" char(1) not null,
    "providerPaymentAmount" numeric(12, 2) not null,
    "referringPhysicianNpi" varchar(12),
    "referringPhysicianUpin" varchar(12),
    "submittedChargeAmount" numeric(12, 2) not null,
    "weeklyProcessDate" date not null,
    constraint "DMEClaims_pkey" primary key ("claimId")
)
${logic.tablespaces-escape} tablespace "dmeclaims_ts"
;

create table "HHAClaimLines" (
   "lineNumber" numeric not null,
    "parentClaim" varchar(255) not null,
    "apcOrHippsCode" varchar(5),
    "deductibleCoinsuranceCd" char(1),
    "hcpcsCode" varchar(5),
    "hcpcsInitialModifierCode" varchar(5),
    "hcpcsSecondModifierCode" varchar(5),
    "nationalDrugCodeQualifierCode" varchar(2),
    "nationalDrugCodeQuantity" numeric,
    "nonCoveredChargeAmount" numeric(12, 2) not null,
    "paymentAmount" numeric(12, 2) not null,
    "paymentMethodCode" varchar(2),
    "rateAmount" numeric(12, 2) not null,
    "revCntr1stAnsiCd" varchar(5),
    "revenueCenterCode" varchar(4) not null,
    "revenueCenterDate" date,
    "revenueCenterRenderingPhysicianNPI" varchar(12),
    "revenueCenterRenderingPhysicianUPIN" varchar(12),
    "statusCode" varchar(2),
    "totalChargeAmount" numeric(12, 2) not null,
    "unitCount" numeric not null,
    constraint "HHAClaimLines_pkey" primary key ("lineNumber", "parentClaim")
)
${logic.tablespaces-escape} tablespace "hhaclaimlines_ts"
;

create table "HHAClaims" (
   "claimId" varchar(15) not null,
    "attendingPhysicianNpi" varchar(10),
    "attendingPhysicianUpin" varchar(9),
    "beneficiaryId" varchar(15) not null,
    "careStartDate" date,
    "claimFacilityTypeCode" char(1) not null,
    "claimFrequencyCode" char(1) not null,
    "claimGroupId" numeric(12) not null,
    "claimLUPACode" char(1),
    "claimNonPaymentReasonCode" varchar(2),
    "claimPrimaryPayerCode" char(1),
    "claimReferralCode" char(1),
    "claimServiceClassificationTypeCode" char(1) not null,
    "claimTypeCode" varchar(2) not null,
    "dateFrom" date not null,
    "dateThrough" date not null,
    "diagnosis10Code" varchar(7),
    "diagnosis10CodeVersion" char(1),
    "diagnosis11Code" varchar(7),
    "diagnosis11CodeVersion" char(1),
    "diagnosis12Code" varchar(7),
    "diagnosis12CodeVersion" char(1),
    "diagnosis13Code" varchar(7),
    "diagnosis13CodeVersion" char(1),
    "diagnosis14Code" varchar(7),
    "diagnosis14CodeVersion" char(1),
    "diagnosis15Code" varchar(7),
    "diagnosis15CodeVersion" char(1),
    "diagnosis16Code" varchar(7),
    "diagnosis16CodeVersion" char(1),
    "diagnosis17Code" varchar(7),
    "diagnosis17CodeVersion" char(1),
    "diagnosis18Code" varchar(7),
    "diagnosis18CodeVersion" char(1),
    "diagnosis19Code" varchar(7),
    "diagnosis19CodeVersion" char(1),
    "diagnosis1Code" varchar(7),
    "diagnosis1CodeVersion" char(1),
    "diagnosis20Code" varchar(7),
    "diagnosis20CodeVersion" char(1),
    "diagnosis21Code" varchar(7),
    "diagnosis21CodeVersion" char(1),
    "diagnosis22Code" varchar(7),
    "diagnosis22CodeVersion" char(1),
    "diagnosis23Code" varchar(7),
    "diagnosis23CodeVersion" char(1),
    "diagnosis24Code" varchar(7),
    "diagnosis24CodeVersion" char(1),
    "diagnosis25Code" varchar(7),
    "diagnosis25CodeVersion" char(1),
    "diagnosis2Code" varchar(7),
    "diagnosis2CodeVersion" char(1),
    "diagnosis3Code" varchar(7),
    "diagnosis3CodeVersion" char(1),
    "diagnosis4Code" varchar(7),
    "diagnosis4CodeVersion" char(1),
    "diagnosis5Code" varchar(7),
    "diagnosis5CodeVersion" char(1),
    "diagnosis6Code" varchar(7),
    "diagnosis6CodeVersion" char(1),
    "diagnosis7Code" varchar(7),
    "diagnosis7CodeVersion" char(1),
    "diagnosis8Code" varchar(7),
    "diagnosis8CodeVersion" char(1),
    "diagnosis9Code" varchar(7),
    "diagnosis9CodeVersion" char(1),
    "diagnosisExternal10Code" varchar(7),
    "diagnosisExternal10CodeVersion" char(1),
    "diagnosisExternal11Code" varchar(7),
    "diagnosisExternal11CodeVersion" char(1),
    "diagnosisExternal12Code" varchar(7),
    "diagnosisExternal12CodeVersion" char(1),
    "diagnosisExternal1Code" varchar(7),
    "diagnosisExternal1CodeVersion" char(1),
    "diagnosisExternal2Code" varchar(7),
    "diagnosisExternal2CodeVersion" char(1),
    "diagnosisExternal3Code" varchar(7),
    "diagnosisExternal3CodeVersion" char(1),
    "diagnosisExternal4Code" varchar(7),
    "diagnosisExternal4CodeVersion" char(1),
    "diagnosisExternal5Code" varchar(7),
    "diagnosisExternal5CodeVersion" char(1),
    "diagnosisExternal6Code" varchar(7),
    "diagnosisExternal6CodeVersion" char(1),
    "diagnosisExternal7Code" varchar(7),
    "diagnosisExternal7CodeVersion" char(1),
    "diagnosisExternal8Code" varchar(7),
    "diagnosisExternal8CodeVersion" char(1),
    "diagnosisExternal9Code" varchar(7),
    "diagnosisExternal9CodeVersion" char(1),
    "diagnosisExternalFirstCode" varchar(7),
    "diagnosisExternalFirstCodeVersion" char(1),
    "diagnosisPrincipalCode" varchar(7),
    "diagnosisPrincipalCodeVersion" char(1),
    "fiscalIntermediaryClaimProcessDate" date,
    "fiscalIntermediaryNumber" varchar(5),
    "nearLineRecordIdCode" char(1) not null,
    "organizationNpi" varchar(10),
    "patientDischargeStatusCode" varchar(2) not null,
    "paymentAmount" numeric(12, 2) not null,
    "primaryPayerPaidAmount" numeric(12, 2) not null,
    "prospectivePaymentCode" char(1) not null,
    "providerNumber" varchar(9) not null,
    "providerStateCode" varchar(2) not null,
    "totalChargeAmount" numeric(12, 2) not null,
    "totalVisitCount" numeric(4) not null,
    "weeklyProcessDate" date not null,
    constraint "HHAClaims_pkey" primary key ("claimId")
)
${logic.tablespaces-escape} tablespace "hhaclaims_ts"
;

create table "HospiceClaimLines" (
   "lineNumber" numeric not null,
    "parentClaim" varchar(255) not null,
    "benficiaryPaymentAmount" numeric(12, 2) not null,
    "deductibleCoinsuranceCd" char(1),
    "hcpcsCode" varchar(5),
    "hcpcsInitialModifierCode" varchar(5),
    "hcpcsSecondModifierCode" varchar(5),
    "nationalDrugCodeQualifierCode" varchar(2),
    "nationalDrugCodeQuantity" numeric,
    "nonCoveredChargeAmount" numeric(12, 2),
    "paymentAmount" numeric(12, 2) not null,
    "providerPaymentAmount" numeric(12, 2) not null,
    "rateAmount" numeric(12, 2) not null,
    "revenueCenterCode" varchar(4) not null,
    "revenueCenterDate" date,
    "revenueCenterRenderingPhysicianNPI" varchar(12),
    "revenueCenterRenderingPhysicianUPIN" varchar(12),
    "totalChargeAmount" numeric(12, 2) not null,
    "unitCount" numeric not null,
    constraint "HospiceClaimLines_pkey" primary key ("lineNumber", "parentClaim")
)
${logic.tablespaces-escape} tablespace "hospiceclaimlines_ts"
;

create table "HospiceClaims" (
   "claimId" varchar(15) not null,
    "attendingPhysicianNpi" varchar(10),
    "attendingPhysicianUpin" varchar(9),
    "beneficiaryDischargeDate" date,
    "beneficiaryId" varchar(15) not null,
    "claimFacilityTypeCode" char(1) not null,
    "claimFrequencyCode" char(1) not null,
    "claimGroupId" numeric(12) not null,
    "claimHospiceStartDate" date,
    "claimNonPaymentReasonCode" varchar(2),
    "claimPrimaryPayerCode" char(1),
    "claimServiceClassificationTypeCode" char(1) not null,
    "claimTypeCode" varchar(2) not null,
    "dateFrom" date not null,
    "dateThrough" date not null,
    "diagnosis10Code" varchar(7),
    "diagnosis10CodeVersion" char(1),
    "diagnosis11Code" varchar(7),
    "diagnosis11CodeVersion" char(1),
    "diagnosis12Code" varchar(7),
    "diagnosis12CodeVersion" char(1),
    "diagnosis13Code" varchar(7),
    "diagnosis13CodeVersion" char(1),
    "diagnosis14Code" varchar(7),
    "diagnosis14CodeVersion" char(1),
    "diagnosis15Code" varchar(7),
    "diagnosis15CodeVersion" char(1),
    "diagnosis16Code" varchar(7),
    "diagnosis16CodeVersion" char(1),
    "diagnosis17Code" varchar(7),
    "diagnosis17CodeVersion" char(1),
    "diagnosis18Code" varchar(7),
    "diagnosis18CodeVersion" char(1),
    "diagnosis19Code" varchar(7),
    "diagnosis19CodeVersion" char(1),
    "diagnosis1Code" varchar(7),
    "diagnosis1CodeVersion" char(1),
    "diagnosis20Code" varchar(7),
    "diagnosis20CodeVersion" char(1),
    "diagnosis21Code" varchar(7),
    "diagnosis21CodeVersion" char(1),
    "diagnosis22Code" varchar(7),
    "diagnosis22CodeVersion" char(1),
    "diagnosis23Code" varchar(7),
    "diagnosis23CodeVersion" char(1),
    "diagnosis24Code" varchar(7),
    "diagnosis24CodeVersion" char(1),
    "diagnosis25Code" varchar(7),
    "diagnosis25CodeVersion" char(1),
    "diagnosis2Code" varchar(7),
    "diagnosis2CodeVersion" char(1),
    "diagnosis3Code" varchar(7),
    "diagnosis3CodeVersion" char(1),
    "diagnosis4Code" varchar(7),
    "diagnosis4CodeVersion" char(1),
    "diagnosis5Code" varchar(7),
    "diagnosis5CodeVersion" char(1),
    "diagnosis6Code" varchar(7),
    "diagnosis6CodeVersion" char(1),
    "diagnosis7Code" varchar(7),
    "diagnosis7CodeVersion" char(1),
    "diagnosis8Code" varchar(7),
    "diagnosis8CodeVersion" char(1),
    "diagnosis9Code" varchar(7),
    "diagnosis9CodeVersion" char(1),
    "diagnosisExternal10Code" varchar(7),
    "diagnosisExternal10CodeVersion" char(1),
    "diagnosisExternal11Code" varchar(7),
    "diagnosisExternal11CodeVersion" char(1),
    "diagnosisExternal12Code" varchar(7),
    "diagnosisExternal12CodeVersion" char(1),
    "diagnosisExternal1Code" varchar(7),
    "diagnosisExternal1CodeVersion" char(1),
    "diagnosisExternal2Code" varchar(7),
    "diagnosisExternal2CodeVersion" char(1),
    "diagnosisExternal3Code" varchar(7),
    "diagnosisExternal3CodeVersion" char(1),
    "diagnosisExternal4Code" varchar(7),
    "diagnosisExternal4CodeVersion" char(1),
    "diagnosisExternal5Code" varchar(7),
    "diagnosisExternal5CodeVersion" char(1),
    "diagnosisExternal6Code" varchar(7),
    "diagnosisExternal6CodeVersion" char(1),
    "diagnosisExternal7Code" varchar(7),
    "diagnosisExternal7CodeVersion" char(1),
    "diagnosisExternal8Code" varchar(7),
    "diagnosisExternal8CodeVersion" char(1),
    "diagnosisExternal9Code" varchar(7),
    "diagnosisExternal9CodeVersion" char(1),
    "diagnosisExternalFirstCode" varchar(7),
    "diagnosisExternalFirstCodeVersion" char(1),
    "diagnosisPrincipalCode" varchar(7),
    "diagnosisPrincipalCodeVersion" char(1),
    "fiscalIntermediaryClaimProcessDate" date,
    "fiscalIntermediaryNumber" varchar(5),
    "hospicePeriodCount" numeric(2),
    "nearLineRecordIdCode" char(1) not null,
    "organizationNpi" varchar(10),
    "patientDischargeStatusCode" varchar(2) not null,
    "patientStatusCd" char(1),
    "paymentAmount" numeric(12, 2) not null,
    "primaryPayerPaidAmount" numeric(12, 2) not null,
    "providerNumber" varchar(9) not null,
    "providerStateCode" varchar(2) not null,
    "totalChargeAmount" numeric(12, 2) not null,
    "utilizationDayCount" numeric not null,
    "weeklyProcessDate" date not null,
    constraint "HospiceClaims_pkey" primary key ("claimId")
)
${logic.tablespaces-escape} tablespace "hospiceclaims_ts"
;

create table "InpatientClaimLines" (
   "lineNumber" numeric not null,
    "parentClaim" varchar(255) not null,
    "deductibleCoinsuranceCd" char(1),
    "hcpcsCode" varchar(5),
    "nationalDrugCodeQualifierCode" varchar(2),
    "nationalDrugCodeQuantity" numeric,
    "nonCoveredChargeAmount" numeric(12, 2) not null,
    "rateAmount" numeric(12, 2) not null,
    "revenueCenter" varchar(4) not null,
    "revenueCenterRenderingPhysicianNPI" varchar(12),
    "revenueCenterRenderingPhysicianUPIN" varchar(12),
    "totalChargeAmount" numeric(12, 2) not null,
    "unitCount" numeric not null,
    constraint "InpatientClaimLines_pkey" primary key ("lineNumber", "parentClaim")
)
${logic.tablespaces-escape} tablespace "inpatientclaimlines_ts"
;

create table "InpatientClaims" (
   "claimId" varchar(15) not null,
    "admissionTypeCd" char(1) not null,
    "attendingPhysicianNpi" varchar(10),
    "attendingPhysicianUpin" varchar(9),
    "beneficiaryDischargeDate" date,
    "beneficiaryId" varchar(15) not null,
    "bloodDeductibleLiabilityAmount" numeric(12, 2) not null,
    "bloodPintsFurnishedQty" numeric not null,
    "claimAdmissionDate" date,
    "claimFacilityTypeCode" char(1) not null,
    "claimFrequencyCode" char(1) not null,
    "claimGroupId" numeric(12) not null,
    "claimNonPaymentReasonCode" varchar(2),
    "claimPPSCapitalDisproportionateShareAmt" numeric(12, 2),
    "claimPPSCapitalDrgWeightNumber" numeric(7, 4),
    "claimPPSCapitalExceptionAmount" numeric(12, 2),
    "claimPPSCapitalFSPAmount" numeric(12, 2),
    "claimPPSCapitalIMEAmount" numeric(12, 2),
    "claimPPSCapitalOutlierAmount" numeric(12, 2),
    "claimPPSOldCapitalHoldHarmlessAmount" numeric(12, 2),
    "claimPrimaryPayerCode" char(1),
    "claimQueryCode" char(1) not null,
    "claimServiceClassificationTypeCode" char(1) not null,
    "claimTotalPPSCapitalAmount" numeric(12, 2),
    "claimTypeCode" varchar(2) not null,
    "coinsuranceDayCount" numeric not null,
    "coveredCareThoughDate" date,
    "dateFrom" date not null,
    "dateThrough" date not null,
    "deductibleAmount" numeric(12, 2) not null,
    "diagnosis10Code" varchar(7),
    "diagnosis10CodeVersion" char(1),
    "diagnosis10PresentOnAdmissionCode" char(1),
    "diagnosis11Code" varchar(7),
    "diagnosis11CodeVersion" char(1),
    "diagnosis11PresentOnAdmissionCode" char(1),
    "diagnosis12Code" varchar(7),
    "diagnosis12CodeVersion" char(1),
    "diagnosis12PresentOnAdmissionCode" char(1),
    "diagnosis13Code" varchar(7),
    "diagnosis13CodeVersion" char(1),
    "diagnosis13PresentOnAdmissionCode" char(1),
    "diagnosis14Code" varchar(7),
    "diagnosis14CodeVersion" char(1),
    "diagnosis14PresentOnAdmissionCode" char(1),
    "diagnosis15Code" varchar(7),
    "diagnosis15CodeVersion" char(1),
    "diagnosis15PresentOnAdmissionCode" char(1),
    "diagnosis16Code" varchar(7),
    "diagnosis16CodeVersion" char(1),
    "diagnosis16PresentOnAdmissionCode" char(1),
    "diagnosis17Code" varchar(7),
    "diagnosis17CodeVersion" char(1),
    "diagnosis17PresentOnAdmissionCode" char(1),
    "diagnosis18Code" varchar(7),
    "diagnosis18CodeVersion" char(1),
    "diagnosis18PresentOnAdmissionCode" char(1),
    "diagnosis19Code" varchar(7),
    "diagnosis19CodeVersion" char(1),
    "diagnosis19PresentOnAdmissionCode" char(1),
    "diagnosis1Code" varchar(7),
    "diagnosis1CodeVersion" char(1),
    "diagnosis1PresentOnAdmissionCode" char(1),
    "diagnosis20Code" varchar(7),
    "diagnosis20CodeVersion" char(1),
    "diagnosis20PresentOnAdmissionCode" char(1),
    "diagnosis21Code" varchar(7),
    "diagnosis21CodeVersion" char(1),
    "diagnosis21PresentOnAdmissionCode" char(1),
    "diagnosis22Code" varchar(7),
    "diagnosis22CodeVersion" char(1),
    "diagnosis22PresentOnAdmissionCode" char(1),
    "diagnosis23Code" varchar(7),
    "diagnosis23CodeVersion" char(1),
    "diagnosis23PresentOnAdmissionCode" char(1),
    "diagnosis24Code" varchar(7),
    "diagnosis24CodeVersion" char(1),
    "diagnosis24PresentOnAdmissionCode" char(1),
    "diagnosis25Code" varchar(7),
    "diagnosis25CodeVersion" char(1),
    "diagnosis25PresentOnAdmissionCode" char(1),
    "diagnosis2Code" varchar(7),
    "diagnosis2CodeVersion" char(1),
    "diagnosis2PresentOnAdmissionCode" char(1),
    "diagnosis3Code" varchar(7),
    "diagnosis3CodeVersion" char(1),
    "diagnosis3PresentOnAdmissionCode" char(1),
    "diagnosis4Code" varchar(7),
    "diagnosis4CodeVersion" char(1),
    "diagnosis4PresentOnAdmissionCode" char(1),
    "diagnosis5Code" varchar(7),
    "diagnosis5CodeVersion" char(1),
    "diagnosis5PresentOnAdmissionCode" char(1),
    "diagnosis6Code" varchar(7),
    "diagnosis6CodeVersion" char(1),
    "diagnosis6PresentOnAdmissionCode" char(1),
    "diagnosis7Code" varchar(7),
    "diagnosis7CodeVersion" char(1),
    "diagnosis7PresentOnAdmissionCode" char(1),
    "diagnosis8Code" varchar(7),
    "diagnosis8CodeVersion" char(1),
    "diagnosis8PresentOnAdmissionCode" char(1),
    "diagnosis9Code" varchar(7),
    "diagnosis9CodeVersion" char(1),
    "diagnosis9PresentOnAdmissionCode" char(1),
    "diagnosisAdmittingCode" varchar(7),
    "diagnosisAdmittingCodeVersion" char(1),
    "diagnosisExternal10Code" varchar(7),
    "diagnosisExternal10CodeVersion" char(1),
    "diagnosisExternal10PresentOnAdmissionCode" char(1),
    "diagnosisExternal11Code" varchar(7),
    "diagnosisExternal11CodeVersion" char(1),
    "diagnosisExternal11PresentOnAdmissionCode" char(1),
    "diagnosisExternal12Code" varchar(7),
    "diagnosisExternal12CodeVersion" char(1),
    "diagnosisExternal12PresentOnAdmissionCode" char(1),
    "diagnosisExternal1Code" varchar(7),
    "diagnosisExternal1CodeVersion" char(1),
    "diagnosisExternal1PresentOnAdmissionCode" char(1),
    "diagnosisExternal2Code" varchar(7),
    "diagnosisExternal2CodeVersion" char(1),
    "diagnosisExternal2PresentOnAdmissionCode" char(1),
    "diagnosisExternal3Code" varchar(7),
    "diagnosisExternal3CodeVersion" char(1),
    "diagnosisExternal3PresentOnAdmissionCode" char(1),
    "diagnosisExternal4Code" varchar(7),
    "diagnosisExternal4CodeVersion" char(1),
    "diagnosisExternal4PresentOnAdmissionCode" char(1),
    "diagnosisExternal5Code" varchar(7),
    "diagnosisExternal5CodeVersion" char(1),
    "diagnosisExternal5PresentOnAdmissionCode" char(1),
    "diagnosisExternal6Code" varchar(7),
    "diagnosisExternal6CodeVersion" char(1),
    "diagnosisExternal6PresentOnAdmissionCode" char(1),
    "diagnosisExternal7Code" varchar(7),
    "diagnosisExternal7CodeVersion" char(1),
    "diagnosisExternal7PresentOnAdmissionCode" char(1),
    "diagnosisExternal8Code" varchar(7),
    "diagnosisExternal8CodeVersion" char(1),
    "diagnosisExternal8PresentOnAdmissionCode" char(1),
    "diagnosisExternal9Code" varchar(7),
    "diagnosisExternal9CodeVersion" char(1),
    "diagnosisExternal9PresentOnAdmissionCode" char(1),
    "diagnosisExternalFirstCode" varchar(7),
    "diagnosisExternalFirstCodeVersion" char(1),
    "diagnosisPrincipalCode" varchar(7),
    "diagnosisPrincipalCodeVersion" char(1),
    "diagnosisRelatedGroupCd" varchar(3),
    "diagnosisRelatedGroupOutlierStayCd" char(1) not null,
    "disproportionateShareAmount" numeric,
    "drgOutlierApprovedPaymentAmount" numeric(12, 2),
    "fiscalIntermediaryClaimActionCode" char(1),
    "fiscalIntermediaryClaimProcessDate" date,
    "fiscalIntermediaryNumber" varchar(5),
    "indirectMedicalEducationAmount" numeric,
    "lifetimeReservedDaysUsedCount" numeric,
    "mcoPaidSw" char(1),
    "medicareBenefitsExhaustedDate" date,
    "nearLineRecordIdCode" char(1) not null,
    "nonUtilizationDayCount" numeric not null,
    "noncoveredCharge" numeric(12, 2) not null,
    "noncoveredStayFromDate" date,
    "noncoveredStayThroughDate" date,
    "operatingPhysicianNpi" varchar(10),
    "operatingPhysicianUpin" varchar(9),
    "organizationNpi" varchar(10),
    "otherPhysicianNpi" varchar(10),
    "otherPhysicianUpin" varchar(9),
    "partACoinsuranceLiabilityAmount" numeric(12, 2) not null,
    "passThruPerDiemAmount" numeric(12, 2) not null,
    "patientDischargeStatusCode" varchar(2) not null,
    "patientStatusCd" char(1),
    "paymentAmount" numeric(12, 2) not null,
    "primaryPayerPaidAmount" numeric(12, 2) not null,
    "procedure10Code" varchar(7),
    "procedure10CodeVersion" char(1),
    "procedure10Date" date,
    "procedure11Code" varchar(7),
    "procedure11CodeVersion" char(1),
    "procedure11Date" date,
    "procedure12Code" varchar(7),
    "procedure12CodeVersion" char(1),
    "procedure12Date" date,
    "procedure13Code" varchar(7),
    "procedure13CodeVersion" char(1),
    "procedure13Date" date,
    "procedure14Code" varchar(7),
    "procedure14CodeVersion" char(1),
    "procedure14Date" date,
    "procedure15Code" varchar(7),
    "procedure15CodeVersion" char(1),
    "procedure15Date" date,
    "procedure16Code" varchar(7),
    "procedure16CodeVersion" char(1),
    "procedure16Date" date,
    "procedure17Code" varchar(7),
    "procedure17CodeVersion" char(1),
    "procedure17Date" date,
    "procedure18Code" varchar(7),
    "procedure18CodeVersion" char(1),
    "procedure18Date" date,
    "procedure19Code" varchar(7),
    "procedure19CodeVersion" char(1),
    "procedure19Date" date,
    "procedure1Code" varchar(7),
    "procedure1CodeVersion" char(1),
    "procedure1Date" date,
    "procedure20Code" varchar(7),
    "procedure20CodeVersion" char(1),
    "procedure20Date" date,
    "procedure21Code" varchar(7),
    "procedure21CodeVersion" char(1),
    "procedure21Date" date,
    "procedure22Code" varchar(7),
    "procedure22CodeVersion" char(1),
    "procedure22Date" date,
    "procedure23Code" varchar(7),
    "procedure23CodeVersion" char(1),
    "procedure23Date" date,
    "procedure24Code" varchar(7),
    "procedure24CodeVersion" char(1),
    "procedure24Date" date,
    "procedure25Code" varchar(7),
    "procedure25CodeVersion" char(1),
    "procedure25Date" date,
    "procedure2Code" varchar(7),
    "procedure2CodeVersion" char(1),
    "procedure2Date" date,
    "procedure3Code" varchar(7),
    "procedure3CodeVersion" char(1),
    "procedure3Date" date,
    "procedure4Code" varchar(7),
    "procedure4CodeVersion" char(1),
    "procedure4Date" date,
    "procedure5Code" varchar(7),
    "procedure5CodeVersion" char(1),
    "procedure5Date" date,
    "procedure6Code" varchar(7),
    "procedure6CodeVersion" char(1),
    "procedure6Date" date,
    "procedure7Code" varchar(7),
    "procedure7CodeVersion" char(1),
    "procedure7Date" date,
    "procedure8Code" varchar(7),
    "procedure8CodeVersion" char(1),
    "procedure8Date" date,
    "procedure9Code" varchar(7),
    "procedure9CodeVersion" char(1),
    "procedure9Date" date,
    "professionalComponentCharge" numeric(12, 2) not null,
    "prospectivePaymentCode" char(1),
    "providerNumber" varchar(9) not null,
    "providerStateCode" varchar(2) not null,
    "sourceAdmissionCd" char(1),
    "totalChargeAmount" numeric(12, 2) not null,
    "totalDeductionAmount" numeric(12, 2) not null,
    "utilizationDayCount" numeric not null,
    "weeklyProcessDate" date not null,
    constraint "InpatientClaims_pkey" primary key ("claimId")
)
${logic.tablespaces-escape} tablespace "inpatientclaims_ts"
;

create table "OutpatientClaimLines" (
   "lineNumber" numeric not null,
    "parentClaim" varchar(255) not null,
    "apcOrHippsCode" varchar(5),
    "benficiaryPaymentAmount" numeric(12, 2) not null,
    "bloodDeductibleAmount" numeric(12, 2) not null,
    "cashDeductibleAmount" numeric(12, 2) not null,
    "discountCode" char(1),
    "firstMspPaidAmount" numeric(12, 2) not null,
    "hcpcsCode" varchar(5),
    "hcpcsInitialModifierCode" varchar(5),
    "hcpcsSecondModifierCode" varchar(5),
    "nationalDrugCode" varchar(24),
    "nationalDrugCodeQualifierCode" varchar(2),
    "nationalDrugCodeQuantity" numeric,
    "nonCoveredChargeAmount" numeric(12, 2) not null,
    "obligationToAcceptAsFullPaymentCode" char(1),
    "packagingCode" char(1),
    "patientResponsibilityAmount" numeric(12, 2) not null,
    "paymentAmount" numeric(12, 2) not null,
    "paymentMethodCode" varchar(2),
    "providerPaymentAmount" numeric(12, 2) not null,
    "rateAmount" numeric(12, 2) not null,
    "reducedCoinsuranceAmount" numeric(12, 2) not null,
    "revCntr1stAnsiCd" varchar(5),
    "revCntr2ndAnsiCd" varchar(5),
    "revCntr3rdAnsiCd" varchar(5),
    "revCntr4thAnsiCd" varchar(5),
    "revenueCenterCode" varchar(4) not null,
    "revenueCenterDate" date,
    "revenueCenterRenderingPhysicianNPI" varchar(12),
    "revenueCenterRenderingPhysicianUPIN" varchar(12),
    "secondMspPaidAmount" numeric(12, 2) not null,
    "statusCode" varchar(2),
    "totalChargeAmount" numeric(12, 2) not null,
    "unitCount" numeric not null,
    "wageAdjustedCoinsuranceAmount" numeric(12, 2) not null,
    constraint "OutpatientClaimLines_pkey" primary key ("lineNumber", "parentClaim")
)
${logic.tablespaces-escape} tablespace "outpatientclaimlines_ts"
;

create table "OutpatientClaims" (
   "claimId" varchar(15) not null,
    "attendingPhysicianNpi" varchar(10),
    "attendingPhysicianUpin" varchar(9),
    "beneficiaryId" varchar(15) not null,
    "beneficiaryPaymentAmount" numeric(12, 2) not null,
    "bloodDeductibleLiabilityAmount" numeric(12, 2) not null,
    "claimFacilityTypeCode" char(1) not null,
    "claimFrequencyCode" char(1) not null,
    "claimGroupId" numeric(12) not null,
    "claimNonPaymentReasonCode" varchar(2),
    "claimPrimaryPayerCode" char(1),
    "claimQueryCode" char(1) not null,
    "claimServiceClassificationTypeCode" char(1) not null,
    "claimTypeCode" varchar(2) not null,
    "coinsuranceAmount" numeric(12, 2) not null,
    "dateFrom" date not null,
    "dateThrough" date not null,
    "deductibleAmount" numeric(12, 2) not null,
    "diagnosis10Code" varchar(7),
    "diagnosis10CodeVersion" char(1),
    "diagnosis11Code" varchar(7),
    "diagnosis11CodeVersion" char(1),
    "diagnosis12Code" varchar(7),
    "diagnosis12CodeVersion" char(1),
    "diagnosis13Code" varchar(7),
    "diagnosis13CodeVersion" char(1),
    "diagnosis14Code" varchar(7),
    "diagnosis14CodeVersion" char(1),
    "diagnosis15Code" varchar(7),
    "diagnosis15CodeVersion" char(1),
    "diagnosis16Code" varchar(7),
    "diagnosis16CodeVersion" char(1),
    "diagnosis17Code" varchar(7),
    "diagnosis17CodeVersion" char(1),
    "diagnosis18Code" varchar(7),
    "diagnosis18CodeVersion" char(1),
    "diagnosis19Code" varchar(7),
    "diagnosis19CodeVersion" char(1),
    "diagnosis1Code" varchar(7),
    "diagnosis1CodeVersion" char(1),
    "diagnosis20Code" varchar(7),
    "diagnosis20CodeVersion" char(1),
    "diagnosis21Code" varchar(7),
    "diagnosis21CodeVersion" char(1),
    "diagnosis22Code" varchar(7),
    "diagnosis22CodeVersion" char(1),
    "diagnosis23Code" varchar(7),
    "diagnosis23CodeVersion" char(1),
    "diagnosis24Code" varchar(7),
    "diagnosis24CodeVersion" char(1),
    "diagnosis25Code" varchar(7),
    "diagnosis25CodeVersion" char(1),
    "diagnosis2Code" varchar(7),
    "diagnosis2CodeVersion" char(1),
    "diagnosis3Code" varchar(7),
    "diagnosis3CodeVersion" char(1),
    "diagnosis4Code" varchar(7),
    "diagnosis4CodeVersion" char(1),
    "diagnosis5Code" varchar(7),
    "diagnosis5CodeVersion" char(1),
    "diagnosis6Code" varchar(7),
    "diagnosis6CodeVersion" char(1),
    "diagnosis7Code" varchar(7),
    "diagnosis7CodeVersion" char(1),
    "diagnosis8Code" varchar(7),
    "diagnosis8CodeVersion" char(1),
    "diagnosis9Code" varchar(7),
    "diagnosis9CodeVersion" char(1),
    "diagnosisAdmission1Code" varchar(7),
    "diagnosisAdmission1CodeVersion" char(1),
    "diagnosisAdmission2Code" varchar(7),
    "diagnosisAdmission2CodeVersion" char(1),
    "diagnosisAdmission3Code" varchar(7),
    "diagnosisAdmission3CodeVersion" char(1),
    "diagnosisExternal10Code" varchar(7),
    "diagnosisExternal10CodeVersion" char(1),
    "diagnosisExternal11Code" varchar(7),
    "diagnosisExternal11CodeVersion" char(1),
    "diagnosisExternal12Code" varchar(7),
    "diagnosisExternal12CodeVersion" char(1),
    "diagnosisExternal1Code" varchar(7),
    "diagnosisExternal1CodeVersion" char(1),
    "diagnosisExternal2Code" varchar(7),
    "diagnosisExternal2CodeVersion" char(1),
    "diagnosisExternal3Code" varchar(7),
    "diagnosisExternal3CodeVersion" char(1),
    "diagnosisExternal4Code" varchar(7),
    "diagnosisExternal4CodeVersion" char(1),
    "diagnosisExternal5Code" varchar(7),
    "diagnosisExternal5CodeVersion" char(1),
    "diagnosisExternal6Code" varchar(7),
    "diagnosisExternal6CodeVersion" char(1),
    "diagnosisExternal7Code" varchar(7),
    "diagnosisExternal7CodeVersion" char(1),
    "diagnosisExternal8Code" varchar(7),
    "diagnosisExternal8CodeVersion" char(1),
    "diagnosisExternal9Code" varchar(7),
    "diagnosisExternal9CodeVersion" char(1),
    "diagnosisExternalFirstCode" varchar(7),
    "diagnosisExternalFirstCodeVersion" char(1),
    "diagnosisPrincipalCode" varchar(7),
    "diagnosisPrincipalCodeVersion" char(1),
    "fiscalIntermediaryClaimProcessDate" date,
    "fiscalIntermediaryNumber" varchar(5),
    "mcoPaidSw" char(1),
    "nearLineRecordIdCode" char(1) not null,
    "operatingPhysicianNpi" varchar(10),
    "operatingPhysicianUpin" varchar(9),
    "organizationNpi" varchar(10),
    "otherPhysicianNpi" varchar(10),
    "otherPhysicianUpin" varchar(9),
    "patientDischargeStatusCode" varchar(2),
    "paymentAmount" numeric(12, 2) not null,
    "primaryPayerPaidAmount" numeric(12, 2) not null,
    "procedure10Code" varchar(7),
    "procedure10CodeVersion" char(1),
    "procedure10Date" date,
    "procedure11Code" varchar(7),
    "procedure11CodeVersion" char(1),
    "procedure11Date" date,
    "procedure12Code" varchar(7),
    "procedure12CodeVersion" char(1),
    "procedure12Date" date,
    "procedure13Code" varchar(7),
    "procedure13CodeVersion" char(1),
    "procedure13Date" date,
    "procedure14Code" varchar(7),
    "procedure14CodeVersion" char(1),
    "procedure14Date" date,
    "procedure15Code" varchar(7),
    "procedure15CodeVersion" char(1),
    "procedure15Date" date,
    "procedure16Code" varchar(7),
    "procedure16CodeVersion" char(1),
    "procedure16Date" date,
    "procedure17Code" varchar(7),
    "procedure17CodeVersion" char(1),
    "procedure17Date" date,
    "procedure18Code" varchar(7),
    "procedure18CodeVersion" char(1),
    "procedure18Date" date,
    "procedure19Code" varchar(7),
    "procedure19CodeVersion" char(1),
    "procedure19Date" date,
    "procedure1Code" varchar(7),
    "procedure1CodeVersion" char(1),
    "procedure1Date" date,
    "procedure20Code" varchar(7),
    "procedure20CodeVersion" char(1),
    "procedure20Date" date,
    "procedure21Code" varchar(7),
    "procedure21CodeVersion" char(1),
    "procedure21Date" date,
    "procedure22Code" varchar(7),
    "procedure22CodeVersion" char(1),
    "procedure22Date" date,
    "procedure23Code" varchar(7),
    "procedure23CodeVersion" char(1),
    "procedure23Date" date,
    "procedure24Code" varchar(7),
    "procedure24CodeVersion" char(1),
    "procedure24Date" date,
    "procedure25Code" varchar(7),
    "procedure25CodeVersion" char(1),
    "procedure25Date" date,
    "procedure2Code" varchar(7),
    "procedure2CodeVersion" char(1),
    "procedure2Date" date,
    "procedure3Code" varchar(7),
    "procedure3CodeVersion" char(1),
    "procedure3Date" date,
    "procedure4Code" varchar(7),
    "procedure4CodeVersion" char(1),
    "procedure4Date" date,
    "procedure5Code" varchar(7),
    "procedure5CodeVersion" char(1),
    "procedure5Date" date,
    "procedure6Code" varchar(7),
    "procedure6CodeVersion" char(1),
    "procedure6Date" date,
    "procedure7Code" varchar(7),
    "procedure7CodeVersion" char(1),
    "procedure7Date" date,
    "procedure8Code" varchar(7),
    "procedure8CodeVersion" char(1),
    "procedure8Date" date,
    "procedure9Code" varchar(7),
    "procedure9CodeVersion" char(1),
    "procedure9Date" date,
    "professionalComponentCharge" numeric(12, 2) not null,
    "providerNumber" varchar(9) not null,
    "providerPaymentAmount" numeric(12, 2) not null,
    "providerStateCode" varchar(2) not null,
    "totalChargeAmount" numeric(12, 2) not null,
    "weeklyProcessDate" date not null,
    constraint "OutpatientClaims_pkey" primary key ("claimId")
)
${logic.tablespaces-escape} tablespace "outpatientclaims_ts"
;

create table "PartDEvents" (
   "eventId" varchar(15) not null,
    "adjustmentDeletionCode" char(1),
    "beneficiaryId" varchar(15) not null,
    "brandGenericCode" char(1),
    "catastrophicCoverageCode" char(1),
    "claimGroupId" numeric(12) not null,
    "compoundCode" ${type.int4} not null,
    "daysSupply" numeric not null,
    "dispenseAsWrittenProductSelectionCode" char(1) not null,
    "dispensingStatusCode" char(1),
    "drugCoverageStatusCode" char(1) not null,
    "fillNumber" numeric not null,
    "gapDiscountAmount" numeric(8, 2) not null,
    "grossCostAboveOutOfPocketThreshold" numeric(8, 2) not null,
    "grossCostBelowOutOfPocketThreshold" numeric(8, 2) not null,
    "lowIncomeSubsidyPaidAmount" numeric(8, 2) not null,
    "nationalDrugCode" varchar(19) not null,
    "nonstandardFormatCode" char(1),
    "otherTrueOutOfPocketPaidAmount" numeric(8, 2) not null,
    "partDPlanCoveredPaidAmount" numeric(8, 2) not null,
    "partDPlanNonCoveredPaidAmount" numeric(8, 2) not null,
    "patientLiabilityReductionOtherPaidAmount" numeric(8, 2) not null,
    "patientPaidAmount" numeric(8, 2) not null,
    "patientResidenceCode" varchar(2) not null,
    "paymentDate" date,
    "pharmacyTypeCode" varchar(2) not null,
    "planBenefitPackageId" varchar(3) not null,
    "planContractId" varchar(5) not null,
    "prescriberId" varchar(15) not null,
    "prescriberIdQualifierCode" varchar(2) not null,
    "prescriptionFillDate" date not null,
    "prescriptionOriginationCode" char(1),
    "prescriptionReferenceNumber" numeric(12) not null,
    "pricingExceptionCode" char(1),
    "quantityDispensed" numeric(10, 3) not null,
    "serviceProviderId" varchar(15) not null,
    "serviceProviderIdQualiferCode" varchar(2) not null,
    "submissionClarificationCode" varchar(2),
    "totalPrescriptionCost" numeric(8, 2) not null,
    constraint "PartDEvents_pkey" primary key ("eventId")
)
${logic.tablespaces-escape} tablespace "partdevents_ts"
;

create table "SNFClaimLines" (
   "lineNumber" numeric not null,
    "parentClaim" varchar(255) not null,
    "deductibleCoinsuranceCd" char(1),
    "hcpcsCode" varchar(5),
    "nationalDrugCodeQualifierCode" varchar(2),
    "nationalDrugCodeQuantity" numeric,
    "nonCoveredChargeAmount" numeric(12, 2) not null,
    "rateAmount" numeric(12, 2) not null,
    "revenueCenter" varchar(4) not null,
    "revenueCenterRenderingPhysicianNPI" varchar(12),
    "revenueCenterRenderingPhysicianUPIN" varchar(12),
    "totalChargeAmount" numeric(12, 2) not null,
    "unitCount" ${type.int4} not null,
    constraint "SNFClaimLines_pkey" primary key ("lineNumber", "parentClaim")
)
${logic.tablespaces-escape} tablespace "snfclaimlines_ts"
;

create table "SNFClaims" (
   "claimId" varchar(15) not null,
    "admissionTypeCd" char(1) not null,
    "attendingPhysicianNpi" varchar(10),
    "attendingPhysicianUpin" varchar(9),
    "beneficiaryDischargeDate" date,
    "beneficiaryId" varchar(15) not null,
    "bloodDeductibleLiabilityAmount" numeric(12, 2) not null,
    "bloodPintsFurnishedQty" numeric not null,
    "claimAdmissionDate" date,
    "claimFacilityTypeCode" char(1) not null,
    "claimFrequencyCode" char(1) not null,
    "claimGroupId" numeric(12) not null,
    "claimNonPaymentReasonCode" varchar(2),
    "claimPPSCapitalDisproportionateShareAmt" numeric(12, 2),
    "claimPPSCapitalExceptionAmount" numeric(12, 2),
    "claimPPSCapitalFSPAmount" numeric(12, 2),
    "claimPPSCapitalIMEAmount" numeric(12, 2),
    "claimPPSCapitalOutlierAmount" numeric(12, 2),
    "claimPPSOldCapitalHoldHarmlessAmount" numeric(12, 2),
    "claimPrimaryPayerCode" char(1),
    "claimQueryCode" char(1) not null,
    "claimServiceClassificationTypeCode" char(1) not null,
    "claimTypeCode" varchar(2) not null,
    "coinsuranceDayCount" numeric not null,
    "coveredCareThroughDate" date,
    "dateFrom" date not null,
    "dateThrough" date not null,
    "deductibleAmount" numeric(12, 2) not null,
    "diagnosis10Code" varchar(7),
    "diagnosis10CodeVersion" char(1),
    "diagnosis11Code" varchar(7),
    "diagnosis11CodeVersion" char(1),
    "diagnosis12Code" varchar(7),
    "diagnosis12CodeVersion" char(1),
    "diagnosis13Code" varchar(7),
    "diagnosis13CodeVersion" char(1),
    "diagnosis14Code" varchar(7),
    "diagnosis14CodeVersion" char(1),
    "diagnosis15Code" varchar(7),
    "diagnosis15CodeVersion" char(1),
    "diagnosis16Code" varchar(7),
    "diagnosis16CodeVersion" char(1),
    "diagnosis17Code" varchar(7),
    "diagnosis17CodeVersion" char(1),
    "diagnosis18Code" varchar(7),
    "diagnosis18CodeVersion" char(1),
    "diagnosis19Code" varchar(7),
    "diagnosis19CodeVersion" char(1),
    "diagnosis1Code" varchar(7),
    "diagnosis1CodeVersion" char(1),
    "diagnosis20Code" varchar(7),
    "diagnosis20CodeVersion" char(1),
    "diagnosis21Code" varchar(7),
    "diagnosis21CodeVersion" char(1),
    "diagnosis22Code" varchar(7),
    "diagnosis22CodeVersion" char(1),
    "diagnosis23Code" varchar(7),
    "diagnosis23CodeVersion" char(1),
    "diagnosis24Code" varchar(7),
    "diagnosis24CodeVersion" char(1),
    "diagnosis25Code" varchar(7),
    "diagnosis25CodeVersion" char(1),
    "diagnosis2Code" varchar(7),
    "diagnosis2CodeVersion" char(1),
    "diagnosis3Code" varchar(7),
    "diagnosis3CodeVersion" char(1),
    "diagnosis4Code" varchar(7),
    "diagnosis4CodeVersion" char(1),
    "diagnosis5Code" varchar(7),
    "diagnosis5CodeVersion" char(1),
    "diagnosis6Code" varchar(7),
    "diagnosis6CodeVersion" char(1),
    "diagnosis7Code" varchar(7),
    "diagnosis7CodeVersion" char(1),
    "diagnosis8Code" varchar(7),
    "diagnosis8CodeVersion" char(1),
    "diagnosis9Code" varchar(7),
    "diagnosis9CodeVersion" char(1),
    "diagnosisAdmittingCode" varchar(7),
    "diagnosisAdmittingCodeVersion" char(1),
    "diagnosisExternal10Code" varchar(7),
    "diagnosisExternal10CodeVersion" char(1),
    "diagnosisExternal11Code" varchar(7),
    "diagnosisExternal11CodeVersion" char(1),
    "diagnosisExternal12Code" varchar(7),
    "diagnosisExternal12CodeVersion" char(1),
    "diagnosisExternal1Code" varchar(7),
    "diagnosisExternal1CodeVersion" char(1),
    "diagnosisExternal2Code" varchar(7),
    "diagnosisExternal2CodeVersion" char(1),
    "diagnosisExternal3Code" varchar(7),
    "diagnosisExternal3CodeVersion" char(1),
    "diagnosisExternal4Code" varchar(7),
    "diagnosisExternal4CodeVersion" char(1),
    "diagnosisExternal5Code" varchar(7),
    "diagnosisExternal5CodeVersion" char(1),
    "diagnosisExternal6Code" varchar(7),
    "diagnosisExternal6CodeVersion" char(1),
    "diagnosisExternal7Code" varchar(7),
    "diagnosisExternal7CodeVersion" char(1),
    "diagnosisExternal8Code" varchar(7),
    "diagnosisExternal8CodeVersion" char(1),
    "diagnosisExternal9Code" varchar(7),
    "diagnosisExternal9CodeVersion" char(1),
    "diagnosisExternalFirstCode" varchar(7),
    "diagnosisExternalFirstCodeVersion" char(1),
    "diagnosisPrincipalCode" varchar(7),
    "diagnosisPrincipalCodeVersion" char(1),
    "diagnosisRelatedGroupCd" varchar(3),
    "fiscalIntermediaryClaimActionCode" char(1),
    "fiscalIntermediaryClaimProcessDate" date,
    "fiscalIntermediaryNumber" varchar(5),
    "mcoPaidSw" char(1),
    "medicareBenefitsExhaustedDate" date,
    "nearLineRecordIdCode" char(1) not null,
    "nonUtilizationDayCount" numeric not null,
    "noncoveredCharge" numeric(12, 2) not null,
    "noncoveredStayFromDate" date,
    "noncoveredStayThroughDate" date,
    "operatingPhysicianNpi" varchar(10),
    "operatingPhysicianUpin" varchar(9),
    "organizationNpi" varchar(10),
    "otherPhysicianNpi" varchar(10),
    "otherPhysicianUpin" varchar(9),
    "partACoinsuranceLiabilityAmount" numeric(12, 2) not null,
    "patientDischargeStatusCode" varchar(2) not null,
    "patientStatusCd" char(1),
    "paymentAmount" numeric(12, 2) not null,
    "primaryPayerPaidAmount" numeric(12, 2) not null,
    "procedure10Code" varchar(7),
    "procedure10CodeVersion" char(1),
    "procedure10Date" date,
    "procedure11Code" varchar(7),
    "procedure11CodeVersion" char(1),
    "procedure11Date" date,
    "procedure12Code" varchar(7),
    "procedure12CodeVersion" char(1),
    "procedure12Date" date,
    "procedure13Code" varchar(7),
    "procedure13CodeVersion" char(1),
    "procedure13Date" date,
    "procedure14Code" varchar(7),
    "procedure14CodeVersion" char(1),
    "procedure14Date" date,
    "procedure15Code" varchar(7),
    "procedure15CodeVersion" char(1),
    "procedure15Date" date,
    "procedure16Code" varchar(7),
    "procedure16CodeVersion" char(1),
    "procedure16Date" date,
    "procedure17Code" varchar(7),
    "procedure17CodeVersion" char(1),
    "procedure17Date" date,
    "procedure18Code" varchar(7),
    "procedure18CodeVersion" char(1),
    "procedure18Date" date,
    "procedure19Code" varchar(7),
    "procedure19CodeVersion" char(1),
    "procedure19Date" date,
    "procedure1Code" varchar(7),
    "procedure1CodeVersion" char(1),
    "procedure1Date" date,
    "procedure20Code" varchar(7),
    "procedure20CodeVersion" char(1),
    "procedure20Date" date,
    "procedure21Code" varchar(7),
    "procedure21CodeVersion" char(1),
    "procedure21Date" date,
    "procedure22Code" varchar(7),
    "procedure22CodeVersion" char(1),
    "procedure22Date" date,
    "procedure23Code" varchar(7),
    "procedure23CodeVersion" char(1),
    "procedure23Date" date,
    "procedure24Code" varchar(7),
    "procedure24CodeVersion" char(1),
    "procedure24Date" date,
    "procedure25Code" varchar(7),
    "procedure25CodeVersion" char(1),
    "procedure25Date" date,
    "procedure2Code" varchar(7),
    "procedure2CodeVersion" char(1),
    "procedure2Date" date,
    "procedure3Code" varchar(7),
    "procedure3CodeVersion" char(1),
    "procedure3Date" date,
    "procedure4Code" varchar(7),
    "procedure4CodeVersion" char(1),
    "procedure4Date" date,
    "procedure5Code" varchar(7),
    "procedure5CodeVersion" char(1),
    "procedure5Date" date,
    "procedure6Code" varchar(7),
    "procedure6CodeVersion" char(1),
    "procedure6Date" date,
    "procedure7Code" varchar(7),
    "procedure7CodeVersion" char(1),
    "procedure7Date" date,
    "procedure8Code" varchar(7),
    "procedure8CodeVersion" char(1),
    "procedure8Date" date,
    "procedure9Code" varchar(7),
    "procedure9CodeVersion" char(1),
    "procedure9Date" date,
    "prospectivePaymentCode" char(1),
    "providerNumber" varchar(9) not null,
    "providerStateCode" varchar(2) not null,
    "qualifiedStayFromDate" date,
    "qualifiedStayThroughDate" date,
    "sourceAdmissionCd" char(1),
    "totalChargeAmount" numeric(12, 2) not null,
    "totalDeductionAmount" numeric(12, 2) not null,
    "utilizationDayCount" numeric not null,
    "weeklyProcessDate" date not null,
    constraint "SNFClaims_pkey" primary key ("claimId")
)
${logic.tablespaces-escape} tablespace "snfclaims_ts"
;

alter table "CarrierClaimLines" 
   add constraint "CarrierClaimLines_parentClaim_to_CarrierClaims" 
   foreign key ("parentClaim") 
   references "CarrierClaims";

alter table "DMEClaimLines" 
   add constraint "DMEClaimLines_parentClaim_to_DMEClaims" 
   foreign key ("parentClaim") 
   references "DMEClaims";

alter table "HHAClaimLines" 
   add constraint "HHAClaimLines_parentClaim_to_HHAClaims" 
   foreign key ("parentClaim") 
   references "HHAClaims";

alter table "HospiceClaimLines" 
   add constraint "HospiceClaimLines_parentClaim_to_HospiceClaims" 
   foreign key ("parentClaim") 
   references "HospiceClaims";

alter table "InpatientClaimLines" 
   add constraint "InpatientClaimLines_parentClaim_to_InpatientClaims" 
   foreign key ("parentClaim") 
   references "InpatientClaims";

alter table "OutpatientClaimLines" 
   add constraint "OutpatientClaimLines_parentClaim_to_OutpatientClaims" 
   foreign key ("parentClaim") 
   references "OutpatientClaims";

alter table "SNFClaimLines" 
   add constraint "SNFClaimLines_parentClaim_to_SNFClaims" 
   foreign key ("parentClaim") 
   references "SNFClaims";
