-- NEW_SCHEMA_OUTPATIENT_CLAIMS.SQL
-- flyway migration for OUTPATIENT_CLAIMS and OUTPATIENT_CLAIM_LINES tables into
-- a new schema structure that:
--   1) changes data type of CLM_ID, BENE_ID from varchar to BIGINT.
--   2) change data type of CLM_GRP_ID from numeric to BIGINT
--   3) organizes parent claim table (OUTPATIENT_CLAIMS) such that common
--      claims data columns are organized at top of table structure.
--
--      The following db columns were redefined from NUMERIC to more
--      appropriate data type(s):
--
--           clm_line_num - changed to smallint
--
-- Once current table data is migrated to new table name/structure, a 
-- subsequent PR will be deployed that changes the ORM model(s) and
-- operational code for Inpatient Claims table(s).
--
-- HSQL differs from PSQL (postgres) in that the table defintion
-- must be explicitly declared prior to loading data into the
-- target table. PSQL can derive the table structure based on
-- the data input (i.e., column name, data type). Thus, for HSQL,
-- we need to explicitly define the table structure prior to loading data.
--
-- For HSQL, explicitly define/create a new OUTPATIENT_CLAIMS_NEW table in
-- the current PUBLIC schema

${logic.hsql-only}  create table public.outpatient_claims_new (
${logic.hsql-only}    clm_id                           bigint not null,
${logic.hsql-only}    bene_id                          bigint not null,
${logic.hsql-only}    clm_grp_id                       bigint not null,
${logic.hsql-only}    last_updated                     timestamp with time zone,
${logic.hsql-only}    clm_from_dt                      date not null,
${logic.hsql-only}    clm_thru_dt                      date not null,
${logic.hsql-only}    clm_fac_type_cd                  char(1) not null,
${logic.hsql-only}    clm_freq_cd                      char(1) not null,
${logic.hsql-only}    final_action                     char(1) not null,
${logic.hsql-only}    clm_tot_chrg_amt                 numeric(12,2) not null,
${logic.hsql-only}    clm_pmt_amt                      numeric(12,2) not null,
${logic.hsql-only}    clm_op_bene_pmt_amt              numeric(12,2) not null,
${logic.hsql-only}    clm_op_prvdr_pmt_amt             numeric(12,2) not null,
${logic.hsql-only}    claim_query_code                 char(1) not null,
${logic.hsql-only}    clm_srvc_clsfctn_type_cd         char(1) not null,
${logic.hsql-only}    clm_mdcr_non_pmt_rsn_cd          varchar(2),
${logic.hsql-only}    clm_mco_pd_sw                    char(1),
${logic.hsql-only}    nch_clm_type_cd                  varchar(2) not null,
${logic.hsql-only}    nch_near_line_rec_ident_cd       char(1) not null,
${logic.hsql-only}    nch_wkly_proc_dt                 date not null,
${logic.hsql-only}    nch_bene_blood_ddctbl_lblty_am   numeric(12,2) not null,
${logic.hsql-only}    nch_bene_ptb_coinsrnc_amt        numeric(12,2) not null,
${logic.hsql-only}    nch_bene_ptb_ddctbl_amt          numeric(12,2) not null,
${logic.hsql-only}    nch_prmry_pyr_clm_pd_amt         numeric(12,2) not null,
${logic.hsql-only}    nch_profnl_cmpnt_chrg_amt        numeric(12,2) not null,
${logic.hsql-only}    nch_prmry_pyr_cd                 char(1),
${logic.hsql-only}    prvdr_num                        varchar(9) not null,
${logic.hsql-only}    prvdr_state_cd                   varchar(2) not null,
${logic.hsql-only}    at_physn_npi                     varchar(10),
${logic.hsql-only}    at_physn_upin                    varchar(9),
${logic.hsql-only}    op_physn_npi                     varchar(10),
${logic.hsql-only}    op_physn_upin                    varchar(9),
${logic.hsql-only}    ot_physn_npi                     varchar(10),
${logic.hsql-only}    ot_physn_upin                    varchar(9),
${logic.hsql-only}    org_npi_num                      varchar(10),
${logic.hsql-only}    prncpal_dgns_cd                  varchar(7),
${logic.hsql-only}    prncpal_dgns_vrsn_cd             char(1),
${logic.hsql-only}    ptnt_dschrg_stus_cd              varchar(2),
${logic.hsql-only}    fi_clm_proc_dt                   date,
${logic.hsql-only}    fi_doc_clm_cntl_num              varchar(23),
${logic.hsql-only}    fi_num                           varchar(5),
${logic.hsql-only}    fi_orig_clm_cntl_num             varchar(23),
${logic.hsql-only}    fst_dgns_e_cd                    varchar(7),
${logic.hsql-only}    fst_dgns_e_vrsn_cd               char(1),
${logic.hsql-only}    rsn_visit_cd1                    varchar(7),
${logic.hsql-only}    rsn_visit_vrsn_cd1               char(1),
${logic.hsql-only}    rsn_visit_cd2                    varchar(7),
${logic.hsql-only}    rsn_visit_vrsn_cd2               char(1),
${logic.hsql-only}    rsn_visit_cd3                    varchar(7),
${logic.hsql-only}    rsn_visit_vrsn_cd3               char(1),
${logic.hsql-only}    prcdr_dt1                        date,
${logic.hsql-only}    icd_dgns_cd1                     varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd1                char(1),
${logic.hsql-only}    icd_prcdr_cd1                    varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd1               char(1),
${logic.hsql-only}    icd_dgns_e_cd1                   varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd1              char(1),
${logic.hsql-only}    prcdr_dt2                        date,
${logic.hsql-only}    icd_dgns_cd2                     varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd2                char(1),
${logic.hsql-only}    icd_prcdr_cd2                    varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd2               char(1),
${logic.hsql-only}    icd_dgns_e_cd2                   varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd2              char(1),
${logic.hsql-only}    prcdr_dt3                        date,
${logic.hsql-only}    icd_dgns_cd3                     varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd3                char(1),
${logic.hsql-only}    icd_prcdr_cd3                    varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd3               char(1),
${logic.hsql-only}    icd_dgns_e_cd3                   varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd3              char(1),
${logic.hsql-only}    prcdr_dt4                        date,
${logic.hsql-only}    icd_dgns_cd4                     varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd4                char(1),
${logic.hsql-only}    icd_prcdr_cd4                    varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd4               char(1),
${logic.hsql-only}    icd_dgns_e_cd4                   varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd4              char(1),
${logic.hsql-only}    prcdr_dt5                        date,
${logic.hsql-only}    icd_dgns_cd5                     varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd5                char(1),
${logic.hsql-only}    icd_prcdr_cd5                    varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd5               char(1),
${logic.hsql-only}    icd_dgns_e_cd5                   varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd5              char(1),
${logic.hsql-only}    prcdr_dt6                        date,
${logic.hsql-only}    icd_dgns_cd6                     varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd6                char(1),
${logic.hsql-only}    icd_prcdr_cd6                    varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd6               char(1),
${logic.hsql-only}    icd_dgns_e_cd6                   varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd6              char(1),
${logic.hsql-only}    prcdr_dt7                        date,
${logic.hsql-only}    icd_dgns_cd7                     varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd7                char(1),
${logic.hsql-only}    icd_prcdr_cd7                    varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd7               char(1),
${logic.hsql-only}    icd_dgns_e_cd7                   varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd7              char(1),
${logic.hsql-only}    prcdr_dt8                        date,
${logic.hsql-only}    icd_dgns_cd8                     varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd8                char(1),
${logic.hsql-only}    icd_prcdr_cd8                    varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd8               char(1),
${logic.hsql-only}    icd_dgns_e_cd8                   varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd8              char(1),
${logic.hsql-only}    prcdr_dt9                        date,
${logic.hsql-only}    icd_dgns_cd9                     varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd9                char(1),
${logic.hsql-only}    icd_prcdr_cd9                    varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd9               char(1),
${logic.hsql-only}    icd_dgns_e_cd9                   varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd9              char(1),
${logic.hsql-only}    prcdr_dt10                       date,
${logic.hsql-only}    icd_dgns_cd10                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd10               char(1),
${logic.hsql-only}    icd_prcdr_cd10                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd10              char(1),
${logic.hsql-only}    icd_dgns_e_cd10                  varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd10             char(1),
${logic.hsql-only}    prcdr_dt11                       date,
${logic.hsql-only}    icd_dgns_cd11                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd11               char(1),
${logic.hsql-only}    icd_prcdr_cd11                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd11              char(1),
${logic.hsql-only}    icd_dgns_e_cd11                  varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd11             char(1),
${logic.hsql-only}    prcdr_dt12                       date,
${logic.hsql-only}    icd_dgns_cd12                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd12               char(1),
${logic.hsql-only}    icd_prcdr_cd12                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd12              char(1),
${logic.hsql-only}    icd_dgns_e_cd12                  varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd12             char(1),
${logic.hsql-only}    prcdr_dt13                       date,
${logic.hsql-only}    icd_dgns_cd13                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd13               char(1),
${logic.hsql-only}    icd_prcdr_cd13                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd13              char(1),
${logic.hsql-only}    prcdr_dt14                       date,
${logic.hsql-only}    icd_dgns_cd14                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd14               char(1),
${logic.hsql-only}    icd_prcdr_cd14                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd14              char(1),
${logic.hsql-only}    prcdr_dt15                       date,
${logic.hsql-only}    icd_dgns_cd15                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd15               char(1),
${logic.hsql-only}    icd_prcdr_cd15                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd15              char(1),
${logic.hsql-only}    prcdr_dt16                       date,
${logic.hsql-only}    icd_dgns_cd16                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd16               char(1),
${logic.hsql-only}    icd_prcdr_cd16                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd16              char(1),
${logic.hsql-only}    prcdr_dt17                       date,
${logic.hsql-only}    icd_dgns_cd17                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd17               char(1),
${logic.hsql-only}    icd_prcdr_cd17                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd17              char(1),
${logic.hsql-only}    prcdr_dt18                       date,
${logic.hsql-only}    icd_dgns_cd18                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd18               char(1),
${logic.hsql-only}    icd_prcdr_cd18                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd18              char(1),
${logic.hsql-only}    prcdr_dt19                       date,
${logic.hsql-only}    icd_dgns_cd19                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd19               char(1),
${logic.hsql-only}    icd_prcdr_cd19                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd19              char(1),
${logic.hsql-only}    prcdr_dt20                       date,
${logic.hsql-only}    icd_dgns_cd20                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd20               char(1),
${logic.hsql-only}    icd_prcdr_cd20                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd20              char(1),
${logic.hsql-only}    prcdr_dt21                       date,
${logic.hsql-only}    icd_dgns_cd21                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd21               char(1),
${logic.hsql-only}    icd_prcdr_cd21                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd21              char(1),
${logic.hsql-only}    prcdr_dt22                       date,
${logic.hsql-only}    icd_dgns_cd22                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd22               char(1),
${logic.hsql-only}    icd_prcdr_cd22                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd22              char(1),
${logic.hsql-only}    prcdr_dt23                       date,
${logic.hsql-only}    icd_dgns_cd23                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd23               char(1),
${logic.hsql-only}    icd_prcdr_cd23                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd23              char(1),
${logic.hsql-only}    prcdr_dt24                       date,
${logic.hsql-only}    icd_dgns_cd24                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd24               char(1),
${logic.hsql-only}    icd_prcdr_cd24                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd24              char(1),
${logic.hsql-only}    prcdr_dt25                       date,
${logic.hsql-only}    icd_dgns_cd25                    varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd25               char(1),
${logic.hsql-only}    icd_prcdr_cd25                   varchar(7),
${logic.hsql-only}    icd_prcdr_vrsn_cd25              char(1),
${logic.hsql-only} constraint public.outpatient_claims_new_pkey
${logic.hsql-only} primary key (clm_id) );
--
-- create a new OUTPATIENT_CLAIM_LINES_NEW table in the current PUBLIC schema
--
${logic.hsql-only}  create table public.outpatient_claim_lines_new (
${logic.hsql-only}    clm_id                           bigint not null,
${logic.hsql-only}    clm_line_num                     smallint not null,
${logic.hsql-only}    rev_cntr                         varchar(4) not null,
${logic.hsql-only}    rev_cntr_unit_cnt                numeric not null,
${logic.hsql-only}    rev_cntr_rate_amt                numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_tot_chrg_amt            numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_ncvrd_chrg_amt          numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_coinsrnc_wge_adjstd_c   numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_bene_pmt_amt            numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_blood_ddctbl_amt        numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_cash_ddctbl_amt         numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_rdcd_coinsrnc_amt       numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_pmt_amt_amt             numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_prvdr_pmt_amt           numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_dt                      date,
${logic.hsql-only}    rev_cntr_ptnt_rspnsblty_pmt      numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_ndc_qty_qlfr_cd         varchar(2),
${logic.hsql-only}    rev_cntr_ndc_qty                 numeric,
${logic.hsql-only}    rev_cntr_1st_ansi_cd             varchar(5),
${logic.hsql-only}    rev_cntr_1st_msp_pd_amt          numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_2nd_ansi_cd             varchar(5),
${logic.hsql-only}    rev_cntr_2nd_msp_pd_amt          numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_3rd_ansi_cd             varchar(5),
${logic.hsql-only}    rev_cntr_4th_ansi_cd             varchar(5),
${logic.hsql-only}    rev_cntr_apc_hipps_cd            varchar(5),
${logic.hsql-only}    rev_cntr_dscnt_ind_cd            char(1),
${logic.hsql-only}    rev_cntr_ide_ndc_upc_num         varchar(24),
${logic.hsql-only}    rev_cntr_otaf_pmt_cd             char(1),
${logic.hsql-only}    rev_cntr_packg_ind_cd            char(1),
${logic.hsql-only}    rev_cntr_pmt_mthd_ind_cd         varchar(2),
${logic.hsql-only}    rev_cntr_stus_ind_cd             varchar(2),
${logic.hsql-only}    hcpcs_cd                         varchar(5),
${logic.hsql-only}    hcpcs_2nd_mdfr_cd                varchar(5),
${logic.hsql-only}    hcpcs_1st_mdfr_cd                varchar(5),
${logic.hsql-only}    rndrng_physn_npi                 varchar(12),
${logic.hsql-only}    rndrng_physn_upin                varchar(12),
${logic.hsql-only} constraint public.outpatient_claim_lines_new_pkey
${logic.hsql-only} primary key (clm_id, clm_line_num) );
--
-- migrate data via INSERT from current INPATIENT_CLAIMS table to INPATIENT_CLAIMS_NEW table
--
${logic.psql-only} SET max_parallel_workers = 24;
${logic.psql-only} SET max_parallel_workers_per_gather = 20;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;

${logic.hsql-only} insert into public.outpatient_claims_new (
${logic.hsql-only}    clm_id,
${logic.hsql-only}    bene_id,
${logic.hsql-only}    clm_grp_id,
${logic.hsql-only}    last_updated,
${logic.hsql-only}    clm_from_dt,
${logic.hsql-only}    clm_thru_dt,
${logic.hsql-only}    clm_fac_type_cd,
${logic.hsql-only}    clm_freq_cd,
${logic.hsql-only}    final_action,
${logic.hsql-only}    clm_tot_chrg_amt,
${logic.hsql-only}    clm_pmt_amt,
${logic.hsql-only}    clm_op_bene_pmt_amt,
${logic.hsql-only}    clm_op_prvdr_pmt_amt,
${logic.hsql-only}    claim_query_code,
${logic.hsql-only}    clm_srvc_clsfctn_type_cd,
${logic.hsql-only}    clm_mdcr_non_pmt_rsn_cd,
${logic.hsql-only}    clm_mco_pd_sw,
${logic.hsql-only}    nch_clm_type_cd,
${logic.hsql-only}    nch_near_line_rec_ident_cd,
${logic.hsql-only}    nch_wkly_proc_dt,
${logic.hsql-only}    nch_bene_blood_ddctbl_lblty_am,
${logic.hsql-only}    nch_bene_ptb_coinsrnc_amt,
${logic.hsql-only}    nch_bene_ptb_ddctbl_amt,
${logic.hsql-only}    nch_prmry_pyr_clm_pd_amt,
${logic.hsql-only}    nch_profnl_cmpnt_chrg_amt,
${logic.hsql-only}    nch_prmry_pyr_cd,
${logic.hsql-only}    prvdr_num,
${logic.hsql-only}    prvdr_state_cd,
${logic.hsql-only}    at_physn_npi,
${logic.hsql-only}    at_physn_upin,
${logic.hsql-only}    op_physn_npi,
${logic.hsql-only}    op_physn_upin,
${logic.hsql-only}    ot_physn_npi,
${logic.hsql-only}    ot_physn_upin,
${logic.hsql-only}    org_npi_num,
${logic.hsql-only}    prncpal_dgns_cd,
${logic.hsql-only}    prncpal_dgns_vrsn_cd,
${logic.hsql-only}    ptnt_dschrg_stus_cd,
${logic.hsql-only}    fi_clm_proc_dt,
${logic.hsql-only}    fi_doc_clm_cntl_num,
${logic.hsql-only}    fi_num,
${logic.hsql-only}    fi_orig_clm_cntl_num,
${logic.hsql-only}    fst_dgns_e_cd,
${logic.hsql-only}    fst_dgns_e_vrsn_cd,
${logic.hsql-only}    rsn_visit_cd1,
${logic.hsql-only}    rsn_visit_vrsn_cd1,
${logic.hsql-only}    rsn_visit_cd2,
${logic.hsql-only}    rsn_visit_vrsn_cd2,
${logic.hsql-only}    rsn_visit_cd3,
${logic.hsql-only}    rsn_visit_vrsn_cd3,
${logic.hsql-only}    prcdr_dt1,
${logic.hsql-only}    icd_dgns_cd1,
${logic.hsql-only}    icd_dgns_vrsn_cd1,
${logic.hsql-only}    icd_prcdr_cd1,
${logic.hsql-only}    icd_prcdr_vrsn_cd1,
${logic.hsql-only}    icd_dgns_e_cd1,
${logic.hsql-only}    icd_dgns_e_vrsn_cd1,
${logic.hsql-only}    prcdr_dt2,
${logic.hsql-only}    icd_dgns_cd2,
${logic.hsql-only}    icd_dgns_vrsn_cd2,
${logic.hsql-only}    icd_prcdr_cd2,
${logic.hsql-only}    icd_prcdr_vrsn_cd2,
${logic.hsql-only}    icd_dgns_e_cd2,
${logic.hsql-only}    icd_dgns_e_vrsn_cd2,
${logic.hsql-only}    prcdr_dt3,
${logic.hsql-only}    icd_dgns_cd3,
${logic.hsql-only}    icd_dgns_vrsn_cd3,
${logic.hsql-only}    icd_prcdr_cd3,
${logic.hsql-only}    icd_prcdr_vrsn_cd3,
${logic.hsql-only}    icd_dgns_e_cd3,
${logic.hsql-only}    icd_dgns_e_vrsn_cd3,
${logic.hsql-only}    prcdr_dt4,
${logic.hsql-only}    icd_dgns_cd4,
${logic.hsql-only}    icd_dgns_vrsn_cd4,
${logic.hsql-only}    icd_prcdr_cd4,
${logic.hsql-only}    icd_prcdr_vrsn_cd4,
${logic.hsql-only}    icd_dgns_e_cd4,
${logic.hsql-only}    icd_dgns_e_vrsn_cd4,
${logic.hsql-only}    prcdr_dt5,
${logic.hsql-only}    icd_dgns_cd5,
${logic.hsql-only}    icd_dgns_vrsn_cd5,
${logic.hsql-only}    icd_prcdr_cd5,
${logic.hsql-only}    icd_prcdr_vrsn_cd5,
${logic.hsql-only}    icd_dgns_e_cd5,
${logic.hsql-only}    icd_dgns_e_vrsn_cd5,
${logic.hsql-only}    prcdr_dt6,
${logic.hsql-only}    icd_dgns_cd6,
${logic.hsql-only}    icd_dgns_vrsn_cd6,
${logic.hsql-only}    icd_prcdr_cd6,
${logic.hsql-only}    icd_prcdr_vrsn_cd6,
${logic.hsql-only}    icd_dgns_e_cd6,
${logic.hsql-only}    icd_dgns_e_vrsn_cd6,
${logic.hsql-only}    prcdr_dt7,
${logic.hsql-only}    icd_dgns_cd7,
${logic.hsql-only}    icd_dgns_vrsn_cd7,
${logic.hsql-only}    icd_prcdr_cd7,
${logic.hsql-only}    icd_prcdr_vrsn_cd7,
${logic.hsql-only}    icd_dgns_e_cd7,
${logic.hsql-only}    icd_dgns_e_vrsn_cd7,
${logic.hsql-only}    prcdr_dt8,
${logic.hsql-only}    icd_dgns_cd8,
${logic.hsql-only}    icd_dgns_vrsn_cd8,
${logic.hsql-only}    icd_prcdr_cd8,
${logic.hsql-only}    icd_prcdr_vrsn_cd8,
${logic.hsql-only}    icd_dgns_e_cd8,
${logic.hsql-only}    icd_dgns_e_vrsn_cd8,
${logic.hsql-only}    prcdr_dt9,
${logic.hsql-only}    icd_dgns_cd9,
${logic.hsql-only}    icd_dgns_vrsn_cd9,
${logic.hsql-only}    icd_prcdr_cd9,
${logic.hsql-only}    icd_prcdr_vrsn_cd9,
${logic.hsql-only}    icd_dgns_e_cd9,
${logic.hsql-only}    icd_dgns_e_vrsn_cd9,
${logic.hsql-only}    prcdr_dt10,
${logic.hsql-only}    icd_dgns_cd10,
${logic.hsql-only}    icd_dgns_vrsn_cd10,
${logic.hsql-only}    icd_prcdr_cd10,
${logic.hsql-only}    icd_prcdr_vrsn_cd10,
${logic.hsql-only}    icd_dgns_e_cd10,
${logic.hsql-only}    icd_dgns_e_vrsn_cd10,
${logic.hsql-only}    prcdr_dt11,
${logic.hsql-only}    icd_dgns_cd11,
${logic.hsql-only}    icd_dgns_vrsn_cd11,
${logic.hsql-only}    icd_prcdr_cd11,
${logic.hsql-only}    icd_prcdr_vrsn_cd11,
${logic.hsql-only}    icd_dgns_e_cd11,
${logic.hsql-only}    icd_dgns_e_vrsn_cd11,
${logic.hsql-only}    prcdr_dt12,
${logic.hsql-only}    icd_dgns_cd12,
${logic.hsql-only}    icd_dgns_vrsn_cd12,
${logic.hsql-only}    icd_prcdr_cd12,
${logic.hsql-only}    icd_prcdr_vrsn_cd12,
${logic.hsql-only}    icd_dgns_e_cd12,
${logic.hsql-only}    icd_dgns_e_vrsn_cd12,
${logic.hsql-only}    prcdr_dt13,
${logic.hsql-only}    icd_dgns_cd13,
${logic.hsql-only}    icd_dgns_vrsn_cd13,
${logic.hsql-only}    icd_prcdr_cd13,
${logic.hsql-only}    icd_prcdr_vrsn_cd13,
${logic.hsql-only}    prcdr_dt14,
${logic.hsql-only}    icd_dgns_cd14,
${logic.hsql-only}    icd_dgns_vrsn_cd14,
${logic.hsql-only}    icd_prcdr_cd14,
${logic.hsql-only}    icd_prcdr_vrsn_cd14,
${logic.hsql-only}    prcdr_dt15,
${logic.hsql-only}    icd_dgns_cd15,
${logic.hsql-only}    icd_dgns_vrsn_cd15,
${logic.hsql-only}    icd_prcdr_cd15,
${logic.hsql-only}    icd_prcdr_vrsn_cd15,
${logic.hsql-only}    prcdr_dt16,
${logic.hsql-only}    icd_dgns_cd16,
${logic.hsql-only}    icd_dgns_vrsn_cd16,
${logic.hsql-only}    icd_prcdr_cd16,
${logic.hsql-only}    icd_prcdr_vrsn_cd16,
${logic.hsql-only}    prcdr_dt17,
${logic.hsql-only}    icd_dgns_cd17,
${logic.hsql-only}    icd_dgns_vrsn_cd17,
${logic.hsql-only}    icd_prcdr_cd17,
${logic.hsql-only}    icd_prcdr_vrsn_cd17,
${logic.hsql-only}    prcdr_dt18,
${logic.hsql-only}    icd_dgns_cd18,
${logic.hsql-only}    icd_dgns_vrsn_cd18,
${logic.hsql-only}    icd_prcdr_cd18,
${logic.hsql-only}    icd_prcdr_vrsn_cd18,
${logic.hsql-only}    prcdr_dt19,
${logic.hsql-only}    icd_dgns_cd19,
${logic.hsql-only}    icd_dgns_vrsn_cd19,
${logic.hsql-only}    icd_prcdr_cd19,
${logic.hsql-only}    icd_prcdr_vrsn_cd19,
${logic.hsql-only}    prcdr_dt20,
${logic.hsql-only}    icd_dgns_cd20,
${logic.hsql-only}    icd_dgns_vrsn_cd20,
${logic.hsql-only}    icd_prcdr_cd20,
${logic.hsql-only}    icd_prcdr_vrsn_cd20,
${logic.hsql-only}    prcdr_dt21,
${logic.hsql-only}    icd_dgns_cd21,
${logic.hsql-only}    icd_dgns_vrsn_cd21,
${logic.hsql-only}    icd_prcdr_cd21,
${logic.hsql-only}    icd_prcdr_vrsn_cd21,
${logic.hsql-only}    prcdr_dt22,
${logic.hsql-only}    icd_dgns_cd22,
${logic.hsql-only}    icd_dgns_vrsn_cd22,
${logic.hsql-only}    icd_prcdr_cd22,
${logic.hsql-only}    icd_prcdr_vrsn_cd22,
${logic.hsql-only}    prcdr_dt23,
${logic.hsql-only}    icd_dgns_cd23,
${logic.hsql-only}    icd_dgns_vrsn_cd23,
${logic.hsql-only}    icd_prcdr_cd23,
${logic.hsql-only}    icd_prcdr_vrsn_cd23,
${logic.hsql-only}    prcdr_dt24,
${logic.hsql-only}    icd_dgns_cd24,
${logic.hsql-only}    icd_dgns_vrsn_cd24,
${logic.hsql-only}    icd_prcdr_cd24,
${logic.hsql-only}    icd_prcdr_vrsn_cd24,
${logic.hsql-only}    prcdr_dt25,
${logic.hsql-only}    icd_dgns_cd25,
${logic.hsql-only}    icd_dgns_vrsn_cd25,
${logic.hsql-only}    icd_prcdr_cd25,
${logic.hsql-only}    icd_prcdr_vrsn_cd25 )
--
-- PSQL allows us to dynamically create a table via the
-- associated SELECT statement used to populate the table.
--
${logic.psql-only} create table public.outpatient_claims_new as
select 
${logic.hsql-only}  convert(clm_id, SQL_BIGINT),
${logic.hsql-only}  convert(bene_id, SQL_BIGINT),
${logic.hsql-only}  convert(clm_grp_id, SQL_BIGINT),
${logic.psql-only}  clm_id::bigint,
${logic.psql-only}  bene_id::bigint,
${logic.psql-only}  clm_grp_id::bigint,  
                    last_updated,
                    clm_from_dt,
                    clm_thru_dt,
                    clm_fac_type_cd,
                    clm_freq_cd,
                    final_action,
                    clm_tot_chrg_amt,
                    clm_pmt_amt,
                    clm_op_bene_pmt_amt,
                    clm_op_prvdr_pmt_amt,
                    claim_query_code,
                    clm_srvc_clsfctn_type_cd,
                    clm_mdcr_non_pmt_rsn_cd,
                    clm_mco_pd_sw,
                    nch_clm_type_cd,
                    nch_near_line_rec_ident_cd,
                    nch_wkly_proc_dt,
                    nch_bene_blood_ddctbl_lblty_am,
                    nch_bene_ptb_coinsrnc_amt,
                    nch_bene_ptb_ddctbl_amt,
                    nch_prmry_pyr_clm_pd_amt,
                    nch_profnl_cmpnt_chrg_amt,
                    nch_prmry_pyr_cd,
                    prvdr_num,
                    prvdr_state_cd,
                    at_physn_npi,
                    at_physn_upin,
                    op_physn_npi,
                    op_physn_upin,
                    ot_physn_npi,
                    ot_physn_upin,
                    org_npi_num,
                    prncpal_dgns_cd,
                    prncpal_dgns_vrsn_cd,
                    ptnt_dschrg_stus_cd,
                    fi_clm_proc_dt,
                    fi_doc_clm_cntl_num,
                    fi_num,
                    fi_orig_clm_cntl_num,
                    fst_dgns_e_cd,
                    fst_dgns_e_vrsn_cd,
                    rsn_visit_cd1,
                    rsn_visit_vrsn_cd1,
                    rsn_visit_cd2,
                    rsn_visit_vrsn_cd2,
                    rsn_visit_cd3,
                    rsn_visit_vrsn_cd3,
                    prcdr_dt1,
                    icd_dgns_cd1,
                    icd_dgns_vrsn_cd1,
                    icd_prcdr_cd1,
                    icd_prcdr_vrsn_cd1,
                    icd_dgns_e_cd1,
                    icd_dgns_e_vrsn_cd1,
                    prcdr_dt2,
                    icd_dgns_cd2,
                    icd_dgns_vrsn_cd2,
                    icd_prcdr_cd2,
                    icd_prcdr_vrsn_cd2,
                    icd_dgns_e_cd2,
                    icd_dgns_e_vrsn_cd2,
                    prcdr_dt3,
                    icd_dgns_cd3,
                    icd_dgns_vrsn_cd3,
                    icd_prcdr_cd3,
                    icd_prcdr_vrsn_cd3,
                    icd_dgns_e_cd3,
                    icd_dgns_e_vrsn_cd3,
                    prcdr_dt4,
                    icd_dgns_cd4,
                    icd_dgns_vrsn_cd4,
                    icd_prcdr_cd4,
                    icd_prcdr_vrsn_cd4,
                    icd_dgns_e_cd4,
                    icd_dgns_e_vrsn_cd4,
                    prcdr_dt5,
                    icd_dgns_cd5,
                    icd_dgns_vrsn_cd5,
                    icd_prcdr_cd5,
                    icd_prcdr_vrsn_cd5,
                    icd_dgns_e_cd5,
                    icd_dgns_e_vrsn_cd5,
                    prcdr_dt6,
                    icd_dgns_cd6,
                    icd_dgns_vrsn_cd6,
                    icd_prcdr_cd6,
                    icd_prcdr_vrsn_cd6,
                    icd_dgns_e_cd6,
                    icd_dgns_e_vrsn_cd6,
                    prcdr_dt7,
                    icd_dgns_cd7,
                    icd_dgns_vrsn_cd7,
                    icd_prcdr_cd7,
                    icd_prcdr_vrsn_cd7,
                    icd_dgns_e_cd7,
                    icd_dgns_e_vrsn_cd7,
                    prcdr_dt8,
                    icd_dgns_cd8,
                    icd_dgns_vrsn_cd8,
                    icd_prcdr_cd8,
                    icd_prcdr_vrsn_cd8,
                    icd_dgns_e_cd8,
                    icd_dgns_e_vrsn_cd8,
                    prcdr_dt9,
                    icd_dgns_cd9,
                    icd_dgns_vrsn_cd9,
                    icd_prcdr_cd9,
                    icd_prcdr_vrsn_cd9,
                    icd_dgns_e_cd9,
                    icd_dgns_e_vrsn_cd9,
                    prcdr_dt10,
                    icd_dgns_cd10,
                    icd_dgns_vrsn_cd10,
                    icd_prcdr_cd10,
                    icd_prcdr_vrsn_cd10,
                    icd_dgns_e_cd10,
                    icd_dgns_e_vrsn_cd10,
                    prcdr_dt11,
                    icd_dgns_cd11,
                    icd_dgns_vrsn_cd11,
                    icd_prcdr_cd11,
                    icd_prcdr_vrsn_cd11,
                    icd_dgns_e_cd11,
                    icd_dgns_e_vrsn_cd11,
                    prcdr_dt12,
                    icd_dgns_cd12,
                    icd_dgns_vrsn_cd12,
                    icd_prcdr_cd12,
                    icd_prcdr_vrsn_cd12,
                    icd_dgns_e_cd12,
                    icd_dgns_e_vrsn_cd12,
                    prcdr_dt13,
                    icd_dgns_cd13,
                    icd_dgns_vrsn_cd13,
                    icd_prcdr_cd13,
                    icd_prcdr_vrsn_cd13,
                    prcdr_dt14,
                    icd_dgns_cd14,
                    icd_dgns_vrsn_cd14,
                    icd_prcdr_cd14,
                    icd_prcdr_vrsn_cd14,
                    prcdr_dt15,
                    icd_dgns_cd15,
                    icd_dgns_vrsn_cd15,
                    icd_prcdr_cd15,
                    icd_prcdr_vrsn_cd15,
                    prcdr_dt16,
                    icd_dgns_cd16,
                    icd_dgns_vrsn_cd16,
                    icd_prcdr_cd16,
                    icd_prcdr_vrsn_cd16,
                    prcdr_dt17,
                    icd_dgns_cd17,
                    icd_dgns_vrsn_cd17,
                    icd_prcdr_cd17,
                    icd_prcdr_vrsn_cd17,
                    prcdr_dt18,
                    icd_dgns_cd18,
                    icd_dgns_vrsn_cd18,
                    icd_prcdr_cd18,
                    icd_prcdr_vrsn_cd18,
                    prcdr_dt19,
                    icd_dgns_cd19,
                    icd_dgns_vrsn_cd19,
                    icd_prcdr_cd19,
                    icd_prcdr_vrsn_cd19,
                    prcdr_dt20,
                    icd_dgns_cd20,
                    icd_dgns_vrsn_cd20,
                    icd_prcdr_cd20,
                    icd_prcdr_vrsn_cd20,
                    prcdr_dt21,
                    icd_dgns_cd21,
                    icd_dgns_vrsn_cd21,
                    icd_prcdr_cd21,
                    icd_prcdr_vrsn_cd21,
                    prcdr_dt22,
                    icd_dgns_cd22,
                    icd_dgns_vrsn_cd22,
                    icd_prcdr_cd22,
                    icd_prcdr_vrsn_cd22,
                    prcdr_dt23,
                    icd_dgns_cd23,
                    icd_dgns_vrsn_cd23,
                    icd_prcdr_cd23,
                    icd_prcdr_vrsn_cd23,
                    prcdr_dt24,
                    icd_dgns_cd24,
                    icd_dgns_vrsn_cd24,
                    icd_prcdr_cd24,
                    icd_prcdr_vrsn_cd24,
                    prcdr_dt25,
                    icd_dgns_cd25,
                    icd_dgns_vrsn_cd25,
                    icd_prcdr_cd25,
                    icd_prcdr_vrsn_cd25
from
    public.outpatient_claims;

-- for PSQL need to define our not null constraints; for HSQL,
-- we explicitly defined a table structure before migrating data.
--
${logic.psql-only} alter table public.outpatient_claims_new
${logic.psql-only}    alter column clm_id                            SET NOT NULL,
${logic.psql-only}    alter column bene_id                           SET NOT NULL,
${logic.psql-only}    alter column clm_grp_id                        SET NOT NULL,
${logic.psql-only}    alter column clm_from_dt                       SET NOT NULL,
${logic.psql-only}    alter column clm_thru_dt                       SET NOT NULL,
${logic.psql-only}    alter column clm_fac_type_cd                   SET NOT NULL,
${logic.psql-only}    alter column clm_freq_cd                       SET NOT NULL,
${logic.psql-only}    alter column final_action                      SET NOT NULL,
${logic.psql-only}    alter column clm_tot_chrg_amt                  SET NOT NULL,
${logic.psql-only}    alter column clm_pmt_amt                       SET NOT NULL,
${logic.psql-only}    alter column clm_op_bene_pmt_amt               SET NOT NULL,
${logic.psql-only}    alter column clm_op_prvdr_pmt_amt              SET NOT NULL,
${logic.psql-only}    alter column claim_query_code                  SET NOT NULL,
${logic.psql-only}    alter column clm_srvc_clsfctn_type_cd          SET NOT NULL,
${logic.psql-only}    alter column nch_clm_type_cd                   SET NOT NULL,
${logic.psql-only}    alter column nch_near_line_rec_ident_cd        SET NOT NULL,
${logic.psql-only}    alter column nch_wkly_proc_dt                  SET NOT NULL,
${logic.psql-only}    alter column nch_bene_blood_ddctbl_lblty_am    SET NOT NULL,
${logic.psql-only}    alter column nch_bene_ptb_coinsrnc_amt         SET NOT NULL,
${logic.psql-only}    alter column nch_bene_ptb_ddctbl_amt           SET NOT NULL,
${logic.psql-only}    alter column nch_prmry_pyr_clm_pd_amt          SET NOT NULL,
${logic.psql-only}    alter column nch_profnl_cmpnt_chrg_amt         SET NOT NULL,
${logic.psql-only}    alter column prvdr_num                         SET NOT NULL,
${logic.psql-only}    alter column prvdr_state_cd                    SET NOT NULL;

-- migrate data via INSERT from current INPATIENT_CLAIM_LINES table to INPATIENT_CLAIM_LINES_NEW table
--
${logic.hsql-only} insert into public.outpatient_claim_lines_new (
${logic.hsql-only}    clm_id,
${logic.hsql-only}    clm_line_num,
${logic.hsql-only}    rev_cntr,
${logic.hsql-only}    rev_cntr_unit_cnt,
${logic.hsql-only}    rev_cntr_rate_amt,
${logic.hsql-only}    rev_cntr_tot_chrg_amt,
${logic.hsql-only}    rev_cntr_ncvrd_chrg_amt,
${logic.hsql-only}    rev_cntr_coinsrnc_wge_adjstd_c,
${logic.hsql-only}    rev_cntr_bene_pmt_amt,
${logic.hsql-only}    rev_cntr_blood_ddctbl_amt,
${logic.hsql-only}    rev_cntr_cash_ddctbl_amt,
${logic.hsql-only}    rev_cntr_rdcd_coinsrnc_amt,
${logic.hsql-only}    rev_cntr_pmt_amt_amt,
${logic.hsql-only}    rev_cntr_prvdr_pmt_amt,
${logic.hsql-only}    rev_cntr_dt,
${logic.hsql-only}    rev_cntr_ptnt_rspnsblty_pmt,
${logic.hsql-only}    rev_cntr_ndc_qty_qlfr_cd,
${logic.hsql-only}    rev_cntr_ndc_qty,
${logic.hsql-only}    rev_cntr_1st_ansi_cd,
${logic.hsql-only}    rev_cntr_1st_msp_pd_amt,
${logic.hsql-only}    rev_cntr_2nd_ansi_cd,
${logic.hsql-only}    rev_cntr_2nd_msp_pd_amt,
${logic.hsql-only}    rev_cntr_3rd_ansi_cd,
${logic.hsql-only}    rev_cntr_4th_ansi_cd,
${logic.hsql-only}    rev_cntr_apc_hipps_cd,
${logic.hsql-only}    rev_cntr_dscnt_ind_cd,
${logic.hsql-only}    rev_cntr_ide_ndc_upc_num,
${logic.hsql-only}    rev_cntr_otaf_pmt_cd,
${logic.hsql-only}    rev_cntr_packg_ind_cd,
${logic.hsql-only}    rev_cntr_pmt_mthd_ind_cd,
${logic.hsql-only}    rev_cntr_stus_ind_cd,
${logic.hsql-only}    hcpcs_cd,
${logic.hsql-only}    hcpcs_2nd_mdfr_cd,
${logic.hsql-only}    hcpcs_1st_mdfr_cd,
${logic.hsql-only}    rndrng_physn_npi,
${logic.hsql-only}    rndrng_physn_upin )
--
-- PSQL allows us to dynamically create a table via the
-- associated SELECT statement used to populate the table.
--
${logic.psql-only} create table public.outpatient_claim_lines_new as
select
${logic.hsql-only}    convert(clm_id, SQL_BIGINT),
${logic.hsql-only}    convert(clm_line_num, SQL_SMALLINT),
${logic.psql-only}    clm_id::bigint,
${logic.psql-only}    clm_line_num::smallint,
                      rev_cntr,
                      rev_cntr_unit_cnt,
                      rev_cntr_rate_amt,
                      rev_cntr_tot_chrg_amt,
                      rev_cntr_ncvrd_chrg_amt,
                      rev_cntr_coinsrnc_wge_adjstd_c,
                      rev_cntr_bene_pmt_amt,
                      rev_cntr_blood_ddctbl_amt,
                      rev_cntr_cash_ddctbl_amt,
                      rev_cntr_rdcd_coinsrnc_amt,
                      rev_cntr_pmt_amt_amt,
                      rev_cntr_prvdr_pmt_amt,
                      rev_cntr_dt,
                      rev_cntr_ptnt_rspnsblty_pmt,
                      rev_cntr_ndc_qty_qlfr_cd,
                      rev_cntr_ndc_qty,
                      rev_cntr_1st_ansi_cd,
                      rev_cntr_1st_msp_pd_amt,
                      rev_cntr_2nd_ansi_cd,
                      rev_cntr_2nd_msp_pd_amt,
                      rev_cntr_3rd_ansi_cd,
                      rev_cntr_4th_ansi_cd,
                      rev_cntr_apc_hipps_cd,
                      rev_cntr_dscnt_ind_cd,
                      rev_cntr_ide_ndc_upc_num,
                      rev_cntr_otaf_pmt_cd,
                      rev_cntr_packg_ind_cd,
                      rev_cntr_pmt_mthd_ind_cd,
                      rev_cntr_stus_ind_cd,
                      hcpcs_cd,
                      hcpcs_2nd_mdfr_cd,
                      hcpcs_1st_mdfr_cd,
                      rndrng_physn_npi,
                      rndrng_physn_upin
from
    public.outpatient_claim_lines;

-- for PSQL need to define our not null constraints; for HSQL,
-- we explicitly defined a table structure before migrating data.
--
${logic.psql-only} alter table public.outpatient_claim_lines_new
${logic.psql-only}    alter column clm_id                          SET NOT NULL,
${logic.psql-only}    alter column clm_line_num                    SET NOT NULL,
${logic.psql-only}    alter column rev_cntr                        SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_unit_cnt               SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_rate_amt               SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_tot_chrg_amt           SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_ncvrd_chrg_amt         SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_coinsrnc_wge_adjstd_c  SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_bene_pmt_amt           SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_blood_ddctbl_amt       SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_cash_ddctbl_amt        SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_rdcd_coinsrnc_amt      SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_pmt_amt_amt            SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_prvdr_pmt_amt          SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_ptnt_rspnsblty_pmt     SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_1st_msp_pd_amt         SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_2nd_msp_pd_amt         SET NOT NULL;

-- for PSQL need to define our primary key    
${logic.psql-only} alter table public.outpatient_claims_new
${logic.psql-only}     add CONSTRAINT outpatient_claims_new_pkey PRIMARY KEY (clm_id);

-- for PSQL need to define our primary key    
${logic.psql-only} ALTER TABLE public.outpatient_claim_lines_new
${logic.psql-only}     ADD CONSTRAINT outpatient_claim_lines_new_pkey PRIMARY KEY (clm_id, clm_line_num);

-- define foreign key constraints between claim lineitems and a parent claims table.
ALTER TABLE IF EXISTS public.outpatient_claim_lines_new
    ADD CONSTRAINT outpatient_claim_lines_clm_id_to_outpatient_claims_new FOREIGN KEY (clm_id)
        REFERENCES public.outpatient_claims_new (clm_id);

-- create an index of the BENE_ID in parent claims table
CREATE INDEX IF NOT EXISTS outpatient_claims_new_bene_id_idx
    ON public.outpatient_claims_new (bene_id);