import csv
import datetime
import os
import sys
import urllib3
import common.config as config
import common.test_setup as setup
import common.read_contract_cursors as cursors
import locust.exception as locust_exception
from locust import HttpUser, task

server_public_key = setup.loadServerPublicKey()

'''
If there is no server cert, the warnings are disabled because thousands will appear in the logs and make it difficult
to see anything else.
'''
if not server_public_key:
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

## Read cursors from the file generated by common/pull_contract_cursors.py
cursor_list = cursors.loaddata("v2")
client_cert = setup.getClientCert()
setup.set_locust_env(config.load())

class BFDUser(HttpUser):
    @task
    def patient(self):
        if len(cursor_list) == 0:
            print("Ran out of data, stopping test...")
            raise locust_exception.StopUser()

        url = cursor_list.pop()
        response = self.client.get(url,
                cert=client_cert,
                verify=server_public_key,
                headers={"IncludeIdentifiers": "mbi"},
                name='/v2/fhir/Patient search by coverage contract (all pages)')