#!/bin/bash

set -e

image=postgres:16.6
max_connections=500
docker pull $image

docker rm -f bfd-db
docker volume rm -f bfd-db

docker run \
  -d \
  --name 'bfd-db' \
  -e 'POSTGRES_USER=bfd' \
  -e 'POSTGRES_PASSWORD=InsecureLocalDev' \
  -p '5432:5432' \
  -v 'bfd-db:/var/lib/postgresql/data' \
  $image \
  postgres -N $max_connections

echo
echo Waiting for port 5432 to become available.
sleep 2
docker exec bfd-db timeout 15 bash -c 'until echo > /dev/tcp/localhost/5432; do sleep 1; done'

echo
echo Creating database
docker exec bfd-db createdb --host localhost --username bfd --owner bfd fhirdb

echo
echo Database created successfully.
