create table idr_new.claim_professional_ss
(
    clm_uniq_id                    bigint                   not null primary key,
    --claim date sgntr
--  instnl   clm_cms_proc_dt                date                     not null,
--   nch   clm_actv_care_from_dt          date,
--   nch  clm_dschrg_dt                  date,
    clm_submsn_dt                  date,
--   nch  clm_ncvrd_from_dt              date,
--   nch  clm_ncvrd_thru_dt              date,
--   nch  clm_actv_care_thru_dt          date,
--   nch  clm_mdcr_exhstd_dt             date,
--   nch  clm_nch_wkly_proc_dt           date,
--   nch  clm_qlfy_stay_from_dt          date,
--   nch  clm_qlfy_stay_thru_dt          date,
    --claim date sgntr
    clm_type_cd                    integer                  not null,
    bene_sk                        bigint                   not null,
    clm_cntl_num                   character varying(40)    not null,
    clm_orig_cntl_num              character varying(40)    not null,
    clm_from_dt                    date                     not null,
    clm_thru_dt                    date,
    clm_efctv_dt                   date,
    clm_obslt_dt                   date,
--     instnl clm_bill_clsfctn_cd        character varying(1)     not null,
--     instnl clm_bill_fac_type_cd       character varying(1)     not null,
--     instnl clm_bill_freq_cd           character varying(1)     not null,
    clm_finl_actn_ind              character varying(1)     not null,
    clm_src_id                     character varying(5)     not null,
--     adj clm_query_cd                 character varying(1)     not null,
    clm_mdcr_coinsrnc_amt          numeric,
    clm_blood_lblty_amt            numeric,
    clm_ncvrd_chrg_amt             numeric,
    clm_mdcr_ddctbl_amt            numeric,
    clm_prvdr_pmt_amt              numeric,
    clm_alowd_chrg_amt             numeric,
    clm_bene_pmt_amt               numeric,
    clm_cntrctr_num                character varying(5)     not null,
    clm_pmt_amt                    numeric,
    clm_pd_dt                      date,
    clm_ltst_clm_ind               character varying(1)     not null,

    prvdr_othr_prvdr_npi_num       character varying(10),
    bfd_prvdr_othr_careteam_name       character varying(135),
--  INSTNL   clm_othr_fed_prvdr_spclty_cd   character varying(2),

    prvdr_blg_prvdr_npi_num        character varying(10),
    clm_blg_prvdr_tax_num          character varying(10),
--  INSTNL   clm_blg_prvdr_oscar_num        character varying(13),
    prvdr_blg_1st_name             character varying(35),
    bfd_prvdr_blg_last_or_lgl_name     character varying(100),
--     clm_blg_prvdr_zip5_cd          character varying(5),
--     geo_blg_ssa_state_cd           character varying(2),

    prvdr_rfrg_prvdr_npi_num       character varying(10),
    bfd_prvdr_rfrg_careteam_name       character varying(135),
--     clm_rfrg_fed_prvdr_spclty_cd   character varying(2),

--  adj   clm_disp_cd                  character varying(2)     not null,
--  instnl   clm_ric_cd                 character varying(1)     not null,
    clm_sbmt_chrg_amt              numeric,
    clm_blood_pt_frnsh_qty         integer,
    clm_nch_prmry_pyr_cd           character varying(1)     not null,
    clm_idr_ld_dt                  date,
    clm_nrln_ric_cd                character varying(1)     not null,

--  drug   prvdr_prscrbng_prvdr_npi_num character varying(10)    not null,
--     idr_insrt_ts_dcmtn         timestamp with time zone not null,
--     idr_updt_ts_dcmtn          timestamp with time zone not null,
    bfd_created_ts                 timestamp with time zone not null,
    bfd_updated_ts                 timestamp with time zone not null,
    clm_adjstmt_type_cd            character varying(2),
    clm_bene_pd_amt                numeric,
    clm_sbmt_frmt_cd               character varying(1),
--  part d   clm_sbmtr_cntrct_num         character varying(5),
--  part d   clm_sbmtr_cntrct_pbp_num     character varying(3),
--  instnl   clm_bnft_enhncmt_1_cd      character varying(2),
--  instnl   clm_ngaco_pbpmt_sw         character varying(1),
--  instnl   clm_ngaco_cptatn_sw        character varying(1),
--  instnl   clm_ngaco_pdschrg_hcbs_sw  character varying(1),
--  instnl   clm_ngaco_snf_wvr_sw       character varying(1),
--  instnl   clm_ngaco_tlhlth_sw        character varying(1),
--  instnl   clm_bnft_enhncmt_2_cd      character varying(2),
--  instnl   clm_bnft_enhncmt_3_cd      character varying(2),
--  instnl   clm_bnft_enhncmt_4_cd      character varying(2),
--  instnl   clm_bnft_enhncmt_5_cd      character varying(2),
--     clm_rfrg_prvdr_pin_num         character varying(14),
--    prvdr_srvc_prvdr_npi_num       character varying(20),
--    prvdr_srvc_careteam_name       character varying(135),

    clm_blood_chrg_amt             numeric,
--  instnl   clm_tot_cntrctl_amt        numeric,
    clm_bene_intrst_pd_amt         numeric,
    clm_bene_pmt_coinsrnc_amt      numeric,
    clm_cob_ptnt_resp_amt          numeric,
    clm_prvdr_otaf_amt             numeric,
    clm_othr_tp_pd_amt             numeric,
    clm_prvdr_rmng_due_amt         numeric,
    clm_blood_ncvrd_chrg_amt       numeric,
    clm_prvdr_intrst_pd_amt        numeric,
    clm_mdcr_prfnl_prvdr_asgnmt_sw character varying(2)     not null,
    clm_audt_trl_stus_cd           character varying(2),
    clm_audt_trl_lctn_cd           character varying(5),
    clm_prvdr_acnt_rcvbl_ofst_amt  numeric,
    clm_clncl_tril_num             character varying(8),
    bfd_claim_updated_ts           timestamp with time zone default now(),
    meta_src_sk                    integer                  not null
);

create table idr_new.claim_professional_nch
(
    clm_uniq_id                    bigint                   not null primary key,
    --claim date sgntr
--  instnl   clm_cms_proc_dt           date,
--    clm_actv_care_from_dt     date,
    --   clm_dschrg_dt             date,
    clm_submsn_dt                  date,
--    clm_ncvrd_from_dt         date,
--    clm_ncvrd_thru_dt         date,
    --   clm_actv_care_thru_dt     date,
--    clm_mdcr_exhstd_dt        date,
    clm_nch_wkly_proc_dt           date,
--    clm_qlfy_stay_from_dt     date,
--    clm_qlfy_stay_thru_dt     date,
    --claim date sgntr
    clm_type_cd                    integer                  not null,
    bene_sk                        bigint                   not null,
    clm_cntl_num                   character varying(40)    not null,
    clm_orig_cntl_num              character varying(40)    not null,
    clm_from_dt                    date                     not null,
    clm_thru_dt                    date,
    clm_efctv_dt                   date,
    clm_obslt_dt                   date,
--     instnl clm_bill_clsfctn_cd        character varying(1)     not null,
--     instnl clm_bill_fac_type_cd       character varying(1)     not null,
--     instnl clm_bill_freq_cd           character varying(1)     not null,
    clm_finl_actn_ind              character varying(1)     not null,
   clm_src_id                character varying(5)     not null,
    clm_query_cd                   character varying(1)     not null,
--     pac clm_mdcr_coinsrnc_amt      numeric,
--     pac clm_blood_lblty_amt        numeric,
--     pac clm_ncvrd_chrg_amt         numeric,
    clm_mdcr_ddctbl_amt            numeric,
    clm_prvdr_pmt_amt              numeric,
    clm_alowd_chrg_amt             numeric,
    clm_bene_pmt_amt               numeric,
    clm_cntrctr_num                character varying(5)     not null,
    clm_pmt_amt                    numeric,
    clm_pd_dt                      date,
    clm_ltst_clm_ind               character varying(1)     not null,
--   pac  prvdr_othr_prvdr_npi_num   character varying(10)    not null,
--   pac  prvdr_othr_sk              bigint                   not null,
--   pac  prvdr_othr_hstry_efctv_dt  date                     not null,
--   pac  prvdr_othr_mdl_name        character varying(25)    not null,
--   pac  prvdr_othr_type_cd         character varying(2)     not null,
--   pac  prvdr_othr_txnmy_cmpst_cd  character varying(150)   not null,
--   pac  prvdr_othr_oscar_num       character varying(13)    not null,
--   pac  prvdr_othr_1st_name        character varying(35)    not null,
--   pac  prvdr_othr_name            character varying(70)    not null,
--   pac  prvdr_othr_hstry_obslt_dt  date                     not null,
--   pac  prvdr_othr_lgl_name        character varying(100)   not null,
--   pac  prvdr_othr_emplr_id_num    character varying(10)    not null,
--   pac  prvdr_othr_last_name       character varying(35)    not null,
    prvdr_blg_prvdr_npi_num        character varying(10),
    clm_blg_prvdr_tax_num          character varying(10),
    prvdr_blg_1st_name             character varying(35),
    bfd_prvdr_blg_last_or_lgl_name     character varying(135),

    prvdr_rfrg_prvdr_npi_num       character varying(10),
    bfd_prvdr_rfrg_careteam_name       character varying(135),

    clm_disp_cd                    character varying(2)     not null,
--  instnl   clm_ric_cd                 character varying(1)     not null,
    clm_sbmt_chrg_amt              numeric,
    clm_blood_pt_frnsh_qty         integer,
--  pac   clm_nch_prmry_pyr_cd       character varying(1)     not null,
--  instnl   clm_blg_prvdr_oscar_num      character varying(20)    not null,
    clm_idr_ld_dt                  date,
    clm_nrln_ric_cd                character varying(1)     not null,

--  drug   prvdr_prscrbng_prvdr_npi_num character varying(10)    not null,
--     idr_insrt_ts_dcmtn         timestamp with time zone not null,
--     idr_updt_ts_dcmtn          timestamp with time zone not null,
    bfd_created_ts                 timestamp with time zone not null,
    bfd_updated_ts                 timestamp with time zone not null,
    clm_adjstmt_type_cd            character varying(2),
    clm_bene_pd_amt                numeric,
    clm_blg_prvdr_zip5_cd          character varying(5),
--  pac   clm_sbmt_frmt_cd           character varying(1),
--  part d   clm_sbmtr_cntrct_num         character varying(5),
--  part d   clm_sbmtr_cntrct_pbp_num     character varying(3),
--  instnl   clm_bnft_enhncmt_1_cd      character varying(2),
--  instnl   clm_ngaco_pbpmt_sw         character varying(1),
--  instnl   clm_ngaco_cptatn_sw        character varying(1),
--  instnl   clm_ngaco_pdschrg_hcbs_sw  character varying(1),
--  instnl   clm_ngaco_snf_wvr_sw       character varying(1),
--  instnl   clm_ngaco_tlhlth_sw        character varying(1),
--  instnl   clm_bnft_enhncmt_2_cd      character varying(2),
--  instnl   clm_bnft_enhncmt_3_cd      character varying(2),
--  instnl   clm_bnft_enhncmt_4_cd      character varying(2),
--  instnl   clm_bnft_enhncmt_5_cd      character varying(2),
    prvdr_srvc_prvdr_npi_num       character varying(20),
    bfd_prvdr_srvc_careteam_name       character varying(135),

    clm_blood_chrg_amt             numeric,
--  instnl   clm_tot_cntrctl_amt        numeric,
--  pac   clm_bene_intrst_pd_amt     numeric,
--  pac   clm_bene_pmt_coinsrnc_amt  numeric,
--  pac   clm_cob_ptnt_resp_amt      numeric,
--  pac   clm_prvdr_otaf_amt         numeric,
--  pac   clm_othr_tp_pd_amt         numeric,
--  pac   clm_prvdr_rmng_due_amt     numeric,
--  pac   clm_blood_ncvrd_chrg_amt   numeric,
--  pac   clm_prvdr_intrst_pd_amt    numeric,
    clm_mdcr_prfnl_prmry_pyr_amt   numeric,
    clm_mdcr_prfnl_prvdr_asgnmt_sw character varying(2)     not null,
    bfd_claim_updated_ts           timestamp with time zone default now(),
    meta_src_sk               integer                       not null,
    clm_clncl_tril_num             character varying(8),
    clm_carr_pmt_dnl_cd            character varying(2)
);

create index on idr_new.claim_professional_ss (bene_sk);

create index on idr_new.claim_professional_nch (bene_sk);

create table idr_new.claim_item_professional_ss
(
    clm_uniq_id                    bigint                   not null,
    bfd_row_id                     integer                  not null,
    clm_line_num                   integer,
--  adj    clm_line_ansthsa_unit_cnt      numeric,
    clm_line_dgns_cd               character varying(7)     not null,
    clm_line_sbmt_chrg_amt         numeric,
    clm_line_alowd_chrg_amt        numeric,
--  instnl   clm_line_ncvrd_chrg_amt        numeric,
    clm_line_prvdr_pmt_amt         numeric,
--  instnl,part d   clm_line_bene_pmt_amt          numeric,
    clm_line_bene_pd_amt           numeric,
    clm_line_cvrd_pd_amt           numeric,
--  instnl   clm_line_blood_ddctbl_amt      numeric,
    clm_line_mdcr_ddctbl_amt       numeric,
    clm_line_mdcr_coinsrnc_amt     numeric,
    clm_line_hcpcs_cd              character varying(5)     not null,
    clm_line_from_dt               date,
    clm_line_ndc_cd                character varying(11)    not null,
    clm_line_ndc_qty               numeric,
    clm_line_ndc_qty_qlfyr_cd      character varying(2)     not null,
    clm_line_srvc_unit_qty         numeric,
--  instnl   clm_line_rev_ctr_cd            character varying(4)     not null,
    clm_line_rx_num                character varying(30)    not null,
    clm_line_thru_dt               date,
    clm_pos_cd                     character varying(2)     not null,

--     clm_rndrg_prvdr_prtcptg_cd     character varying(1)     not null,

    hcpcs_1_mdfr_cd                character varying(2)     not null,
    hcpcs_2_mdfr_cd                character varying(2)     not null,
    hcpcs_3_mdfr_cd                character varying(2)     not null,
    hcpcs_4_mdfr_cd                character varying(2)     not null,
    hcpcs_5_mdfr_cd                character varying(2)     not null,

    clm_val_sqnc_num_prod          integer,
    clm_dgns_prcdr_icd_ind         character varying(1)     not null,
    clm_dgns_cd                    character varying(7)     not null,
-- instnl    clm_prcdr_cd                   character varying(7)     not null,
    clm_prod_type_cd               character varying(1)     not null,
    clm_poa_ind                    character varying(1)     not null,
-- instnl    clm_prcdr_prfrm_dt             date,
--     idr_insrt_ts_prod              timestamp with time zone not null,
--     idr_updt_ts_prod               timestamp with time zone not null,
-- instnl    clm_val_sqnc_num_val           integer,
-- instnl    clm_val_cd                     character varying(2)     not null,
-- instnl    clm_val_amt                    numeric,
--     idr_insrt_ts_val               timestamp with time zone not null,
--     idr_updt_ts_val                timestamp with time zone not null,

    clm_line_bnft_enhncmt_2_cd     character varying(2),
    clm_line_bnft_enhncmt_3_cd     character varying(2),
    clm_line_bnft_enhncmt_4_cd     character varying(2),
    clm_line_bnft_enhncmt_5_cd     character varying(2),
--     _sw fields from v2_mdcr_clm_line_dcmtn for pac professional can be removed.
--     they are derived from other fields (clm_line_bnft_enhncmt_x_cd)
--     clm_line_ngaco_cptatn_sw       character varying(1),
--     clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
--     clm_line_ngaco_snf_wvr_sw      character varying(1),
--     clm_line_ngaco_tlhlth_sw       character varying(1),
--     clm_line_aco_care_mgmt_hcbs_sw character varying(1),
--     clm_line_ngaco_pbpmt_sw        character varying(1),
--  adj  clm_line_pmd_uniq_trkng_num    character varying(14),
    clm_line_pa_uniq_trkng_num     character varying(50),
    clm_line_bnft_enhncmt_1_cd     character varying(2),
--  instnl   clm_rlt_cond_cd                character varying(20),
--  instnl   clm_rlt_cond_sgntr_sqnc_num    integer,

    prvdr_rndrng_prvdr_npi_num     character varying(10),
    prvdr_rndrng_type_cd           character varying(2),
    bfd_prvdr_rndrng_careteam_name     character varying(135),
    clm_rndrg_fed_prvdr_spclty_cd  character varying(2),
    clm_rndrg_prvdr_tax_num        character varying(10)    not null,
    geo_rndrg_ssa_state_cd         character varying(2),
    clm_rndrg_prvdr_type_cd        character varying(3),

--  instnl, part d   clm_line_othr_tp_pd_amt        numeric,
--  instnl, part d   clm_line_ncvrd_pd_amt          numeric,
    clm_line_otaf_amt              numeric,
    -- claim line professional columns
--  adj   clm_bene_prmry_pyr_pd_amt      numeric,
    clm_fed_type_srvc_cd           character varying(1)     not null,
--  adj   clm_line_carr_clncl_lab_num    character varying(10)    not null,
--  adj   clm_line_carr_hpsa_scrcty_cd   character varying(1)     not null,
--  adj   clm_line_dmerc_scrn_svgs_amt   numeric,
    clm_line_hct_hgb_rslt_num      numeric,
--  adj   clm_line_hct_hgb_type_cd       character varying(2)     not null,
    clm_line_prfnl_dme_price_amt   numeric,
--  adj   clm_line_prfnl_mtus_cnt        numeric,
--  adj   clm_mtus_ind_cd                character varying(1)     not null,
--  adj   clm_physn_astnt_cd             character varying(1)     not null,
    clm_pmt_80_100_cd              character varying(1),
--  adj   clm_prcng_lclty_cd             character varying(2)     not null,
--  adj   clm_prcsg_ind_cd               character varying(2)     not null,
--  adj   clm_prmry_pyr_cd               character varying(1)     not null,
    clm_prvdr_spclty_cd            character varying(2)     not null,
    clm_srvc_ddctbl_sw             character varying(1)     not null,
    clm_suplr_type_cd              character varying(1)     not null,
    bfd_created_ts                 timestamp with time zone not null,
    bfd_updated_ts                 timestamp with time zone not null,
--  adj   clm_line_prfnl_intrst_amt      numeric,
    clm_line_carr_psych_ot_lmt_amt numeric,
--  adj   clm_line_carr_clncl_chrg_amt   numeric,
--  adj   clm_mdcr_prmry_pyr_alowd_amt   numeric,

--    clm_ocrnc_sgntr_sk             numeric,
--    clm_rlt_ocrnc_sgntr_sk         numeric,
    -- v2_mdcr_clm_line_mcs columns
    clm_line_rbndlg_crtfctn_num    character varying(10),
    clm_line_hct_lvl_num           numeric,
    clm_line_hgb_lvl_num           numeric,
    primary key (clm_uniq_id, bfd_row_id)
);

create table idr_new.claim_institutional_ss
(
    clm_uniq_id                    bigint                   not null primary key,
    --claim date sgntr
    clm_cms_proc_dt                date,
    clm_actv_care_from_dt          date,
    clm_dschrg_dt                  date,
    clm_submsn_dt                  date,
--     clm_ncvrd_from_dt          date,
--   nch  clm_ncvrd_thru_dt          date,
--   nch  clm_actv_care_thru_dt      date,
--   nch  clm_mdcr_exhstd_dt         date,
--   nch  clm_nch_wkly_proc_dt       date,
    clm_qlfy_stay_from_dt          date,
--  nch   clm_qlfy_stay_thru_dt      date,
    --claim date sgntr
    clm_type_cd                    integer                  not null,
    bene_sk                        bigint                   not null,
    clm_cntl_num                   character varying(40)    not null,
    clm_orig_cntl_num              character varying(40)    not null,
    clm_from_dt                    date                     not null,
    clm_thru_dt                    date,
    clm_efctv_dt                   date,
    clm_obslt_dt                   date,
    clm_bill_clsfctn_cd            character varying(1)     not null,
    clm_bill_fac_type_cd           character varying(1)     not null,
    clm_bill_freq_cd               character varying(1)     not null,
    clm_finl_actn_ind              character varying(1)     not null,
    clm_src_id                     character varying(5)     not null,
    clm_query_cd                 character varying(1)     not null,
    clm_mdcr_coinsrnc_amt          numeric,
    clm_blood_lblty_amt            numeric,
    clm_ncvrd_chrg_amt             numeric,
    clm_mdcr_ddctbl_amt            numeric,
    clm_prvdr_pmt_amt              numeric,
    clm_alowd_chrg_amt             numeric,
    clm_bene_pmt_amt               numeric,
    clm_cntrctr_num                character varying(5)     not null,
    clm_pmt_amt                    numeric,
    clm_pd_dt                      date,
    clm_ltst_clm_ind               character varying(1)     not null,

    prvdr_atndg_prvdr_npi_num      character varying(10),
    bfd_prvdr_atndg_careteam_name      character varying(135),
    clm_atndg_fed_prvdr_spclty_cd  character varying(2),

    prvdr_oprtg_prvdr_npi_num      character varying(10),
    bfd_prvdr_oprtg_careteam_name      character varying(135),
    clm_oprtg_fed_prvdr_spclty_cd  character varying(2),

    prvdr_othr_prvdr_npi_num       character varying(10),
    bfd_prvdr_othr_careteam_name       character varying(135),
    clm_othr_fed_prvdr_spclty_cd   character varying(2),

    prvdr_rndrg_prvdr_npi_num      character varying(10),
    bfd_prvdr_rndrg_careteam_name      character varying(135),
    clm_rndrg_fed_prvdr_spclty_cd  character varying(2),

    prvdr_blg_prvdr_npi_num        character varying(10),
    clm_blg_prvdr_oscar_num        character varying(13),
    prvdr_blg_1st_name             character varying(35),
    bfd_prvdr_blg_last_or_lgl_name     character varying(100),
    clm_blg_prvdr_zip5_cd          character varying(5),
    geo_blg_ssa_state_cd           character varying(2),

    prvdr_rfrg_prvdr_npi_num       character varying(10),
    bfd_prvdr_rfrg_careteam_name       character varying(135),
    clm_rfrg_fed_prvdr_spclty_cd   character varying(2),

    clm_disp_cd                  character varying(2)     not null,
    clm_ric_cd                     character varying(1)     not null,
    clm_sbmt_chrg_amt              numeric,
    clm_blood_pt_frnsh_qty         integer,
    clm_nch_prmry_pyr_cd           character varying(1)     not null,
--     clm_blg_prvdr_oscar_num      character varying(20)    not null,
    clm_idr_ld_dt                  date,
-- nch    clm_nrln_ric_cd            character varying(1)     not null,
--     prvdr_srvc_prvdr_npi_num   character varying(20)    not null,
--     prvdr_prscrbng_prvdr_npi_num character varying(10)    not null,
    bfd_created_ts                 timestamp with time zone not null,
    bfd_updated_ts                 timestamp with time zone not null,
    clm_adjstmt_type_cd            character varying(2),
    clm_bene_pd_amt                numeric,
    clm_sbmt_frmt_cd               character varying(1),
--     clm_sbmtr_cntrct_num         character varying(5),
--     clm_sbmtr_cntrct_pbp_num     character varying(3),
    clm_bnft_enhncmt_1_cd          character varying(2),
--  nch   clm_ngaco_pbpmt_sw         character varying(1),
--  nch   clm_ngaco_cptatn_sw        character varying(1),
--  nch   clm_ngaco_pdschrg_hcbs_sw  character varying(1),
--  nch   clm_ngaco_snf_wvr_sw       character varying(1),
--  nch   clm_ngaco_tlhlth_sw        character varying(1),
    clm_bnft_enhncmt_2_cd          character varying(2),
    clm_bnft_enhncmt_3_cd          character varying(2),
    clm_bnft_enhncmt_4_cd          character varying(2),
    clm_bnft_enhncmt_5_cd          character varying(2),
--     clm_rfrg_prvdr_pin_num     character varying(14),
--    prvdr_srvc_prvdr_npi_num       character varying(10),
--    prvdr_srvc_careteam_name       character varying(135),

    clm_blood_chrg_amt             numeric,
    clm_tot_cntrctl_amt            numeric,
    clm_bene_intrst_pd_amt         numeric,
    clm_bene_pmt_coinsrnc_amt      numeric,
    clm_cob_ptnt_resp_amt          numeric,
    clm_prvdr_otaf_amt             numeric,
    clm_othr_tp_pd_amt             numeric,
    clm_prvdr_rmng_due_amt         numeric,
    clm_blood_ncvrd_chrg_amt       numeric,
    clm_prvdr_intrst_pd_amt        numeric,
    bfd_claim_updated_ts           timestamp with time zone default now(),
--  clm_lctn_hstry
    clm_audt_trl_stus_cd           character varying(2),
    clm_audt_trl_lctn_cd           character varying(5),
--  fiss
    clm_crnt_stus_cd               character varying(1)     not null,
-- ss    clm_pps_ind_cd                character varying(1)     not null,
    meta_src_sk                    integer                  not null,
--     clm_instl columns
    clm_admsn_type_cd              varchar(2)               not null,
    bene_ptnt_stus_cd              varchar(2)               not null,
    dgns_drg_cd                    integer,
    clm_mdcr_instnl_mco_pd_sw      varchar(1)               not null,
    clm_admsn_src_cd               varchar(2)               not null,
    clm_fi_actn_cd                 varchar(1)               not null,
    clm_mdcr_ip_lrd_use_cnt        integer,
--   nch  clm_hha_rfrl_cd                varchar(1)               not null,
--   nch  clm_hha_lup_ind_cd             varchar(1)               not null,
    clm_hipps_uncompd_care_amt     numeric,
    clm_instnl_mdcr_coins_day_cnt  integer,
    clm_instnl_ncvrd_day_cnt       numeric,
    clm_instnl_per_diem_amt        numeric,
    clm_mdcr_hha_tot_visit_cnt     numeric,
    clm_mdcr_npmt_rsn_cd           varchar(2)               not null,
    clm_mdcr_ip_pps_drg_wt_num     numeric,
    clm_mdcr_ip_pps_dsprprtnt_amt  numeric,
    clm_mdcr_ip_pps_excptn_amt     numeric,
    clm_mdcr_ip_pps_cptl_fsp_amt   numeric,
    clm_mdcr_ip_pps_cptl_ime_amt   numeric,
    clm_mdcr_ip_pps_outlier_amt    numeric,
    clm_mdcr_ip_pps_cptl_hrmls_amt numeric,
    clm_mdcr_instnl_bene_pd_amt    numeric,
    clm_mdcr_hospc_prd_cnt         integer,
    clm_pps_ind                    varchar(1)               not null,
    clm_mdcr_ip_pps_cptl_tot_amt   numeric,
    clm_instnl_cvrd_day_cnt        numeric,
    clm_mdcr_instnl_prmry_pyr_amt  numeric,
    clm_instnl_prfnl_amt           numeric,
    clm_mdcr_ip_bene_ddctbl_amt    numeric,
    clm_instnl_drg_outlier_amt     numeric,
--  nch   dgns_drg_outlier_cd            varchar(1),
    clm_mdcr_ip_scnd_yr_rate_amt   numeric,
    clm_instnl_low_vol_pmt_amt     numeric,
    clm_hipps_readmsn_rdctn_amt    numeric,
    clm_hipps_model_bndld_pmt_amt  numeric,
    clm_hipps_vbp_amt              numeric,
    clm_site_ntrl_ip_pps_pymt_amt  numeric,
    clm_finl_stdzd_pymt_amt        numeric,
    clm_pps_md_wvr_stdzd_val_amt   numeric,
    clm_hac_rdctn_pymt_amt         numeric,
    clm_mdcr_ip_1st_yr_rate_amt    numeric,
    clm_site_ntrl_cst_bsd_pymt_amt numeric,
    clm_ss_outlier_std_pymt_amt    numeric
--  nch   clm_op_srvc_type_cd            varchar(1)
);

create table idr_new.claim_item_professional_nch
(
    clm_uniq_id                    bigint                   not null,
    bfd_row_id                     integer                  not null,
    clm_line_num                   integer,
--     missing implementation
    clm_line_ansthsa_unit_cnt      numeric,
    clm_line_dgns_cd               character varying(7)     not null,
    clm_line_sbmt_chrg_amt         numeric,
    clm_line_alowd_chrg_amt        numeric,
--  instnl   clm_line_ncvrd_chrg_amt        numeric,
    clm_line_prvdr_pmt_amt         numeric,
--  instnl,part d   clm_line_bene_pmt_amt          numeric,
    clm_line_bene_pd_amt           numeric,
    clm_line_cvrd_pd_amt           numeric,
--  instnl   clm_line_blood_ddctbl_amt      numeric,
    clm_line_mdcr_ddctbl_amt       numeric,
    clm_line_mdcr_coinsrnc_amt     numeric,
    clm_line_hcpcs_cd              character varying(5)     not null,
    clm_line_from_dt               date,
    clm_line_ndc_cd                character varying(11)    not null,
--  shared systems   clm_line_ndc_qty               numeric,
--  shared systems   clm_line_ndc_qty_qlfyr_cd      character varying(2)     not null,
    clm_line_srvc_unit_qty         numeric,
--  instnl   clm_line_rev_ctr_cd            character varying(4)     not null,
    clm_line_rx_num                character varying(30)    not null,
    clm_line_thru_dt               date,
    clm_pos_cd                     character varying(2)     not null,

    hcpcs_1_mdfr_cd                character varying(2)     not null,
    hcpcs_2_mdfr_cd                character varying(2)     not null,
    hcpcs_3_mdfr_cd                character varying(2)     not null,
    hcpcs_4_mdfr_cd                character varying(2)     not null,
    hcpcs_5_mdfr_cd                character varying(2)     not null,

    clm_val_sqnc_num_prod          integer,
    clm_dgns_prcdr_icd_ind         character varying(1)     not null,
    clm_dgns_cd                    character varying(7)     not null,
-- instnl    clm_prcdr_cd                   character varying(7)     not null,
    clm_prod_type_cd               character varying(1)     not null,
    clm_poa_ind                    character varying(1)     not null,
-- instnl    clm_prcdr_prfrm_dt             date,
--     idr_insrt_ts_prod              timestamp with time zone not null,
--     idr_updt_ts_prod               timestamp with time zone not null,
-- instnl    clm_val_sqnc_num_val           integer,
-- instnl    clm_val_cd                     character varying(2)     not null,
-- instnl    clm_val_amt                    numeric,
--     idr_insrt_ts_val               timestamp with time zone not null,
--     idr_updt_ts_val                timestamp with time zone not null,

    clm_line_bnft_enhncmt_2_cd     character varying(2),
    clm_line_bnft_enhncmt_3_cd     character varying(2),
    clm_line_bnft_enhncmt_4_cd     character varying(2),
    clm_line_bnft_enhncmt_5_cd     character varying(2),
    clm_line_ngaco_cptatn_sw       character varying(1),
    clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
    clm_line_ngaco_snf_wvr_sw      character varying(1),
    clm_line_ngaco_tlhlth_sw       character varying(1),
    clm_line_aco_care_mgmt_hcbs_sw character varying(1),
    clm_line_ngaco_pbpmt_sw        character varying(1),
    clm_line_pmd_uniq_trkng_num    character varying(14),
--  pac   clm_line_pa_uniq_trkng_num     character varying(50),
    clm_line_bnft_enhncmt_1_cd     character varying(2),
--  instnl   clm_rlt_cond_cd                character varying(20),
--  instnl   clm_rlt_cond_sgntr_sqnc_num    integer,

    prvdr_rndrng_prvdr_npi_num     character varying(10),
    prvdr_rndrng_type_cd           character varying(2),
    bfd_prvdr_rndrng_careteam_name     character varying(135),
    clm_rndrg_fed_prvdr_spclty_cd  character varying(2),
    clm_rndrg_prvdr_tax_num        character varying(10),
    geo_rndrg_ssa_state_cd         character varying(2),
    clm_rndrg_prvdr_type_cd         character varying(3),

--  instnl, part d   clm_line_othr_tp_pd_amt        numeric,
--  instnl, part d   clm_line_ncvrd_pd_amt          numeric,
--  pac   clm_line_otaf_amt              numeric,
    -- claim line professional columns
    clm_bene_prmry_pyr_pd_amt      numeric,
    clm_fed_type_srvc_cd           character varying(1)     not null,
    clm_line_carr_clncl_lab_num    character varying(10)    not null,
    clm_line_carr_hpsa_scrcty_cd   character varying(1)     not null,
    clm_line_dmerc_scrn_svgs_amt   numeric,
    clm_line_hct_hgb_rslt_num      numeric,
    clm_line_hct_hgb_type_cd       character varying(2)     not null,
    clm_line_prfnl_dme_price_amt   numeric,
    clm_line_prfnl_mtus_cnt        numeric,
    clm_mtus_ind_cd                character varying(1)     not null,
    clm_physn_astnt_cd             character varying(1)     not null,
    clm_pmt_80_100_cd              character varying(1)     not null,
    clm_prcng_lclty_cd             character varying(2)     not null,
    clm_prcsg_ind_cd               character varying(2)     not null,
    clm_prmry_pyr_cd               character varying(1)     not null,
    clm_prvdr_spclty_cd            character varying(2)     not null,
    clm_srvc_ddctbl_sw             character varying(1)     not null,
    clm_suplr_type_cd              character varying(1)     not null,
    bfd_created_ts                 timestamp with time zone not null,
    bfd_updated_ts                 timestamp with time zone not null,
    clm_line_prfnl_intrst_amt      numeric,
    clm_line_carr_psych_ot_lmt_amt numeric,
    clm_line_carr_clncl_chrg_amt   numeric,
    clm_mdcr_prmry_pyr_alowd_amt   numeric,

--    clm_ocrnc_sgntr_sk             numeric,
--    clm_rlt_ocrnc_sgntr_sk         numeric,
    -- v2_mdcr_clm_line_mcs columns
-- ss    clm_line_rbndlg_crtfctn_num    character varying(10),
-- ss    clm_line_hct_lvl_num           numeric,
-- ss    clm_line_hgb_lvl_num           numeric,
    primary key (clm_uniq_id, bfd_row_id)
);

create table idr_new.claim_institutional_nch
(
    clm_uniq_id                    bigint                   not null primary key,
    --claim date sgntr
    clm_cms_proc_dt                date,
    clm_actv_care_from_dt          date,
    clm_dschrg_dt                  date,
    clm_submsn_dt                  date,
    clm_ncvrd_from_dt              date,
    clm_ncvrd_thru_dt              date,
    clm_actv_care_thru_dt          date,
    clm_mdcr_exhstd_dt             date,
    clm_nch_wkly_proc_dt           date,
    clm_qlfy_stay_from_dt          date,
    clm_qlfy_stay_thru_dt          date,
    --claim date sgntr
    clm_type_cd                    integer,
    bene_sk                        bigint                   not null,
    clm_cntl_num                   character varying(40)    not null,
    clm_orig_cntl_num              character varying(40)    not null,
    clm_from_dt                    date                     not null,
    clm_thru_dt                    date,
    clm_efctv_dt                   date,
    clm_obslt_dt                   date,
    clm_bill_clsfctn_cd            character varying(1)     not null,
    clm_bill_fac_type_cd           character varying(1)     not null,
    clm_bill_freq_cd               character varying(1)     not null,
    clm_finl_actn_ind              character varying(1)     not null,
     clm_src_id                 character varying(5)     not null,
    clm_query_cd                 character varying(1)     not null,
    clm_mdcr_coinsrnc_amt      numeric,
    clm_blood_lblty_amt        numeric,
    clm_ncvrd_chrg_amt         numeric,
    clm_mdcr_ddctbl_amt            numeric,
    clm_prvdr_pmt_amt              numeric,
    clm_alowd_chrg_amt             numeric,
--     clm_bene_pmt_amt           numeric,
    clm_cntrctr_num                character varying(5)     not null,
    clm_pmt_amt                    numeric,
    clm_pd_dt                      date,
    clm_ltst_clm_ind               character varying(1)     not null,

    prvdr_atndg_prvdr_npi_num      character varying(10),
    bfd_prvdr_atndg_careteam_name      character varying(135),
    clm_atndg_fed_prvdr_spclty_cd  character varying(2),

    prvdr_oprtg_prvdr_npi_num      character varying(10),
    bfd_prvdr_oprtg_careteam_name      character varying(135),
    clm_oprtg_fed_prvdr_spclty_cd  character varying(2),

    prvdr_othr_prvdr_npi_num       character varying(10),
    bfd_prvdr_othr_careteam_name       character varying(135),
    clm_othr_fed_prvdr_spclty_cd   character varying(2),

    prvdr_rndrg_prvdr_npi_num      character varying(10),
    bfd_prvdr_rndrg_careteam_name      character varying(135),
    clm_rndrg_fed_prvdr_spclty_cd  character varying(2),

    prvdr_blg_prvdr_npi_num        character varying(10),
    clm_blg_prvdr_oscar_num        character varying(13),
    prvdr_blg_1st_name             character varying(35),
    bfd_prvdr_blg_last_or_lgl_name     character varying(100),
    clm_blg_prvdr_zip5_cd          character varying(5),
    geo_blg_ssa_state_cd           character varying(2),

    prvdr_rfrg_prvdr_npi_num       character varying(10),
    bfd_prvdr_rfrg_careteam_name       character varying(135),
    clm_rfrg_fed_prvdr_spclty_cd   character varying(2),

    clm_disp_cd                    character varying(2)     not null,
-- pac    clm_ric_cd                 character varying(1)     not null,
    clm_sbmt_chrg_amt              numeric,
    clm_blood_pt_frnsh_qty         integer,
    clm_nch_prmry_pyr_cd       character varying(1)     not null,
--     clm_blg_prvdr_oscar_num      character varying(20)    not null,
    clm_idr_ld_dt                  date,
    clm_nrln_ric_cd                character varying(1)     not null,
--     prvdr_srvc_prvdr_npi_num   character varying(20)    not null,
--     prvdr_prscrbng_prvdr_npi_num character varying(10)    not null,
    bfd_created_ts                 timestamp with time zone not null,
    bfd_updated_ts                 timestamp with time zone not null,
    clm_adjstmt_type_cd            character varying(2),
    clm_bene_pd_amt                numeric,
--     clm_sbmt_frmt_cd           character varying(1),
--     clm_sbmtr_cntrct_num         character varying(5),
--     clm_sbmtr_cntrct_pbp_num     character varying(3),
    clm_bnft_enhncmt_1_cd          character varying(2),
    clm_ngaco_pbpmt_sw             character varying(1),
    clm_ngaco_cptatn_sw            character varying(1),
    clm_aco_care_mgmt_hcbs_sw      character varying(1),
    clm_ngaco_pdschrg_hcbs_sw      character varying(1),
    clm_ngaco_snf_wvr_sw           character varying(1),
    clm_ngaco_tlhlth_sw            character varying(1),
    clm_bnft_enhncmt_2_cd          character varying(2),
    clm_bnft_enhncmt_3_cd          character varying(2),
    clm_bnft_enhncmt_4_cd          character varying(2),
    clm_bnft_enhncmt_5_cd          character varying(2),
--     clm_rfrg_prvdr_pin_num     character varying(10),

    prvdr_srvc_prvdr_npi_num       character varying(10),
    bfd_prvdr_srvc_careteam_name       character varying(135),

    clm_blood_chrg_amt         numeric,
--     clm_tot_cntrctl_amt        numeric,
--     clm_bene_intrst_pd_amt     numeric,
--     clm_bene_pmt_coinsrnc_amt  numeric,
--     clm_cob_ptnt_resp_amt      numeric,
--     clm_prvdr_otaf_amt         numeric,
--     clm_othr_tp_pd_amt         numeric,
--     clm_prvdr_rmng_due_amt     numeric,
    clm_blood_ncvrd_chrg_amt   numeric,
--     clm_prvdr_intrst_pd_amt    numeric,
    bfd_claim_updated_ts           timestamp with time zone default now(),
    meta_src_sk                    integer                  not null,
    --     clm_instl columns
    clm_admsn_type_cd              varchar(2)               not null,
    bene_ptnt_stus_cd              varchar(2)               not null,
    dgns_drg_cd                    integer,
    clm_mdcr_instnl_mco_pd_sw      varchar(1)               not null,
    clm_admsn_src_cd               varchar(2)               not null,
    clm_fi_actn_cd                 varchar(1)               not null,
    clm_mdcr_ip_lrd_use_cnt        integer,
    clm_hha_rfrl_cd                varchar(1)               not null,
    clm_hha_lup_ind_cd             varchar(1)               not null,
    clm_hipps_uncompd_care_amt     numeric,
    clm_instnl_mdcr_coins_day_cnt  integer,
    clm_instnl_ncvrd_day_cnt       numeric,
    clm_instnl_per_diem_amt        numeric,
    clm_mdcr_hha_tot_visit_cnt     numeric,
    clm_mdcr_npmt_rsn_cd           varchar(2)               not null,
    clm_mdcr_ip_pps_drg_wt_num     numeric,
    clm_mdcr_ip_pps_dsprprtnt_amt  numeric,
    clm_mdcr_ip_pps_excptn_amt     numeric,
    clm_mdcr_ip_pps_cptl_fsp_amt   numeric,
    clm_mdcr_ip_pps_cptl_ime_amt   numeric,
    clm_mdcr_ip_pps_outlier_amt    numeric,
    clm_mdcr_ip_pps_cptl_hrmls_amt numeric,
    clm_mdcr_instnl_bene_pd_amt    numeric,
    clm_mdcr_hospc_prd_cnt         integer,
    clm_pps_ind_cd                 varchar(1)               not null,
    clm_mdcr_ip_pps_cptl_tot_amt   numeric,
    clm_instnl_cvrd_day_cnt        numeric,
    clm_mdcr_instnl_prmry_pyr_amt  numeric,
    clm_instnl_prfnl_amt           numeric,
    clm_mdcr_ip_bene_ddctbl_amt    numeric,
    clm_instnl_drg_outlier_amt     numeric,
    dgns_drg_outlier_cd            varchar(1),
    clm_mdcr_ip_scnd_yr_rate_amt   numeric,
    clm_instnl_low_vol_pmt_amt     numeric,
    clm_hipps_readmsn_rdctn_amt    numeric,
    clm_hipps_model_bndld_pmt_amt  numeric,
    clm_hipps_vbp_amt              numeric,
    clm_site_ntrl_ip_pps_pymt_amt  numeric,
    clm_finl_stdzd_pymt_amt        numeric,
    clm_pps_md_wvr_stdzd_val_amt   numeric,
    clm_hac_rdctn_pymt_amt         numeric,
    clm_mdcr_ip_1st_yr_rate_amt    numeric,
    clm_site_ntrl_cst_bsd_pymt_amt numeric,
    clm_ss_outlier_std_pymt_amt    numeric,
    clm_op_srvc_type_cd            varchar(1)
);


create index on idr_new.claim_institutional_ss (bene_sk);

create index on idr_new.claim_institutional_nch (bene_sk);


create table idr_new.claim_item_institutional_ss
(
    clm_uniq_id                 bigint                   not null,
    bfd_row_id                  integer                  not null,
    clm_line_num                integer,
--     missing implementation
    clm_line_ansthsa_unit_cnt   numeric,
--  prfnl   clm_line_dgns_cd               character varying(7)     not null,
    clm_line_sbmt_chrg_amt      numeric,
    clm_line_alowd_chrg_amt     numeric,
    clm_line_ncvrd_chrg_amt     numeric,
    clm_line_prvdr_pmt_amt      numeric,
    clm_line_bene_pmt_amt       numeric,
    clm_line_bene_pd_amt        numeric,
    clm_line_cvrd_pd_amt        numeric,
    clm_line_blood_ddctbl_amt   numeric,
    clm_line_mdcr_ddctbl_amt    numeric,
--  null for all   clm_line_mdcr_coinsrnc_amt     numeric,
    clm_line_hcpcs_cd           character varying(5)     not null,
    clm_line_from_dt            date,
    clm_line_ndc_cd             character varying(11)    not null,
    clm_line_ndc_qty            numeric,
    clm_line_ndc_qty_qlfyr_cd   character varying(2)     not null,
    clm_line_srvc_unit_qty      numeric,
    clm_line_rev_ctr_cd         character varying(4)     not null,
--  pfrnl, drug   clm_line_rx_num                character varying(30)    not null,
    clm_line_thru_dt            date,
--  prfnl   clm_pos_cd                     character varying(2)     not null,
--  prfnl   clm_rndrg_prvdr_prtcptg_cd     character varying(1)     not null,
--  prfnl   clm_rndrg_prvdr_tax_num        character varying(10)    not null,
    hcpcs_1_mdfr_cd             character varying(2)     not null,
    hcpcs_2_mdfr_cd             character varying(2)     not null,
    hcpcs_3_mdfr_cd             character varying(2)     not null,
    hcpcs_4_mdfr_cd             character varying(2)     not null,
    hcpcs_5_mdfr_cd             character varying(2)     not null,

    clm_val_sqnc_num_prod       integer,
    clm_dgns_prcdr_icd_ind      character varying(1)     not null,
    clm_dgns_cd                 character varying(7)     not null,
    clm_prcdr_cd                character varying(7)     not null,
    clm_prod_type_cd            character varying(1)     not null,
    clm_poa_ind                 character varying(1)     not null,
    clm_prcdr_prfrm_dt          date,
--     idr_insrt_ts_prod              timestamp with time zone not null,
--     idr_updt_ts_prod               timestamp with time zone not null,
    clm_val_sqnc_num_val        integer,
    clm_val_cd                  character varying(2)     not null,
    clm_val_amt                 numeric,
    clm_val_ansi_grp_cd         character varying(2)     not null,
    clm_val_ansi_rsn_cd         character varying(3)     not null,
--     idr_insrt_ts_val               timestamp with time zone not null,
--     idr_updt_ts_val                timestamp with time zone not null,
    bfd_created_ts              timestamp with time zone not null,
    bfd_updated_ts              timestamp with time zone not null,
--  prfnl   clm_rndrg_prvdr_type_cd        character varying(3),
--  prfnl   clm_line_bnft_enhncmt_2_cd     character varying(2),
--  prfnl   clm_line_bnft_enhncmt_3_cd     character varying(2),
--  prfnl   clm_line_bnft_enhncmt_4_cd     character varying(2),
--  prfnl   clm_line_bnft_enhncmt_5_cd     character varying(2),
--  prfnl   clm_line_ngaco_cptatn_sw       character varying(1),
--  prfnl   clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
--  prfnl   clm_line_ngaco_snf_wvr_sw      character varying(1),
--  prfnl   clm_line_ngaco_tlhlth_sw       character varying(1),
--  prfnl   clm_line_aco_care_mgmt_hcbs_sw character varying(1),
--  prfnl   clm_line_ngaco_pbpmt_sw        character varying(1),
--  adj  clm_line_pmd_uniq_trkng_num    character varying(14),
    clm_line_pa_uniq_trkng_num  character varying(50),
--  prfnl   clm_line_bnft_enhncmt_1_cd     character varying(2),
    clm_rlt_cond_cd             character varying(20),
    clm_rlt_cond_sgntr_sqnc_num integer,

    prvdr_rndrng_prvdr_npi_num      character varying(10),
    bfd_prvdr_rndrng_careteam_name      character varying(135),
    clm_rndrg_prvdr_type_cd        character varying(3),
    clm_rndrg_fed_prvdr_spclty_cd  character varying(2),

--     prvdr_rndrng_prvdr_npi_num   character varying(10),
--     prvdr_rndrng_sk              bigint,
--     prvdr_rndrng_mdl_name        character varying(25),
--     prvdr_rndrng_type_cd         character varying(2),
--     prvdr_rndrng_txnmy_cmpst_cd  character varying(150),
--     prvdr_rndrng_oscar_num       character varying(13),
--     prvdr_rndrng_1st_name        character varying(35),
--     prvdr_rndrng_name            character varying(70),
--     prvdr_rndrng_lgl_name        character varying(100),
--     prvdr_rndrng_emplr_id_num    character varying(10),
--     prvdr_rndrng_last_name       character varying(35),

    clm_line_othr_tp_pd_amt     numeric,
    clm_line_ncvrd_pd_amt       numeric,
    clm_line_otaf_amt           numeric,
    -- claim line institutional columns
    clm_rev_apc_hipps_cd        character varying(5)     not null,
    clm_otaf_one_ind_cd         character varying(1)     not null,
    clm_rev_dscnt_ind_cd        character varying(1)     not null,
    clm_rev_packg_ind_cd        character varying(1)     not null,
    clm_rev_cntr_stus_cd        character varying(2)     not null,
    clm_rev_pmt_mthd_cd         character varying(2)     not null,
    clm_ddctbl_coinsrnc_cd      character varying(1)     not null,
    clm_line_instnl_rate_amt    numeric,
    clm_line_instnl_adjstd_amt  numeric,
    clm_line_instnl_rdcd_amt    numeric,
    clm_line_instnl_msp1_pd_amt numeric,
    clm_line_instnl_msp2_pd_amt numeric,
    clm_line_instnl_rev_ctr_dt  date,
    clm_rev_cntr_tdapa_amt      numeric,
    clm_line_non_ehr_rdctn_amt  numeric,
    clm_line_add_on_pymt_amt    numeric,
    clm_ocrnc_sgntr_sk          numeric,
    clm_rlt_ocrnc_sgntr_sk      numeric,
    -- claim line fiss
    clm_line_msp_coinsrnc_amt   numeric,
    -- clm_line_fiss_bnft_svg
    clm_bnft_svg_ansi_grp_cd    character varying(2),
    clm_bnft_svg_ansi_rsn_cd    character varying(3),
    --  clm_ansi_sgntr
--  nch   clm_1_rev_cntr_ansi_grp_cd character varying(2)     not null,
--  not used   clm_2_rev_cntr_ansi_grp_cd character varying(2)     not null,
--  not used   clm_3_rev_cntr_ansi_grp_cd character varying(2)     not null,
--  not used   clm_4_rev_cntr_ansi_grp_cd character varying(2)     not null,
--  nch   clm_1_rev_cntr_ansi_rsn_cd character varying(3)     not null,
--  not used   clm_2_rev_cntr_ansi_rsn_cd character varying(3)     not null,
--  not used   clm_3_rev_cntr_ansi_rsn_cd character varying(3)     not null,
--  not used   clm_4_rev_cntr_ansi_rsn_cd character varying(3)     not null,
    primary key (clm_uniq_id, bfd_row_id)
);

create table idr_new.claim_item_institutional_nch
(
    clm_uniq_id                 bigint                   not null,
    bfd_row_id                  integer                  not null,
    clm_line_num                integer,
--  pac   clm_line_ansthsa_unit_cnt      numeric,
--  prfnl   clm_line_dgns_cd               character varying(7)     not null,
    clm_line_sbmt_chrg_amt      numeric,
--  pac   clm_line_alowd_chrg_amt        numeric,
    clm_line_ncvrd_chrg_amt     numeric,
    clm_line_prvdr_pmt_amt      numeric,
    clm_line_bene_pmt_amt       numeric,
    clm_line_bene_pd_amt        numeric,
    clm_line_cvrd_pd_amt        numeric,
    clm_line_blood_ddctbl_amt   numeric,
    clm_line_mdcr_ddctbl_amt    numeric,
--  null for all   clm_line_mdcr_coinsrnc_amt     numeric,
    clm_line_hcpcs_cd           character varying(5)     not null,
    clm_line_from_dt            date,
    clm_line_ndc_cd             character varying(11)    not null,
    clm_line_ndc_qty            numeric,
    clm_line_ndc_qty_qlfyr_cd   character varying(2)     not null,
    clm_line_srvc_unit_qty      numeric,
    clm_line_rev_ctr_cd         character varying(4)     not null,
--  pfrnl, drug   clm_line_rx_num                character varying(30)    not null,
    clm_line_thru_dt            date,
--  prfnl   clm_pos_cd                     character varying(2)     not null,
--  prfnl   clm_rndrg_prvdr_prtcptg_cd     character varying(1)     not null,
--  prfnl   clm_rndrg_prvdr_tax_num        character varying(10)    not null,
    hcpcs_1_mdfr_cd             character varying(2)     not null,
    hcpcs_2_mdfr_cd             character varying(2)     not null,
    hcpcs_3_mdfr_cd             character varying(2)     not null,
    hcpcs_4_mdfr_cd             character varying(2)     not null,
    hcpcs_5_mdfr_cd             character varying(2)     not null,

    clm_val_sqnc_num_prod       integer,
    clm_dgns_prcdr_icd_ind      character varying(1)     not null,
    clm_dgns_cd                 character varying(7)     not null,
    clm_prcdr_cd                character varying(7)     not null,
    clm_prod_type_cd            character varying(1)     not null,
    clm_poa_ind                 character varying(1)     not null,
    clm_prcdr_prfrm_dt          date,
--     idr_insrt_ts_prod              timestamp with time zone not null,
--     idr_updt_ts_prod               timestamp with time zone not null,
    clm_val_sqnc_num_val        integer,
    clm_val_cd                  character varying(2)     not null,
    clm_val_amt                 numeric,
--     idr_insrt_ts_val               timestamp with time zone not null,
--     idr_updt_ts_val                timestamp with time zone not null,
    bfd_created_ts              timestamp with time zone not null,
    bfd_updated_ts              timestamp with time zone not null,
--  prfnl   clm_rndrg_prvdr_type_cd        character varying(3),
--  prfnl   clm_line_bnft_enhncmt_2_cd     character varying(2),
--  prfnl   clm_line_bnft_enhncmt_3_cd     character varying(2),
--  prfnl   clm_line_bnft_enhncmt_4_cd     character varying(2),
--  prfnl   clm_line_bnft_enhncmt_5_cd     character varying(2),
--  prfnl   clm_line_ngaco_cptatn_sw       character varying(1),
--  prfnl   clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
--  prfnl   clm_line_ngaco_snf_wvr_sw      character varying(1),
--  prfnl   clm_line_ngaco_tlhlth_sw       character varying(1),
--  prfnl   clm_line_aco_care_mgmt_hcbs_sw character varying(1),
--  prfnl   clm_line_ngaco_pbpmt_sw        character varying(1),
    clm_line_pmd_uniq_trkng_num character varying(14),
--  pac   clm_line_pa_uniq_trkng_num     character varying(50),
--  prfnl   clm_line_bnft_enhncmt_1_cd     character varying(2),
    clm_rlt_cond_cd             character varying(20),
    clm_rlt_cond_sgntr_sqnc_num integer,

    bfd_prvdr_rndrng_careteam_name character varying(135),
    clm_rndrg_fed_prvdr_spclty_cd  character varying(2),
    clm_rndrg_prvdr_type_cd        character varying(3),
    prvdr_rndrng_prvdr_npi_num  character varying(10),
--     prvdr_rndrng_sk             bigint,
--     prvdr_rndrng_mdl_name       character varying(25),
--     prvdr_rndrng_type_cd        character varying(2),
--     prvdr_rndrng_txnmy_cmpst_cd character varying(150),
--     prvdr_rndrng_oscar_num      character varying(13),
--     prvdr_rndrng_1st_name       character varying(35),
--     prvdr_rndrng_name           character varying(70),
--     prvdr_rndrng_lgl_name       character varying(100),
--     prvdr_rndrng_emplr_id_num   character varying(10),
--     prvdr_rndrng_last_name      character varying(35),

--  pac   clm_line_othr_tp_pd_amt        numeric,
--  pac   clm_line_ncvrd_pd_amt          numeric,
--  pac   clm_line_otaf_amt              numeric,
    -- claim line institutional columns
    clm_rev_apc_hipps_cd        character varying(5)     not null,
    clm_otaf_one_ind_cd         character varying(1)     not null,
    clm_rev_dscnt_ind_cd        character varying(1)     not null,
    clm_rev_packg_ind_cd        character varying(1)     not null,
    clm_rev_cntr_stus_cd        character varying(2)     not null,
    clm_rev_pmt_mthd_cd         character varying(2)     not null,
    clm_ddctbl_coinsrnc_cd      character varying(1)     not null,
    clm_line_instnl_rate_amt    numeric,
    clm_line_instnl_adjstd_amt  numeric,
    clm_line_instnl_rdcd_amt    numeric,
    clm_line_instnl_msp1_pd_amt numeric,
    clm_line_instnl_msp2_pd_amt numeric,
    clm_line_instnl_rev_ctr_dt  date,
    clm_rev_cntr_tdapa_amt      numeric,
--  pac   clm_line_non_ehr_rdctn_amt  numeric,
    clm_line_add_on_pymt_amt    numeric,
    clm_ocrnc_sgntr_sk          numeric,
    clm_rlt_ocrnc_sgntr_sk      numeric,
    --  clm_ansi_sgntr
    clm_1_rev_cntr_ansi_grp_cd  character varying(2)     not null,
--  not used   clm_2_rev_cntr_ansi_grp_cd character varying(2)     not null,
--  not used   clm_3_rev_cntr_ansi_grp_cd character varying(2)     not null,
--  not used   clm_4_rev_cntr_ansi_grp_cd character varying(2)     not null,
    clm_1_rev_cntr_ansi_rsn_cd  character varying(3)     not null,
--  not used   clm_2_rev_cntr_ansi_rsn_cd character varying(3)     not null,
--  not used   clm_3_rev_cntr_ansi_rsn_cd character varying(3)     not null,
--  not used   clm_4_rev_cntr_ansi_rsn_cd character varying(3)     not null,
    primary key (clm_uniq_id, bfd_row_id)
);


create table idr_new.claim_rx
(
    clm_uniq_id                       bigint                not null primary key,
    --claim date sgntr
    clm_cms_proc_dt                   date,
--     clm_actv_care_from_dt date                     ,
--  non_rx   clm_dschrg_dt         date                     ,
    clm_submsn_dt                     date,
--  non_rx   clm_ncvrd_from_dt     date                     ,
--  non_rx   clm_ncvrd_thru_dt     date                     ,
--     clm_actv_care_thru_dt date                     ,
--  non_rx   clm_mdcr_exhstd_dt                date,
--  non_rx   clm_nch_wkly_proc_dt              date,
--  non_rx   clm_qlfy_stay_from_dt date                     not null,
--  non_rx   clm_qlfy_stay_thru_dt date                     not null,
    --claim date sgntr
    clm_type_cd                       integer               not null,
    bene_sk                           bigint                not null,
    clm_cntl_num                      character varying(40) not null,
    clm_orig_cntl_num                 character varying(40) not null,
    clm_from_dt                       date                  not null,
    clm_thru_dt                       date,
    clm_efctv_dt                      date,
    clm_obslt_dt                      date,
--     instnl clm_bill_clsfctn_cd        character varying(1)     not null,
--     instnl clm_bill_fac_type_cd       character varying(1)     not null,
--     instnl clm_bill_freq_cd           character varying(1)     not null,
    clm_finl_actn_ind                 character varying(1)  not null,
    clm_src_id                        character varying(5)  not null,
--  non_rx clm_query_cd                 character varying(1)     not null,
    clm_mdcr_coinsrnc_amt      numeric,
--  non_rx   clm_blood_lblty_amt        numeric,
--  non_rx   clm_ncvrd_chrg_amt         numeric,
    clm_mdcr_ddctbl_amt        numeric,
--  non_rx   clm_prvdr_pmt_amt          numeric,
    clm_alowd_chrg_amt         numeric,
    clm_bene_pmt_amt                  numeric,
    clm_cntrctr_num            character varying(5)     not null,
    clm_pmt_amt                numeric,
    clm_pd_dt                         date,
    clm_ltst_clm_ind                  character varying(1)  not null,
--     prvdr_othr_prvdr_npi_num   character varying(10)    not null,
--     prvdr_othr_sk              bigint                   not null,
--     prvdr_othr_hstry_efctv_dt  date                     not null,
--     prvdr_othr_mdl_name        character varying(25)    not null,
--     prvdr_othr_type_cd         character varying(2)     not null,
--     prvdr_othr_txnmy_cmpst_cd  character varying(150)   not null,
--     prvdr_othr_oscar_num       character varying(13)    not null,
--     prvdr_othr_1st_name        character varying(35)    not null,
--     prvdr_othr_name            character varying(70)    not null,
--     prvdr_othr_hstry_obslt_dt  date                     not null,
--     prvdr_othr_lgl_name        character varying(100)   not null,
--     prvdr_othr_emplr_id_num    character varying(10)    not null,
--     prvdr_othr_last_name       character varying(35)    not null,
--     prvdr_blg_prvdr_npi_num    character varying(10)    not null,
--     prvdr_blg_sk               bigint                   not null,
--     prvdr_blg_hstry_efctv_dt   date                     not null,
--     prvdr_blg_mdl_name         character varying(25)    not null,
--     prvdr_blg_type_cd          character varying(2)     not null,
--     prvdr_blg_txnmy_cmpst_cd   character varying(150)   not null,
--     prvdr_blg_oscar_num        character varying(13)    not null,
--     prvdr_blg_1st_name         character varying(35)    not null,
--     prvdr_blg_name             character varying(70)    not null,
--     prvdr_blg_hstry_obslt_dt   date                     not null,
--     prvdr_blg_lgl_name         character varying(100)   not null,
--     prvdr_blg_emplr_id_num     character varying(10)    not null,
--     prvdr_blg_last_name        character varying(35)    not null,
--     prvdr_rfrg_prvdr_npi_num   character varying(10)    not null,
--     prvdr_rfrg_sk              bigint                   not null,
--     prvdr_rfrg_hstry_efctv_dt  date                     not null,
--     prvdr_rfrg_mdl_name        character varying(25)    not null,
--     prvdr_rfrg_type_cd         character varying(2)     not null,
--     prvdr_rfrg_txnmy_cmpst_cd  character varying(150)   not null,
--     prvdr_rfrg_oscar_num       character varying(13)    not null,
--     prvdr_rfrg_1st_name        character varying(35)    not null,
--     prvdr_rfrg_name            character varying(70)    not null,
--     prvdr_rfrg_hstry_obslt_dt  date                     not null,
--     prvdr_rfrg_lgl_name        character varying(100)   not null,
--     prvdr_rfrg_emplr_id_num    character varying(10)    not null,
--     prvdr_rfrg_last_name       character varying(35)    not null,
--  non_rx   clm_disp_cd                  character varying(2)     not null,
--  instnl   clm_ric_cd                 character varying(1)     not null,
    clm_sbmt_chrg_amt          numeric,
--  non_rx   clm_blood_pt_frnsh_qty     integer,
    clm_nch_prmry_pyr_cd       character varying(1)     not null,
--  instnl   clm_blg_prvdr_oscar_num      character varying(20)    not null,
    clm_idr_ld_dt                     date,
--  instnl   clm_nrln_ric_cd            character varying(1)     not null,
--  prvdr   prvdr_srvc_prvdr_npi_num   character varying(20)    not null,

    prvdr_prscrbng_prvdr_npi_num      character varying(10),
    bfd_prvdr_prscrbng_careteam_name      character varying(135),
    prvdr_prsbng_id_qlfyr_cd          character varying(2),
--     idr_insrt_ts_dcmtn         timestamp with time zone not null,
--     idr_updt_ts_dcmtn          timestamp with time zone not null,
    bfd_created_ts                    timestamp with time zone,
    bfd_updated_ts                    timestamp with time zone,
    clm_adjstmt_type_cd               character varying(2),
    clm_bene_pd_amt            numeric,
--  prvdr   clm_blg_prvdr_zip5_cd        character varying(5),
    clm_sbmt_frmt_cd                  character varying(1),
    clm_sbmtr_cntrct_num              character varying(5),
    clm_sbmtr_cntrct_pbp_num          character varying(3),
--  instnl   clm_bnft_enhncmt_1_cd      character varying(2),
--  instnl   clm_ngaco_pbpmt_sw         character varying(1),
--  instnl   clm_ngaco_cptatn_sw        character varying(1),
--  instnl   clm_ngaco_pdschrg_hcbs_sw  character varying(1),
--  instnl   clm_ngaco_snf_wvr_sw       character varying(1),
--  instnl   clm_ngaco_tlhlth_sw        character varying(1),
--  instnl   clm_bnft_enhncmt_2_cd      character varying(2),
--  instnl   clm_bnft_enhncmt_3_cd      character varying(2),
--  instnl   clm_bnft_enhncmt_4_cd      character varying(2),
--  instnl   clm_bnft_enhncmt_5_cd      character varying(2),
--  prvdr   clm_rfrg_prvdr_pin_num     character varying(10),
    prvdr_srvc_prvdr_npi_num          character varying(10),
    prvdr_srvc_last_or_lgl_name          character varying(135),
    prvdr_srvc_1st_name          character varying(35),
    prvdr_srvc_id_qlfyr_cd              character varying(2),
    clm_srvc_prvdr_gnrc_id_num      character varying(20),
    clm_prsbng_prvdr_gnrc_id_num     character varying(20),
--     clm_blood_chrg_amt         numeric,
--  instnl   clm_tot_cntrctl_amt        numeric,
    clm_bene_intrst_pd_amt     numeric,
    clm_bene_pmt_coinsrnc_amt  numeric,
--  non_rx   clm_cob_ptnt_resp_amt      numeric,
--  non_rx   clm_prvdr_otaf_amt         numeric,
    clm_othr_tp_pd_amt                numeric,
--  non_rx   clm_prvdr_rmng_due_amt     numeric,
--  non_rx   clm_blood_ncvrd_chrg_amt   numeric,
--  non_rx   clm_prvdr_intrst_pd_amt    numeric,
    bfd_claim_updated_ts              timestamp with time zone default now(),
--- line_item columns
--    clm_line_num                      integer               not null,
--     clm_line_ansthsa_unit_cnt         numeric,
--  prfnl   clm_line_dgns_cd               character varying(7)     not null,
--  non_rx   clm_line_sbmt_chrg_amt         numeric,
--  non_rx   clm_line_alowd_chrg_amt        numeric,
--  instnl   clm_line_ncvrd_chrg_amt        numeric,
--  non_rx   clm_line_prvdr_pmt_amt         numeric,
    clm_line_bene_pmt_amt             numeric,
--  non_rx   clm_line_bene_pd_amt           numeric,
    clm_line_cvrd_pd_amt              numeric,
--  instnl  clm_line_blood_ddctbl_amt      numeric,
--  instnl  clm_line_mdcr_ddctbl_amt       numeric,
--  null for all   clm_line_mdcr_coinsrnc_amt     numeric,
--  non_rx   clm_line_hcpcs_cd              character varying(5)     not null,
    clm_line_from_dt                  date,
    clm_line_ndc_cd                   character varying(11) not null,
    clm_line_ndc_qty                  numeric,
    clm_line_ndc_qty_qlfyr_cd         character varying(2)  not null,
    clm_line_srvc_unit_qty            numeric,
--  instnl   clm_line_rev_ctr_cd            character varying(4)     not null,
    clm_line_rx_num                   character varying(30) not null,
    clm_line_thru_dt                  date,
--  prfnl   clm_pos_cd                     character varying(2)     not null,
--  prfnl   clm_rndrg_prvdr_prtcptg_cd     character varying(1)     not null,
--  prfnl   clm_rndrg_prvdr_tax_num        character varying(10)    not null,
--  non_rx   hcpcs_1_mdfr_cd                character varying(2)     not null,
--  non_rx   hcpcs_2_mdfr_cd                character varying(2)     not null,
--  non_rx   hcpcs_3_mdfr_cd                character varying(2)     not null,
--  non_rx   hcpcs_4_mdfr_cd                character varying(2)     not null,
--  non_rx   hcpcs_5_mdfr_cd                character varying(2)     not null,
--  non_rx   clm_val_sqnc_num_prod          integer,
--  non_rx   clm_dgns_prcdr_icd_ind         character varying(1)     not null,
--  non_rx   clm_dgns_cd                    character varying(7)     not null,
--  non_rx   clm_prcdr_cd                   character varying(7)     not null,
--  non_rx   clm_prod_type_cd               character varying(1)     not null,
--  non_rx   clm_poa_ind                    character varying(1)     not null,
--  non_rx   clm_prcdr_prfrm_dt             date                     not null,
--  non_rx   idr_insrt_ts_prod              timestamp with time zone not null,
--  non_rx   idr_updt_ts_prod               timestamp with time zone not null,
--  non_rx   clm_val_sqnc_num_val           integer,
--  non_rx   clm_val_cd                     character varying(2)     not null,
--  non_rx   clm_val_amt                    numeric,
--  non_rx   idr_insrt_ts_val               timestamp with time zone not null,
--  non_rx   idr_updt_ts_val                timestamp with time zone not null,
--  non_rx   clm_rndrg_prvdr_type_cd        character varying(3),
--  non_rx   clm_line_bnft_enhncmt_2_cd     character varying(2),
--  non_rx   clm_line_bnft_enhncmt_3_cd     character varying(2),
--  non_rx   clm_line_bnft_enhncmt_4_cd     character varying(2),
--  non_rx   clm_line_bnft_enhncmt_5_cd     character varying(2),
--  non_rx   clm_line_ngaco_cptatn_sw       character varying(1),
--  non_rx   clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
--  non_rx   clm_line_ngaco_snf_wvr_sw      character varying(1),
--  non_rx   clm_line_ngaco_tlhlth_sw       character varying(1),
--  non_rx   clm_line_aco_care_mgmt_hcbs_sw character varying(1),
--  non_rx   clm_line_ngaco_pbpmt_sw        character varying(1),
--  non_rx   idr_insrt_ts_line_dcmtn        timestamp with time zone,
--  non_rx   idr_updt_ts_line_dcmtn         timestamp with time zone,
--  non_rx   clm_line_pmd_uniq_trkng_num    character varying(14),
--  non_rx   clm_line_pa_uniq_trkng_num     character varying(50),
--  non_rx   clm_line_bnft_enhncmt_1_cd     character varying(2),
--  non_rx   clm_rlt_cond_sgntr_sk          bigint,
--  non_rx   clm_rlt_cond_cd                character varying(20),
--  non_rx   clm_rlt_cond_sgntr_sqnc_num    integer,
--  non_rx   idr_insrt_ts_rlt_cond          timestamp with time zone,
--  non_rx   idr_updt_ts_rlt_cond           timestamp with time zone,
--  non_rx   clm_rndrg_prvdr_npi_num        character varying(10),
--  non_rx   prvdr_rndrng_prvdr_npi_num     character varying(10),
    clm_line_othr_tp_pd_amt           numeric,
    clm_line_ncvrd_pd_amt             numeric,
--  non_rx   clm_line_otaf_amt              numeric,
-- clm_line_rx columns
    clm_brnd_gnrc_cd                  character varying(1)  not null,
    clm_cmpnd_cd                      character varying(1)  not null,
    clm_ctstrphc_cvrg_ind_cd          character varying(1)  not null,
    clm_daw_prod_slctn_cd             character varying(1)  not null,
    clm_drug_cvrg_stus_cd             character varying(2)  not null,
    clm_dspnsng_stus_cd               character varying(1)  not null,
    clm_line_authrzd_fill_num         character varying(2),
    clm_line_days_suply_qty           integer,
    clm_line_grs_above_thrshld_amt    numeric,
    clm_line_grs_blw_thrshld_amt      numeric,
    clm_prnt_cntl_num                 varchar(40),
    clm_line_ingrdnt_cst_amt          numeric,
    clm_line_lis_amt                  numeric,
    clm_line_plro_amt                 numeric,
    clm_line_rx_fill_num              integer,
    clm_line_rx_orgn_cd               character varying(1)  not null,
    clm_line_sls_tax_amt              numeric,
    clm_line_srvc_cst_amt             numeric,
    clm_line_troop_tot_amt            numeric,
    clm_line_vccn_admin_fee_amt       numeric,
    clm_ltc_dspnsng_mthd_cd           character varying(3)  not null,
    clm_phrmcy_srvc_type_cd           character varying(2)  not null,
    clm_prcng_excptn_cd               character varying(1)  not null,
    clm_ptnt_rsdnc_cd                 character varying(2)  not null,
    clm_line_rptd_gap_dscnt_amt       numeric,
    clm_rptd_mftr_dscnt_amt           numeric,
    clm_line_rebt_passthru_pos_amt    numeric,
    clm_cms_calcd_mftr_dscnt_amt      numeric,
    clm_line_grs_cvrd_cst_tot_amt     numeric,
    clm_phrmcy_price_dscnt_at_pos_amt numeric,
    cntrct_pbp_name                   character varying(75) not null,
    meta_src_sk                    integer                  not null
);


create index on idr_new.claim_rx (bene_sk);
