CREATE TABLE idr_new.claim_professional_ss
(
    clm_uniq_id                    bigint                   NOT NULL PRIMARY KEY,
    --CLAIM DATE SGNTR
--  INSTNL   clm_cms_proc_dt                date                     NOT NULL,
--   NCH   clm_actv_care_from_dt          date,
--   NCH  clm_dschrg_dt                  date,
    clm_submsn_dt                  date,
--   NCH  clm_ncvrd_from_dt              date,
--   NCH  clm_ncvrd_thru_dt              date,
--   NCH  clm_actv_care_thru_dt          date,
--   NCH  clm_mdcr_exhstd_dt             date,
--   NCH  clm_nch_wkly_proc_dt           date,
--   NCH  clm_qlfy_stay_from_dt          date,
--   NCH  clm_qlfy_stay_thru_dt          date,
    --CLAIM DATE SGNTR
    clm_type_cd                    integer                  NOT NULL,
    bene_sk                        bigint                   NOT NULL,
    clm_cntl_num                   character varying(40)    NOT NULL,
    clm_orig_cntl_num              character varying(40)    NOT NULL,
    clm_from_dt                    date                     NOT NULL,
    clm_thru_dt                    date,
    clm_efctv_dt                   date,
    clm_obslt_dt                   date,
--     INSTNL clm_bill_clsfctn_cd        character varying(1)     NOT NULL,
--     INSTNL clm_bill_fac_type_cd       character varying(1)     NOT NULL,
--     INSTNL clm_bill_freq_cd           character varying(1)     NOT NULL,
    clm_finl_actn_ind              character varying(1)     NOT NULL,
    clm_src_id                     character varying(5)     NOT NULL,
--     ADJ clm_query_cd                 character varying(1)     NOT NULL,
    clm_mdcr_coinsrnc_amt          numeric,
    clm_blood_lblty_amt            numeric,
    clm_ncvrd_chrg_amt             numeric,
    clm_mdcr_ddctbl_amt            numeric,
    clm_prvdr_pmt_amt              numeric,
    clm_alowd_chrg_amt             numeric,
    clm_bene_pmt_amt               numeric,
    clm_cntrctr_num                character varying(5)     NOT NULL,
    clm_pmt_amt                    numeric,
    clm_pd_dt                      date,
    clm_ltst_clm_ind               character varying(1)     NOT NULL,
    prvdr_othr_prvdr_npi_num       character varying(10),
    prvdr_othr_sk                  bigint,
    prvdr_othr_mdl_name            character varying(25),
    prvdr_othr_type_cd             character varying(2),
    prvdr_othr_txnmy_cmpst_cd      character varying(150),
    prvdr_othr_oscar_num           character varying(13),
    prvdr_othr_1st_name            character varying(35),
    prvdr_othr_name                character varying(70),
    prvdr_othr_lgl_name            character varying(100),
    prvdr_othr_emplr_id_num        character varying(10),
    prvdr_othr_last_name           character varying(35),
    prvdr_blg_prvdr_npi_num        character varying(10),
    prvdr_blg_sk                  bigint,
    prvdr_blg_mdl_name             character varying(25),
    prvdr_blg_type_cd              character varying(2),
    prvdr_blg_txnmy_cmpst_cd       character varying(150),
    prvdr_blg_oscar_num            character varying(13),
    prvdr_blg_1st_name             character varying(35),
    prvdr_blg_name                 character varying(70),
    prvdr_blg_lgl_name             character varying(100),
    prvdr_blg_emplr_id_num         character varying(10),
    prvdr_blg_last_name            character varying(35),
    prvdr_rfrg_prvdr_npi_num       character varying(10),
    prvdr_rfrg_sk                  bigint,
    prvdr_rfrg_mdl_name            character varying(25),
    prvdr_rfrg_type_cd             character varying(2),
    prvdr_rfrg_txnmy_cmpst_cd      character varying(150),
    prvdr_rfrg_oscar_num           character varying(13),
    prvdr_rfrg_1st_name            character varying(35),
    prvdr_rfrg_name                character varying(70),
    prvdr_rfrg_lgl_name            character varying(100),
    prvdr_rfrg_emplr_id_num        character varying(10),
    prvdr_rfrg_last_name           character varying(35),
--  ADJ   clm_disp_cd                  character varying(2)     NOT NULL,
--  INSTNL   clm_ric_cd                 character varying(1)     NOT NULL,
    clm_sbmt_chrg_amt              numeric,
    clm_blood_pt_frnsh_qty         integer,
    clm_nch_prmry_pyr_cd           character varying(1)     NOT NULL,
--  INSTNL   clm_blg_prvdr_oscar_num      character varying(20)    NOT NULL,
    clm_idr_ld_dt                  date,
    clm_nrln_ric_cd            character varying(1)     NOT NULL,
    prvdr_srvc_prvdr_npi_num   character varying(20),
--  DRUG   prvdr_prscrbng_prvdr_npi_num character varying(10)    NOT NULL,
--     idr_insrt_ts_dcmtn         timestamp with time zone NOT NULL,
--     idr_updt_ts_dcmtn          timestamp with time zone NOT NULL,
    bfd_created_ts                 timestamp with time zone NOT NULL,
    bfd_updated_ts                 timestamp with time zone NOT NULL,
    clm_adjstmt_type_cd            character varying(2),
    clm_bene_pd_amt                numeric,
    clm_blg_prvdr_zip5_cd        character varying(5),
    clm_sbmt_frmt_cd               character varying(1),
--  Part D   clm_sbmtr_cntrct_num         character varying(5),
--  Part D   clm_sbmtr_cntrct_pbp_num     character varying(3),
--  INSTNL   clm_bnft_enhncmt_1_cd      character varying(2),
--  INSTNL   clm_ngaco_pbpmt_sw         character varying(1),
--  INSTNL   clm_ngaco_cptatn_sw        character varying(1),
--  INSTNL   clm_ngaco_pdschrg_hcbs_sw  character varying(1),
--  INSTNL   clm_ngaco_snf_wvr_sw       character varying(1),
--  INSTNL   clm_ngaco_tlhlth_sw        character varying(1),
--  INSTNL   clm_bnft_enhncmt_2_cd      character varying(2),
--  INSTNL   clm_bnft_enhncmt_3_cd      character varying(2),
--  INSTNL   clm_bnft_enhncmt_4_cd      character varying(2),
--  INSTNL   clm_bnft_enhncmt_5_cd      character varying(2),
    clm_rfrg_prvdr_pin_num     character varying(14),
    prvdr_srvc_sk                  bigint,
    prvdr_srvc_mdl_name            character varying(25),
    prvdr_srvc_type_cd             character varying(2),
    prvdr_srvc_txnmy_cmpst_cd      character varying(150),
    prvdr_srvc_oscar_num           character varying(13),
    prvdr_srvc_1st_name            character varying(35),
    prvdr_srvc_name                character varying(70),
    prvdr_srvc_lgl_name            character varying(100),
    prvdr_srvc_emplr_id_num        character varying(10),
    prvdr_srvc_last_name           character varying(35),
    clm_blood_chrg_amt             numeric,
--  INSTNL   clm_tot_cntrctl_amt        numeric,
    clm_bene_intrst_pd_amt         numeric,
    clm_bene_pmt_coinsrnc_amt      numeric,
    clm_cob_ptnt_resp_amt          numeric,
    clm_prvdr_otaf_amt             numeric,
    clm_othr_tp_pd_amt             numeric,
    clm_prvdr_rmng_due_amt         numeric,
    clm_blood_ncvrd_chrg_amt       numeric,
    clm_prvdr_intrst_pd_amt        numeric,
    clm_mdcr_prfnl_prvdr_asgnmt_sw character varying(2)     NOT NULL,
    clm_audt_trl_stus_cd           character varying(2),
    clm_prvdr_acnt_rcvbl_ofst_amt  numeric,
    clm_clncl_tril_num        character varying(8),
    bfd_claim_updated_ts           timestamp with time zone DEFAULT now(),
    meta_src_sk                    integer
);

CREATE TABLE idr_new.claim_professional_nch
(
    clm_uniq_id               bigint                   NOT NULL PRIMARY KEY,
    --CLAIM DATE SGNTR
--  INSTNL   clm_cms_proc_dt           date,
--    clm_actv_care_from_dt     date,
    --   clm_dschrg_dt             date,
    clm_submsn_dt             date,
--    clm_ncvrd_from_dt         date,
--    clm_ncvrd_thru_dt         date,
    --   clm_actv_care_thru_dt     date,
--    clm_mdcr_exhstd_dt        date,
    clm_nch_wkly_proc_dt      date,
--    clm_qlfy_stay_from_dt     date,
--    clm_qlfy_stay_thru_dt     date,
    --CLAIM DATE SGNTR
    clm_type_cd               integer                  NOT NULL,
    bene_sk                   bigint                   NOT NULL,
    clm_cntl_num              character varying(40)    NOT NULL,
    clm_orig_cntl_num          character varying(40)    NOT NULL,
    clm_from_dt               date                     NOT NULL,
    clm_thru_dt               date,
    clm_efctv_dt              date,
    clm_obslt_dt              date,
--     INSTNL clm_bill_clsfctn_cd        character varying(1)     NOT NULL,
--     INSTNL clm_bill_fac_type_cd       character varying(1)     NOT NULL,
--     INSTNL clm_bill_freq_cd           character varying(1)     NOT NULL,
    clm_finl_actn_ind         character varying(1)     NOT NULL,
--   clm_src_id                character varying(5)     NOT NULL,
    clm_query_cd              character varying(1)     NOT NULL,
--     PAC clm_mdcr_coinsrnc_amt      numeric,
--     PAC clm_blood_lblty_amt        numeric,
--     PAC clm_ncvrd_chrg_amt         numeric,
    clm_mdcr_ddctbl_amt       numeric,
    clm_prvdr_pmt_amt         numeric,
    clm_alowd_chrg_amt        numeric,
    clm_bene_pmt_amt          numeric,
    clm_cntrctr_num           character varying(5)     NOT NULL,
    clm_pmt_amt               numeric,
    clm_pd_dt                 date,
    clm_ltst_clm_ind          character varying(1)     NOT NULL,
--   PAC  prvdr_othr_prvdr_npi_num   character varying(10)    NOT NULL,
--   PAC  prvdr_othr_sk              bigint                   NOT NULL,
--   PAC  prvdr_othr_hstry_efctv_dt  date                     NOT NULL,
--   PAC  prvdr_othr_mdl_name        character varying(25)    NOT NULL,
--   PAC  prvdr_othr_type_cd         character varying(2)     NOT NULL,
--   PAC  prvdr_othr_txnmy_cmpst_cd  character varying(150)   NOT NULL,
--   PAC  prvdr_othr_oscar_num       character varying(13)    NOT NULL,
--   PAC  prvdr_othr_1st_name        character varying(35)    NOT NULL,
--   PAC  prvdr_othr_name            character varying(70)    NOT NULL,
--   PAC  prvdr_othr_hstry_obslt_dt  date                     NOT NULL,
--   PAC  prvdr_othr_lgl_name        character varying(100)   NOT NULL,
--   PAC  prvdr_othr_emplr_id_num    character varying(10)    NOT NULL,
--   PAC  prvdr_othr_last_name       character varying(35)    NOT NULL,
    prvdr_blg_prvdr_npi_num   character varying(10),
    prvdr_blg_sk              bigint,
    prvdr_blg_mdl_name        character varying(25),
    prvdr_blg_type_cd         character varying(2),
    prvdr_blg_txnmy_cmpst_cd  character varying(150),
    prvdr_blg_oscar_num       character varying(13),
    prvdr_blg_1st_name        character varying(35),
    prvdr_blg_name            character varying(70),
    prvdr_blg_lgl_name        character varying(100),
    prvdr_blg_emplr_id_num    character varying(10),
    prvdr_blg_last_name       character varying(35),
    prvdr_rfrg_prvdr_npi_num  character varying(10),
    prvdr_rfrg_sk             bigint,
    prvdr_rfrg_mdl_name       character varying(25),
    prvdr_rfrg_type_cd        character varying(2),
    prvdr_rfrg_txnmy_cmpst_cd character varying(150),
    prvdr_rfrg_oscar_num      character varying(13),
    prvdr_rfrg_1st_name       character varying(35),
    prvdr_rfrg_name           character varying(70),
    prvdr_rfrg_lgl_name       character varying(100),
    prvdr_rfrg_emplr_id_num   character varying(10),
    prvdr_rfrg_last_name      character varying(35),
    clm_disp_cd               character varying(2)     NOT NULL,
--  INSTNL   clm_ric_cd                 character varying(1)     NOT NULL,
    clm_sbmt_chrg_amt         numeric,
    clm_blood_pt_frnsh_qty    integer,
--  PAC   clm_nch_prmry_pyr_cd       character varying(1)     NOT NULL,
--  INSTNL   clm_blg_prvdr_oscar_num      character varying(20)    NOT NULL,
    clm_idr_ld_dt             date,
    clm_nrln_ric_cd            character varying(1)     NOT NULL,
    prvdr_srvc_prvdr_npi_num   character varying(20)    NOT NULL,
--  DRUG   prvdr_prscrbng_prvdr_npi_num character varying(10)    NOT NULL,
--     idr_insrt_ts_dcmtn         timestamp with time zone NOT NULL,
--     idr_updt_ts_dcmtn          timestamp with time zone NOT NULL,
    bfd_created_ts            timestamp with time zone NOT NULL,
    bfd_updated_ts            timestamp with time zone NOT NULL,
    clm_adjstmt_type_cd       character varying(2),
    clm_bene_pd_amt           numeric,
    clm_blg_prvdr_zip5_cd        character varying(5),
--  PAC   clm_sbmt_frmt_cd           character varying(1),
--  Part D   clm_sbmtr_cntrct_num         character varying(5),
--  Part D   clm_sbmtr_cntrct_pbp_num     character varying(3),
--  INSTNL   clm_bnft_enhncmt_1_cd      character varying(2),
--  INSTNL   clm_ngaco_pbpmt_sw         character varying(1),
--  INSTNL   clm_ngaco_cptatn_sw        character varying(1),
--  INSTNL   clm_ngaco_pdschrg_hcbs_sw  character varying(1),
--  INSTNL   clm_ngaco_snf_wvr_sw       character varying(1),
--  INSTNL   clm_ngaco_tlhlth_sw        character varying(1),
--  INSTNL   clm_bnft_enhncmt_2_cd      character varying(2),
--  INSTNL   clm_bnft_enhncmt_3_cd      character varying(2),
--  INSTNL   clm_bnft_enhncmt_4_cd      character varying(2),
--  INSTNL   clm_bnft_enhncmt_5_cd      character varying(2),
    clm_rfrg_prvdr_pin_num     character varying(14),
    prvdr_srvc_sk             bigint,
    prvdr_srvc_mdl_name       character varying(25),
    prvdr_srvc_type_cd        character varying(2),
    prvdr_srvc_txnmy_cmpst_cd character varying(150),
    prvdr_srvc_oscar_num      character varying(13),
    prvdr_srvc_1st_name       character varying(35),
    prvdr_srvc_name           character varying(70),
    prvdr_srvc_lgl_name       character varying(100),
    prvdr_srvc_emplr_id_num   character varying(10),
    prvdr_srvc_last_name      character varying(35),
    clm_blood_chrg_amt        numeric,
--  INSTNL   clm_tot_cntrctl_amt        numeric,
--  PAC   clm_bene_intrst_pd_amt     numeric,
--  PAC   clm_bene_pmt_coinsrnc_amt  numeric,
--  PAC   clm_cob_ptnt_resp_amt      numeric,
--  PAC   clm_prvdr_otaf_amt         numeric,
--  PAC   clm_othr_tp_pd_amt         numeric,
--  PAC   clm_prvdr_rmng_due_amt     numeric,
--  PAC   clm_blood_ncvrd_chrg_amt   numeric,
--  PAC   clm_prvdr_intrst_pd_amt    numeric,
    clm_mdcr_prfnl_prmry_pyr_amt     numeric,
    clm_mdcr_prfnl_prvdr_asgnmt_sw character varying(2)     NOT NULL,
    bfd_claim_updated_ts      timestamp with time zone DEFAULT now(),
    --meta_src_sk               integer,
    clm_clncl_tril_num        character varying(8),
    clm_carr_pmt_dnl_cd            character varying(2)
);

CREATE INDEX ON idr_new.claim_professional_ss(bene_sk);

CREATE INDEX ON idr_new.claim_professional_nch(bene_sk);

CREATE TABLE idr_new.claim_item_professional_ss
(
    clm_uniq_id                    bigint                   NOT NULL,
    bfd_row_id                     integer                  NOT NULL,
    clm_line_num                   integer,
--  ADJ    clm_line_ansthsa_unit_cnt      numeric,
    clm_line_dgns_cd               character varying(7)     NOT NULL,
    clm_line_sbmt_chrg_amt         numeric,
    clm_line_alowd_chrg_amt        numeric,
--  INSTNL   clm_line_ncvrd_chrg_amt        numeric,
    clm_line_prvdr_pmt_amt         numeric,
--  INSTNL,PART D   clm_line_bene_pmt_amt          numeric,
    clm_line_bene_pd_amt           numeric,
    clm_line_cvrd_pd_amt           numeric,
--  INSTNL   clm_line_blood_ddctbl_amt      numeric,
    clm_line_mdcr_ddctbl_amt       numeric,
--  NULL FOR ALL   clm_line_mdcr_coinsrnc_amt     numeric,
    clm_line_hcpcs_cd              character varying(5)     NOT NULL,
    clm_line_from_dt               date,
    clm_line_ndc_cd                character varying(11)    NOT NULL,
    clm_line_ndc_qty               numeric,
    clm_line_ndc_qty_qlfyr_cd      character varying(2)     NOT NULL,
    clm_line_srvc_unit_qty         numeric,
--  INSTNL   clm_line_rev_ctr_cd            character varying(4)     NOT NULL,
    clm_line_rx_num                character varying(30)    NOT NULL,
    clm_line_thru_dt               date,
    clm_pos_cd                     character varying(2)     NOT NULL,
    clm_rndrg_prvdr_prtcptg_cd     character varying(1)     NOT NULL,
    clm_rndrg_prvdr_tax_num        character varying(10)    NOT NULL,
    hcpcs_1_mdfr_cd                character varying(2)     NOT NULL,
    hcpcs_2_mdfr_cd                character varying(2)     NOT NULL,
    hcpcs_3_mdfr_cd                character varying(2)     NOT NULL,
    hcpcs_4_mdfr_cd                character varying(2)     NOT NULL,
    hcpcs_5_mdfr_cd                character varying(2)     NOT NULL,

    clm_val_sqnc_num_prod          integer,
    clm_dgns_prcdr_icd_ind         character varying(1)     NOT NULL,
    clm_dgns_cd                    character varying(7)     NOT NULL,
-- INSTNL    clm_prcdr_cd                   character varying(7)     NOT NULL,
    clm_prod_type_cd               character varying(1)     NOT NULL,
    clm_poa_ind                    character varying(1)     NOT NULL,
-- INSTNL    clm_prcdr_prfrm_dt             date,
--     idr_insrt_ts_prod              timestamp with time zone NOT NULL,
--     idr_updt_ts_prod               timestamp with time zone NOT NULL,
    clm_val_sqnc_num_val           integer,
    clm_val_cd                     character varying(2)     NOT NULL,
    clm_val_amt                    numeric,
--     idr_insrt_ts_val               timestamp with time zone NOT NULL,
--     idr_updt_ts_val                timestamp with time zone NOT NULL,
    clm_rndrg_prvdr_type_cd        character varying(3),
    clm_line_bnft_enhncmt_2_cd     character varying(2),
    clm_line_bnft_enhncmt_3_cd     character varying(2),
    clm_line_bnft_enhncmt_4_cd     character varying(2),
    clm_line_bnft_enhncmt_5_cd     character varying(2),
    clm_line_ngaco_cptatn_sw       character varying(1),
    clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
    clm_line_ngaco_snf_wvr_sw      character varying(1),
    clm_line_ngaco_tlhlth_sw       character varying(1),
    clm_line_aco_care_mgmt_hcbs_sw character varying(1),
    clm_line_ngaco_pbpmt_sw        character varying(1),
--  ADJ  clm_line_pmd_uniq_trkng_num    character varying(14),
    clm_line_pa_uniq_trkng_num     character varying(50),
    clm_line_bnft_enhncmt_1_cd     character varying(2),
--  INSTNL   clm_rlt_cond_cd                character varying(20),
--  INSTNL   clm_rlt_cond_sgntr_sqnc_num    integer,

    prvdr_rndrng_prvdr_npi_num     character varying(10),
    prvdr_rndrng_sk                bigint,
    prvdr_rndrng_mdl_name          character varying(25),
    prvdr_rndrng_type_cd           character varying(2),
    prvdr_rndrng_txnmy_cmpst_cd    character varying(150),
    prvdr_rndrng_oscar_num         character varying(13),
    prvdr_rndrng_1st_name          character varying(35),
    prvdr_rndrng_name              character varying(70),
    prvdr_rndrng_lgl_name          character varying(100),
    prvdr_rndrng_emplr_id_num      character varying(10),
    prvdr_rndrng_last_name         character varying(35),

--  INSTNL, PART D   clm_line_othr_tp_pd_amt        numeric,
--  INSTNL, PART D   clm_line_ncvrd_pd_amt          numeric,
    clm_line_otaf_amt              numeric,
    -- CLAIM LINE PROFESSIONAL columns
--  ADJ   clm_bene_prmry_pyr_pd_amt      numeric,
    clm_fed_type_srvc_cd           character varying(1)     NOT NULL,
--  ADJ   clm_line_carr_clncl_lab_num    character varying(10)    NOT NULL,
--  ADJ   clm_line_carr_hpsa_scrcty_cd   character varying(1)     NOT NULL,
--  ADJ   clm_line_dmerc_scrn_svgs_amt   numeric,
--  ADJ   clm_line_hct_hgb_rslt_num      numeric,
--  ADJ   clm_line_hct_hgb_type_cd       character varying(2)     NOT NULL,
    clm_line_prfnl_dme_price_amt   numeric,
--  ADJ   clm_line_prfnl_mtus_cnt        numeric,
--  ADJ   clm_mtus_ind_cd                character varying(1)     NOT NULL,
--  ADJ   clm_physn_astnt_cd             character varying(1)     NOT NULL,
    clm_pmt_80_100_cd              character varying(1),
--  ADJ   clm_prcng_lclty_cd             character varying(2)     NOT NULL,
--  ADJ   clm_prcsg_ind_cd               character varying(2)     NOT NULL,
--  ADJ   clm_prmry_pyr_cd               character varying(1)     NOT NULL,
    clm_prvdr_spclty_cd            character varying(2)     NOT NULL,
    clm_srvc_ddctbl_sw             character varying(1)     NOT NULL,
    clm_suplr_type_cd              character varying(1)     NOT NULL,
    bfd_created_ts                 timestamp with time zone NOT NULL,
    bfd_updated_ts                 timestamp with time zone NOT NULL,
--  ADJ   clm_line_prfnl_intrst_amt      numeric,
    clm_line_carr_psych_ot_lmt_amt numeric,
--  ADJ   clm_line_carr_clncl_chrg_amt   numeric,
--  ADJ   clm_mdcr_prmry_pyr_alowd_amt   numeric,

--    clm_ocrnc_sgntr_sk             numeric,
--    clm_rlt_ocrnc_sgntr_sk         numeric,
    -- v2_mdcr_clm_line_mcs COLUMNS
    clm_line_rbndlg_crtfctn_num    character varying(10),
    clm_line_hct_lvl_num           numeric,
    clm_line_hgb_lvl_num           numeric,
    PRIMARY KEY (clm_uniq_id, bfd_row_id)
);

CREATE TABLE idr_new.claim_item_professional_nch
(
    clm_uniq_id                    bigint                   NOT NULL,
    bfd_row_id                     integer                  NOT NULL,
    clm_line_num                   integer,
--     MISSING IMPLEMENTATION
    clm_line_ansthsa_unit_cnt      numeric,
    clm_line_dgns_cd               character varying(7)     NOT NULL,
    clm_line_sbmt_chrg_amt         numeric,
    clm_line_alowd_chrg_amt        numeric,
--  INSTNL   clm_line_ncvrd_chrg_amt        numeric,
    clm_line_prvdr_pmt_amt         numeric,
--  INSTNL,PART D   clm_line_bene_pmt_amt          numeric,
    clm_line_bene_pd_amt           numeric,
    clm_line_cvrd_pd_amt           numeric,
--  INSTNL   clm_line_blood_ddctbl_amt      numeric,
    clm_line_mdcr_ddctbl_amt       numeric,
--  NULL FOR ALL   clm_line_mdcr_coinsrnc_amt     numeric,
    clm_line_hcpcs_cd              character varying(5)     NOT NULL,
    clm_line_from_dt               date,
    clm_line_ndc_cd                character varying(11)    NOT NULL,
--  Shared Systems   clm_line_ndc_qty               numeric,
--  Shared Systems   clm_line_ndc_qty_qlfyr_cd      character varying(2)     NOT NULL,
    clm_line_srvc_unit_qty         numeric,
--  INSTNL   clm_line_rev_ctr_cd            character varying(4)     NOT NULL,
    clm_line_rx_num                character varying(30)    NOT NULL,
    clm_line_thru_dt               date,
    clm_pos_cd                     character varying(2)     NOT NULL,
    clm_rndrg_prvdr_prtcptg_cd     character varying(1)     NOT NULL,
    clm_rndrg_prvdr_tax_num        character varying(10)    NOT NULL,
    hcpcs_1_mdfr_cd                character varying(2)     NOT NULL,
    hcpcs_2_mdfr_cd                character varying(2)     NOT NULL,
    hcpcs_3_mdfr_cd                character varying(2)     NOT NULL,
    hcpcs_4_mdfr_cd                character varying(2)     NOT NULL,
    hcpcs_5_mdfr_cd                character varying(2)     NOT NULL,

    clm_val_sqnc_num_prod          integer,
    clm_dgns_prcdr_icd_ind         character varying(1)     NOT NULL,
    clm_dgns_cd                    character varying(7)     NOT NULL,
-- INSTNL    clm_prcdr_cd                   character varying(7)     NOT NULL,
    clm_prod_type_cd               character varying(1)     NOT NULL,
    clm_poa_ind                    character varying(1)     NOT NULL,
-- INSTNL    clm_prcdr_prfrm_dt             date,
--     idr_insrt_ts_prod              timestamp with time zone NOT NULL,
--     idr_updt_ts_prod               timestamp with time zone NOT NULL,
    clm_val_sqnc_num_val           integer,
    clm_val_cd                     character varying(2)     NOT NULL,
    clm_val_amt                    numeric,
--     idr_insrt_ts_val               timestamp with time zone NOT NULL,
--     idr_updt_ts_val                timestamp with time zone NOT NULL,
    clm_rndrg_prvdr_type_cd        character varying(3),
    clm_line_bnft_enhncmt_2_cd     character varying(2),
    clm_line_bnft_enhncmt_3_cd     character varying(2),
    clm_line_bnft_enhncmt_4_cd     character varying(2),
    clm_line_bnft_enhncmt_5_cd     character varying(2),
    clm_line_ngaco_cptatn_sw       character varying(1),
    clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
    clm_line_ngaco_snf_wvr_sw      character varying(1),
    clm_line_ngaco_tlhlth_sw       character varying(1),
    clm_line_aco_care_mgmt_hcbs_sw character varying(1),
    clm_line_ngaco_pbpmt_sw        character varying(1),
    clm_line_pmd_uniq_trkng_num    character varying(14),
--  PAC   clm_line_pa_uniq_trkng_num     character varying(50),
    clm_line_bnft_enhncmt_1_cd     character varying(2),
--  INSTNL   clm_rlt_cond_cd                character varying(20),
--  INSTNL   clm_rlt_cond_sgntr_sqnc_num    integer,

    prvdr_rndrng_prvdr_npi_num     character varying(10),
    prvdr_rndrng_sk                bigint,
    prvdr_rndrng_mdl_name          character varying(25),
    prvdr_rndrng_type_cd           character varying(2),
    prvdr_rndrng_txnmy_cmpst_cd    character varying(150),
    prvdr_rndrng_oscar_num         character varying(13),
    prvdr_rndrng_1st_name          character varying(35),
    prvdr_rndrng_name              character varying(70),
    prvdr_rndrng_lgl_name          character varying(100),
    prvdr_rndrng_emplr_id_num      character varying(10),
    prvdr_rndrng_last_name         character varying(35),

--  INSTNL, PART D   clm_line_othr_tp_pd_amt        numeric,
--  INSTNL, PART D   clm_line_ncvrd_pd_amt          numeric,
--  PAC   clm_line_otaf_amt              numeric,
    -- CLAIM LINE PROFESSIONAL columns
    clm_bene_prmry_pyr_pd_amt      numeric,
    clm_fed_type_srvc_cd           character varying(1)     NOT NULL,
    clm_line_carr_clncl_lab_num    character varying(10)    NOT NULL,
    clm_line_carr_hpsa_scrcty_cd   character varying(1)     NOT NULL,
    clm_line_dmerc_scrn_svgs_amt   numeric,
    clm_line_hct_hgb_rslt_num      numeric,
    clm_line_hct_hgb_type_cd       character varying(2)     NOT NULL,
    clm_line_prfnl_dme_price_amt   numeric,
    clm_line_prfnl_mtus_cnt        numeric,
    clm_mtus_ind_cd                character varying(1)     NOT NULL,
    clm_physn_astnt_cd             character varying(1)     NOT NULL,
    clm_pmt_80_100_cd              character varying(1)     NOT NULL,
    clm_prcng_lclty_cd             character varying(2)     NOT NULL,
    clm_prcsg_ind_cd               character varying(2)     NOT NULL,
    clm_prmry_pyr_cd               character varying(1)     NOT NULL,
    clm_prvdr_spclty_cd            character varying(2)     NOT NULL,
    clm_srvc_ddctbl_sw             character varying(1)     NOT NULL,
    clm_suplr_type_cd              character varying(1)     NOT NULL,
    bfd_created_ts                 timestamp with time zone NOT NULL,
    bfd_updated_ts                 timestamp with time zone NOT NULL,
    clm_line_prfnl_intrst_amt      numeric,
    clm_line_carr_psych_ot_lmt_amt numeric,
    clm_line_carr_clncl_chrg_amt   numeric,
    clm_mdcr_prmry_pyr_alowd_amt   numeric,

--    clm_ocrnc_sgntr_sk             numeric,
--    clm_rlt_ocrnc_sgntr_sk         numeric,
    -- v2_mdcr_clm_line_mcs COLUMNS
-- SS    clm_line_rbndlg_crtfctn_num    character varying(10),
-- SS    clm_line_hct_lvl_num           numeric,
-- SS    clm_line_hgb_lvl_num           numeric,
    PRIMARY KEY (clm_uniq_id, bfd_row_id)
);

CREATE TABLE idr_new.claim_institutional_ss
(
    clm_uniq_id                bigint                   NOT NULL PRIMARY KEY,
    --CLAIM DATE SGNTR
    clm_cms_proc_dt            date,
    clm_actv_care_from_dt      date,
    clm_dschrg_dt              date,
    clm_submsn_dt              date,
--     clm_ncvrd_from_dt          date,
--   NCH  clm_ncvrd_thru_dt          date,
--   NCH  clm_actv_care_thru_dt      date,
--   NCH  clm_mdcr_exhstd_dt         date,
--   NCH  clm_nch_wkly_proc_dt       date,
    clm_qlfy_stay_from_dt      date,
--  NCH   clm_qlfy_stay_thru_dt      date,
    --CLAIM DATE SGNTR
    clm_type_cd                integer                  NOT NULL,
    bene_sk                    bigint                   NOT NULL,
    clm_cntl_num               character varying(40)    NOT NULL,
    clm_orig_cntl_num          character varying(40)    NOT NULL,
    clm_from_dt                date                     NOT NULL,
    clm_thru_dt                date,
    clm_efctv_dt               date,
    clm_obslt_dt               date,
    clm_bill_clsfctn_cd        character varying(1)     NOT NULL,
    clm_bill_fac_type_cd       character varying(1)     NOT NULL,
    clm_bill_freq_cd           character varying(1)     NOT NULL,
    clm_finl_actn_ind          character varying(1)     NOT NULL,
    clm_src_id                 character varying(5)     NOT NULL,
--     clm_query_cd                 character varying(1)     NOT NULL,
    clm_mdcr_coinsrnc_amt      numeric,
    clm_blood_lblty_amt        numeric,
    clm_ncvrd_chrg_amt         numeric,
    clm_mdcr_ddctbl_amt        numeric,
    clm_prvdr_pmt_amt          numeric,
    clm_alowd_chrg_amt         numeric,
    clm_bene_pmt_amt           numeric,
    clm_cntrctr_num            character varying(5)     NOT NULL,
    clm_pmt_amt                numeric,
    clm_pd_dt                  date,
    clm_ltst_clm_ind           character varying(1)     NOT NULL,
    prvdr_atndg_prvdr_npi_num  character varying(10),
    prvdr_atndg_last_name      character varying(60),
    prvdr_atndg_sk             bigint,
    prvdr_atndg_mdl_name       character varying(25),
    prvdr_atndg_type_cd        character varying(2),
    prvdr_atndg_txnmy_cmpst_cd character varying(150),
    prvdr_atndg_oscar_num      character varying(13),
    prvdr_atndg_1st_name       character varying(35),
    prvdr_atndg_name           character varying(70),
    prvdr_atndg_lgl_name       character varying(100),
    prvdr_atndg_emplr_id_num   character varying(10),
    prvdr_oprtg_prvdr_npi_num  character varying(10),
    prvdr_oprtg_sk             bigint,
    prvdr_oprtg_mdl_name       character varying(25),
    prvdr_oprtg_type_cd        character varying(2),
    prvdr_oprtg_txnmy_cmpst_cd character varying(150),
    prvdr_oprtg_oscar_num      character varying(13),
    prvdr_oprtg_1st_name       character varying(35),
    prvdr_oprtg_name           character varying(70),
    prvdr_oprtg_lgl_name       character varying(100),
    prvdr_oprtg_emplr_id_num   character varying(10),
    prvdr_oprtg_last_name      character varying(35),

    prvdr_othr_prvdr_npi_num   character varying(10),
    prvdr_othr_sk              bigint,
    prvdr_othr_mdl_name        character varying(25),
    prvdr_othr_type_cd         character varying(2),
    prvdr_othr_txnmy_cmpst_cd  character varying(150),
    prvdr_othr_oscar_num       character varying(13),
    prvdr_othr_1st_name        character varying(35),
    prvdr_othr_name            character varying(70),
    prvdr_othr_lgl_name        character varying(100),
    prvdr_othr_emplr_id_num    character varying(10),
    prvdr_othr_last_name       character varying(35),

    prvdr_rndrng_prvdr_npi_num  character varying(10),
    prvdr_rndrng_sk             bigint,
    prvdr_rndrng_mdl_name       character varying(25),
    prvdr_rndrng_type_cd        character varying(2),
    prvdr_rndrng_txnmy_cmpst_cd character varying(150),
    prvdr_rndrng_oscar_num      character varying(13),
    prvdr_rndrng_1st_name       character varying(35),
    prvdr_rndrng_name           character varying(70),
    prvdr_rndrng_lgl_name       character varying(100),
    prvdr_rndrng_emplr_id_num   character varying(10),
    prvdr_rndrng_last_name      character varying(35),

    prvdr_blg_prvdr_npi_num    character varying(10),
    prvdr_blg_sk               bigint,
    prvdr_blg_mdl_name         character varying(25),
    prvdr_blg_type_cd          character varying(2),
    prvdr_blg_txnmy_cmpst_cd   character varying(150),
    prvdr_blg_oscar_num        character varying(13),
    prvdr_blg_1st_name         character varying(35),
    prvdr_blg_name             character varying(70),
    prvdr_blg_lgl_name         character varying(100),
    prvdr_blg_emplr_id_num     character varying(10),
    prvdr_blg_last_name        character varying(35),

    prvdr_rfrg_prvdr_npi_num   character varying(10),
    prvdr_rfrg_sk              bigint,
    prvdr_rfrg_mdl_name        character varying(25),
    prvdr_rfrg_type_cd         character varying(2),
    prvdr_rfrg_txnmy_cmpst_cd  character varying(150),
    prvdr_rfrg_oscar_num       character varying(13),
    prvdr_rfrg_1st_name        character varying(35),
    prvdr_rfrg_name            character varying(70),
    prvdr_rfrg_lgl_name        character varying(100),
    prvdr_rfrg_emplr_id_num    character varying(10),
    prvdr_rfrg_last_name       character varying(35),
--     clm_disp_cd                  character varying(2)     NOT NULL,
    clm_ric_cd                 character varying(1)     NOT NULL,
    clm_sbmt_chrg_amt          numeric,
    clm_blood_pt_frnsh_qty     integer,
    clm_nch_prmry_pyr_cd       character varying(1)     NOT NULL,
--     clm_blg_prvdr_oscar_num      character varying(20)    NOT NULL,
    clm_idr_ld_dt              date,
-- NCH    clm_nrln_ric_cd            character varying(1)     NOT NULL,
--     prvdr_srvc_prvdr_npi_num   character varying(20)    NOT NULL,
--     prvdr_prscrbng_prvdr_npi_num character varying(10)    NOT NULL,
    bfd_created_ts             timestamp with time zone NOT NULL,
    bfd_updated_ts             timestamp with time zone NOT NULL,
    clm_adjstmt_type_cd        character varying(2),
    clm_bene_pd_amt            numeric,
    clm_blg_prvdr_zip5_cd        character varying(5),
    clm_sbmt_frmt_cd           character varying(1),
--     clm_sbmtr_cntrct_num         character varying(5),
--     clm_sbmtr_cntrct_pbp_num     character varying(3),
    clm_bnft_enhncmt_1_cd      character varying(2),
    clm_ngaco_pbpmt_sw         character varying(1),
    clm_ngaco_cptatn_sw        character varying(1),
    clm_ngaco_pdschrg_hcbs_sw  character varying(1),
    clm_ngaco_snf_wvr_sw       character varying(1),
    clm_ngaco_tlhlth_sw        character varying(1),
    clm_bnft_enhncmt_2_cd      character varying(2),
    clm_bnft_enhncmt_3_cd      character varying(2),
    clm_bnft_enhncmt_4_cd      character varying(2),
    clm_bnft_enhncmt_5_cd      character varying(2),
--     clm_rfrg_prvdr_pin_num     character varying(14),
    prvdr_srvc_prvdr_npi_num   character varying(10),
    prvdr_srvc_sk              bigint,
    prvdr_srvc_mdl_name        character varying(25),
    prvdr_srvc_type_cd         character varying(2),
    prvdr_srvc_txnmy_cmpst_cd  character varying(150),
    prvdr_srvc_oscar_num       character varying(13),
    prvdr_srvc_1st_name        character varying(35),
    prvdr_srvc_name            character varying(70),
    prvdr_srvc_lgl_name        character varying(100),
    prvdr_srvc_emplr_id_num    character varying(10),
    prvdr_srvc_last_name       character varying(35),
    clm_blood_chrg_amt         numeric,
    clm_tot_cntrctl_amt        numeric,
    clm_bene_intrst_pd_amt     numeric,
    clm_bene_pmt_coinsrnc_amt  numeric,
    clm_cob_ptnt_resp_amt      numeric,
    clm_prvdr_otaf_amt         numeric,
    clm_othr_tp_pd_amt         numeric,
    clm_prvdr_rmng_due_amt     numeric,
    clm_blood_ncvrd_chrg_amt   numeric,
    clm_prvdr_intrst_pd_amt    numeric,
    bfd_claim_updated_ts       timestamp with time zone DEFAULT now(),
--  CLM_LCTN_HSTRY
    clm_audt_trl_stus_cd       character varying(2),
--  FISS
    clm_crnt_stus_cd           character varying(1)     NOT NULL,
    clm_pps_ind                character varying(1)     NOT NULL,
    meta_src_sk                integer,
--     CLM_INSTL Columns
    clm_admsn_type_cd              varchar(2)               not null,
    bene_ptnt_stus_cd              varchar(2)               not null,
    dgns_drg_cd                    integer,
    clm_mdcr_instnl_mco_pd_sw      varchar(1)               not null,
    clm_admsn_src_cd               varchar(2)               not null,
    clm_fi_actn_cd                 varchar(1)               not null,
    clm_mdcr_ip_lrd_use_cnt        integer,
--   NCH  clm_hha_rfrl_cd                varchar(1)               not null,
--   NCH  clm_hha_lup_ind_cd             varchar(1)               not null,
    clm_hipps_uncompd_care_amt     numeric,
    clm_instnl_mdcr_coins_day_cnt  integer,
    clm_instnl_ncvrd_day_cnt       numeric,
    clm_instnl_per_diem_amt        numeric,
    clm_mdcr_hha_tot_visit_cnt     numeric,
    clm_mdcr_npmt_rsn_cd           varchar(2)               not null,
    clm_mdcr_ip_pps_drg_wt_num     numeric,
    clm_mdcr_ip_pps_dsprprtnt_amt  numeric,
    clm_mdcr_ip_pps_excptn_amt     numeric,
    clm_mdcr_ip_pps_cptl_fsp_amt   numeric,
    clm_mdcr_ip_pps_cptl_ime_amt   numeric,
    clm_mdcr_ip_pps_outlier_amt    numeric,
    clm_mdcr_ip_pps_cptl_hrmls_amt numeric,
    clm_mdcr_instnl_bene_pd_amt    numeric,
    clm_mdcr_hospc_prd_cnt         integer,
--  NCH   clm_pps_ind_cd                 varchar(1)               not null,
    clm_mdcr_ip_pps_cptl_tot_amt   numeric,
    clm_instnl_cvrd_day_cnt        numeric,
    clm_mdcr_instnl_prmry_pyr_amt  numeric,
    clm_instnl_prfnl_amt           numeric,
    clm_mdcr_ip_bene_ddctbl_amt    numeric,
    clm_instnl_drg_outlier_amt     numeric,
--  NCH   dgns_drg_outlier_cd            varchar(1),
    clm_mdcr_ip_scnd_yr_rate_amt   numeric,
    clm_instnl_low_vol_pmt_amt     numeric,
    clm_hipps_readmsn_rdctn_amt    numeric,
    clm_hipps_model_bndld_pmt_amt  numeric,
    clm_hipps_vbp_amt              numeric,
    clm_site_ntrl_ip_pps_pymt_amt  numeric,
    clm_finl_stdzd_pymt_amt        numeric,
    clm_pps_md_wvr_stdzd_val_amt   numeric,
    clm_hac_rdctn_pymt_amt         numeric,
    clm_mdcr_ip_1st_yr_rate_amt    numeric,
    clm_site_ntrl_cst_bsd_pymt_amt numeric,
    clm_ss_outlier_std_pymt_amt    numeric
--  NCH   clm_op_srvc_type_cd            varchar(1)
);

CREATE TABLE idr_new.claim_institutional_nch
(
    clm_uniq_id                bigint                   NOT NULL PRIMARY KEY,
    --CLAIM DATE SGNTR
    clm_cms_proc_dt            date,
    clm_actv_care_from_dt      date,
    clm_dschrg_dt              date,
    clm_submsn_dt              date,
    clm_ncvrd_from_dt          date,
    clm_ncvrd_thru_dt          date,
    clm_actv_care_thru_dt      date,
    clm_mdcr_exhstd_dt         date,
    clm_nch_wkly_proc_dt       date,
    clm_qlfy_stay_from_dt      date,
    clm_qlfy_stay_thru_dt      date,
    --CLAIM DATE SGNTR
    clm_type_cd                integer,
    bene_sk                    bigint                   NOT NULL,
    clm_cntl_num               character varying(40)    NOT NULL,
    clm_orig_cntl_num          character varying(40)    NOT NULL,
    clm_from_dt                date                     NOT NULL,
    clm_thru_dt                date,
    clm_efctv_dt               date,
    clm_obslt_dt               date,
    clm_bill_clsfctn_cd        character varying(1)     NOT NULL,
    clm_bill_fac_type_cd       character varying(1)     NOT NULL,
    clm_bill_freq_cd           character varying(1)     NOT NULL,
    clm_finl_actn_ind          character varying(1)     NOT NULL,
--     clm_src_id                 character varying(5)     NOT NULL,
--     clm_query_cd                 character varying(1)     NOT NULL,
--     clm_mdcr_coinsrnc_amt      numeric,
--     clm_blood_lblty_amt        numeric,
--     clm_ncvrd_chrg_amt         numeric,
    clm_mdcr_ddctbl_amt        numeric,
    clm_prvdr_pmt_amt          numeric,
    clm_alowd_chrg_amt         numeric,
--     clm_bene_pmt_amt           numeric,
    clm_cntrctr_num            character varying(5)     NOT NULL,
    clm_pmt_amt                numeric,
    clm_pd_dt                  date,
    clm_ltst_clm_ind           character varying(1)     NOT NULL,
    prvdr_atndg_prvdr_npi_num  character varying(10),
    prvdr_atndg_last_name      character varying(60),
    prvdr_atndg_sk             bigint,
    prvdr_atndg_mdl_name       character varying(25),
    prvdr_atndg_type_cd        character varying(2),
    prvdr_atndg_txnmy_cmpst_cd character varying(150),
    prvdr_atndg_oscar_num      character varying(13),
    prvdr_atndg_1st_name       character varying(35),
    prvdr_atndg_name           character varying(70),
    prvdr_atndg_lgl_name       character varying(100),
    prvdr_atndg_emplr_id_num   character varying(10),
    prvdr_oprtg_prvdr_npi_num  character varying(10),
    prvdr_oprtg_sk             bigint,
    prvdr_oprtg_mdl_name       character varying(25),
    prvdr_oprtg_type_cd        character varying(2),
    prvdr_oprtg_txnmy_cmpst_cd character varying(150),
    prvdr_oprtg_oscar_num      character varying(13),
    prvdr_oprtg_1st_name       character varying(35),
    prvdr_oprtg_name           character varying(70),
    prvdr_oprtg_lgl_name       character varying(100),
    prvdr_oprtg_emplr_id_num   character varying(10),
    prvdr_oprtg_last_name      character varying(35),

    prvdr_othr_prvdr_npi_num   character varying(10),
    prvdr_othr_sk              bigint,
    prvdr_othr_mdl_name        character varying(25),
    prvdr_othr_type_cd         character varying(2),
    prvdr_othr_txnmy_cmpst_cd  character varying(150),
    prvdr_othr_oscar_num       character varying(13),
    prvdr_othr_1st_name        character varying(35),
    prvdr_othr_name            character varying(70),
    prvdr_othr_lgl_name        character varying(100),
    prvdr_othr_emplr_id_num    character varying(10),
    prvdr_othr_last_name       character varying(35),

    prvdr_rndrng_prvdr_npi_num  character varying(10),
    prvdr_rndrng_sk             bigint,
    prvdr_rndrng_mdl_name       character varying(25),
    prvdr_rndrng_type_cd        character varying(2),
    prvdr_rndrng_txnmy_cmpst_cd character varying(150),
    prvdr_rndrng_oscar_num      character varying(13),
    prvdr_rndrng_1st_name       character varying(35),
    prvdr_rndrng_name           character varying(70),
    prvdr_rndrng_lgl_name       character varying(100),
    prvdr_rndrng_emplr_id_num   character varying(10),
    prvdr_rndrng_last_name      character varying(35),

    prvdr_blg_prvdr_npi_num    character varying(10),
    prvdr_blg_sk               bigint,
    prvdr_blg_mdl_name         character varying(25),
    prvdr_blg_type_cd          character varying(2),
    prvdr_blg_txnmy_cmpst_cd   character varying(150),
    prvdr_blg_oscar_num        character varying(13),
    prvdr_blg_1st_name         character varying(35),
    prvdr_blg_name             character varying(70),
    prvdr_blg_lgl_name         character varying(100),
    prvdr_blg_emplr_id_num     character varying(10),
    prvdr_blg_last_name        character varying(35),

    prvdr_rfrg_prvdr_npi_num   character varying(10),
    prvdr_rfrg_sk              bigint,
    prvdr_rfrg_mdl_name        character varying(25),
    prvdr_rfrg_type_cd         character varying(2),
    prvdr_rfrg_txnmy_cmpst_cd  character varying(150),
    prvdr_rfrg_oscar_num       character varying(13),
    prvdr_rfrg_1st_name        character varying(35),
    prvdr_rfrg_name            character varying(70),
    prvdr_rfrg_lgl_name        character varying(100),
    prvdr_rfrg_emplr_id_num    character varying(10),
    prvdr_rfrg_last_name       character varying(35),

    clm_disp_cd                character varying(2)     NOT NULL,
-- PAC    clm_ric_cd                 character varying(1)     NOT NULL,
    clm_sbmt_chrg_amt          numeric,
    clm_blood_pt_frnsh_qty     integer,
--     clm_nch_prmry_pyr_cd       character varying(1)     NOT NULL,
--     clm_blg_prvdr_oscar_num      character varying(20)    NOT NULL,
    clm_idr_ld_dt              date,
    clm_nrln_ric_cd            character varying(1)     NOT NULL,
--     prvdr_srvc_prvdr_npi_num   character varying(20)    NOT NULL,
--     prvdr_prscrbng_prvdr_npi_num character varying(10)    NOT NULL,
    bfd_created_ts             timestamp with time zone NOT NULL,
    bfd_updated_ts             timestamp with time zone NOT NULL,
    clm_adjstmt_type_cd        character varying(2),
    clm_bene_pd_amt            numeric,
    clm_blg_prvdr_zip5_cd        character varying(5),
--     clm_sbmt_frmt_cd           character varying(1),
--     clm_sbmtr_cntrct_num         character varying(5),
--     clm_sbmtr_cntrct_pbp_num     character varying(3),
    clm_bnft_enhncmt_1_cd      character varying(2),
    clm_ngaco_pbpmt_sw         character varying(1),
    clm_ngaco_cptatn_sw        character varying(1),
    clm_ngaco_pdschrg_hcbs_sw  character varying(1),
    clm_ngaco_snf_wvr_sw       character varying(1),
    clm_ngaco_tlhlth_sw        character varying(1),
    clm_bnft_enhncmt_2_cd      character varying(2),
    clm_bnft_enhncmt_3_cd      character varying(2),
    clm_bnft_enhncmt_4_cd      character varying(2),
    clm_bnft_enhncmt_5_cd      character varying(2),
--     clm_rfrg_prvdr_pin_num     character varying(10),
    prvdr_srvc_prvdr_npi_num   character varying(10),
    prvdr_srvc_sk              bigint,
    prvdr_srvc_mdl_name        character varying(25),
    prvdr_srvc_type_cd         character varying(2),
    prvdr_srvc_txnmy_cmpst_cd  character varying(150),
    prvdr_srvc_oscar_num       character varying(13),
    prvdr_srvc_1st_name        character varying(35),
    prvdr_srvc_name            character varying(70),
    prvdr_srvc_lgl_name        character varying(100),
    prvdr_srvc_emplr_id_num    character varying(10),
    prvdr_srvc_last_name       character varying(35),
--     clm_blood_chrg_amt         numeric,
--     clm_tot_cntrctl_amt        numeric,
--     clm_bene_intrst_pd_amt     numeric,
--     clm_bene_pmt_coinsrnc_amt  numeric,
--     clm_cob_ptnt_resp_amt      numeric,
--     clm_prvdr_otaf_amt         numeric,
--     clm_othr_tp_pd_amt         numeric,
--     clm_prvdr_rmng_due_amt     numeric,
--     clm_blood_ncvrd_chrg_amt   numeric,
--     clm_prvdr_intrst_pd_amt    numeric,
    bfd_claim_updated_ts       timestamp with time zone DEFAULT now(),
--    meta_src_sk                integer,
    --     CLM_INSTL Columns
    clm_admsn_type_cd              varchar(2)               not null,
    bene_ptnt_stus_cd              varchar(2)               not null,
    dgns_drg_cd                    integer,
    clm_mdcr_instnl_mco_pd_sw      varchar(1)               not null,
    clm_admsn_src_cd               varchar(2)               not null,
    clm_fi_actn_cd                 varchar(1)               not null,
    clm_mdcr_ip_lrd_use_cnt        integer,
    clm_hha_rfrl_cd                varchar(1)               not null,
    clm_hha_lup_ind_cd             varchar(1)               not null,
    clm_hipps_uncompd_care_amt     numeric,
    clm_instnl_mdcr_coins_day_cnt  integer,
    clm_instnl_ncvrd_day_cnt       numeric ,
    clm_instnl_per_diem_amt        numeric,
    clm_mdcr_hha_tot_visit_cnt     numeric,
    clm_mdcr_npmt_rsn_cd           varchar(2)               not null,
    clm_mdcr_ip_pps_drg_wt_num     numeric,
    clm_mdcr_ip_pps_dsprprtnt_amt  numeric,
    clm_mdcr_ip_pps_excptn_amt     numeric,
    clm_mdcr_ip_pps_cptl_fsp_amt   numeric,
    clm_mdcr_ip_pps_cptl_ime_amt   numeric,
    clm_mdcr_ip_pps_outlier_amt    numeric,
    clm_mdcr_ip_pps_cptl_hrmls_amt numeric,
    clm_mdcr_instnl_bene_pd_amt    numeric,
    clm_mdcr_hospc_prd_cnt         integer,
    clm_pps_ind_cd                 varchar(1)               not null,
    clm_mdcr_ip_pps_cptl_tot_amt   numeric,
    clm_instnl_cvrd_day_cnt        numeric,
    clm_mdcr_instnl_prmry_pyr_amt  numeric,
    clm_instnl_prfnl_amt           numeric,
    clm_mdcr_ip_bene_ddctbl_amt    numeric,
    clm_instnl_drg_outlier_amt     numeric,
    dgns_drg_outlier_cd            varchar(1),
    clm_mdcr_ip_scnd_yr_rate_amt   numeric,
    clm_instnl_low_vol_pmt_amt     numeric,
    clm_hipps_readmsn_rdctn_amt    numeric,
    clm_hipps_model_bndld_pmt_amt  numeric,
    clm_hipps_vbp_amt              numeric,
    clm_site_ntrl_ip_pps_pymt_amt  numeric,
    clm_finl_stdzd_pymt_amt        numeric,
    clm_pps_md_wvr_stdzd_val_amt   numeric,
    clm_hac_rdctn_pymt_amt         numeric,
    clm_mdcr_ip_1st_yr_rate_amt    numeric,
    clm_site_ntrl_cst_bsd_pymt_amt numeric,
    clm_ss_outlier_std_pymt_amt    numeric,
    clm_op_srvc_type_cd            varchar(1)
);


CREATE INDEX ON idr_new.claim_institutional_ss(bene_sk);

CREATE INDEX ON idr_new.claim_institutional_nch(bene_sk);


CREATE TABLE idr_new.claim_item_institutional_ss
(
    clm_uniq_id                 bigint                   NOT NULL,
    bfd_row_id                  integer                  NOT NULL,
    clm_line_num                integer,
--     MISSING IMPLEMENTATION
    clm_line_ansthsa_unit_cnt   numeric,
--  PRFNL   clm_line_dgns_cd               character varying(7)     NOT NULL,
    clm_line_sbmt_chrg_amt      numeric,
    clm_line_alowd_chrg_amt     numeric,
    clm_line_ncvrd_chrg_amt     numeric,
    clm_line_prvdr_pmt_amt      numeric,
    clm_line_bene_pmt_amt       numeric,
    clm_line_bene_pd_amt        numeric,
    clm_line_cvrd_pd_amt        numeric,
    clm_line_blood_ddctbl_amt   numeric,
    clm_line_mdcr_ddctbl_amt    numeric,
--  NULL FOR ALL   clm_line_mdcr_coinsrnc_amt     numeric,
    clm_line_hcpcs_cd           character varying(5)     NOT NULL,
    clm_line_from_dt            date,
    clm_line_ndc_cd             character varying(11)    NOT NULL,
    clm_line_ndc_qty            numeric,
    clm_line_ndc_qty_qlfyr_cd   character varying(2)     NOT NULL,
    clm_line_srvc_unit_qty      numeric,
    clm_line_rev_ctr_cd         character varying(4)     NOT NULL,
--  PFRNL, DRUG   clm_line_rx_num                character varying(30)    NOT NULL,
    clm_line_thru_dt            date,
--  PRFNL   clm_pos_cd                     character varying(2)     NOT NULL,
--  PRFNL   clm_rndrg_prvdr_prtcptg_cd     character varying(1)     NOT NULL,
--  PRFNL   clm_rndrg_prvdr_tax_num        character varying(10)    NOT NULL,
    hcpcs_1_mdfr_cd             character varying(2)     NOT NULL,
    hcpcs_2_mdfr_cd             character varying(2)     NOT NULL,
    hcpcs_3_mdfr_cd             character varying(2)     NOT NULL,
    hcpcs_4_mdfr_cd             character varying(2)     NOT NULL,
    hcpcs_5_mdfr_cd             character varying(2)     NOT NULL,

    clm_val_sqnc_num_prod       integer,
    clm_dgns_prcdr_icd_ind      character varying(1)     NOT NULL,
    clm_dgns_cd                 character varying(7)     NOT NULL,
    clm_prcdr_cd                character varying(7)     NOT NULL,
    clm_prod_type_cd            character varying(1)     NOT NULL,
    clm_poa_ind                 character varying(1)     NOT NULL,
    clm_prcdr_prfrm_dt          date,
--     idr_insrt_ts_prod              timestamp with time zone NOT NULL,
--     idr_updt_ts_prod               timestamp with time zone NOT NULL,
    clm_val_sqnc_num_val        integer,
    clm_val_cd                  character varying(2)     NOT NULL,
    clm_val_amt                 numeric,
--     idr_insrt_ts_val               timestamp with time zone NOT NULL,
--     idr_updt_ts_val                timestamp with time zone NOT NULL,
    bfd_created_ts              timestamp with time zone NOT NULL,
    bfd_updated_ts              timestamp with time zone NOT NULL,
--  PRFNL   clm_rndrg_prvdr_type_cd        character varying(3),
--  PRFNL   clm_line_bnft_enhncmt_2_cd     character varying(2),
--  PRFNL   clm_line_bnft_enhncmt_3_cd     character varying(2),
--  PRFNL   clm_line_bnft_enhncmt_4_cd     character varying(2),
--  PRFNL   clm_line_bnft_enhncmt_5_cd     character varying(2),
--  PRFNL   clm_line_ngaco_cptatn_sw       character varying(1),
--  PRFNL   clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
--  PRFNL   clm_line_ngaco_snf_wvr_sw      character varying(1),
--  PRFNL   clm_line_ngaco_tlhlth_sw       character varying(1),
--  PRFNL   clm_line_aco_care_mgmt_hcbs_sw character varying(1),
--  PRFNL   clm_line_ngaco_pbpmt_sw        character varying(1),
--  ADJ  clm_line_pmd_uniq_trkng_num    character varying(14),
    clm_line_pa_uniq_trkng_num  character varying(50),
--  PRFNL   clm_line_bnft_enhncmt_1_cd     character varying(2),
    clm_rlt_cond_cd             character varying(20),
    clm_rlt_cond_sgntr_sqnc_num integer,

--     prvdr_rndrng_prvdr_npi_num   character varying(10),
--     prvdr_rndrng_sk              bigint,
--     prvdr_rndrng_mdl_name        character varying(25),
--     prvdr_rndrng_type_cd         character varying(2),
--     prvdr_rndrng_txnmy_cmpst_cd  character varying(150),
--     prvdr_rndrng_oscar_num       character varying(13),
--     prvdr_rndrng_1st_name        character varying(35),
--     prvdr_rndrng_name            character varying(70),
--     prvdr_rndrng_lgl_name        character varying(100),
--     prvdr_rndrng_emplr_id_num    character varying(10),
--     prvdr_rndrng_last_name       character varying(35),

    clm_line_othr_tp_pd_amt     numeric,
    clm_line_ncvrd_pd_amt       numeric,
    clm_line_otaf_amt           numeric,
    -- CLAIM LINE INSTITUTIONAL columns
    clm_rev_apc_hipps_cd        character varying(5)     NOT NULL,
    clm_otaf_one_ind_cd         character varying(1)     NOT NULL,
    clm_rev_dscnt_ind_cd        character varying(1)     NOT NULL,
    clm_rev_packg_ind_cd        character varying(1)     NOT NULL,
    clm_rev_cntr_stus_cd        character varying(2)     NOT NULL,
    clm_rev_pmt_mthd_cd         character varying(2)     NOT NULL,
    clm_ddctbl_coinsrnc_cd      character varying(1)     NOT NULL,
    clm_line_instnl_rate_amt    numeric,
    clm_line_instnl_adjstd_amt  numeric,
    clm_line_instnl_rdcd_amt    numeric,
    clm_line_instnl_msp1_pd_amt numeric,
    clm_line_instnl_msp2_pd_amt numeric,
    clm_line_instnl_rev_ctr_dt  date,
    clm_rev_cntr_tdapa_amt      numeric,
    clm_line_non_ehr_rdctn_amt  numeric,
    clm_line_add_on_pymt_amt    numeric,
    clm_ocrnc_sgntr_sk          numeric,
    clm_rlt_ocrnc_sgntr_sk      numeric,
    -- CLAIM LINE FISS
    clm_line_msp_coinsrnc_amt   numeric,
    -- CLM_LINE_FISS_BNFT_SVG
    clm_bnft_svg_ansi_grp_cd    character varying(2),
    clm_bnft_svg_ansi_rsn_cd    character varying(3),
    --  CLM_ANSI_SGNTR
--  NCH   clm_1_rev_cntr_ansi_grp_cd character varying(2)     NOT NULL,
--  NOT USED   clm_2_rev_cntr_ansi_grp_cd character varying(2)     NOT NULL,
--  NOT USED   clm_3_rev_cntr_ansi_grp_cd character varying(2)     NOT NULL,
--  NOT USED   clm_4_rev_cntr_ansi_grp_cd character varying(2)     NOT NULL,
--  NCH   clm_1_rev_cntr_ansi_rsn_cd character varying(3)     NOT NULL,
--  NOT USED   clm_2_rev_cntr_ansi_rsn_cd character varying(3)     NOT NULL,
--  NOT USED   clm_3_rev_cntr_ansi_rsn_cd character varying(3)     NOT NULL,
--  NOT USED   clm_4_rev_cntr_ansi_rsn_cd character varying(3)     NOT NULL,
    PRIMARY KEY (clm_uniq_id, bfd_row_id)
);

CREATE TABLE idr_new.claim_item_institutional_nch
(
    clm_uniq_id                 bigint                   NOT NULL,
    bfd_row_id                  integer                  NOT NULL,
    clm_line_num                integer,
--  PAC   clm_line_ansthsa_unit_cnt      numeric,
--  PRFNL   clm_line_dgns_cd               character varying(7)     NOT NULL,
    clm_line_sbmt_chrg_amt      numeric,
--  PAC   clm_line_alowd_chrg_amt        numeric,
    clm_line_ncvrd_chrg_amt     numeric,
    clm_line_prvdr_pmt_amt      numeric,
    clm_line_bene_pmt_amt       numeric,
    clm_line_bene_pd_amt        numeric,
    clm_line_cvrd_pd_amt        numeric,
    clm_line_blood_ddctbl_amt   numeric,
    clm_line_mdcr_ddctbl_amt    numeric,
--  NULL FOR ALL   clm_line_mdcr_coinsrnc_amt     numeric,
    clm_line_hcpcs_cd           character varying(5)     NOT NULL,
    clm_line_from_dt            date,
    clm_line_ndc_cd             character varying(11)    NOT NULL,
    clm_line_ndc_qty            numeric,
    clm_line_ndc_qty_qlfyr_cd   character varying(2)     NOT NULL,
    clm_line_srvc_unit_qty      numeric,
    clm_line_rev_ctr_cd         character varying(4)     NOT NULL,
--  PFRNL, DRUG   clm_line_rx_num                character varying(30)    NOT NULL,
    clm_line_thru_dt            date,
--  PRFNL   clm_pos_cd                     character varying(2)     NOT NULL,
--  PRFNL   clm_rndrg_prvdr_prtcptg_cd     character varying(1)     NOT NULL,
--  PRFNL   clm_rndrg_prvdr_tax_num        character varying(10)    NOT NULL,
    hcpcs_1_mdfr_cd             character varying(2)     NOT NULL,
    hcpcs_2_mdfr_cd             character varying(2)     NOT NULL,
    hcpcs_3_mdfr_cd             character varying(2)     NOT NULL,
    hcpcs_4_mdfr_cd             character varying(2)     NOT NULL,
    hcpcs_5_mdfr_cd             character varying(2)     NOT NULL,

    clm_val_sqnc_num_prod       integer,
    clm_dgns_prcdr_icd_ind      character varying(1)     NOT NULL,
    clm_dgns_cd                 character varying(7)     NOT NULL,
    clm_prcdr_cd                character varying(7)     NOT NULL,
    clm_prod_type_cd            character varying(1)     NOT NULL,
    clm_poa_ind                 character varying(1)     NOT NULL,
    clm_prcdr_prfrm_dt          date,
--     idr_insrt_ts_prod              timestamp with time zone NOT NULL,
--     idr_updt_ts_prod               timestamp with time zone NOT NULL,
    clm_val_sqnc_num_val        integer,
    clm_val_cd                  character varying(2)     NOT NULL,
    clm_val_amt                 numeric,
--     idr_insrt_ts_val               timestamp with time zone NOT NULL,
--     idr_updt_ts_val                timestamp with time zone NOT NULL,
    bfd_created_ts              timestamp with time zone NOT NULL,
    bfd_updated_ts              timestamp with time zone NOT NULL,
--  PRFNL   clm_rndrg_prvdr_type_cd        character varying(3),
--  PRFNL   clm_line_bnft_enhncmt_2_cd     character varying(2),
--  PRFNL   clm_line_bnft_enhncmt_3_cd     character varying(2),
--  PRFNL   clm_line_bnft_enhncmt_4_cd     character varying(2),
--  PRFNL   clm_line_bnft_enhncmt_5_cd     character varying(2),
--  PRFNL   clm_line_ngaco_cptatn_sw       character varying(1),
--  PRFNL   clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
--  PRFNL   clm_line_ngaco_snf_wvr_sw      character varying(1),
--  PRFNL   clm_line_ngaco_tlhlth_sw       character varying(1),
--  PRFNL   clm_line_aco_care_mgmt_hcbs_sw character varying(1),
--  PRFNL   clm_line_ngaco_pbpmt_sw        character varying(1),
    clm_line_pmd_uniq_trkng_num character varying(14),
--  PAC   clm_line_pa_uniq_trkng_num     character varying(50),
--  PRFNL   clm_line_bnft_enhncmt_1_cd     character varying(2),
    clm_rlt_cond_cd             character varying(20),
    clm_rlt_cond_sgntr_sqnc_num integer,

--     prvdr_rndrng_prvdr_npi_num  character varying(10),
--     prvdr_rndrng_sk             bigint,
--     prvdr_rndrng_mdl_name       character varying(25),
--     prvdr_rndrng_type_cd        character varying(2),
--     prvdr_rndrng_txnmy_cmpst_cd character varying(150),
--     prvdr_rndrng_oscar_num      character varying(13),
--     prvdr_rndrng_1st_name       character varying(35),
--     prvdr_rndrng_name           character varying(70),
--     prvdr_rndrng_lgl_name       character varying(100),
--     prvdr_rndrng_emplr_id_num   character varying(10),
--     prvdr_rndrng_last_name      character varying(35),

--  PAC   clm_line_othr_tp_pd_amt        numeric,
--  PAC   clm_line_ncvrd_pd_amt          numeric,
--  PAC   clm_line_otaf_amt              numeric,
    -- CLAIM LINE INSTITUTIONAL columns
    clm_rev_apc_hipps_cd        character varying(5)     NOT NULL,
    clm_otaf_one_ind_cd         character varying(1)     NOT NULL,
    clm_rev_dscnt_ind_cd        character varying(1)     NOT NULL,
    clm_rev_packg_ind_cd        character varying(1)     NOT NULL,
    clm_rev_cntr_stus_cd        character varying(2)     NOT NULL,
    clm_rev_pmt_mthd_cd         character varying(2)     NOT NULL,
    clm_ddctbl_coinsrnc_cd      character varying(1)     NOT NULL,
    clm_line_instnl_rate_amt    numeric,
    clm_line_instnl_adjstd_amt  numeric,
    clm_line_instnl_rdcd_amt    numeric,
    clm_line_instnl_msp1_pd_amt numeric,
    clm_line_instnl_msp2_pd_amt numeric,
    clm_line_instnl_rev_ctr_dt  date,
    clm_rev_cntr_tdapa_amt      numeric,
--  PAC   clm_line_non_ehr_rdctn_amt  numeric,
    clm_line_add_on_pymt_amt    numeric,
    clm_ocrnc_sgntr_sk          numeric,
    clm_rlt_ocrnc_sgntr_sk      numeric,
    --  CLM_ANSI_SGNTR
    clm_1_rev_cntr_ansi_grp_cd character varying(2)     NOT NULL,
--  NOT USED   clm_2_rev_cntr_ansi_grp_cd character varying(2)     NOT NULL,
--  NOT USED   clm_3_rev_cntr_ansi_grp_cd character varying(2)     NOT NULL,
--  NOT USED   clm_4_rev_cntr_ansi_grp_cd character varying(2)     NOT NULL,
    clm_1_rev_cntr_ansi_rsn_cd character varying(3)     NOT NULL,
--  NOT USED   clm_2_rev_cntr_ansi_rsn_cd character varying(3)     NOT NULL,
--  NOT USED   clm_3_rev_cntr_ansi_rsn_cd character varying(3)     NOT NULL,
--  NOT USED   clm_4_rev_cntr_ansi_rsn_cd character varying(3)     NOT NULL,
    PRIMARY KEY (clm_uniq_id, bfd_row_id)
);


CREATE TABLE idr_new.claim_rx
(
    clm_uniq_id                       bigint                NOT NULL PRIMARY KEY,
    --CLAIM DATE SGNTR
    clm_cms_proc_dt                   date,
--     clm_actv_care_from_dt date                     ,
--  NON_RX   clm_dschrg_dt         date                     ,
    clm_submsn_dt                     date,
--  NON_RX   clm_ncvrd_from_dt     date                     ,
--  NON_RX   clm_ncvrd_thru_dt     date                     ,
--     clm_actv_care_thru_dt date                     ,
--  NON_RX   clm_mdcr_exhstd_dt                date,
--  NON_RX   clm_nch_wkly_proc_dt              date,
--  NON_RX   clm_qlfy_stay_from_dt date                     NOT NULL,
--  NON_RX   clm_qlfy_stay_thru_dt date                     NOT NULL,
    --CLAIM DATE SGNTR
    clm_type_cd                       integer               NOT NULL,
    bene_sk                           bigint                NOT NULL,
    clm_cntl_num                      character varying(40) NOT NULL,
    clm_orig_cntl_num                 character varying(40) NOT NULL,
    clm_from_dt                       date                  NOT NULL,
    clm_thru_dt                       date,
    clm_efctv_dt                      date,
    clm_obslt_dt                      date,
--     INSTNL clm_bill_clsfctn_cd        character varying(1)     NOT NULL,
--     INSTNL clm_bill_fac_type_cd       character varying(1)     NOT NULL,
--     INSTNL clm_bill_freq_cd           character varying(1)     NOT NULL,
    clm_finl_actn_ind                 character varying(1)  NOT NULL,
--    clm_src_id                        character varying(5)  NOT NULL,
--  NON_RX clm_query_cd                 character varying(1)     NOT NULL,
--  NON_RX   clm_mdcr_coinsrnc_amt      numeric,
--  NON_RX   clm_blood_lblty_amt        numeric,
--  NON_RX   clm_ncvrd_chrg_amt         numeric,
--  NON_RX   clm_mdcr_ddctbl_amt        numeric,
--  NON_RX   clm_prvdr_pmt_amt          numeric,
--  NON_RX   clm_alowd_chrg_amt         numeric,
    clm_bene_pmt_amt                  numeric,
--     clm_cntrctr_num            character varying(5)     NOT NULL,
--     clm_pmt_amt                numeric,
    clm_pd_dt                         date,
    clm_ltst_clm_ind                  character varying(1)  NOT NULL,
--     prvdr_othr_prvdr_npi_num   character varying(10)    NOT NULL,
--     prvdr_othr_sk              bigint                   NOT NULL,
--     prvdr_othr_hstry_efctv_dt  date                     NOT NULL,
--     prvdr_othr_mdl_name        character varying(25)    NOT NULL,
--     prvdr_othr_type_cd         character varying(2)     NOT NULL,
--     prvdr_othr_txnmy_cmpst_cd  character varying(150)   NOT NULL,
--     prvdr_othr_oscar_num       character varying(13)    NOT NULL,
--     prvdr_othr_1st_name        character varying(35)    NOT NULL,
--     prvdr_othr_name            character varying(70)    NOT NULL,
--     prvdr_othr_hstry_obslt_dt  date                     NOT NULL,
--     prvdr_othr_lgl_name        character varying(100)   NOT NULL,
--     prvdr_othr_emplr_id_num    character varying(10)    NOT NULL,
--     prvdr_othr_last_name       character varying(35)    NOT NULL,
--     prvdr_blg_prvdr_npi_num    character varying(10)    NOT NULL,
--     prvdr_blg_sk               bigint                   NOT NULL,
--     prvdr_blg_hstry_efctv_dt   date                     NOT NULL,
--     prvdr_blg_mdl_name         character varying(25)    NOT NULL,
--     prvdr_blg_type_cd          character varying(2)     NOT NULL,
--     prvdr_blg_txnmy_cmpst_cd   character varying(150)   NOT NULL,
--     prvdr_blg_oscar_num        character varying(13)    NOT NULL,
--     prvdr_blg_1st_name         character varying(35)    NOT NULL,
--     prvdr_blg_name             character varying(70)    NOT NULL,
--     prvdr_blg_hstry_obslt_dt   date                     NOT NULL,
--     prvdr_blg_lgl_name         character varying(100)   NOT NULL,
--     prvdr_blg_emplr_id_num     character varying(10)    NOT NULL,
--     prvdr_blg_last_name        character varying(35)    NOT NULL,
--     prvdr_rfrg_prvdr_npi_num   character varying(10)    NOT NULL,
--     prvdr_rfrg_sk              bigint                   NOT NULL,
--     prvdr_rfrg_hstry_efctv_dt  date                     NOT NULL,
--     prvdr_rfrg_mdl_name        character varying(25)    NOT NULL,
--     prvdr_rfrg_type_cd         character varying(2)     NOT NULL,
--     prvdr_rfrg_txnmy_cmpst_cd  character varying(150)   NOT NULL,
--     prvdr_rfrg_oscar_num       character varying(13)    NOT NULL,
--     prvdr_rfrg_1st_name        character varying(35)    NOT NULL,
--     prvdr_rfrg_name            character varying(70)    NOT NULL,
--     prvdr_rfrg_hstry_obslt_dt  date                     NOT NULL,
--     prvdr_rfrg_lgl_name        character varying(100)   NOT NULL,
--     prvdr_rfrg_emplr_id_num    character varying(10)    NOT NULL,
--     prvdr_rfrg_last_name       character varying(35)    NOT NULL,
--  NON_RX   clm_disp_cd                  character varying(2)     NOT NULL,
--  INSTNL   clm_ric_cd                 character varying(1)     NOT NULL,
--  NON_RX  clm_sbmt_chrg_amt          numeric,
--  NON_RX   clm_blood_pt_frnsh_qty     integer,
--  NON_RX   clm_nch_prmry_pyr_cd       character varying(1)     NOT NULL,
--  INSTNL   clm_blg_prvdr_oscar_num      character varying(20)    NOT NULL,
    clm_idr_ld_dt                     date,
--  INSTNL   clm_nrln_ric_cd            character varying(1)     NOT NULL,
--  PRVDR   prvdr_srvc_prvdr_npi_num   character varying(20)    NOT NULL,
    prvdr_prscrbng_prvdr_npi_num      character varying(10),
    prvdr_prscrbng_sk                 bigint,
    prvdr_prscrbng_mdl_name           character varying(25),
    prvdr_prscrbng_type_cd            character varying(2),
    prvdr_prscrbng_txnmy_cmpst_cd     character varying(150),
    prvdr_prscrbng_oscar_num          character varying(13),
    prvdr_prscrbng_1st_name           character varying(35),
    prvdr_prscrbng_name               character varying(70),
    prvdr_prscrbng_lgl_name           character varying(100),
    prvdr_prscrbng_emplr_id_num       character varying(10),
    prvdr_prscrbng_last_name          character varying(35),
--     idr_insrt_ts_dcmtn         timestamp with time zone NOT NULL,
--     idr_updt_ts_dcmtn          timestamp with time zone NOT NULL,
    bfd_created_ts                    timestamp with time zone,
    bfd_updated_ts                    timestamp with time zone,
    clm_adjstmt_type_cd               character varying(2),
--  NON_RX   clm_bene_pd_amt            numeric,
--  PRVDR   clm_blg_prvdr_zip5_cd        character varying(5),
    clm_sbmt_frmt_cd                  character varying(1),
    clm_sbmtr_cntrct_num              character varying(5),
    clm_sbmtr_cntrct_pbp_num          character varying(3),
--  INSTNL   clm_bnft_enhncmt_1_cd      character varying(2),
--  INSTNL   clm_ngaco_pbpmt_sw         character varying(1),
--  INSTNL   clm_ngaco_cptatn_sw        character varying(1),
--  INSTNL   clm_ngaco_pdschrg_hcbs_sw  character varying(1),
--  INSTNL   clm_ngaco_snf_wvr_sw       character varying(1),
--  INSTNL   clm_ngaco_tlhlth_sw        character varying(1),
--  INSTNL   clm_bnft_enhncmt_2_cd      character varying(2),
--  INSTNL   clm_bnft_enhncmt_3_cd      character varying(2),
--  INSTNL   clm_bnft_enhncmt_4_cd      character varying(2),
--  INSTNL   clm_bnft_enhncmt_5_cd      character varying(2),
--  PRVDR   clm_rfrg_prvdr_pin_num     character varying(10),
    prvdr_srvc_prvdr_npi_num          character varying(10),
    prvdr_srvc_sk                     bigint,
    prvdr_srvc_mdl_name               character varying(25),
    prvdr_srvc_type_cd                character varying(2),
    prvdr_srvc_txnmy_cmpst_cd         character varying(150),
    prvdr_srvc_oscar_num              character varying(13),
    prvdr_srvc_1st_name               character varying(35),
    prvdr_srvc_name                   character varying(70),
    prvdr_srvc_lgl_name               character varying(100),
    prvdr_srvc_emplr_id_num           character varying(10),
    prvdr_srvc_last_name              character varying(35),
--     clm_blood_chrg_amt         numeric,
--  INSTNL   clm_tot_cntrctl_amt        numeric,
--  NON_RX   clm_bene_intrst_pd_amt     numeric,
--  NON_RX   clm_bene_pmt_coinsrnc_amt  numeric,
--  NON_RX   clm_cob_ptnt_resp_amt      numeric,
--  NON_RX   clm_prvdr_otaf_amt         numeric,
    clm_othr_tp_pd_amt                numeric,
--  NON_RX   clm_prvdr_rmng_due_amt     numeric,
--  NON_RX   clm_blood_ncvrd_chrg_amt   numeric,
--  NON_RX   clm_prvdr_intrst_pd_amt    numeric,
    bfd_claim_updated_ts              timestamp with time zone DEFAULT now(),
--- LINE_ITEM COLUMNS
--    clm_line_num                      integer               NOT NULL,
--     clm_line_ansthsa_unit_cnt         numeric,
--  PRFNL   clm_line_dgns_cd               character varying(7)     NOT NULL,
--  NON_RX   clm_line_sbmt_chrg_amt         numeric,
--  NON_RX   clm_line_alowd_chrg_amt        numeric,
--  INSTNL   clm_line_ncvrd_chrg_amt        numeric,
--  NON_RX   clm_line_prvdr_pmt_amt         numeric,
    clm_line_bene_pmt_amt             numeric,
--  NON_RX   clm_line_bene_pd_amt           numeric,
    clm_line_cvrd_pd_amt              numeric,
--  INSTNL  clm_line_blood_ddctbl_amt      numeric,
--  INSTNL  clm_line_mdcr_ddctbl_amt       numeric,
--  NULL FOR ALL   clm_line_mdcr_coinsrnc_amt     numeric,
--  NON_RX   clm_line_hcpcs_cd              character varying(5)     NOT NULL,
    clm_line_from_dt                  date,
    clm_line_ndc_cd                   character varying(11) NOT NULL,
    clm_line_ndc_qty                  numeric,
    clm_line_ndc_qty_qlfyr_cd         character varying(2)  NOT NULL,
    clm_line_srvc_unit_qty            numeric,
--  INSTNL   clm_line_rev_ctr_cd            character varying(4)     NOT NULL,
    clm_line_rx_num                   character varying(30) NOT NULL,
    clm_line_thru_dt                  date,
--  PRFNL   clm_pos_cd                     character varying(2)     NOT NULL,
--  PRFNL   clm_rndrg_prvdr_prtcptg_cd     character varying(1)     NOT NULL,
--  PRFNL   clm_rndrg_prvdr_tax_num        character varying(10)    NOT NULL,
--  NON_RX   hcpcs_1_mdfr_cd                character varying(2)     NOT NULL,
--  NON_RX   hcpcs_2_mdfr_cd                character varying(2)     NOT NULL,
--  NON_RX   hcpcs_3_mdfr_cd                character varying(2)     NOT NULL,
--  NON_RX   hcpcs_4_mdfr_cd                character varying(2)     NOT NULL,
--  NON_RX   hcpcs_5_mdfr_cd                character varying(2)     NOT NULL,
--  NON_RX   clm_val_sqnc_num_prod          integer,
--  NON_RX   clm_dgns_prcdr_icd_ind         character varying(1)     NOT NULL,
--  NON_RX   clm_dgns_cd                    character varying(7)     NOT NULL,
--  NON_RX   clm_prcdr_cd                   character varying(7)     NOT NULL,
--  NON_RX   clm_prod_type_cd               character varying(1)     NOT NULL,
--  NON_RX   clm_poa_ind                    character varying(1)     NOT NULL,
--  NON_RX   clm_prcdr_prfrm_dt             date                     NOT NULL,
--  NON_RX   idr_insrt_ts_prod              timestamp with time zone NOT NULL,
--  NON_RX   idr_updt_ts_prod               timestamp with time zone NOT NULL,
--  NON_RX   clm_val_sqnc_num_val           integer,
--  NON_RX   clm_val_cd                     character varying(2)     NOT NULL,
--  NON_RX   clm_val_amt                    numeric,
--  NON_RX   idr_insrt_ts_val               timestamp with time zone NOT NULL,
--  NON_RX   idr_updt_ts_val                timestamp with time zone NOT NULL,
--  NON_RX   clm_rndrg_prvdr_type_cd        character varying(3),
--  NON_RX   clm_line_bnft_enhncmt_2_cd     character varying(2),
--  NON_RX   clm_line_bnft_enhncmt_3_cd     character varying(2),
--  NON_RX   clm_line_bnft_enhncmt_4_cd     character varying(2),
--  NON_RX   clm_line_bnft_enhncmt_5_cd     character varying(2),
--  NON_RX   clm_line_ngaco_cptatn_sw       character varying(1),
--  NON_RX   clm_line_ngaco_pdschrg_hcbs_sw character varying(1),
--  NON_RX   clm_line_ngaco_snf_wvr_sw      character varying(1),
--  NON_RX   clm_line_ngaco_tlhlth_sw       character varying(1),
--  NON_RX   clm_line_aco_care_mgmt_hcbs_sw character varying(1),
--  NON_RX   clm_line_ngaco_pbpmt_sw        character varying(1),
--  NON_RX   idr_insrt_ts_line_dcmtn        timestamp with time zone,
--  NON_RX   idr_updt_ts_line_dcmtn         timestamp with time zone,
--  NON_RX   clm_line_pmd_uniq_trkng_num    character varying(14),
--  NON_RX   clm_line_pa_uniq_trkng_num     character varying(50),
--  NON_RX   clm_line_bnft_enhncmt_1_cd     character varying(2),
--  NON_RX   clm_rlt_cond_sgntr_sk          bigint,
--  NON_RX   clm_rlt_cond_cd                character varying(20),
--  NON_RX   clm_rlt_cond_sgntr_sqnc_num    integer,
--  NON_RX   idr_insrt_ts_rlt_cond          timestamp with time zone,
--  NON_RX   idr_updt_ts_rlt_cond           timestamp with time zone,
--  NON_RX   clm_rndrg_prvdr_npi_num        character varying(10),
--  NON_RX   prvdr_rndrng_prvdr_npi_num     character varying(10),
    clm_line_othr_tp_pd_amt           numeric,
    clm_line_ncvrd_pd_amt             numeric,
--  NON_RX   clm_line_otaf_amt              numeric,
-- CLM_LINE_RX COLUMNS
    clm_brnd_gnrc_cd                  character varying(1)  NOT NULL,
    clm_cmpnd_cd                      character varying(1)  NOT NULL,
    clm_ctstrphc_cvrg_ind_cd          character varying(1)  NOT NULL,
    clm_daw_prod_slctn_cd             character varying(1)  NOT NULL,
    clm_drug_cvrg_stus_cd             character varying(2)  NOT NULL,
    clm_dspnsng_stus_cd               character varying(1)  NOT NULL,
    clm_line_authrzd_fill_num         character varying(2),
    clm_line_days_suply_qty           integer,
    clm_line_grs_above_thrshld_amt    numeric,
    clm_line_grs_blw_thrshld_amt      numeric,
    clm_prnt_cntl_num                varchar(40),
    clm_line_ingrdnt_cst_amt          numeric,
    clm_line_lis_amt                  numeric,
    clm_line_plro_amt                 numeric,
    clm_line_rx_fill_num              integer,
    clm_line_rx_orgn_cd               character varying(1)  NOT NULL,
    clm_line_sls_tax_amt              numeric,
    clm_line_srvc_cst_amt             numeric,
    clm_line_troop_tot_amt            numeric,
    clm_line_vccn_admin_fee_amt       numeric,
    clm_ltc_dspnsng_mthd_cd           character varying(3)  NOT NULL,
    clm_phrmcy_srvc_type_cd           character varying(2)  NOT NULL,
    clm_prcng_excptn_cd               character varying(1)  NOT NULL,
    clm_ptnt_rsdnc_cd                 character varying(2)  NOT NULL,
    clm_line_rptd_gap_dscnt_amt       numeric,
    clm_rptd_mftr_dscnt_amt           numeric,
    clm_line_rebt_passthru_pos_amt    numeric,
    clm_cms_calcd_mftr_dscnt_amt      numeric,
    clm_line_grs_cvrd_cst_tot_amt     numeric,
    clm_phrmcy_price_dscnt_at_pos_amt numeric,
    cntrct_pbp_name character varying(75) NOT NULL
);


CREATE INDEX ON idr_new.claim_rx(bene_sk);
