#!/usr/bin/env groovy

pipeline {
  agent {
    kubernetes {
      defaultContainer 'bfd-cbc-build'
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccount: bfd
  containers:
  - name: bfd-cbc-build
    image: 'public.ecr.aws/c2o1d8s9/bfd-cbc-build:jdk11-mvn3-an29-tfenv-aeaa61fa6'
    command:
    - cat
    tty: true
    imagePullPolicy: Always
    resources:
      requests:
        memory: '16384Mi'
        cpu: '8000m'
      limits:
        memory: '16384Mi'
        cpu: '8000m'
"""
    }
  }

  parameters {
    choice(name: 'ENVIRONMENT',
           choices: ['test', 'prod-sbx', 'prod'],
           description: 'The BFD SDLC environment to run against')

    string(name: 'TEST_HOST',
           defaultValue: 'https://%s.bfd.cms.gov',
           description: 'The URL under test -- should match the given environment. "%s" will be '
                        + 'replaced with the chosen environment')

    string(name: 'INITIAL_WORKER_NODES',
           defaultValue: '0',
           description: 'The number of initial Locust worker nodes to spawn before checking for '
                        + 'stop signals. Useful for static load tests')

    string(name: 'NODE_SPAWN_TIME',
           defaultValue: '10',
           description: 'The amount of time to wait between spawning more Lambda Locust worker '
                        + 'nodes. Does not affect initial spawned nodes')

    string(name: 'MAX_SPAWNED_NODES',
           defaultValue: '80',
           description: 'The maximum number of Lambda worker nodes to spawn over the lifetime of a '
                        + 'given test run. Does not account for failed nodes or nodes that reach '
                        + 'their Lambda timeout')

    string(name: 'MAX_USERS',
           defaultValue: '5000',
           description: 'The maximum number of simulated Locust users (not worker nodes) to spawn. '
                        + 'Use this and spawn rate to constrain the load during a test run')

    string(name: 'USER_SPAWN_RATE',
           defaultValue: '1',
           description: 'The rate at which simulated Locust users (not worker nodes) will spawn. '
                        + 'Set this equal to max_spawned_users if all users should be spawned '
                        + 'immediately')

    string(name: 'RUNTIME_LIMIT',
           defaultValue: '10m30s',
           description: 'The maximum runtime for the current load test. Acts as a failsafe against '
                        + 'runaway load testing')

    string(name: 'COASTING_TIME',
           defaultValue: '10',
           description: 'The amount of time the load test should continue for after receiving a '
                        + 'scaling notification. Does not effect operator stop signals')

    string(name: 'WARM_INSTANCE_TARGET',
           defaultValue: '7',
           description: 'The number of BFD Server instances to target before scaling causes the '
                        + 'load test to stop')

    booleanParam(name: 'STOP_ON_SCALING',
                 defaultValue: true,
                 description: 'Whether the load test run should end once receiving a scaling '
                              + 'notification. Set to false for scenarios where a static load test '
                              + 'is desired')

    booleanParam(name: 'STOP_ON_NODE_LIMIT',
                 defaultValue: true,
                 description: 'Whether the load test run should end once the maximum Lambda worker '
                              + 'node limit is reached. Set to false for scenarios where a static '
                              + 'load test is desired')
  }

  stages {
    stage('Run Load Tests') {
      steps {
        script {
          hostUnderTest = String.format(params.TEST_HOST, params.ENVIRONMENT)
          terraformVars = params.findAll { it.key != 'ENVIRONMENT' && it.key != 'TEST_HOST' }
                                .collectEntries { key, value -> [(key.toLowerCase()): value] }
          terraformVars.putAll(['test_host': hostUnderTest])
        }
        // TODO: Run terraform apply, create infrastructure (which starts load test service)
        echo "${terraformVars}"
        sleep 60
        // TODO: Await some signal from controller (SQS or other) with log location and other detail
      }
    }
  }

  post {
    cleanup {
      script {
        if (env.NODE_NAME != null) {
          sh 'terraform version'
        } else {
          echo 'Build ended prior to node being created'
        }
      }
    }
  }
}
