spring.config.import=optional:aws-parameterstore:/bfd/local/server?prefix=bfd.
logging.level.io.awspring=debug
# MiniStack configuration
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.parameterstore.endpoint=http://localhost:4566
spring.cloud.aws.parameterstore.region=us-east-1
spring.cloud.aws.parameterstore.reload.strategy=refresh
spring.cloud.aws.parameterstore.reload.period=10s
# Local database configuration
bfd.sensitive.db.username=bfd
bfd.sensitive.db.password=InsecureLocalDev

# SAMHSA-filtering certificate properties to enable testing
bfd.nonsensitive.client_certificates.samhsa_allowed=samhsa_allowed
bfd.nonsensitive.client_certificates.samhsa_not_allowed=samhsa_not_allowed
bfd.nonsensitive.samhsa_allowed_certificate_aliases_json=["samhsa_allowed"]
bfd.nonsensitive.cert_partners.partner_certificate.bbapi={"name":"Blue Button API","certificateAliases":["bluebutton_backend_prod_data_server_client_test","bluebutton_root_ca","bluebutton_root_ca_sbx","bb2_local_client","bluebutton_backend_dpr_data_server_client_test","bluebutton_root_ca_test","bluebutton_backend_test_samhsa"]}
bfd.nonsensitive.cert_partners.partner_certificate.ab2d={"name":"AB2D","certificateAliases":["ab2d_cms_gov","ab2d_cms_gov_non_prod","ab2d_prod_client","ab2d_prod_validation_client","ab2d_dev_prod_sbx_client","ab2d_sbx_client","ab2d_imp_client"]}
bfd.nonsensitive.cert_partners.partner_certificate.bcda={"name":"BCDA","certificateAliases":["bcda_prod_client","bcda_sbx_client","bcda_dev_client","bcda_test_client","bcda_local_client"]}
bfd.nonsensitive.cert_partners.partner_certificate.dpc={"name":"DPC","certificateAliases":["dpc_local_client","dpc_prod_client","dpc_prod_sbx_client","dpc_test_client","dpc_dev_client"]}
# Micrometer properties
management.metrics.export.cloudwatch.enabled=false
