/*
 * This migration creates a new schema to hold partially adjudicated claims data sourced from the RDA API.
 * The primary motivation of the change is to rename the schema to more generally reflect the data source
 * and to rename all tables, indexes, and columns to follow the snake case naming convention used
 * in the public schema.
 *
 * Because the production database is not yet populated the simplest approach is to create a new schema
 * and reload data into that new schema.  A later migration will drop the old pre_adj schema completely.
 */

create schema if not exists rda;

create table rda.rda_api_progress (
    claim_type           varchar(20) not null primary key,
    last_sequence_number bigint      not null,
    last_updated         timestamp with time zone
);

create table rda.mbi_cache (
    mbi_id       bigint generated by default as identity primary key,
    mbi          varchar(11) not null,
    hash         varchar(64) not null,
    old_hash     varchar(64),
    last_updated timestamp with time zone
);

create unique index mbi_cache_mbi_idx on rda.mbi_cache(mbi);

create unique index mbi_cache_hash_idx on rda.mbi_cache(hash);

create index mbi_cache_old_hash_idx on rda.mbi_cache(old_hash);

create sequence rda.rda_api_claim_message_meta_data_meta_data_id_seq as bigint ${logic.sequence-start} 1 ${logic.sequence-increment} 25 no cycle;

create table rda.rda_api_claim_message_meta_data (
    meta_data_id    bigint                   not null primary key,
    claim_type      char                     not null,
    sequence_number bigint                   not null,
    claim_id        varchar(25)              not null,
    mbi_id          bigint,
    claim_state     varchar(1),
    received_date   timestamp with time zone not null,
    foreign key (mbi_id) references rda.mbi_cache(mbi_id)
);


create table rda.fiss_claims (
    dcn                  varchar(23) not null primary key,
    hic_no               varchar(12) not null,
    curr_status          char        not null,
    curr_loc1            char        not null,
    curr_loc2            varchar(5)  not null,
    meda_prov_id         varchar(13),
    total_charge_amount  numeric(11, 2),
    received_date        date,
    curr_tran_date       date,
    admit_diag_code      varchar(7),
    principle_diag       varchar(7),
    npi_number           varchar(10),
    fed_tax_number       varchar(10),
    last_updated         timestamp with time zone,
    prac_loc_addr1       ${type.text},
    prac_loc_addr2       ${type.text},
    prac_loc_city        ${type.text},
    prac_loc_state       varchar(2),
    prac_loc_zip         varchar(15),
    meda_prov_6          varchar(6),
    stmt_cov_from_date   date,
    stmt_cov_to_date     date,
    lob_cd               varchar(1),
    serv_type_cd_mapping varchar(20),
    serv_type_cd         varchar(1),
    freq_cd              varchar(1),
    bill_typ_cd          varchar(3),
    sequence_number      bigint      not null,
    api_source           varchar(24),
    reject_cd            varchar(5),
    full_part_den_ind    varchar(1),
    non_pay_ind          varchar(2),
    xref_dcn_nbr         varchar(23),
    adj_req_cd           varchar(1),
    adj_reas_cd          varchar(2),
    cancel_xref_dcn      varchar(23),
    cancel_date          date,
    canc_adj_cd          varchar(1),
    original_xref_dcn    varchar(23),
    paid_dt              date,
    adm_date             date,
    adm_source           varchar(1),
    primary_payer_code   varchar(1),
    attend_phys_id       varchar(16),
    attend_phys_lname    varchar(17),
    attend_phys_fname    varchar(18),
    attend_phys_mint     varchar(1),
    attend_phys_flag     varchar(1),
    operating_phys_id    varchar(16),
    oper_phys_lname      varchar(17),
    oper_phys_fname      varchar(18),
    oper_phys_mint       varchar(1),
    oper_phys_flag       varchar(1),
    oth_phys_id          varchar(16),
    oth_phys_lname       varchar(17),
    oth_phys_fname       varchar(18),
    oth_phys_mint        varchar(1),
    oth_phys_flag        varchar(1),
    xref_hic_nbr         varchar(12),
    proc_new_hic_ind     varchar(1),
    new_hic              varchar(12),
    repos_ind            varchar(1),
    repos_hic            varchar(12),
    mbi_subm_bene_ind    varchar(1),
    adj_mbi_ind          varchar(1),
    adj_mbi              varchar(11),
    medical_record_no    varchar(17),
    prov_state_cd        varchar(2),
    prov_typ_facil_cd    varchar(1),
    prov_emer_ind        varchar(1),
    prov_dept_id         varchar(3),
    mbi_id               bigint,
    foreign key (mbi_id) references rda.mbi_cache(mbi_id)
);

create index fiss_claims_last_updated_idx
    on rda.fiss_claims(last_updated);

create index fiss_claims_mbi_id_idx
    on rda.fiss_claims(mbi_id);

create table rda.fiss_audit_trails (
    dcn            varchar(23) not null,
    priority       smallint    not null,
    last_updated   timestamp with time zone,
    badt_status    varchar(1),
    badt_loc       varchar(5),
    badt_oper_id   varchar(9),
    badt_reas      varchar(5),
    badt_curr_date date,
    primary key (dcn, priority),
    foreign key (dcn) references rda.fiss_claims(dcn)
);

create table rda.fiss_diagnosis_codes (
    dcn          varchar(23) not null,
    priority     smallint    not null,
    diag_cd2     varchar(7)  not null,
    diag_poa_ind varchar(1),
    bit_flags    varchar(4),
    last_updated timestamp with time zone,
    primary key (dcn, priority),
    foreign key (dcn) references rda.fiss_claims(dcn)
);

create table rda.fiss_proc_codes (
    dcn          varchar(23) not null,
    priority     smallint    not null,
    proc_code    varchar(10) not null,
    proc_flag    varchar(4),
    proc_date    date,
    last_updated timestamp with time zone,
    primary key (dcn, priority),
    foreign key (dcn) references rda.fiss_claims(dcn)
);

create table rda.fiss_payers (
    dcn                varchar(23) not null,
    priority           smallint    not null,
    payer_type         varchar(20),
    payers_id          varchar(1),
    payers_name        varchar(32),
    rel_ind            varchar(1),
    assign_ind         varchar(1),
    provider_number    varchar(13),
    adj_dcn_icn        varchar(23),
    prior_pmt          numeric(11, 2),
    est_amt_due        numeric(11, 2),
    bene_rel           varchar(2),
    bene_last_name     varchar(15),
    bene_first_name    varchar(10),
    bene_mid_init      varchar(1),
    bene_ssn_hic       varchar(19),
    insured_rel        varchar(2),
    insured_name       varchar(25),
    insured_ssn_hic    varchar(19),
    insured_group_name varchar(17),
    insured_group_nbr  varchar(20),
    bene_dob           date,
    bene_sex           varchar(1),
    treat_auth_cd      varchar(18),
    insured_sex        varchar(1),
    insured_rel_x12    varchar(2),
    insured_dob        date,
    insured_dob_text   varchar(9),
    last_updated       timestamp with time zone,
    primary key (dcn, priority),
    foreign key (dcn) references rda.fiss_claims(dcn)
);



create table rda.mcs_claims (
    idr_clm_hd_icn              varchar(15) not null primary key,
    idr_contr_id                varchar(5)  not null,
    idr_hic                     varchar(12),
    idr_claim_type              varchar(1)  not null,
    idr_dtl_cnt                 integer,
    idr_bene_last_1_6           varchar(6),
    idr_bene_first_init         varchar(1),
    idr_bene_mid_init           varchar(1),
    idr_bene_sex                varchar(1),
    idr_status_code             varchar(1),
    idr_status_date             date,
    idr_bill_prov_npi           varchar(10),
    idr_bill_prov_num           varchar(10),
    idr_bill_prov_ein           varchar(10),
    idr_bill_prov_type          varchar(2),
    idr_bill_prov_spec          varchar(2),
    idr_bill_prov_group_ind     varchar(1),
    idr_bill_prov_price_spec    varchar(2),
    idr_bill_prov_county        varchar(2),
    idr_bill_prov_loc           varchar(2),
    idr_tot_allowed             numeric(7, 2),
    idr_coinsurance             numeric(7, 2),
    idr_deductible              numeric(7, 2),
    idr_bill_prov_status_cd     varchar(1),
    idr_tot_billed_amt          numeric(7, 2),
    idr_claim_receipt_date      date,
    idr_hdr_from_date_of_svc    date,
    idr_hdr_to_date_of_svc      date,
    last_updated                timestamp with time zone,
    sequence_number             bigint      not null,
    api_source                  varchar(24),
    idr_assignment              varchar(1),
    idr_clm_level_ind           varchar(1),
    idr_hdr_audit               integer,
    idr_hdr_audit_ind           varchar(1),
    idr_u_split_reason          varchar(1),
    idr_j_referring_prov_npi    varchar(10),
    idr_j_fac_prov_npi          varchar(10),
    idr_u_demo_prov_npi         varchar(10),
    idr_u_super_npi             varchar(10),
    idr_u_fcadj_bil_npi         varchar(10),
    idr_amb_pickup_addres_line1 varchar(25),
    idr_amb_pickup_addres_line2 varchar(20),
    idr_amb_pickup_city         varchar(20),
    idr_amb_pickup_state        varchar(2),
    idr_amb_pickup_zipcode      varchar(9),
    idr_amb_dropoff_name        varchar(24),
    idr_amb_dropoff_addr_line1  varchar(25),
    idr_amb_dropoff_addr_line2  varchar(20),
    idr_amb_dropoff_city        varchar(20),
    idr_amb_dropoff_state       varchar(2),
    idr_amb_dropoff_zipcode     varchar(9),
    mbi_id                      bigint,
    foreign key (mbi_id) references rda.mbi_cache(mbi_id)
);

create index mcs_claims_last_updated_idx
    on rda.mcs_claims(last_updated);

create index mcs_claims_mbi_id_idx
    on rda.mcs_claims(mbi_id);

create table rda.mcs_adjustments (
    idr_clm_hd_icn     varchar(15) not null,
    priority           smallint    not null,
    last_updated       timestamp with time zone,
    idr_adj_date       date,
    idr_xref_icn       varchar(15),
    idr_adj_clerk      varchar(4),
    idr_init_ccn       varchar(15),
    idr_adj_chk_wrt_dt date,
    idr_adj_b_eomb_amt numeric(7, 2),
    idr_adj_p_eomb_amt numeric(7, 2),
    primary key (idr_clm_hd_icn, priority),
    foreign key (idr_clm_hd_icn) references rda.mcs_claims(idr_clm_hd_icn)
);

create table rda.mcs_audits (
    idr_clm_hd_icn   varchar(15) not null,
    priority         smallint    not null,
    last_updated     timestamp with time zone,
    idr_j_audit_num  integer,
    idr_j_audit_ind  varchar(1),
    idr_j_audit_disp varchar(1),
    primary key (idr_clm_hd_icn, priority),
    foreign key (idr_clm_hd_icn) references rda.mcs_claims(idr_clm_hd_icn)
);

create table rda.mcs_details (
    idr_clm_hd_icn              varchar(15) not null,
    priority                    smallint    not null,
    idr_dtl_status              varchar(1),
    idr_dtl_from_date           date,
    idr_dtl_to_date             date,
    idr_proc_code               varchar(5),
    idr_mod_one                 varchar(2),
    idr_mod_two                 varchar(2),
    idr_mod_three               varchar(2),
    idr_mod_four                varchar(2),
    idr_dtl_diag_icd_type       varchar(1),
    idr_dtl_primary_diag_code   varchar(7),
    idr_k_pos_lname_org         varchar(60),
    idr_k_pos_fname             varchar(35),
    idr_k_pos_mname             varchar(25),
    idr_k_pos_addr1             varchar(55),
    idr_k_pos_addr2_1st         varchar(30),
    idr_k_pos_addr2_2nd         varchar(25),
    idr_k_pos_city              varchar(30),
    idr_k_pos_state             varchar(2),
    idr_k_pos_zip               varchar(15),
    last_updated                timestamp with time zone,
    idr_tos                     varchar(1),
    idr_two_digit_pos           varchar(2),
    idr_dtl_rend_type           varchar(2),
    idr_dtl_rend_spec           varchar(2),
    idr_dtl_rend_npi            varchar(10),
    idr_dtl_rend_prov           varchar(10),
    idr_k_dtl_fac_prov_npi      varchar(10),
    idr_dtl_amb_pickup_addres1  varchar(25),
    idr_dtl_amb_pickup_addres2  varchar(20),
    idr_dtl_amb_pickup_city     varchar(20),
    idr_dtl_amb_pickup_state    varchar(2),
    idr_dtl_amb_pickup_zipcode  varchar(9),
    idr_dtl_amb_dropoff_name    varchar(24),
    idr_dtl_amb_dropoff_addr_l1 varchar(25),
    idr_dtl_amb_dropoff_addr_l2 varchar(20),
    idr_dtl_amb_dropoff_city    varchar(20),
    idr_dtl_amb_dropoff_state   varchar(2),
    idr_dtl_amb_dropoff_zipcode varchar(9),
    primary key (idr_clm_hd_icn, priority),
    foreign key (idr_clm_hd_icn) references rda.mcs_claims(idr_clm_hd_icn)
);

create table rda.mcs_diagnosis_codes (
    idr_clm_hd_icn    varchar(15) not null,
    priority          smallint    not null,
    idr_diag_icd_type varchar(1),
    idr_diag_code     varchar(7)  not null,
    last_updated      timestamp with time zone,
    primary key (idr_clm_hd_icn, priority),
    foreign key (idr_clm_hd_icn) references rda.mcs_claims(idr_clm_hd_icn)
);

create table rda.mcs_locations (
    idr_clm_hd_icn    varchar(15) not null,
    priority          smallint    not null,
    last_updated      timestamp with time zone,
    idr_loc_clerk     varchar(4),
    idr_loc_code      varchar(3),
    idr_loc_date      date,
    idr_loc_actv_code varchar(1),
    primary key (idr_clm_hd_icn, priority),
    foreign key (idr_clm_hd_icn) references rda.mcs_claims(idr_clm_hd_icn)
);
