-- NEW_SCHEMA_HOSPICE_CLAIMS.SQL
-- flyway migration for HOSPICE_CLAIMS and HOSPICE_CLAIM_LINES tables into
-- a new schema structure that:
--   1) changes data type of CLM_ID, BENE_ID from varchar to BIGINT.
--   2) change data type of CLM_GROUP_ID from numeric to BIGINT
--   3) organizes parent claim table (HOSPICE_CLAIMS_NEW) such that common
--      claims data columns are organized at top of table structure.
--
--      The following db columns were redefined from NUMERIC to more
--      appropriate data type(s):
--
--      from: clm_line_num numeric   : changed to smallint
--
--       Current db data values for changed columns
--      +-----------------------+--------+------+-------+
--      |  db Column            |   Max  |  Min | Scale |
--      +-----------------------+--------+------+-------+
--      | CLM_LINE_NUM          |    450 |   1  |   0   |
--      +-----------------------+--------+------+-------+   
--
-- Once current table data is migrated to new table name/structure, a 
-- subsequent PR will be deployed that changes the ORM model(s) and
-- operational code for Hospice Claims table(s).
--
-- HSQL differs from PSQL (postgres) in that the table defintion
-- must be explicitly declared prior to loading data into the
-- target table. PSQL can derive the table structure based on
-- the data input (i.e., column name, data type). Thus, for HSQL,
-- we need to explicitly define the table structure prior to loading data.
--
-- For HSQL, explicitly define/create a new HOSPICE_CLAIMS_NEW table in
-- the current PUBLIC schema

${logic.hsql-only}  create table public.hospice_claims_new (
${logic.hsql-only}    clm_id                                bigint NOT NULL,
${logic.hsql-only}    bene_id                               bigint NOT NULL,
${logic.hsql-only}    clm_grp_id                            bigint NOT NULL,
${logic.hsql-only}    last_updated                          timestamp with time zone,
${logic.hsql-only}    clm_from_dt                           date NOT NULL,
${logic.hsql-only}    clm_thru_dt                           date NOT NULL,
${logic.hsql-only}    final_action                          char(1) NOT NULL,
${logic.hsql-only}    clm_pmt_amt                           numeric(12,2) NOT NULL,
${logic.hsql-only}    clm_fac_type_cd                       char(1) NOT NULL,
${logic.hsql-only}    clm_freq_cd                           char(1) NOT NULL,
${logic.hsql-only}    clm_srvc_clsfctn_type_cd              char(1) NOT NULL,
${logic.hsql-only}    clm_tot_chrg_amt                      numeric(12,2) NOT NULL,
${logic.hsql-only}    clm_utlztn_day_cnt                    numeric NOT NULL,
${logic.hsql-only}    clm_hospc_start_dt_id                 date,
${logic.hsql-only}    clm_mdcr_non_pmt_rsn_cd               varchar(2),
${logic.hsql-only}    nch_clm_type_cd                       varchar(2) NOT NULL,
${logic.hsql-only}    nch_near_line_rec_ident_cd            char(1) NOT NULL,
${logic.hsql-only}    nch_wkly_proc_dt                      date NOT NULL,
${logic.hsql-only}    nch_prmry_pyr_clm_pd_amt              numeric(12,2) NOT NULL,
${logic.hsql-only}    nch_prmry_pyr_cd                      char(1),
${logic.hsql-only}    nch_ptnt_status_ind_cd                char(1),
${logic.hsql-only}    nch_bene_dschrg_dt                    date,
${logic.hsql-only}    prvdr_num                             varchar(9) NOT NULL,
${logic.hsql-only}    prvdr_state_cd                        varchar(2) NOT NULL,
${logic.hsql-only}    ptnt_dschrg_stus_cd                   varchar(2) NOT NULL,
${logic.hsql-only}    fi_num                                varchar(5),
${logic.hsql-only}    fi_orig_clm_cntl_num                  varchar(23),
${logic.hsql-only}    fi_clm_proc_dt                        date,
${logic.hsql-only}    fi_doc_clm_cntl_num                   varchar(23),
${logic.hsql-only}    at_physn_npi                          varchar(10),
${logic.hsql-only}    at_physn_upin                         varchar(9),
${logic.hsql-only}    org_npi_num                           varchar(10),
${logic.hsql-only}    prncpal_dgns_cd                       varchar(7),
${logic.hsql-only}    prncpal_dgns_vrsn_cd                  char(1),
${logic.hsql-only}    bene_hospc_prd_cnt                    numeric(2,0),
${logic.hsql-only}    fst_dgns_e_cd                         varchar(7),
${logic.hsql-only}    fst_dgns_e_vrsn_cd                    char(1),
${logic.hsql-only}    icd_dgns_cd1                          varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd1                     char(1),
${logic.hsql-only}    icd_dgns_e_cd1                        varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd1                   char(1),
${logic.hsql-only}    icd_dgns_cd2                          varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd2                     char(1),
${logic.hsql-only}    icd_dgns_e_cd2                        varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd2                   char(1),
${logic.hsql-only}    icd_dgns_cd3                          varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd3                     char(1),
${logic.hsql-only}    icd_dgns_e_cd3                        varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd3                   char(1),
${logic.hsql-only}    icd_dgns_cd4                          varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd4                     char(1),
${logic.hsql-only}    icd_dgns_e_cd4                        varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd4                   char(1),
${logic.hsql-only}    icd_dgns_cd5                          varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd5                     char(1),
${logic.hsql-only}    icd_dgns_e_cd5                        varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd5                   char(1),
${logic.hsql-only}    icd_dgns_cd6                          varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd6                     char(1),
${logic.hsql-only}    icd_dgns_e_cd6                        varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd6                   char(1),
${logic.hsql-only}    icd_dgns_cd7                          varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd7                     char(1),
${logic.hsql-only}    icd_dgns_e_cd7                        varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd7                   char(1),
${logic.hsql-only}    icd_dgns_cd8                          varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd8                     char(1),
${logic.hsql-only}    icd_dgns_e_cd8                        varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd8                   char(1),
${logic.hsql-only}    icd_dgns_cd9                          varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd9                     char(1),
${logic.hsql-only}    icd_dgns_e_cd9                        varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd9                   char(1),
${logic.hsql-only}    icd_dgns_cd10                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd10                    char(1),
${logic.hsql-only}    icd_dgns_e_cd10                       varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd10                  char(1),
${logic.hsql-only}    icd_dgns_cd11                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd11                    char(1),
${logic.hsql-only}    icd_dgns_e_cd11                       varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd11                  char(1),
${logic.hsql-only}    icd_dgns_cd12                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd12                    char(1),
${logic.hsql-only}    icd_dgns_e_cd12                       varchar(7),
${logic.hsql-only}    icd_dgns_e_vrsn_cd12                  char(1),
${logic.hsql-only}    icd_dgns_cd13                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd13                    char(1),
${logic.hsql-only}    icd_dgns_cd14                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd14                    char(1),
${logic.hsql-only}    icd_dgns_cd15                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd15                    char(1),
${logic.hsql-only}    icd_dgns_cd16                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd16                    char(1),
${logic.hsql-only}    icd_dgns_cd17                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd17                    char(1),
${logic.hsql-only}    icd_dgns_cd18                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd18                    char(1),
${logic.hsql-only}    icd_dgns_cd19                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd19                    char(1),
${logic.hsql-only}    icd_dgns_cd20                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd20                    char(1),
${logic.hsql-only}    icd_dgns_cd21                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd21                    char(1),
${logic.hsql-only}    icd_dgns_cd22                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd22                    char(1),
${logic.hsql-only}    icd_dgns_cd23                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd23                    char(1),
${logic.hsql-only}    icd_dgns_cd24                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd24                    char(1),
${logic.hsql-only}    icd_dgns_cd25                         varchar(7),
${logic.hsql-only}    icd_dgns_vrsn_cd25                    char(1),
${logic.hsql-only} constraint public.hospice_claims_new_pkey
${logic.hsql-only} primary key (clm_id) );

-- create a new HOSPICE_CLAIM_LINES_NEW table in the current PUBLIC schema
--
${logic.hsql-only}  create table public.hospice_claim_lines_new (
${logic.hsql-only}    clm_id                                bigint NOT NULL,
${logic.hsql-only}    clm_line_num                          smallint not null,
${logic.hsql-only}    rev_cntr                              varchar(4) not null,
${logic.hsql-only}    rev_cntr_unit_cnt                     numeric not null,
${logic.hsql-only}    rev_cntr_tot_chrg_amt                 numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_rate_amt                     numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_ncvrd_chrg_amt               numeric(12,2),
${logic.hsql-only}    rev_cntr_ddctbl_coinsrnc_cd           character(1),
${logic.hsql-only}    rev_cntr_bene_pmt_amt                 numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_pmt_amt_amt                  numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_prvdr_pmt_amt                numeric(12,2) not null,
${logic.hsql-only}    rev_cntr_dt                           date,
${logic.hsql-only}    rev_cntr_ndc_qty_qlfr_cd              varchar(2),
${logic.hsql-only}    rev_cntr_ndc_qty                      numeric,
${logic.hsql-only}    hcpcs_cd                              varchar(5),
${logic.hsql-only}    hcpcs_1st_mdfr_cd                     varchar(5),
${logic.hsql-only}    hcpcs_2nd_mdfr_cd                     varchar(5),
${logic.hsql-only}    rndrng_physn_npi                      varchar(12),
${logic.hsql-only}    rndrng_physn_upin                     varchar(12),
${logic.hsql-only}    constraint public.hospice_claim_lines_new_pkey
${logic.hsql-only}    primary key (clm_id, clm_line_num) );

${logic.psql-only} SET max_parallel_workers = 24;
${logic.psql-only} SET max_parallel_workers_per_gather = 20;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;

-- migrate data via INSERT from current HOSPICE_CLAIMS table to HOSPICE_CLAIMS_NEW table
--
${logic.hsql-only} insert into public.hospice_claims_new (
${logic.hsql-only}    clm_id,
${logic.hsql-only}    bene_id,
${logic.hsql-only}    clm_grp_id,
${logic.hsql-only}    last_updated,
${logic.hsql-only}    clm_from_dt,
${logic.hsql-only}    clm_thru_dt,
${logic.hsql-only}    final_action,
${logic.hsql-only}    clm_pmt_amt,
${logic.hsql-only}    clm_fac_type_cd,
${logic.hsql-only}    clm_freq_cd,
${logic.hsql-only}    clm_srvc_clsfctn_type_cd,
${logic.hsql-only}    clm_tot_chrg_amt,
${logic.hsql-only}    clm_utlztn_day_cnt,
${logic.hsql-only}    clm_hospc_start_dt_id,
${logic.hsql-only}    clm_mdcr_non_pmt_rsn_cd,
${logic.hsql-only}    nch_clm_type_cd,
${logic.hsql-only}    nch_near_line_rec_ident_cd,
${logic.hsql-only}    nch_wkly_proc_dt,
${logic.hsql-only}    nch_prmry_pyr_clm_pd_amt,
${logic.hsql-only}    nch_prmry_pyr_cd,
${logic.hsql-only}    nch_ptnt_status_ind_cd,
${logic.hsql-only}    nch_bene_dschrg_dt,
${logic.hsql-only}    prvdr_num,
${logic.hsql-only}    prvdr_state_cd,
${logic.hsql-only}    ptnt_dschrg_stus_cd,
${logic.hsql-only}    fi_num,
${logic.hsql-only}    fi_orig_clm_cntl_num,
${logic.hsql-only}    fi_clm_proc_dt,
${logic.hsql-only}    fi_doc_clm_cntl_num,
${logic.hsql-only}    at_physn_npi,
${logic.hsql-only}    at_physn_upin,
${logic.hsql-only}    org_npi_num,
${logic.hsql-only}    prncpal_dgns_cd,
${logic.hsql-only}    prncpal_dgns_vrsn_cd,
${logic.hsql-only}    bene_hospc_prd_cnt,
${logic.hsql-only}    fst_dgns_e_cd,
${logic.hsql-only}    fst_dgns_e_vrsn_cd,
${logic.hsql-only}    icd_dgns_cd1,
${logic.hsql-only}    icd_dgns_vrsn_cd1,
${logic.hsql-only}    icd_dgns_e_cd1,
${logic.hsql-only}    icd_dgns_e_vrsn_cd1,
${logic.hsql-only}    icd_dgns_cd2,
${logic.hsql-only}    icd_dgns_vrsn_cd2,
${logic.hsql-only}    icd_dgns_e_cd2,
${logic.hsql-only}    icd_dgns_e_vrsn_cd2,
${logic.hsql-only}    icd_dgns_cd3,
${logic.hsql-only}    icd_dgns_vrsn_cd3,
${logic.hsql-only}    icd_dgns_e_cd3,
${logic.hsql-only}    icd_dgns_e_vrsn_cd3,
${logic.hsql-only}    icd_dgns_cd4,
${logic.hsql-only}    icd_dgns_vrsn_cd4,
${logic.hsql-only}    icd_dgns_e_cd4,
${logic.hsql-only}    icd_dgns_e_vrsn_cd4,
${logic.hsql-only}    icd_dgns_cd5,
${logic.hsql-only}    icd_dgns_vrsn_cd5,
${logic.hsql-only}    icd_dgns_e_cd5,
${logic.hsql-only}    icd_dgns_e_vrsn_cd5,
${logic.hsql-only}    icd_dgns_cd6,
${logic.hsql-only}    icd_dgns_vrsn_cd6,
${logic.hsql-only}    icd_dgns_e_cd6,
${logic.hsql-only}    icd_dgns_e_vrsn_cd6,
${logic.hsql-only}    icd_dgns_cd7,
${logic.hsql-only}    icd_dgns_vrsn_cd7,
${logic.hsql-only}    icd_dgns_e_cd7,
${logic.hsql-only}    icd_dgns_e_vrsn_cd7,
${logic.hsql-only}    icd_dgns_cd8,
${logic.hsql-only}    icd_dgns_vrsn_cd8,
${logic.hsql-only}    icd_dgns_e_cd8,
${logic.hsql-only}    icd_dgns_e_vrsn_cd8,
${logic.hsql-only}    icd_dgns_cd9,
${logic.hsql-only}    icd_dgns_vrsn_cd9,
${logic.hsql-only}    icd_dgns_e_cd9,
${logic.hsql-only}    icd_dgns_e_vrsn_cd9,
${logic.hsql-only}    icd_dgns_cd10,
${logic.hsql-only}    icd_dgns_vrsn_cd10,
${logic.hsql-only}    icd_dgns_e_cd10,
${logic.hsql-only}    icd_dgns_e_vrsn_cd10,
${logic.hsql-only}    icd_dgns_cd11,
${logic.hsql-only}    icd_dgns_vrsn_cd11,
${logic.hsql-only}    icd_dgns_e_cd11,
${logic.hsql-only}    icd_dgns_e_vrsn_cd11,
${logic.hsql-only}    icd_dgns_cd12,
${logic.hsql-only}    icd_dgns_vrsn_cd12,
${logic.hsql-only}    icd_dgns_e_cd12,
${logic.hsql-only}    icd_dgns_e_vrsn_cd12,
${logic.hsql-only}    icd_dgns_cd13,
${logic.hsql-only}    icd_dgns_vrsn_cd13,
${logic.hsql-only}    icd_dgns_cd14,
${logic.hsql-only}    icd_dgns_vrsn_cd14,
${logic.hsql-only}    icd_dgns_cd15,
${logic.hsql-only}    icd_dgns_vrsn_cd15,
${logic.hsql-only}    icd_dgns_cd16,
${logic.hsql-only}    icd_dgns_vrsn_cd16,
${logic.hsql-only}    icd_dgns_cd17,
${logic.hsql-only}    icd_dgns_vrsn_cd17,
${logic.hsql-only}    icd_dgns_cd18,
${logic.hsql-only}    icd_dgns_vrsn_cd18,
${logic.hsql-only}    icd_dgns_cd19,
${logic.hsql-only}    icd_dgns_vrsn_cd19,
${logic.hsql-only}    icd_dgns_cd20,
${logic.hsql-only}    icd_dgns_vrsn_cd20,
${logic.hsql-only}    icd_dgns_cd21,
${logic.hsql-only}    icd_dgns_vrsn_cd21,
${logic.hsql-only}    icd_dgns_cd22,
${logic.hsql-only}    icd_dgns_vrsn_cd22,
${logic.hsql-only}    icd_dgns_cd23,
${logic.hsql-only}    icd_dgns_vrsn_cd23,
${logic.hsql-only}    icd_dgns_cd24,
${logic.hsql-only}    icd_dgns_vrsn_cd24,
${logic.hsql-only}    icd_dgns_cd25,
${logic.hsql-only}    icd_dgns_vrsn_cd25 )
--
-- PSQL allows us to dynamically create a table via the
-- associated SELECT statement used to populate the table.
--
${logic.psql-only} create table public.hospice_claims_new as
select
${logic.hsql-only}    convert(clm_id, SQL_BIGINT),
${logic.hsql-only}    convert(bene_id, SQL_BIGINT),
${logic.hsql-only}    convert(clm_grp_id, SQL_BIGINT),
${logic.psql-only}    cast(clm_id as bigint),
${logic.psql-only}    cast(bene_id as bigint),
${logic.psql-only}    cast(clm_grp_id as bigint),
                      last_updated,
                      clm_from_dt,
                      clm_thru_dt,
                      final_action,
                      clm_pmt_amt,
                      clm_fac_type_cd,
                      clm_freq_cd,
                      clm_srvc_clsfctn_type_cd,
                      clm_tot_chrg_amt,
                      clm_utlztn_day_cnt,
                      clm_hospc_start_dt_id,
                      clm_mdcr_non_pmt_rsn_cd,
                      nch_clm_type_cd,
                      nch_near_line_rec_ident_cd,
                      nch_wkly_proc_dt,
                      nch_prmry_pyr_clm_pd_amt,
                      nch_prmry_pyr_cd,
                      nch_ptnt_status_ind_cd,
                      nch_bene_dschrg_dt,
                      prvdr_num,
                      prvdr_state_cd,
                      ptnt_dschrg_stus_cd,
                      fi_num,
                      fi_orig_clm_cntl_num,
                      fi_clm_proc_dt,
                      fi_doc_clm_cntl_num,
                      at_physn_npi,
                      at_physn_upin,
                      org_npi_num,
                      prncpal_dgns_cd,
                      prncpal_dgns_vrsn_cd,
                      bene_hospc_prd_cnt,
                      fst_dgns_e_cd,
                      fst_dgns_e_vrsn_cd,
                      icd_dgns_cd1,
                      icd_dgns_vrsn_cd1,
                      icd_dgns_e_cd1,
                      icd_dgns_e_vrsn_cd1,
                      icd_dgns_cd2,
                      icd_dgns_vrsn_cd2,
                      icd_dgns_e_cd2,
                      icd_dgns_e_vrsn_cd2,
                      icd_dgns_cd3,
                      icd_dgns_vrsn_cd3,
                      icd_dgns_e_cd3,
                      icd_dgns_e_vrsn_cd3,
                      icd_dgns_cd4,
                      icd_dgns_vrsn_cd4,
                      icd_dgns_e_cd4,
                      icd_dgns_e_vrsn_cd4,
                      icd_dgns_cd5,
                      icd_dgns_vrsn_cd5,
                      icd_dgns_e_cd5,
                      icd_dgns_e_vrsn_cd5,
                      icd_dgns_cd6,
                      icd_dgns_vrsn_cd6,
                      icd_dgns_e_cd6,
                      icd_dgns_e_vrsn_cd6,
                      icd_dgns_cd7,
                      icd_dgns_vrsn_cd7,
                      icd_dgns_e_cd7,
                      icd_dgns_e_vrsn_cd7,
                      icd_dgns_cd8,
                      icd_dgns_vrsn_cd8,
                      icd_dgns_e_cd8,
                      icd_dgns_e_vrsn_cd8,
                      icd_dgns_cd9,
                      icd_dgns_vrsn_cd9,
                      icd_dgns_e_cd9,
                      icd_dgns_e_vrsn_cd9,
                      icd_dgns_cd10,
                      icd_dgns_vrsn_cd10,
                      icd_dgns_e_cd10,
                      icd_dgns_e_vrsn_cd10,
                      icd_dgns_cd11,
                      icd_dgns_vrsn_cd11,
                      icd_dgns_e_cd11,
                      icd_dgns_e_vrsn_cd11,
                      icd_dgns_cd12,
                      icd_dgns_vrsn_cd12,
                      icd_dgns_e_cd12,
                      icd_dgns_e_vrsn_cd12,
                      icd_dgns_cd13,
                      icd_dgns_vrsn_cd13,
                      icd_dgns_cd14,
                      icd_dgns_vrsn_cd14,
                      icd_dgns_cd15,
                      icd_dgns_vrsn_cd15,
                      icd_dgns_cd16,
                      icd_dgns_vrsn_cd16,
                      icd_dgns_cd17,
                      icd_dgns_vrsn_cd17,
                      icd_dgns_cd18,
                      icd_dgns_vrsn_cd18,
                      icd_dgns_cd19,
                      icd_dgns_vrsn_cd19,
                      icd_dgns_cd20,
                      icd_dgns_vrsn_cd20,
                      icd_dgns_cd21,
                      icd_dgns_vrsn_cd21,
                      icd_dgns_cd22,
                      icd_dgns_vrsn_cd22,
                      icd_dgns_cd23,
                      icd_dgns_vrsn_cd23,
                      icd_dgns_cd24,
                      icd_dgns_vrsn_cd24,
                      icd_dgns_cd25,
                      icd_dgns_vrsn_cd25
from
    public.hospice_claims;                      

-- migrate data via INSERT from current HOSPICE_CLAIM_LINES table to HOSPICE_CLAIM_LINES_NEW table
--
${logic.hsql-only} insert into public.hospice_claim_lines_new (
${logic.hsql-only}    clm_id,
${logic.hsql-only}    clm_line_num,
${logic.hsql-only}    rev_cntr,
${logic.hsql-only}    rev_cntr_unit_cnt,
${logic.hsql-only}    rev_cntr_tot_chrg_amt,
${logic.hsql-only}    rev_cntr_rate_amt,
${logic.hsql-only}    rev_cntr_ncvrd_chrg_amt,
${logic.hsql-only}    rev_cntr_ddctbl_coinsrnc_cd,
${logic.hsql-only}    rev_cntr_bene_pmt_amt,
${logic.hsql-only}    rev_cntr_pmt_amt_amt,
${logic.hsql-only}    rev_cntr_prvdr_pmt_amt,
${logic.hsql-only}    rev_cntr_dt,
${logic.hsql-only}    rev_cntr_ndc_qty_qlfr_cd,
${logic.hsql-only}    rev_cntr_ndc_qty,
${logic.hsql-only}    hcpcs_cd,
${logic.hsql-only}    hcpcs_1st_mdfr_cd,
${logic.hsql-only}    hcpcs_2nd_mdfr_cd,
${logic.hsql-only}    rndrng_physn_npi,
${logic.hsql-only}    rndrng_physn_upin )
--
-- PSQL allows us to dynamically create a table via the
-- associated SELECT statement used to populate the table.
--
${logic.psql-only} create table public.hospice_claim_lines_new as
select
${logic.hsql-only}    convert(clm_id, SQL_BIGINT),
${logic.hsql-only}    convert(clm_line_num, SQL_SMALLINT),
${logic.psql-only}    cast(clm_id as bigint),
${logic.psql-only}    cast(clm_line_num as smallint),
                      rev_cntr,
                      rev_cntr_unit_cnt,
                      rev_cntr_tot_chrg_amt,
                      rev_cntr_rate_amt,
                      rev_cntr_ncvrd_chrg_amt,
                      rev_cntr_ddctbl_coinsrnc_cd,
                      rev_cntr_bene_pmt_amt,
                      rev_cntr_pmt_amt_amt,
                      rev_cntr_prvdr_pmt_amt,
                      rev_cntr_dt,
                      rev_cntr_ndc_qty_qlfr_cd,
                      rev_cntr_ndc_qty,
                      hcpcs_cd,
                      hcpcs_1st_mdfr_cd,
                      hcpcs_2nd_mdfr_cd,
                      rndrng_physn_npi,
                      rndrng_physn_upin
from
    public.hospice_claim_lines;
    
-- for PSQL need to define our not null constraints; for HSQL,
-- we explicitly defined a table structure before migrating data.
--
${logic.psql-only} alter table public.hospice_claims_new
${logic.psql-only}    alter column clm_id                       SET NOT NULL,
${logic.psql-only}    alter column bene_id                      SET NOT NULL,
${logic.psql-only}    alter column clm_grp_id                   SET NOT NULL,
${logic.psql-only}    alter column clm_from_dt                  SET NOT NULL,
${logic.psql-only}    alter column clm_thru_dt                  SET NOT NULL,
${logic.psql-only}    alter column final_action                 SET NOT NULL,
${logic.psql-only}    alter column clm_pmt_amt                  SET NOT NULL,
${logic.psql-only}    alter column clm_fac_type_cd              SET NOT NULL,
${logic.psql-only}    alter column clm_freq_cd                  SET NOT NULL,
${logic.psql-only}    alter column clm_srvc_clsfctn_type_cd     SET NOT NULL,
${logic.psql-only}    alter column clm_tot_chrg_amt             SET NOT NULL,
${logic.psql-only}    alter column clm_utlztn_day_cnt           SET NOT NULL,
${logic.psql-only}    alter column nch_clm_type_cd              SET NOT NULL,
${logic.psql-only}    alter column nch_near_line_rec_ident_cd   SET NOT NULL,
${logic.psql-only}    alter column nch_wkly_proc_dt             SET NOT NULL,
${logic.psql-only}    alter column nch_prmry_pyr_clm_pd_amt     SET NOT NULL,
${logic.psql-only}    alter column prvdr_num                    SET NOT NULL,
${logic.psql-only}    alter column prvdr_state_cd               SET NOT NULL,
${logic.psql-only}    alter column ptnt_dschrg_stus_cd          SET NOT NULL;

${logic.psql-only} alter table public.hospice_claim_lines_new
${logic.psql-only}    alter column clm_id                       SET NOT NULL,
${logic.psql-only}    alter column clm_line_num                 SET NOT NULL,
${logic.psql-only}    alter column rev_cntr                     SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_unit_cnt            SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_tot_chrg_amt        SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_rate_amt            SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_bene_pmt_amt        SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_pmt_amt_amt         SET NOT NULL,
${logic.psql-only}    alter column rev_cntr_prvdr_pmt_amt       SET NOT NULL;

-- for PSQL need to define our primary key    
${logic.psql-only} alter table public.hospice_claims_new
${logic.psql-only}     add CONSTRAINT hospice_claims_new_pkey PRIMARY KEY (clm_id);

-- for PSQL need to define our primary key    
${logic.psql-only} ALTER TABLE public.hospice_claim_lines_new
${logic.psql-only}     ADD CONSTRAINT hospice_claim_lines_new_pkey PRIMARY KEY (clm_id, clm_line_num);

-- define foreign key constraints between claim lineitems and a parent claims table.
ALTER TABLE IF EXISTS public.hospice_claim_lines_new
    ADD CONSTRAINT hospice_claim_lines_clm_id_to_hospice_claims_new FOREIGN KEY (clm_id)
        REFERENCES public.hospice_claims_new (clm_id);

-- create an index of the BENE_ID in parent claims table
CREATE INDEX IF NOT EXISTS hospice_claims_new_bene_id_idx
    ON public.hospice_claims_new (bene_id);
