#!/usr/bin/env groovy

pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccount: bfd
  volumes:
  - name: docker-socket
    emptyDir: {}
  containers:
  - name: docker
    image: docker:20.10-git
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    tty: true
  - name: docker-daemon
    image: docker:20.10-dind
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
"""
    }
  }
  options {
        buildDiscarder(logRotator(numToKeepStr: '15', daysToKeepStr: '30'))
  }
  stages {
    stage('Docker Build') {
      steps {
        container('docker') {
          // Install prerequisites
          sh 'apk add --no-cache aws-cli bash'

          // Address limitations resulting from CVE-2022-24767
          sh 'git config --global --add safe.directory "$WORKSPACE"'

          // Setup AWS Credentials
          script {
            awsAuth.assumeRole()
          }

          // Execute the existing build-push.sh script
          dir('ops/jenkins/bfd-availability-checker-build') {
            sh 'bash build-push.sh'
          }
        }
      }
    }
  }
}
