#!/usr/bin/env groovy

/**
 * <p>
 * This script will be run by Jenkins when building deploying apps and app AMIs to the traditional, non-ephemeral environments.
 * </p>
 */

// These variables are accessible throughout this file (except inside methods and classes).
def amiIds

pipeline {
    agent {
        kubernetes {
            defaultContainer 'bfd-cbc-build'
            yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccount: bfd
  containers:
  - name: bfd-cbc-build
    image: 'public.ecr.aws/c2o1d8s9/bfd-cbc-build:jdk17-mvn3-tfenv3-latest'
    command:
    - cat
    tty: true
    imagePullPolicy: Always
    resources:
      requests:
        memory: '16384Mi'
        cpu: '8000m'
      limits:
        memory: '16384Mi'
        cpu: '8000m'
"""
        }
    }

  parameters {
        booleanParam(name: 'verbose_mvn_logging',
        description: 'When true, `mvn` will produce verbose logs.',
        defaultValue: false)

        booleanParam(
        name: 'force_migrator_deployment',
        description: 'When true, force the migrator to deploy.',
        defaultValue: false
        )

        string(
        name: 'server_regression_image_override',
        description: 'Overrides the Docker image tag used when deploying the server-regression lambda',
        defaultValue: null
        )
  }

  stages {
    stage('Prepare') {
      steps {
        script {
            // Address limitations resulting from CVE-2022-24767
            sh 'git config --global --add safe.directory "$WORKSPACE"'

            // Get the current commit id
            gitCommitId = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()

            // Get the remote repo url. This assumes we are using git+https not git+ssh.
            gitRepoUrl = sh(returnStdout: true, script: 'git config --get remote.origin.url').trim().replaceAll(/\.git$/, '')

            // Load the child Jenkinsfiles.
            scriptForApps = load('apps/build.groovy')
            scriptForDeploys = load('ops/deploy-ccs.groovy')
        }
      }
    }

    /* This stage switches the gitBranchName (needed for our CCS downsream stages)
          value if the build is a PR as the BRANCH_NAME var is populated with the build
          name during PR builds.
    */
    stage('Set Branch Name') {
        steps {
          script {
            currentStage = env.STAGE_NAME
            if (env.BRANCH_NAME.startsWith('PR')) {
                gitBranchName = env.CHANGE_BRANCH
            } else {
                gitBranchName = env.BRANCH_NAME
            }
          }
        }
    }

    stage('Run Build Apps') {
      steps {
        script {
          def jobToRun = "bfd-build-apps/${env.BRANCH_NAME.replace('/', '%2F')}"

          build job:
            jobToRun,
            parameters: [
              booleanParam(name: "verbose_mvn_logging", value: "${params.verbose_mvn_logging}")
            ],
            wait: true
        }
      }
    }

    stage('Run Deploy To Test') {
      steps {
        script {
          def jobToRun = "bfd-deploy-apps/${env.BRANCH_NAME.replace('/', '%2F')}"

            awsAuth.assumeRole()

            // Find the most current AMI IDs (if any).
            amiIds = null
            amiIds = scriptForDeploys.findAmis()

          build job:
                jobToRun,
                parameters: [
                  string(name: "env", value: "test"),
                  string(name: "migrator_ami_override", value: "${amiIds.bfdMigratorAmiId}"),
                  string(name: "pipeline_ami_override", value: "${amiIds.bfdPipelineAmiId}"),
                  string(name: "server_ami", value: "${amiIds.bfdServerAmiId}"),
                  booleanParam(name: "force_migrator_deployment", value: "${params.force_migrator_deployment}"),
                  string(name: "server_regression_image_override", value: "${params.server_regression_image_override}")
                ],
                wait: true
        }
      }
    }

    stage('Run Deploy To Prod-SBX') {
      steps {
        script {
          def jobToRun = "bfd-deploy-apps/${env.BRANCH_NAME.replace('/', '%2F')}"

          awsAuth.assumeRole()

          build job:
                jobToRun,
                parameters: [
                  string(name: "env", value: "prod-sbx"),
                  string(name: "migrator_ami_override", value: "${amiIds.bfdMigratorAmiId}"),
                  string(name: "pipeline_ami_override", value: "${amiIds.bfdPipelineAmiId}"),
                  string(name: "server_ami", value: "${amiIds.bfdServerAmiId}"),
                  booleanParam(name: "force_migrator_deployment", value: "${params.force_migrator_deployment}"),
                  string(name: "server_regression_image_override", value: "${params.server_regression_image_override}")
                ],
                wait: true
        }
      }
    }

    stage('Run Deploy To PROD') {
      steps {
        script {
          def jobToRun = "bfd-deploy-apps/${env.BRANCH_NAME.replace('/', '%2F')}"

          awsAuth.assumeRole()

          build job:
                jobToRun,
                parameters: [
                  string(name: "env", value: "prod"),
                  string(name: "migrator_ami_override", value: "${amiIds.bfdMigratorAmiId}"),
                  string(name: "pipeline_ami_override", value: "${amiIds.bfdPipelineAmiId}"),
                  string(name: "server_ami", value: "${amiIds.bfdServerAmiId}"),
                  booleanParam(name: "force_migrator_deployment", value: "${params.force_migrator_deployment}"),
                  string(name: "server_regression_image_override", value: "${params.server_regression_image_override}")
                ],
                wait: true
        }
      }
    }
  }
}
