server:
  servlet:
    context-path: /matchboxv3
spring:
  datasource:
    url: 'jdbc:postgresql://matchbox-db:5432/matchbox'
    username: matchbox
    password: matchbox
    driverClassName: org.postgresql.Driver

    # database connection pool size
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.search.enabled: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
matchbox:
  fhir:
    context:
      displayIssuesAreWarnings: false
      txServer: http://localhost:8080/matchboxv3/tx
      onlyOneEngine: true
      fhirVersion: R4
      suppressR5: true
logging:
  level:
    ca.uhn.fhir: ERROR
    ca.uhn.fhir.rest.server.ResourceBinding: ERROR
    ch.ahdis.matchbox: DEBUG
hapi:
  fhir:
    fhir_version: R4
    mdm_enabled: false
    openapi_enabled: false
    narrative_enabled: false
    jpa:
      subscription_matching_enabled: false
      bulk_export_enabled: false
      dao_scheduling_enabled: false
      enforce_referential_integrity_on_delete: false
      enforce_referential_integrity_on_write: false

