[project]
name = "generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.3"
dependencies = [
  "faker>=37.1.0",
  "pandas>=3.0.2",
  "xlsxwriter>=3.2.5",
  "pyyaml>=6.0.2",
  "pydantic>=2.12.3",
  "tqdm>=4.67.1",
  "click>=8.3.1",
  "requests>=2.32.5",
  "cryptography>=50.0.0",
]

[project.scripts]
idr-extract = "idr_extract:main"


[build-system]
requires = ["uv_build<=0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "idr_model"
packages = ["src/idr_model", "src/idr_extract"]
