[project]
name = "idr-bfd-validator"
version = "0.1.0"
description = "Validates that data is correctly loaded incrementally from IDR"
readme = "README.md"
requires-python = ">=3.14.3"
dependencies = [
    "idr-pipeline",
    "anyio",
    "loguru",
    "pydantic-partial",
    "boto3",
    "click>=8.4.2",
]

[dependency-groups]
dev = [
    "boto3-stubs[sns]",
    "ruff",
    "uv>=0.11.15",
]

[tool.uv]
exclude-newer = "7 days"

[tool.uv.sources]
idr-pipeline = { path = "packages/idr-pipeline", editable = true }
loguru = { git = "https://github.com/Delgan/loguru", rev = "2a17be730e111cf874d0bf967c4c5da15b7e4670" }

[tool.ruff]
# Set the maximum line length to 100.
line-length = 100

[tool.ruff.lint]
extend-select = [
    "D",    # pydocstyle
    "E501",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    "ANN",
    "LOG",
    "G",
    "PT",
    "RSE",
    "PIE",
    "RET",
    "SLF",
    "ARG",
    "PTH",
    "PLE",
    "PLW",
    "PERF",
    "FURB",
    "RUF",
]
# Don't require docstrings
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D107"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.pyright]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"
