package gov.cms.bfd.server.ng.claim.model;

import gov.cms.bfd.server.ng.util.SystemUrls;
import java.util.Arrays;
import java.util.Optional;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.hl7.fhir.r4.model.CodeableConcept;
import org.hl7.fhir.r4.model.Coding;

/** Claim place of service codes. */
public sealed interface ClaimPlaceOfServiceCode
    permits ClaimPlaceOfServiceCode.Valid, ClaimPlaceOfServiceCode.Invalid {

  /**
   * Gets the code value.
   *
   * @return the code
   */
  String getCode();

  /**
   * Gets the display value.
   *
   * @return the display
   */
  String getDisplay();

  /**
   * Convert from a database code.
   *
   * @param code database code
   * @return claim place of service code
   */
  static Optional<ClaimPlaceOfServiceCode> fromCode(String code) {
    if (code == null || code.isBlank()) {
      return Optional.empty();
    }
    return Optional.of(
        Arrays.stream(Valid.values())
            .filter(v -> v.code.equals(code))
            .map(v -> (ClaimPlaceOfServiceCode) v)
            .findFirst()
            .orElseGet(() -> new Invalid(code)));
  }

  /**
   * Maps enum/record to FHIR spec.
   *
   * @return CodeableConcept
   */
  default CodeableConcept toFhir() {
    return new CodeableConcept(
        new Coding()
            .setSystem(SystemUrls.SYS_CLM_POS_CD)
            .setCode(getCode())
            .setDisplay(getDisplay()));
  }

  /** Valid place of service codes. */
  @AllArgsConstructor
  @Getter
  enum Valid implements ClaimPlaceOfServiceCode {
    /** 00 - Unassigned. */
    _00("00", "Unassigned"),
    /**
     * 01 - PHARMACY (EFFECTIVE OCTOBER 1, 2005)- A FACILITY OR LOCATION WHERE DRUGS AND OTHER
     * MEDICALLY RELATED ITEMS AND SERVICES ARE SOLD, DISPENSED, OR OTHERWISE PROVIDED DIRECTLY TO
     * PATIENTS.
     */
    _01("01", "Pharmacy"),
    /**
     * 02 - TELEHEALTH (EFFECTIVE JANUARY 1, 2022) - THE LOCATION WHERE HEALTH SERVICES AND HEALTH
     * RELATED SERVICES ARE PROVIDED OR RECEIVED, THROUGH TELECOMMUNICATION TECHNOLOGY. PATIENT IS
     * NOT LOCATED IN THEIR HOME WHEN RECEIVING HEALTH SERVICES OR HEALTH RELATED SERVICES THROUGH
     * TELECOMMUNICATION TECHNOLOGY.
     */
    _02("02", "Telehealth Provided Other than in Patient’s Home"),
    /** 03 - SCHOOL (EFFECTIVE JANUARY 1, 2003) - A FACILITY WHOSE PRIMARY PURPOSE IS EDUCATION. */
    _03("03", "School"),
    /**
     * 04 - HOMELESS SHELTER (EFFECTIVE JANUARY 1, 2003) A FACILITY OR LOCATION WHOSE PRIMARY
     * PURPOSE IS TO PROVIDE TEMPORARY HOUSING TO HOMELESS INDIVIDUALS (E.G., EMERGENCY SHELTERS,
     * INDIVIDUAL OR FAMILY SHELTERS).
     */
    _04("04", "Homeless Shelter"),
    /**
     * 05 - INDIAN HEALTH SERVICE FREE-STANDING FACILITY (EFFECTIVE JANUARY 1, 2003) A FACILITY OR
     * LOCATION, OWNED AND OPERATED BY THE INDIAN HEALTH SERVICE, WHICH PROVIDES DIAGNOSTIC,
     * THERAPEUTIC (SURGICAL AND NONSURGICAL), AND REHABILITATION SERVICES TO AMERICAN INDIANS AND
     * ALASKA NATIVES WHO DO NOT REQUIRE HOSPITALIZATION.
     */
    _05("05", "Indian Health Service Free-standing Facility"),
    /**
     * 06 - INDIAN HEALTH SERVICE PROVIDER-BASED FACILITY (EFFECTIVE JANUARY 1, 2003) A FACILITY OR
     * LOCATION, OWNED AND OPERATED BY THE INDIAN HEALTH SERVICE, WHICH PROVIDES DIAGNOSTIC,
     * THERAPEUTIC (SURGICAL AND NONSURGICAL), AND REHABILITATION SERVICES RENDERED BY, OR UNDER THE
     * SUPERVISION OF, PHYSICIANS TO AMERICAN INDIANS AND ALASKA NATIVES ADMITTED A S INPATIENTS OR
     * OUTPATIENTS.
     */
    _06("06", "Indian Health Service Provider-based Facility"),
    /**
     * 07 - TRIBAL 638 FREE-STANDING FACILITY (EFFECTIVE JANUARY 1, 2003) A FACILITY OR LOCATION
     * OWNED AND OPERATED BY A FEDERALLY RECOGNIZED AMERICAN INDIAN OR ALASKA NATIVE TRIBE OR TRIBAL
     * ORGANIZATION UNDER A 638 AGREEMENT, WHICH PROVIDES DIAGNOSTIC, THERAPEUTIC (SURGICAL AND
     * NONSURGICAL), AND REHABILITATION SERVICES TO TRIBAL MEMBERS WHO DO NOT REQUIRE
     * HOSPITIALIZATION.
     */
    _07("07", "Tribal 638 Free-standing Facility"),
    /**
     * 08 - TRIBAL 638 PROVIDER-BASED FACILITY (EFFECTIVE JANUARY 1, 2003) A FACILITY OR LOCATION
     * OWNED AND OPERATED BY A FEDERALLY RECOGNIZED AMERICAN INDIAN OR ALASKA NATIVE TRIBE OR TRIBAL
     * ORGANIZATION UNDER A 638 AGREEMENT, WHICH PROVIDES DIAGNOSTIC, THERAPEUTIC (SURGICAL AND
     * NONSURGICAL), AND REHABILITATION SERVICES TO TRIBAL MEMBERS ADMITTED AS INPATIENTS OR
     * OUTPATIENTS.
     */
    _08("08", "Tribal 638 Provider-based Facility"),
    /**
     * 09 - PRISON/CORRECTIONAL FACILITY (EFFECTIVE JULY 1, 2006) A PRISON, JAIL, REFORMATORY, WORK
     * FARM, DETENTION CENTER, OR ANY OTHER SIMILAR FACILITY MAINTAINED BY EITHER FEDERAL, STATE OR
     * LOCAL AUTHORITIES FOR THE PURPOSE OF CONFINEMENT OR REHABILITATION OF ADULT OR JUVENILE
     * CRIMINAL OFFENDERS.
     */
    _09("09", "Prison/ Correctional Facility"),
    /**
     * 10 - TELEHEALTH (EFFECTIVE JANUARY 1, 2022) - THE LOCATION WHERE HEALTH SERVICES AND HEALTH
     * RELATED SERVICES ARE PROVIDED OR RECEIVED THROUGH TELECOMMUNICATION TECHNOLOGY. PATIENT IS
     * LOCATED IN THEIR HOME (WHICH IS A LOCATION OTHER THAN A HOSPITAL OR OTHER FACILITY WHERE THE
     * PATIENT RECEIVES CARE IN A PRIVATE RESIDENCE) WHEN RECEIVING HEALTH SERVICES OR HEALTH
     * RELATED SERVICES THROUGH TELECOMMUNICATION TECHNOLOGY.
     */
    _10("10", "Telehealth Provided in Patient’s Home"),
    /**
     * 11 - OFFICE - LOCATION, OTHER THAN A HOSPITAL, SKILLED NURSING FACILITY (SNF), MILITARY
     * TREATMENT FACILITY, COMMUNITY HEALTH CENTER, STATE OR LOCAL PUBLIC HEALTH CLINIC, OR
     * INTERMEDIATE CARE FACILITY (ICF), WHERE THE HEALTH PROFESSIONAL ROUTINELY PROVIDES HEALTH
     * EXAMINATIONS, DIAGNOSIS, AND TREATMENT OF ILLNESS OR INJURY ON AN AMBULATORY BASIS.
     */
    _11("11", "Office"),
    /**
     * 12 - HOME - LOCATION, OTHER THAN A HOSPITAL OR OTHER FACILITY, WHERE THE PATIENT RECEIVES
     * CARE IN A PRIVATE RESIDENCE.
     */
    _12("12", "Home"),
    /**
     * 13 - ASSISTED LIVING FACILITY (EFFECTIVE OCTOBER 1, 2003)- CONGREGATE RESIDENTIAL FACILITY
     * WITH SELF-CONTAINED LIVING UNITS PROVIDING ASSESSMENT OF EACH RESIDENT’S NEEDS AND ON-SITE
     * SUPPORT 24 HOURS A DAY, 7 DAYS A WEEK, WITH THE CAPACITY TO DELIVER OR ARRANGE FOR SERVICES
     * INCLUDING SOME HEALTH CARE AND OTHER SERVICES.
     */
    _13("13", "Assisted Living Facility"),
    /**
     * 14 - GROUP HOME (CODE EFFECTIVE, OCTOBER 1, 2003; DESCRIPTION REVISED,EFFECTIVE APRIL 1,
     * 2004) - A RESIDENCE, WITH SHARED LIVING AREAS, WHERE CLIENTS RECEIVE SUPERVISION AND OTHER
     * SERVICES SUCH AS SOCIAL AND/OR BEHAVIORAL SERVICES, CUSTODIAL SERVICE, AND MINIMAL SERVICES
     * (E.G., MEDICATION ADMINISTRATION).
     */
    _14("14", "Group Home"),
    /**
     * 15 - MOBILE UNIT (EFFECTIVE JANUARY 1, 2003)- A FACILITY/UNIT THAT MOVES FROM PLACE-TO-PLACE
     * EQUIPPED TO PROVIDE PREVENTIVE, SCREENING, DIAGNOSTIC, AND/OR TREATMENT SERVICES.
     */
    _15("15", "Mobile Unit"),
    /**
     * 16 - TEMPORARY LODGING (EFFECTIVE APRIL 1, 2008) - A SHORT-TERM ACCOMMODATION SUCH AS A
     * HOTEL, CAMP GROUND, HOSTEL, CRUISE SHIP OR RESORT WHERE THE PATIENT RECEIVES CARE, AND WHICH
     * IS NOT IDENTIFIED BY ANY OTHER POS CODE.
     */
    _16("16", "Temporary Lodging"),
    /**
     * 17 - WALK-IN RETAIL HEALTH CLINIC (EFFECTIVE NO LATER THAN MAY 1, 2010) - A WALK-IN HEALTH
     * CLINIC, OTHER THAN AN OFFICE, URGENT CARE FACILITY, PHARMACY OR INDEPENDENT CLINIC AND NOT
     * DESCRIBED BY ANY OTHER PLACE OF SERVICE CODE, THAT IS LOCATED WITHIN A RETAIL OPERATION AND
     * PROVIDES, ON AN AMBULATORY BASIS, PREVENTIVE AND PRIMARY CARE SERVICES.
     */
    _17("17", "Walk-in Retail Health Clinic"),
    /**
     * 18 - PLACE OF EMPLOYMENT/WORKSITE (EFFECTIVE NO LATER THAN MAY 1, 2013) - A LOCATION, NOT
     * DESCRIBED BY ANY OTHER POS CODE, OWNED OR OPERATED BY A PUBLIC OR PRIVATE ENTITY WHERE THE
     * PATIENT IS EMPLOYED, AND WHERE A HEALTH PROFESSIONAL PROVIDES ON-GOING OR EPISODIC
     * OCCUPATIONAL MEDICAL, THERAPEUTIC OR REHABILITATIVE SERVICES TO THE INDIVIDUAL.
     */
    _18("18", "Place of Employment-Worksite"),
    /**
     * 19 - OFF CAMPUS-OUTPATIENT HOSPITAL (EFFECTIVE JANUARY 1, 2016) - A PORTION OF AN OFF-CAMPUS
     * HOSPITAL PROVIDER BASED DEPARTMENT WHICH PROVIDES DIAGNOSTIC, THERAPEUTIC (BOTH SURGICAL AND
     * NONSURGICAL), AND REHABILITATION SERVICES TO SICK OR INJURED PERSONS WHO DO NOT REQUIRE
     * HOSPITALIZATION OR INSTITUTIONALIZATION.
     */
    _19("19", "Off Campus-Outpatient Hospital"),
    /**
     * 20 - URGENT CARE FACILITY (EFFECTIVE JANUARY 1, 2003) - LOCATION, DISTINCT FROM A HOSPITAL
     * EMERGENCY ROOM, AN OFFICE, OR A CLINIC, WHOSE PURPOSE IS TO DIAGNOSE AND TREAT ILLNESS OR
     * INJURY FOR UNSCHEDULED, AMBULATORY PATIENTS SEEKING IMMEDIATE MEDICAL ATTENTION.
     */
    _20("20", "Urgent Care Facility"),
    /**
     * 21 - INPATIENT HOSPITAL - A FACILITY, OTHER THAN PSYCHIATRIC, WHICH PRIMARILY PROVIDES
     * DIAGNOSTIC, THERAPEUTIC (BOTH SURGICAL AND NONSURGICAL), AND REHABILITATION SERVICES BY, OR
     * UNDER, THE SUPERVISION OF PHYSICIANS TO PATIENTS ADMITTED FOR A VARIETY OF MEDICAL
     * CONDITIONS.
     */
    _21("21", "Inpatient Hospital"),
    /**
     * 22 - ON CAMPUS-OUTPATIENT HOSPITAL (DESCRIPTION REVISED JANUARY 1, 2016) - A PORTION OF A
     * HOSPITAL’S MAIN CAMPUS WHICH PROVIDES DIAGNOSTIC, THERAPEUTIC (BOTH SURGICAL AND
     * NONSURGICAL), AND REHABILITATION SERVICES TO SICK OR INJURED PERSONS WHO DO NOT REQUIRE
     * HOSPITALIZATION OR INSTITUTIONALIZATION.
     */
    _22("22", "On Campus-Outpatient Hospital"),
    /**
     * 23 - EMERGENCY ROOM-HOSPITAL- A PORTION OF A HOSPITAL WHERE EMERGENCY DIAGNOSIS AND TREATMENT
     * OF ILLNESS OR INJURY IS PROVIDED.
     */
    _23("23", "Emergency Room – Hospital"),
    /**
     * 24 - AMBULATORY SURGICAL CENTER - A FREESTANDING FACILITY, OTHER THAN A PHYSICIAN'S OFFICE,
     * WHERE SURGICAL AND DIAGNOSTIC SERVICES ARE PROVIDED ON AN AMBULATORY BASIS.
     */
    _24("24", "Ambulatory Surgical Center"),
    /**
     * 25 - BIRTHING CENTER - A FACILITY, OTHER THAN A HOSPITAL'S MATERNITY FACILITIES OR A
     * PHYSICIAN'S OFFICE, WHICH PROVIDES A SETTING FOR LABOR, DELIVERY, AND IMMEDIATE POSTPARTUM
     * CARE AS WELL AS IMMEDIATE CARE OF NEWBORN INFANTS.
     */
    _25("25", "Birthing Center"),
    /**
     * 26 - MILITARY TREATMENT FACILITY - A MEDICAL FACILITY OPERATED BY ONE OR MORE OF THE
     * UNIFORMED SERVICES. MILITARY TREATMENT FACILITY (MTF) ALSO REFERS TO CERTAIN FORMER U.S.
     * PUBLIC HEALTH SERVICE (USPHS) FACILITIES NOW DESIGNATED AS UNIFORMED SERVICE TREATMENT
     * FACILITIES (USTF).
     */
    _26("26", "Military Treatment Facility"),
    /** 27 - OUTREACH SITE/STREET (EFF. 10/1/23). */
    _27("27", "Outreach Site/ Street"),
    /** 28 - Unassigned. */
    _28("28", "Unassigned"),
    /** 29 - Unassigned. */
    _29("29", "Unassigned"),
    /** 30 - Unassigned. */
    _30("30", "Unassigned"),
    /**
     * 31 - SKILLED NURSING FACILITY - A FACILITY WHICH PRIMARILY PROVIDES INPATIENT SKILLED NURSING
     * CARE AND RELATED SERVICES TO PATIENTS WHO REQUIRE MEDICAL, NURSING, OR REHABILITATIVE
     * SERVICES BUT DOES NOT PROVIDE THE LEVEL OF CARE OR TREATMENT AVAILABLE IN A HOSPITAL.
     */
    _31("31", "Skilled Nursing Facility"),
    /**
     * 32 - NURSING FACILITY- A FACILITY WHICH PRIMARILY PROVIDES TO RESIDENTS SKILLED NURSING CARE
     * AND RELATED SERVICES FOR THE REHABILITATION OF INJURED, DISABLED, OR SICK PERSONS, OR, ON A
     * REGULAR BASIS, HEALTH-RELATED CARE SERVICES ABOVE THE LEVEL OF CUSTODIAL CARE TO OTHER THAN
     * INDIVIDUALS WITH INTELLECTUAL DISABILITIES.
     */
    _32("32", "Nursing Facility"),
    /**
     * 33 - CUSTODIAL CARE FACILITY - A FACILITY WHICH PROVIDES ROOM, BOARD AND OTHER PERSONAL
     * ASSISTANCE SERVICES, GENERALLY ON A LONGTERM BASIS, AND WHICH DOES NOT INCLUDE A MEDICAL
     * COMPONENT.
     */
    _33("33", "Custodial Care Facility"),
    /**
     * 34 - HOSPICE - A FACILITY, OTHER THAN A PATIENT'S HOME, IN WHICH PALLIATIVE AND SUPPORTIVE
     * CARE FOR TERMINALLY ILL PATIENTS AND THEIR FAMILIES ARE PROVIDED.
     */
    _34("34", "Hospice"),
    /** 35 - Unassigned. */
    _35("35", "Unassigned"),
    /** 36 - Unassigned. */
    _36("36", "Unassigned"),
    /** 37 - Unassigned. */
    _37("37", "Unassigned"),
    /** 38 - Unassigned. */
    _38("38", "Unassigned"),
    /** 39 - Unassigned. */
    _39("39", "Unassigned"),
    /** 40 - Unassigned. */
    _40("40", "Unassigned"),
    /**
     * 41 - AMBULANCE—LAND A LAND VEHICLE SPECIFICALLY DESIGNED, EQUIPPED AND STAFFED FOR LIFESAVING
     * AND TRANSPORTING THE SICK OR INJURED.
     */
    _41("41", "Ambulance - Land"),
    /**
     * 42 - AMBULANCE—AIR OR WATER AN AIR OR WATER VEHICLE SPECIFICALLY DESIGNED, EQUIPPED AND
     * STAFFED FOR LIFESAVING AND TRANSPORTING THE SICK OR INJURED.
     */
    _42("42", "Ambulance – Air or Water"),
    /** 43 - Unassigned. */
    _43("43", "Unassigned"),
    /** 44 - Unassigned. */
    _44("44", "Unassigned"),
    /** 45 - Unassigned. */
    _45("45", "Unassigned"),
    /** 46 - Unassigned. */
    _46("46", "Unassigned"),
    /** 47 - Unassigned. */
    _47("47", "Unassigned"),
    /** 48 - Unassigned. */
    _48("48", "Unassigned"),
    /**
     * 49 - INDEPENDENT CLINIC (EFFECTIVE OCTOBER 1, 2003) - A LOCATION, NOT PART OF A HOSPITAL AND
     * NOT DESCRIBED BY ANY OTHER PLACE OF SERVICE CODE, THAT IS ORGANIZED AND OPERATED TO PROVIDE
     * PREVENTIVE, DIAGNOSTIC, THERAPEUTIC, REHABILITATIVE, OR PALLIATIVE SERVICES TO OUTPATIENTS
     * ONLY.
     */
    _49("49", "Independent Clinic"),
    /**
     * 50 - FEDERALLY QUALIFIED HEALTH CENTER - A FACILITY LOCATED IN A MEDICALLY UNDERSERVED AREA
     * THAT PROVIDES MEDICARE BENEFICIARIES PREVENTIVE PRIMARY MEDICAL CARE UNDER THE GENERAL
     * DIRECTION OF A PHYSICIAN.
     */
    _50("50", "Federally Qualified Health Center"),
    /**
     * 51 - INPATIENT PSYCHIATRIC FACILITY - A FACILITY THAT PROVIDES INPATIENT PSYCHIATRIC SERVICES
     * FOR THE DIAGNOSIS AND TREATMENT OF MENTAL ILLNESS ON A 24-HOUR BASIS, BY OR UNDER THE
     * SUPERVISION OF A PHYSICIAN.
     */
    _51("51", "Inpatient Psychiatric Facility"),
    /**
     * 52 - PSYCHIATRIC FACILITY-PARTIAL HOSPITALIZATION - A FACILITY FOR THE DIAGNOSIS AND
     * TREATMENT OF MENTAL ILLNESS THAT PROVIDES A PLANNED THERAPEUTIC PROGRAM FOR PATIENTS WHO DO
     * NOT REQUIRE FULL TIME HOSPITALIZATION, BUT WHO NEED BROADER PROGRAMS THAN ARE POSSIBLE FROM
     * OUTPATIENT VISITS TO A HOSPITAL-BASED OR HOSPITAL-AFFILIATED FACILITY.
     */
    _52("52", "Psychiatric Facility-Partial Hospitalization"),
    /**
     * 53 - COMMUNITY MENTAL HEALTH CENTER - A FACILITY THAT PROVIDES THE FOLLOWING SERVICES:
     * OUTPATIENT SERVICES, INCLUDING SPECIALIZED OUTPATIENT SERVICES FOR CHILDREN, THE ELDERLY,
     * INDIVIDUALS WHO ARE CHRONICALLY ILL, AND RESIDENTS OF THE CMHC’S MENTAL HEALTH SERVICES AREA
     * WHO HAVE BEEN DISCHARGED FROM INPATIENT TREATMENT AT A MENTAL HEALTH FACILITY; 24 HOUR A DAY
     * EMERGENCY CARE SERVICES; DAY TREATMENT, OTHER PARTIAL HOSPITALIZATION SERVICES, OR
     * PSYCHOSOCIAL REHABILITATION SERVICES; SCREENING FOR PATIENTS BEING CONSIDERED FOR ADMISSION
     * TO STATE MENTAL HEALTH FACILITIES TO DETERMINE THE APPROPRIATENESS OF SUCH ADMISSION; AND
     * CONSULTATION AND EDUCATION SERVICES.
     */
    _53("53", "Community Mental Health Center"),
    /**
     * 54 - INTERMEDIATE CARE FACILITY/INDIVIDUALS WITH INTELLECTUAL DISABILITIES - A FACILITY WHICH
     * PRIMARILY PROVIDES HEALTH-RELATED CARE AND SERVICES ABOVE THE LEVEL OF CUSTODIAL CARE TO
     * INDIVIDUALS BUT DOES NOT PROVIDE THE LEVEL OF CARE OR TREATMENT AVAILABLE IN A HOSPITAL OR
     * SNF.
     */
    _54("54", "Intermediate Care Facility/ Individuals with Intellectual Disabilities"),
    /**
     * 55 - RESIDENTIAL SUBSTANCE ABUSE TREATMENT FACILITY - A FACILITY WHICH PROVIDES TREATMENT FOR
     * SUBSTANCE (ALCOHOL AND DRUG) ABUSE TO LIVE-IN RESIDENTS WHO DO NOT REQUIRE ACUTE MEDICAL
     * CARE. SERVICES INCLUDE INDIVIDUAL AND GROUP THERAPY AND COUNSELING, FAMILY COUNSELING,
     * LABORATORY TESTS, DRUGS AND SUPPLIES, PSYCHOLOGICAL TESTING, AND ROOM AND BOARD.
     */
    _55("55", "Residential Substance Abuse Treatment Facility"),
    /**
     * 56 - PSYCHIATRIC RESIDENTIAL TREATMENT CENTER - A FACILITY OR DISTINCT PART OF A FACILITY FOR
     * PSYCHIATRIC CARE WHICH PROVIDES A TOTAL 24-HOUR THERAPEUTICALLY PLANNED AND PROFESSIONALLY
     * STAFFED GROUP LIVING AND LEARNING ENVIRONMENT.
     */
    _56("56", "Psychiatric Residential Treatment Center"),
    /**
     * 57 - NON-RESIDENTIAL SUBSTANCE ABUSE TREATMENT FACILITY (OCTOBER 1, 2003) - A LOCATION WHICH
     * PROVIDES TREATMENT FOR SUBSTANCE (ALCOHOL AND DRUG) ABUSE ON AN AMBULATORY BASIS. SERVICES
     * INCLUDE INDIVIDUAL AND GROUP THERAPY AND COUNSELING, FAMILY COUNSELING, LABORATORY TESTS,
     * DRUGS AND SUPPLIES, AND PSYCHOLOGICAL TESTING.
     */
    _57("57", "Non-residential Substance Abuse Treatment Facility"),
    /** 58 - NON-RESIDENTIAL OPIOID TREATMENT FACILITY. */
    _58("58", "Non-residential Opioid Treatment Facility"),
    /** 59 - Unassigned. */
    _59("59", "Unassigned"),
    /**
     * 60 - MASS IMMUNIZATION CENTER - A LOCATION WHERE PROVIDERS ADMINISTER PNEUMOCOCCAL PNEUMONIA
     * AND INFLUENZA VIRUS VACCINATIONS AND SUBMIT THESE SERVICES AS ELECTRONIC MEDIA CLAIMS, PAPER
     * CLAIMS, OR USING THE ROSTER BILLING METHOD. THIS GENERALLY TAKES PLACE IN A MASS IMMUNIZATION
     * SETTING, SUCH AS, A PUBLIC HEALTH CENTER, PHARMACY, OR MALL BUT MAY INCLUDE A PHYSICIAN
     * OFFICE SETTING.
     */
    _60("60", "Mass Immunization Center"),
    /**
     * 61 - COMPREHENSIVE INPATIENT REHABILITATION FACILITY - A FACILITY THAT PROVIDES COMPREHENSIVE
     * REHABILITATION SERVICES UNDER THE SUPERVISION OF A PHYSICIAN TO INPATIENTS WITH PHYSICAL
     * DISABILITIES. SERVICES INCLUDE PHYSICAL THERAPY, OCCUPATIONAL THERAPY, SPEECH PATHOLOGY,
     * SOCIAL OR PSYCHOLOGICAL SERVICES, AND ORTHOTICS AND PROSTHETICS SERVICES.
     */
    _61("61", "Comprehensive Inpatient Rehabilitation Facility"),
    /**
     * 62 - COMPREHENSIVE OUTPATIENT REHABILITATION FACILITY A FACILITY THAT PROVIDES COMPREHENSIVE
     * REHABILITATION SERVICES UNDER THE SUPERVISION OF A PHYSICIAN TO OUTPATIENTS WITH PHYSICAL
     * DISABILITIES. SERVICES INCLUDE PHYSICAL THERAPY, OCCUPATIONAL THERAPY, AND SPEECH PATHOLOGY
     * SERVICES.
     */
    _62("62", "Comprehensive Outpatient Rehabilitation Facility"),
    /** 63 - Unassigned. */
    _63("63", "Unassigned"),
    /** 64 - Unassigned. */
    _64("64", "Unassigned"),
    /**
     * 65 - END-STAGE RENAL DISEASE TREATMENT FACILITY - A FACILITY OTHER THAN A HOSPITAL, WHICH
     * PROVIDES DIALYSIS TREATMENT, MAINTENANCE, AND/OR TRAINING TO PATIENTS OR CAREGIVERS ON AN
     * AMBULATORY OR HOME-CARE BASIS.
     */
    _65("65", "End-Stage Renal Disease Treatment Facility"),
    /** 66 - PROGRAMS OF ALL INCLUSIVE CARE FOR THE ELDERLY (PACE) CENTER. */
    _66("66", "Programs of All-Inclusive Care for the Elderly (PACE) Center"),
    /** 67 - Unassigned. */
    _67("67", "Unassigned"),
    /** 68 - Unassigned. */
    _68("68", "Unassigned"),
    /** 69 - Unassigned. */
    _69("69", "Unassigned"),
    /** 70 - Unassigned. */
    _70("70", "Unassigned"),
    /**
     * 71 - STATE OR LOCAL PUBLIC HEALTH CLINIC - A FACILITY MAINTAINED BY EITHER STATE OR LOCAL
     * HEALTH DEPARTMENTS THAT PROVIDES AMBULATORY PRIMARY MEDICAL CARE UNDER THE GENERAL DIRECTION
     * OF A PHYSICIAN.
     */
    _71("71", "Public Health Clinic"),
    /**
     * 72 - RURAL HEALTH CLINIC - A CERTIFIED FACILITY WHICH IS LOCATED IN A RURAL MEDICALLY
     * UNDERSERVED AREA THAT PROVIDES AMBULATORY PRIMARY MEDICAL CARE UNDER THE GENERAL DIRECTION OF
     * A PHYSICIAN.
     */
    _72("72", "Rural Health Clinic"),
    /** 73 - Unassigned. */
    _73("73", "Unassigned"),
    /** 74 - Unassigned. */
    _74("74", "Unassigned"),
    /** 75 - Unassigned. */
    _75("75", "Unassigned"),
    /** 76 - Unassigned. */
    _76("76", "Unassigned"),
    /** 77 - Unassigned. */
    _77("77", "Unassigned"),
    /** 78 - Unassigned. */
    _78("78", "Unassigned"),
    /** 79 - Unassigned. */
    _79("79", "Unassigned"),
    /** 80 - Unassigned. */
    _80("80", "Unassigned"),
    /**
     * 81 - INDEPENDENT LABORATORY - A LABORATORY CERTIFIED TO PERFORM DIAGNOSTIC AND/OR CLINICAL
     * TESTS INDEPENDENT OF AN INSTITUTION OR A PHYSICIAN'S OFFICE.
     */
    _81("81", "Independent Laboratory"),
    /** 82 - Unassigned. */
    _82("82", "Unassigned"),
    /** 83 - Unassigned. */
    _83("83", "Unassigned"),
    /** 84 - Unassigned. */
    _84("84", "Unassigned"),
    /** 85 - Unassigned. */
    _85("85", "Unassigned"),
    /** 86 - Unassigned. */
    _86("86", "Unassigned"),
    /** 87 - Unassigned. */
    _87("87", "Unassigned"),
    /** 88 - Unassigned. */
    _88("88", "Unassigned"),
    /** 89 - Unassigned. */
    _89("89", "Unassigned"),
    /** 90 - Unassigned. */
    _90("90", "Unassigned"),
    /** 91 - Unassigned. */
    _91("91", "Unassigned"),
    /** 92 - Unassigned. */
    _92("92", "Unassigned"),
    /** 93 - Unassigned. */
    _93("93", "Unassigned"),
    /** 94 - Unassigned. */
    _94("94", "Unassigned"),
    /** 95 - Unassigned. */
    _95("95", "Unassigned"),
    /** 96 - Unassigned. */
    _96("96", "Unassigned"),
    /** 97 - Unassigned. */
    _97("97", "Unassigned"),
    /** 98 - Unassigned. */
    _98("98", "Unassigned"),
    /** 99 - OTHER PLACE OF SERVICE - OTHER PLACE OF SERVICE NOT IDENTIFIED ABOVE. */
    _99("99", "Other Place of Service");

    private final String code;
    private final String display;
  }

  /** Captures unknown/invalid codes. */
  record Invalid(String code) implements ClaimPlaceOfServiceCode {
    @Override
    public String getDisplay() {
      return "";
    }

    @Override
    public String getCode() {
      return code;
    }
  }
}
