package gov.cms.bfd.server.ng.claim.model;

import gov.cms.bfd.server.ng.util.SystemUrls;
import java.util.Arrays;
import java.util.Optional;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.hl7.fhir.r4.model.CodeableConcept;
import org.hl7.fhir.r4.model.Coding;

/**
 * Revenue centers. Suppress SonarQube warning that constant names should comply with naming
 * conventions
 */
@AllArgsConstructor
@Getter
@SuppressWarnings("java:S115")
public enum ClaimLineRevenueCenterCode {
  /** 0001 - TOTAL CHARGE. */
  _0001("0001", "TOTAL CHARGE"),
  /**
   * 0022 - HEALTH INSURANCE - PROSPECTIVE PAYMENT SYSTEM (HIPPS) - SKILLED NURSING FACILITY PPS.
   */
  _0022(
      "0022",
      "HEALTH INSURANCE - PROSPECTIVE PAYMENT SYSTEM (HIPPS) - SKILLED NURSING FACILITY PPS"),
  /** 0023 - HEALTH INSURANCE - PROSPECTIVE PAYMENT SYSTEM (HIPPS) - HOME HEALTH PPS. */
  _0023("0023", "HEALTH INSURANCE - PROSPECTIVE PAYMENT SYSTEM (HIPPS) - HOME HEALTH PPS"),
  /** 0024 - HEALTH INSURANCE - PROSPECTIVE PAYMENT SYSTEM (HIPPS)/INPATIENT REHAB FACILITY PPS. */
  _0024(
      "0024", "HEALTH INSURANCE - PROSPECTIVE PAYMENT SYSTEM (HIPPS)/INPATIENT REHAB FACILITY PPS"),
  /** 0100 - ALL INCLUSIVE RATE - ALL-INCLUSIVE ROOM AND BOARD PLUS ANCILLARY. */
  _0100("0100", "ALL INCLUSIVE RATE - ALL-INCLUSIVE ROOM AND BOARD PLUS ANCILLARY"),
  /** 0101 - ALL INCLUSIVE RATE - ALL-INCLUSIVE ROOM AND BOARD. */
  _0101("0101", "ALL INCLUSIVE RATE - ALL-INCLUSIVE ROOM AND BOARD"),
  /** 0110 - ROOM &amp; BOARD - PRIVATE (ONE BED) - GENERAL CLASSIFICATION. */
  _0110("0110", "ROOM & BOARD - PRIVATE (ONE BED) - GENERAL CLASSIFICATION"),
  /** 0111 - ROOM &amp; BOARD - PRIVATE (ONE BED) - MEDICAL/SURGICAL/GYN. */
  _0111("0111", "ROOM & BOARD - PRIVATE (ONE BED) - MEDICAL/SURGICAL/GYN"),
  /** 0112 - ROOM &amp; BOARD - PRIVATE (ONE BED) - OBSTETRICS (OB). */
  _0112("0112", "ROOM & BOARD - PRIVATE (ONE BED) - OBSTETRICS (OB)"),
  /** 0113 - ROOM &amp; BOARD - PRIVATE (ONE BED) - PEDIATRIC. */
  _0113("0113", "ROOM & BOARD - PRIVATE (ONE BED) - PEDIATRIC"),
  /** 0114 - ROOM &amp; BOARD - PRIVATE (ONE BED) - PSYCHIATRIC. */
  _0114("0114", "ROOM & BOARD - PRIVATE (ONE BED) - PSYCHIATRIC"),
  /** 0115 - ROOM &amp; BOARD - PRIVATE (ONE BED) - HOSPICE. */
  _0115("0115", "ROOM & BOARD - PRIVATE (ONE BED) - HOSPICE"),
  /** 0116 - ROOM &amp; BOARD - PRIVATE (ONE BED) - DETOXIFICATION. */
  _0116("0116", "ROOM & BOARD - PRIVATE (ONE BED) - DETOXIFICATION"),
  /** 0117 - ROOM &amp; BOARD - PRIVATE (ONE BED) - ONCOLOGY. */
  _0117("0117", "ROOM & BOARD - PRIVATE (ONE BED) - ONCOLOGY"),
  /** 0118 - ROOM &amp; BOARD - PRIVATE (ONE BED) - REHABILITATION. */
  _0118("0118", "ROOM & BOARD - PRIVATE (ONE BED) - REHABILITATION"),
  /** 0119 - ROOM &amp; BOARD - PRIVATE (ONE BED) - OTHER. */
  _0119("0119", "ROOM & BOARD - PRIVATE (ONE BED) - OTHER"),
  /** 0120 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - GENERAL CLASSIFICATION. */
  _0120("0120", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - GENERAL CLASSIFICATION"),
  /** 0121 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - MEDICAL/SURGICAL/GYN. */
  _0121("0121", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - MEDICAL/SURGICAL/GYN"),
  /** 0122 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - OBSTETRICS (OB). */
  _0122("0122", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - OBSTETRICS (OB)"),
  /** 0123 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - PEDIATRIC. */
  _0123("0123", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - PEDIATRIC"),
  /** 0124 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - PSYCHIATRIC. */
  _0124("0124", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - PSYCHIATRIC"),
  /** 0125 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - HOSPICE. */
  _0125("0125", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - HOSPICE"),
  /** 0126 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - DETOXIFICATION. */
  _0126("0126", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - DETOXIFICATION"),
  /** 0127 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - ONCOLOGY. */
  _0127("0127", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - ONCOLOGY"),
  /** 0128 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - REHABILITATION. */
  _0128("0128", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - REHABILITATION"),
  /** 0129 - ROOM &amp; BOARD - SEMI-PRIVATE TWO BEDS - OTHER. */
  _0129("0129", "ROOM & BOARD - SEMI-PRIVATE TWO BEDS - OTHER"),
  /** 0130 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - GENERAL CLASSIFICATION. */
  _0130("0130", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - GENERAL CLASSIFICATION"),
  /** 0131 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - MEDICAL/SURGICAL/GYN. */
  _0131("0131", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - MEDICAL/SURGICAL/GYN"),
  /** 0132 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - OBSTETRICS (OB). */
  _0132("0132", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - OBSTETRICS (OB)"),
  /** 0133 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - PEDIATRIC. */
  _0133("0133", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - PEDIATRIC"),
  /** 0134 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - PSYCHIATRIC. */
  _0134("0134", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - PSYCHIATRIC"),
  /** 0135 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - HOSPICE. */
  _0135("0135", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - HOSPICE"),
  /** 0136 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - DETOXIFICATION. */
  _0136("0136", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - DETOXIFICATION"),
  /** 0137 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - ONCOLOGY. */
  _0137("0137", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - ONCOLOGY"),
  /** 0138 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - REHABILITATION. */
  _0138("0138", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - REHABILITATION"),
  /** 0139 - ROOM &amp; BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - OTHER. */
  _0139("0139", "ROOM & BOARD - SEMI-PRIVATE - THREE AND FOUR BEDS - OTHER"),
  /** 0140 - ROOM &amp; BOARD - DELUXE PRIVATE - GENERAL CLASSIFICATION. */
  _0140("0140", "ROOM & BOARD - DELUXE PRIVATE - GENERAL CLASSIFICATION"),
  /** 0141 - ROOM &amp; BOARD - DELUXE PRIVATE - MEDICAL/SURGICAL/GYN. */
  _0141("0141", "ROOM & BOARD - DELUXE PRIVATE - MEDICAL/SURGICAL/GYN"),
  /** 0142 - ROOM &amp; BOARD - DELUXE PRIVATE - OBSTETRICS (OB). */
  _0142("0142", "ROOM & BOARD - DELUXE PRIVATE - OBSTETRICS (OB)"),
  /** 0143 - ROOM &amp; BOARD - DELUXE PRIVATE - PEDIATRIC. */
  _0143("0143", "ROOM & BOARD - DELUXE PRIVATE - PEDIATRIC"),
  /** 0144 - ROOM &amp; BOARD - DELUXE PRIVATE - PSYCHIATRIC. */
  _0144("0144", "ROOM & BOARD - DELUXE PRIVATE - PSYCHIATRIC"),
  /** 0145 - ROOM &amp; BOARD - DELUXE PRIVATE - HOSPICE. */
  _0145("0145", "ROOM & BOARD - DELUXE PRIVATE - HOSPICE"),
  /** 0146 - ROOM &amp; BOARD - DELUXE PRIVATE - DETOXIFICATION. */
  _0146("0146", "ROOM & BOARD - DELUXE PRIVATE - DETOXIFICATION"),
  /** 0147 - ROOM &amp; BOARD - DELUXE PRIVATE - ONCOLOGY. */
  _0147("0147", "ROOM & BOARD - DELUXE PRIVATE - ONCOLOGY"),
  /** 0148 - ROOM &amp; BOARD - DELUXE PRIVATE - REHABILITATION. */
  _0148("0148", "ROOM & BOARD - DELUXE PRIVATE - REHABILITATION"),
  /** 0149 - ROOM &amp; BOARD - DELUXE PRIVATE - OTHER. */
  _0149("0149", "ROOM & BOARD - DELUXE PRIVATE - OTHER"),
  /** 0150 - ROOM &amp; BOARD - WARD - GENERAL CLASSIFICATION. */
  _0150("0150", "ROOM & BOARD - WARD  - GENERAL CLASSIFICATION"),
  /** 0151 - ROOM &amp; BOARD - WARD - MEDICAL/SURGICAL/GYN. */
  _0151("0151", "ROOM & BOARD - WARD  - MEDICAL/SURGICAL/GYN"),
  /** 0152 - ROOM &amp; BOARD - WARD - OBSTETRICS (OB). */
  _0152("0152", "ROOM & BOARD - WARD  - OBSTETRICS (OB)"),
  /** 0153 - ROOM &amp; BOARD - WARD - PEDIATRIC. */
  _0153("0153", "ROOM & BOARD - WARD  - PEDIATRIC"),
  /** 0154 - ROOM &amp; BOARD - WARD - PSYCHIATRIC. */
  _0154("0154", "ROOM & BOARD - WARD  - PSYCHIATRIC"),
  /** 0155 - ROOM &amp; BOARD - WARD - HOSPICE. */
  _0155("0155", "ROOM & BOARD - WARD - HOSPICE"),
  /** 0156 - ROOM &amp; BOARD - WARD - DETOXIFICATION. */
  _0156("0156", "ROOM & BOARD - WARD - DETOXIFICATION"),
  /** 0157 - ROOM &amp; BOARD - WARD - ONCOLOGY. */
  _0157("0157", "ROOM & BOARD - WARD - ONCOLOGY"),
  /** 0158 - ROOM &amp; BOARD - WARD - REHABILITATION. */
  _0158("0158", "ROOM & BOARD - WARD - REHABILITATION"),
  /** 0159 - ROOM &amp; BOARD - WARD - OTHER. */
  _0159("0159", "ROOM & BOARD - WARD - OTHER"),
  /** 0160 - ROOM &amp; BOARD - OTHER - GENERAL CLASSIFICATION. */
  _0160("0160", "ROOM & BOARD - OTHER - GENERAL CLASSIFICATION"),
  /** 0164 - ROOM &amp; BOARD - OTHER - STERILE ENVIRONMENT. */
  _0164("0164", "ROOM & BOARD - OTHER - STERILE ENVIRONMENT"),
  /** 0167 - ROOM &amp; BOARD - OTHER - SELF CARE. */
  _0167("0167", "ROOM & BOARD - OTHER - SELF CARE"),
  /** 0169 - ROOM &amp; BOARD - OTHER - OTHER. */
  _0169("0169", "ROOM & BOARD - OTHER - OTHER"),
  /** 0170 - NURSERY - GENERAL CLASSIFICATION. */
  _0170("0170", "NURSERY - GENERAL CLASSIFICATION"),
  /** 0171 - NURSERY - NEWBORN - LEVEL I. */
  _0171("0171", "NURSERY - NEWBORN - LEVEL I"),
  /** 0172 - NURSERY - NEWBORN - LEVEL II. */
  _0172("0172", "NURSERY - NEWBORN - LEVEL II"),
  /** 0173 - NURSERY - NEWBORN - LEVEL III. */
  _0173("0173", "NURSERY - NEWBORN - LEVEL III"),
  /** 0174 - NURSERY - NEWBORN - LEVEL IV. */
  _0174("0174", "NURSERY - NEWBORN - LEVEL IV"),
  /** 0179 - NURSERY - OTHER NURSERY. */
  _0179("0179", "NURSERY - OTHER NURSERY"),
  /** 0180 - LEAVE OF ABSENCE - GENERAL CLASSIFICATION. */
  _0180("0180", "LEAVE OF ABSENCE - GENERAL CLASSIFICATION"),
  /** 0182 - LEAVE OF ABSENCE - PATIENT CONVENIENCE. */
  _0182("0182", "LEAVE OF ABSENCE - PATIENT CONVENIENCE"),
  /** 0183 - LEAVE OF ABSENCE - THERAPEUTIC LEAVE. */
  _0183("0183", "LEAVE OF ABSENCE - THERAPEUTIC LEAVE"),
  /** 0185 - LEAVE OF ABSENCE - NURSING HOME (FOR HOSPITALIZATION). */
  _0185("0185", "LEAVE OF ABSENCE - NURSING HOME (FOR HOSPITALIZATION)"),
  /** 0189 - LEAVE OF ABSENCE - OTHER LOA. */
  _0189("0189", "LEAVE OF ABSENCE - OTHER LOA"),
  /** 0190 - SUBACUTE CARE - GENERAL CLASSIFICATION. */
  _0190("0190", "SUBACUTE CARE - GENERAL CLASSIFICATION"),
  /** 0191 - SUBACUTE CARE - SUBACUTE CARE - LEVEL I. */
  _0191("0191", "SUBACUTE CARE - SUBACUTE CARE - LEVEL I"),
  /** 0192 - SUBACUTE CARE - SUBACUTE CARE - LEVEL II. */
  _0192("0192", "SUBACUTE CARE - SUBACUTE CARE - LEVEL II"),
  /** 0193 - SUBACUTE CARE - SUBACUTE CARE - LEVEL III. */
  _0193("0193", "SUBACUTE CARE - SUBACUTE CARE - LEVEL III"),
  /** 0194 - SUBACUTE CARE - SUBACUTE CARE - LEVEL IV. */
  _0194("0194", "SUBACUTE CARE - SUBACUTE CARE - LEVEL IV"),
  /** 0199 - SUBACUTE CARE - OTHER SUBACUTE CARE. */
  _0199("0199", "SUBACUTE CARE - OTHER SUBACUTE CARE"),
  /** 0200 - INTENSIVE CARE UNIT - GENERAL CLASSIFICATION. */
  _0200("0200", "INTENSIVE CARE UNIT - GENERAL CLASSIFICATION"),
  /** 0201 - INTENSIVE CARE UNIT - SURGICAL. */
  _0201("0201", "INTENSIVE CARE UNIT - SURGICAL"),
  /** 0202 - INTENSIVE CARE UNIT - MEDICAL. */
  _0202("0202", "INTENSIVE CARE UNIT - MEDICAL"),
  /** 0203 - INTENSIVE CARE UNIT - PEDIATRIC. */
  _0203("0203", "INTENSIVE CARE UNIT - PEDIATRIC"),
  /** 0204 - INTENSIVE CARE UNIT - PSYCHIATRIC. */
  _0204("0204", "INTENSIVE CARE UNIT - PSYCHIATRIC"),
  /** 0206 - INTENSIVE CARE UNIT - INTERMEDIATE ICU. */
  _0206("0206", "INTENSIVE CARE UNIT - INTERMEDIATE ICU"),
  /** 0207 - INTENSIVE CARE UNIT - BURN CARE. */
  _0207("0207", "INTENSIVE CARE UNIT - BURN CARE"),
  /** 0208 - INTENSIVE CARE UNIT - TRAUMA. */
  _0208("0208", "INTENSIVE CARE UNIT - TRAUMA"),
  /** 0209 - INTENSIVE CARE UNIT - OTHER INTENSIVE CARE. */
  _0209("0209", "INTENSIVE CARE UNIT - OTHER INTENSIVE CARE"),
  /** 0210 - CORONARY CARE UNIT - GENERAL CLASSIFICATION. */
  _0210("0210", "CORONARY CARE UNIT - GENERAL CLASSIFICATION"),
  /** 0211 - CORONARY CARE UNIT - MYOCARDIAL INFARCTION. */
  _0211("0211", "CORONARY CARE UNIT - MYOCARDIAL INFARCTION"),
  /** 0212 - CORONARY CARE UNIT - PULMONARY CARE. */
  _0212("0212", "CORONARY CARE UNIT - PULMONARY CARE"),
  /** 0213 - CORONARY CARE UNIT - HEART TRANSPLANT. */
  _0213("0213", "CORONARY CARE UNIT - HEART TRANSPLANT"),
  /** 0214 - CORONARY CARE UNIT - INTERMEDIATE CCU. */
  _0214("0214", "CORONARY CARE UNIT - INTERMEDIATE CCU"),
  /** 0219 - CORONARY CARE UNIT - OTHER CORONARY CCU. */
  _0219("0219", "CORONARY CARE UNIT - OTHER CORONARY CCU"),
  /** 0220 - SPECIAL CHARGES - GENERAL CLASSIFICATION. */
  _0220("0220", "SPECIAL CHARGES - GENERAL CLASSIFICATION"),
  /** 0221 - SPECIAL CHARGES - ADMISSION CHARGES. */
  _0221("0221", "SPECIAL CHARGES - ADMISSION CHARGES"),
  /** 0222 - SPECIAL CHARGES - TECHNICAL SUPPORT CHARGE. */
  _0222("0222", "SPECIAL CHARGES - TECHNICAL SUPPORT CHARGE"),
  /** 0223 - SPECIAL CHARGES - U.R. SERVICE CHARGE. */
  _0223("0223", "SPECIAL CHARGES - U.R. SERVICE CHARGE"),
  /** 0224 - SPECIAL CHARGES - LATE DISCHARGE, MEDICALLY NECESSARY. */
  _0224("0224", "SPECIAL CHARGES - LATE DISCHARGE, MEDICALLY NECESSARY"),
  /** 0229 - SPECIAL CHARGES - OTHER SPECIAL CHARGES. */
  _0229("0229", "SPECIAL CHARGES - OTHER SPECIAL CHARGES"),
  /** 0230 - INCREMENTAL NURSING CHARGE - GENERAL CLASSIFICATION. */
  _0230("0230", "INCREMENTAL NURSING CHARGE - GENERAL CLASSIFICATION"),
  /** 0231 - INCREMENTAL NURSING CHARGE - NURSERY. */
  _0231("0231", "INCREMENTAL NURSING CHARGE - NURSERY"),
  /** 0232 - INCREMENTAL NURSING CHARGE - OB. */
  _0232("0232", "INCREMENTAL NURSING CHARGE  - OB"),
  /** 0233 - INCREMENTAL NURSING CHARGE - ICU. */
  _0233("0233", "INCREMENTAL NURSING CHARGE - ICU"),
  /** 0234 - INCREMENTAL NURSING CHARGE - CCU. */
  _0234("0234", "INCREMENTAL NURSING CHARGE - CCU"),
  /** 0235 - INCREMENTAL NURSING CHARGE - HOSPICE. */
  _0235("0235", "INCREMENTAL NURSING CHARGE - HOSPICE"),
  /** 0239 - INCREMENTAL NURSING CHARGE - OTHER. */
  _0239("0239", "INCREMENTAL NURSING CHARGE  - OTHER"),
  /** 0240 - ALL INCLUSIVE ANCILLARY - GENERAL CLASSIFICATION. */
  _0240("0240", "ALL INCLUSIVE ANCILLARY - GENERAL CLASSIFICATION"),
  /** 0241 - ALL INCLUSIVE ANCILLARY - BASIC. */
  _0241("0241", "ALL INCLUSIVE ANCILLARY - BASIC"),
  /** 0242 - ALL INCLUSIVE ANCILLARY - COMPREHENSIVE. */
  _0242("0242", "ALL INCLUSIVE ANCILLARY - COMPREHENSIVE"),
  /** 0243 - ALL INCLUSIVE ANCILLARY - SPECIALTY. */
  _0243("0243", "ALL INCLUSIVE ANCILLARY - SPECIALTY"),
  /** 0249 - ALL INCLUSIVE ANCILLARY - OTHER ALL INCLUSIVE ANCILLARY. */
  _0249("0249", "ALL INCLUSIVE ANCILLARY - OTHER ALL INCLUSIVE ANCILLARY"),
  /** 0250 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - GENERAL CLASSIFICATION. */
  _0250("0250", "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - GENERAL CLASSIFICATION"),
  /** 0251 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - GENERIC DRUGS. */
  _0251("0251", "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - GENERIC DRUGS"),
  /** 0252 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - NON-GENERIC DRUGS. */
  _0252("0252", "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - NON-GENERIC DRUGS"),
  /** 0253 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - TAKE HOME DRUGS. */
  _0253("0253", "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - TAKE HOME DRUGS"),
  /**
   * 0254 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - DRUGS INCIDENT TO OTHER DIAGNOSTIC
   * SERVICES.
   */
  _0254(
      "0254",
      "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - DRUGS INCIDENT TO OTHER DIAGNOSTIC SERVICES"),
  /** 0255 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - DRUGS INCIDENT TO RADIOLOGY. */
  _0255("0255", "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - DRUGS INCIDENT TO RADIOLOGY"),
  /** 0256 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - EXPERIMENTAL DRUGS. */
  _0256("0256", "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - EXPERIMENTAL DRUGS"),
  /** 0257 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - NON-PRESCRIPTION. */
  _0257("0257", "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - NON-PRESCRIPTION"),
  /** 0258 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - IV SOLUTIONS. */
  _0258("0258", "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - IV SOLUTIONS"),
  /** 0259 - PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - OTHER PHARMACY. */
  _0259("0259", "PHARMACY (ALSO SEE 063X, AN EXTENSION OF 025X) - OTHER PHARMACY"),
  /** 0260 - IV THERAPY - GENERAL CLASSIFICATION. */
  _0260("0260", "IV THERAPY - GENERAL CLASSIFICATION"),
  /** 0261 - IV THERAPY - INFUSION PUMP. */
  _0261("0261", "IV THERAPY - INFUSION PUMP"),
  /** 0262 - IV THERAPY - IV THERAPY/PHARMACY SVCS. */
  _0262("0262", "IV THERAPY - IV THERAPY/PHARMACY SVCS"),
  /** 0263 - IV THERAPY - IV THERAPY/DRUG/SUPPLY/ DELIVERY. */
  _0263("0263", "IV THERAPY - IV THERAPY/DRUG/SUPPLY/ DELIVERY"),
  /** 0264 - IV THERAPY - IV THERAPY/SUPPLIES. */
  _0264("0264", "IV THERAPY - IV THERAPY/SUPPLIES"),
  /** 0269 - IV THERAPY - OTHER IV THERAPY. */
  _0269("0269", "IV THERAPY - OTHER IV THERAPY"),
  /**
   * 0270 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027) - GENERAL
   * CLASSIFICATION.
   */
  _0270(
      "0270",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027) - GENERAL CLASSIFICATION"),
  /**
   * 0271 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - NON
   * STERILE SUPPLY.
   */
  _0271(
      "0271",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - NON STERILE SUPPLY"),
  /**
   * 0272 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - STERILE
   * SUPPLY.
   */
  _0272(
      "0272",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - STERILE SUPPLY"),
  /**
   * 0273 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - TAKE HOME
   * SUPPLIES.
   */
  _0273(
      "0273",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - TAKE HOME SUPPLIES"),
  /**
   * 0274 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) -
   * PROSTHETIC/ORTHOTIC DEVICES.
   */
  _0274(
      "0274",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - PROSTHETIC/ORTHOTIC DEVICES"),
  /**
   * 0275 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062 X, AN EXTENSION OF 027X) -
   * PACEMAKER.
   */
  _0275(
      "0275",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062 X, AN EXTENSION OF 027X) - PACEMAKER"),
  /**
   * 0276 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) -
   * INTRAOCULAR LENS.
   */
  _0276(
      "0276",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X,  AN EXTENSION OF 027X) - INTRAOCULAR LENS"),
  /**
   * 0277 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) -
   * OXYGEN-TAKE HOME.
   */
  _0277(
      "0277",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - OXYGEN-TAKE HOME"),
  /**
   * 0278 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - OTHER
   * IMPLANT.
   */
  _0278(
      "0278",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - OTHER IMPLANT"),
  /**
   * 0279 - MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - OTHER
   * SUPPLIES/DEVICES.
   */
  _0279(
      "0279",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES (ALSO SEE 062X, AN EXTENSION OF 027X) - OTHER SUPPLIES/DEVICES"),
  /** 0280 - ONCOLOGY - GENERAL CLASSIFICATION. */
  _0280("0280", "ONCOLOGY - GENERAL CLASSIFICATION"),
  /** 0289 - ONCOLOGY - OTHER ONCOLOGY. */
  _0289("0289", "ONCOLOGY - OTHER ONCOLOGY"),
  /** 0290 - DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - GENERAL CLASSIFICATION. */
  _0290("0290", "DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - GENERAL CLASSIFICATION"),
  /** 0291 - DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - RENTAL. */
  _0291("0291", "DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - RENTAL"),
  /** 0292 - DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - PURCHASE OF NEW DME. */
  _0292("0292", "DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - PURCHASE OF NEW DME"),
  /** 0293 - DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - PURCHASE OF USED DME. */
  _0293("0293", "DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - PURCHASE OF USED DME"),
  /** 0294 - DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - SUPPLIES/DRUGS FOR DME. */
  _0294("0294", "DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - SUPPLIES/DRUGS FOR DME"),
  /** 0299 - DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - OTHER EQUIPMENT. */
  _0299("0299", "DURABLE MEDICAL EQUIPMENT (OTHER THAN RENAL) - OTHER EQUIPMENT"),
  /** 0300 - LABORATORY - GENERAL CLASSIFICATION. */
  _0300("0300", "LABORATORY - GENERAL CLASSIFICATION"),
  /** 0301 - LABORATORY - CHEMISTRY. */
  _0301("0301", "LABORATORY - CHEMISTRY"),
  /** 0302 - LABORATORY - IMMUNOLOGY. */
  _0302("0302", "LABORATORY - IMMUNOLOGY"),
  /** 0303 - LABORATORY - RENAL PATIENT (HOME). */
  _0303("0303", "LABORATORY - RENAL PATIENT (HOME)"),
  /** 0304 - LABORATORY - NON-ROUTINE DIALYSIS. */
  _0304("0304", "LABORATORY - NON-ROUTINE DIALYSIS"),
  /** 0305 - LABORATORY - HEMATOLOGY. */
  _0305("0305", "LABORATORY - HEMATOLOGY"),
  /** 0306 - LABORATORY - BACTERIOLOGY &amp; MICROBIOLOGY. */
  _0306("0306", "LABORATORY - BACTERIOLOGY & MICROBIOLOGY"),
  /** 0307 - LABORATORY - UROLOGY. */
  _0307("0307", "LABORATORY - UROLOGY"),
  /** 0309 - LABORATORY - OTHER LABORATORY. */
  _0309("0309", "LABORATORY - OTHER LABORATORY"),
  /** 0310 - LABORATORY PATHOLOGY - GENERAL CLASSIFICATION. */
  _0310("0310", "LABORATORY PATHOLOGY - GENERAL CLASSIFICATION"),
  /** 0311 - LABORATORY PATHOLOGY - CYTOLOGY. */
  _0311("0311", "LABORATORY PATHOLOGY - CYTOLOGY"),
  /** 0312 - LABORATORY PATHOLOGY - HISTOLOGY. */
  _0312("0312", "LABORATORY PATHOLOGY - HISTOLOGY"),
  /** 0314 - LABORATORY PATHOLOGY - BIOPSY. */
  _0314("0314", "LABORATORY PATHOLOGY - BIOPSY"),
  /** 0319 - LABORATORY PATHOLOGY - OTHER LABORATORY PATHOLOGY. */
  _0319("0319", "LABORATORY PATHOLOGY - OTHER LABORATORY PATHOLOGY"),
  /** 0320 - RADIOLOGY - DIAGNOSTIC - GENERAL CLASSIFICATION. */
  _0320("0320", "RADIOLOGY - DIAGNOSTIC - GENERAL CLASSIFICATION"),
  /** 0321 - RADIOLOGY - DIAGNOSTIC - ANGIOCARDIOGRAPHY. */
  _0321("0321", "RADIOLOGY - DIAGNOSTIC - ANGIOCARDIOGRAPHY"),
  /** 0322 - RADIOLOGY - DIAGNOSTIC - ARTHROGRAPHY. */
  _0322("0322", "RADIOLOGY - DIAGNOSTIC - ARTHROGRAPHY"),
  /** 0323 - RADIOLOGY - DIAGNOSTIC - ARTERIOGRAPHY. */
  _0323("0323", "RADIOLOGY - DIAGNOSTIC - ARTERIOGRAPHY"),
  /** 0324 - RADIOLOGY - DIAGNOSTIC - CHEST X-RAY. */
  _0324("0324", "RADIOLOGY - DIAGNOSTIC - CHEST X-RAY"),
  /** 0329 - RADIOLOGY - DIAGNOSTIC - OTHER RADIOLOGY - DIAGNOSTIC. */
  _0329("0329", "RADIOLOGY - DIAGNOSTIC - OTHER RADIOLOGY - DIAGNOSTIC"),
  /** 0330 - RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - GENERAL CLASSIFICATION. */
  _0330(
      "0330",
      "RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - GENERAL CLASSIFICATION"),
  /**
   * 0331 - RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - CHEMOTHERAPY ADMIN -
   * INJECTED.
   */
  _0331(
      "0331",
      "RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - CHEMOTHERAPY ADMIN - INJECTED"),
  /**
   * 0332 - RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - CHEMOTHERAPY ADMINISTRATION
   * - ORAL.
   */
  _0332(
      "0332",
      "RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - CHEMOTHERAPY ADMINISTRATION - ORAL"),
  /** 0333 - RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - RADIATION THERAPY. */
  _0333("0333", "RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - RADIATION THERAPY"),
  /**
   * 0335 - RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - CHEMOTHERAPY ADMIN - IV.
   */
  _0335(
      "0335",
      "RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - CHEMOTHERAPY ADMIN - IV"),
  /**
   * 0339 - RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - OTHER RADIOLOGY -
   * THERAPEUTIC.
   */
  _0339(
      "0339",
      "RADIOLOGY - THERAPEUTIC AND/OR CHEMOTHERAPY ADMINISTRATION - OTHER RADIOLOGY - THERAPEUTIC"),
  /** 0340 - NUCLEAR MEDICINE - GENERAL CLASSIFICATION. */
  _0340("0340", "NUCLEAR MEDICINE - GENERAL CLASSIFICATION"),
  /** 0341 - NUCLEAR MEDICINE - DIAGNOSTIC. */
  _0341("0341", "NUCLEAR MEDICINE - DIAGNOSTIC"),
  /** 0342 - NUCLEAR MEDICINE - THERAPEUTIC. */
  _0342("0342", "NUCLEAR MEDICINE - THERAPEUTIC"),
  /** 0343 - NUCLEAR MEDICINE - DIAGNOSTIC RADIOPHARMACEUTICALS. */
  _0343("0343", "NUCLEAR MEDICINE - DIAGNOSTIC RADIOPHARMACEUTICALS"),
  /** 0344 - NUCLEAR MEDICINE - THERAPEUTIC RADIOPHARMACEUTICALS. */
  _0344("0344", "NUCLEAR MEDICINE - THERAPEUTIC RADIOPHARMACEUTICALS"),
  /** 0349 - NUCLEAR MEDICINE - OTHER NUCLEAR MEDICINE. */
  _0349("0349", "NUCLEAR MEDICINE - OTHER NUCLEAR MEDICINE"),
  /** 0350 - CT SCAN - GENERAL CLASSIFICATION. */
  _0350("0350", "CT SCAN - GENERAL CLASSIFICATION"),
  /** 0351 - CT SCAN - HEAD SCAN. */
  _0351("0351", "CT SCAN - HEAD SCAN"),
  /** 0352 - CT SCAN - BODY SCAN. */
  _0352("0352", "CT SCAN - BODY SCAN"),
  /** 0359 - CT SCAN - CT - OTHER. */
  _0359("0359", "CT SCAN - CT - OTHER"),
  /** 0360 - OPERATING ROOM SERVICES - GENERAL CLASSIFICATION. */
  _0360("0360", "OPERATING ROOM SERVICES - GENERAL CLASSIFICATION"),
  /** 0361 - OPERATING ROOM SERVICES - MINOR SURGERY. */
  _0361("0361", "OPERATING ROOM SERVICES - MINOR SURGERY"),
  /** 0362 - OPERATING ROOM SERVICES - ORGAN TRANSPLANT-OTHER THAN KIDNEY. */
  _0362("0362", "OPERATING ROOM SERVICES - ORGAN TRANSPLANT-OTHER THAN KIDNEY"),
  /** 0367 - OPERATING ROOM SERVICES - KIDNEY TRANSPLANT. */
  _0367("0367", "OPERATING ROOM SERVICES - KIDNEY TRANSPLANT"),
  /** 0369 - OPERATING ROOM SERVICES - OTHER OR SERVICES. */
  _0369("0369", "OPERATING ROOM SERVICES - OTHER OR SERVICES"),
  /** 0370 - ANESTHESIA - GENERAL CLASSIFICATION. */
  _0370("0370", "ANESTHESIA - GENERAL CLASSIFICATION"),
  /** 0371 - ANESTHESIA - ANESTHESIA INCIDENT TO RADIOLOGY. */
  _0371("0371", "ANESTHESIA - ANESTHESIA INCIDENT TO RADIOLOGY"),
  /** 0372 - ANESTHESIA - ANESTHESIA INCIDENT TO OTHER DX SERVICES. */
  _0372("0372", "ANESTHESIA - ANESTHESIA INCIDENT TO OTHER DX SERVICES"),
  /** 0374 - ANESTHESIA - ACUPUNCTURE. */
  _0374("0374", "ANESTHESIA - ACUPUNCTURE"),
  /** 0379 - ANESTHESIA - OTHER ANESTHESIA. */
  _0379("0379", "ANESTHESIA - OTHER ANESTHESIA"),
  /** 0380 - BLOOD AND BLOOD COMPONENTS - GENERAL CLASSIFICATION. */
  _0380("0380", "BLOOD AND BLOOD COMPONENTS - GENERAL CLASSIFICATION"),
  /** 0381 - BLOOD AND BLOOD COMPONENTS - PACKED RED CELLS. */
  _0381("0381", "BLOOD  AND BLOOD COMPONENTS - PACKED RED CELLS"),
  /** 0382 - BLOOD AND BLOOD COMPONENTS - WHOLE BLOOD. */
  _0382("0382", "BLOOD  AND BLOOD COMPONENTS - WHOLE BLOOD"),
  /** 0383 - BLOOD AND BLOOD COMPONENTS- PLASMA. */
  _0383("0383", "BLOOD  AND BLOOD COMPONENTS- PLASMA"),
  /** 0384 - BLOOD AND BLOOD COMPONENTS - PLATELETS. */
  _0384("0384", "BLOOD  AND BLOOD COMPONENTS - PLATELETS"),
  /** 0385 - BLOOD AND BLOOD COMPONENTS - LEUCOCYTES. */
  _0385("0385", "BLOOD  AND BLOOD COMPONENTS - LEUCOCYTES"),
  /** 0386 - BLOOD AND BLOOD COMPONENTS - OTHER BLOOD COMPONENTS. */
  _0386("0386", "BLOOD  AND BLOOD COMPONENTS - OTHER BLOOD COMPONENTS"),
  /** 0387 - BLOOD AND BLOOD COMPONENTS - OTHER DERIVATIVES (CRYOPRECIPITATE). */
  _0387("0387", "BLOOD  AND BLOOD COMPONENTS - OTHER DERIVATIVES (CRYOPRECIPITATE)"),
  /** 0389 - BLOOD AND BLOOD COMPONENTS - OTHER BLOOD AND BLOOD COMPONENTS. */
  _0389("0389", "BLOOD  AND BLOOD COMPONENTS - OTHER BLOOD AND BLOOD COMPONENTS"),
  /**
   * 0390 - ADMINISTRATION, PROCESSING, AND STORAGE FOR BLOOD AND BLOOD COMPONENTS - GENERAL
   * CLASSIFICATION.
   */
  _0390(
      "0390",
      "ADMINISTRATION, PROCESSING, AND STORAGE FOR BLOOD AND BLOOD COMPONENTS - GENERAL CLASSIFICATION"),
  /**
   * 0391 - ADMINISTRATION, PROCESSING, AND STORAGE FOR BLOOD AND BLOOD COMPONENTS - ADMINISTRATION
   * (E.G. TRANSFUSIONS).
   */
  _0391(
      "0391",
      "ADMINISTRATION, PROCESSING, AND STORAGE FOR BLOOD AND BLOOD COMPONENTS - ADMINISTRATION (E.G. TRANSFUSIONS)"),
  /**
   * 0392 - ADMINISTRATION, PROCESSING, AND STORAGE FOR BLOOD AND BLOOD COMPONENTS - PROCESSING AND
   * STORAGE.
   */
  _0392(
      "0392",
      "ADMINISTRATION, PROCESSING, AND STORAGE FOR BLOOD AND BLOOD COMPONENTS -  PROCESSING  AND STORAGE"),
  /**
   * 0399 - ADMINISTRATION, PROCESSING, AND STORAGE FOR BLOOD AND BLOOD COMPONENTS - OTHER BLOOD
   * HANDLING.
   */
  _0399(
      "0399",
      "ADMINISTRATION, PROCESSING, AND STORAGE FOR BLOOD AND BLOOD COMPONENTS - OTHER BLOOD HANDLING"),
  /** 0400 - OTHER IMAGING SERVICES - GENERAL CLASSIFICATION. */
  _0400("0400", "OTHER IMAGING SERVICES - GENERAL CLASSIFICATION"),
  /** 0401 - OTHER IMAGING SERVICES - DIAGNOSTIC MAMMOGRAPHY. */
  _0401("0401", "OTHER IMAGING SERVICES - DIAGNOSTIC MAMMOGRAPHY"),
  /** 0402 - OTHER IMAGING SERVICES - ULTRASOUND. */
  _0402("0402", "OTHER IMAGING SERVICES - ULTRASOUND"),
  /** 0403 - OTHER IMAGING SERVICES - SCREENING MAMMOGRAPHY. */
  _0403("0403", "OTHER IMAGING SERVICES - SCREENING MAMMOGRAPHY"),
  /** 0404 - OTHER IMAGING SERVICES - POSITRON EMISSION TOMOGRAPHY. */
  _0404("0404", "OTHER IMAGING SERVICES - POSITRON EMISSION TOMOGRAPHY"),
  /** 0409 - OTHER IMAGING SERVICES - OTHER IMAGING SERVICES. */
  _0409("0409", "OTHER IMAGING SERVICES - OTHER IMAGING SERVICES"),
  /** 0410 - RESPIRATORY SERVICES - GENERAL CLASSIFICATION. */
  _0410("0410", "RESPIRATORY SERVICES - GENERAL CLASSIFICATION"),
  /** 0412 - RESPIRATORY SERVICES - INHALATION SERVICES. */
  _0412("0412", "RESPIRATORY SERVICES - INHALATION SERVICES"),
  /** 0413 - RESPIRATORY SERVICES - HYPERBARIC OXYGEN THERAPY. */
  _0413("0413", "RESPIRATORY SERVICES - HYPERBARIC OXYGEN THERAPY"),
  /** 0419 - RESPIRATORY SERVICES - OTHER RESPIRATORY SERVICES. */
  _0419("0419", "RESPIRATORY SERVICES - OTHER RESPIRATORY SERVICES"),
  /** 0420 - PHYSICAL THERAPY - GENERAL CLASSIFICATION. */
  _0420("0420", "PHYSICAL THERAPY - GENERAL CLASSIFICATION"),
  /** 0421 - PHYSICAL THERAPY - VISIT. */
  _0421("0421", "PHYSICAL THERAPY - VISIT"),
  /** 0422 - PHYSICAL THERAPY - HOURLY. */
  _0422("0422", "PHYSICAL THERAPY - HOURLY"),
  /** 0423 - PHYSICAL THERAPY - GROUP. */
  _0423("0423", "PHYSICAL THERAPY - GROUP"),
  /** 0424 - PHYSICAL THERAPY - EVALUATION OR RE-EVALUATION. */
  _0424("0424", "PHYSICAL THERAPY - EVALUATION OR RE-EVALUATION"),
  /** 0429 - PHYSICAL THERAPY - OTHER PHYSICAL THERAPY. */
  _0429("0429", "PHYSICAL THERAPY - OTHER PHYSICAL THERAPY"),
  /** 0430 - OCCUPATIONAL THERAPY - GENERAL CLASSIFICATION. */
  _0430("0430", "OCCUPATIONAL THERAPY - GENERAL CLASSIFICATION"),
  /** 0431 - OCCUPATIONAL THERAPY - VISIT. */
  _0431("0431", "OCCUPATIONAL THERAPY - VISIT"),
  /** 0432 - OCCUPATIONAL THERAPY - HOURLY. */
  _0432("0432", "OCCUPATIONAL THERAPY - HOURLY"),
  /** 0433 - OCCUPATIONAL THERAPY - GROUP. */
  _0433("0433", "OCCUPATIONAL THERAPY - GROUP"),
  /** 0434 - OCCUPATIONAL THERAPY - EVALUATION OR REEVALUATION. */
  _0434("0434", "OCCUPATIONAL THERAPY - EVALUATION OR REEVALUATION"),
  /** 0439 - OCCUPATIONAL THERAPY - OTHER OCCUPATIONAL THERAPY. */
  _0439("0439", "OCCUPATIONAL THERAPY - OTHER OCCUPATIONAL THERAPY"),
  /** 0440 - SPEECH-LANGUAGE PATHOLOGY - GENERAL CLASSIFICATION. */
  _0440("0440", "SPEECH-LANGUAGE PATHOLOGY - GENERAL CLASSIFICATION"),
  /** 0441 - SPEECH-LANGUAGE PATHOLOGY - VISIT. */
  _0441("0441", "SPEECH-LANGUAGE PATHOLOGY - VISIT"),
  /** 0442 - SPEECH-LANGUAGE PATHOLOGY - HOURLY. */
  _0442("0442", "SPEECH-LANGUAGE PATHOLOGY - HOURLY"),
  /** 0443 - SPEECH-LANGUAGE PATHOLOGY - GROUP. */
  _0443("0443", "SPEECH-LANGUAGE PATHOLOGY - GROUP"),
  /** 0444 - SPEECH-LANGUAGE PATHOLOGY - EVALUATION OR REEVALUATION. */
  _0444("0444", "SPEECH-LANGUAGE PATHOLOGY - EVALUATION OR REEVALUATION"),
  /** 0449 - SPEECH-LANGUAGE PATHOLOGY - OTHER SPEECH THERAPY. */
  _0449("0449", "SPEECH-LANGUAGE PATHOLOGY - OTHER SPEECH THERAPY"),
  /** 0450 - EMERGENCY ROOM - GENERAL CLASSIFICATION. */
  _0450("0450", "EMERGENCY ROOM - GENERAL CLASSIFICATION"),
  /** 0451 - EMERGENCY ROOM - EMTALA EMERGENCY MEDICAL SCREENING SERVICES. */
  _0451("0451", "EMERGENCY ROOM - EMTALA EMERGENCY MEDICAL SCREENING SERVICES"),
  /** 0452 - EMERGENCY ROOM - ER BEYOND EMTALA SCREENING. */
  _0452("0452", "EMERGENCY ROOM - ER BEYOND EMTALA SCREENING"),
  /** 0456 - EMERGENCY ROOM - URGENT CARE. */
  _0456("0456", "EMERGENCY ROOM - URGENT CARE"),
  /** 0459 - EMERGENCY ROOM - OTHER EMERGENCY ROOM. */
  _0459("0459", "EMERGENCY ROOM - OTHER EMERGENCY ROOM"),
  /** 0460 - PULMONARY FUNCTION - GENERAL CLASSIFICATION. */
  _0460("0460", "PULMONARY FUNCTION - GENERAL CLASSIFICATION"),
  /** 0469 - PULMONARY FUNCTION - OTHER PULMONARY FUNCTION. */
  _0469("0469", "PULMONARY FUNCTION - OTHER PULMONARY FUNCTION"),
  /** 0470 - AUDIOLOGY - GENERAL CLASSIFICATION. */
  _0470("0470", "AUDIOLOGY - GENERAL CLASSIFICATION"),
  /** 0471 - AUDIOLOGY - DIAGNOSTIC. */
  _0471("0471", "AUDIOLOGY - DIAGNOSTIC"),
  /** 0472 - AUDIOLOGY - TREATMENT. */
  _0472("0472", "AUDIOLOGY - TREATMENT"),
  /** 0479 - AUDIOLOGY - OTHER AUDIOLOGY. */
  _0479("0479", "AUDIOLOGY - OTHER AUDIOLOGY"),
  /** 0480 - CARDIOLOGY - GENERAL CLASSIFICATION. */
  _0480("0480", "CARDIOLOGY - GENERAL CLASSIFICATION"),
  /** 0481 - CARDIOLOGY - CARDIAC CATH LAB. */
  _0481("0481", "CARDIOLOGY - CARDIAC CATH LAB"),
  /** 0482 - CARDIOLOGY - STRESS TEST. */
  _0482("0482", "CARDIOLOGY - STRESS TEST"),
  /** 0483 - CARDIOLOGY - ECHOCARDIOLOGY. */
  _0483("0483", "CARDIOLOGY - ECHOCARDIOLOGY"),
  /** 0489 - CARDIOLOGY - OTHER CARDIOLOGY. */
  _0489("0489", "CARDIOLOGY - OTHER CARDIOLOGY"),
  /** 0490 - AMBULATORY SURGICAL CARE - GENERAL CLASSIFICATION. */
  _0490("0490", "AMBULATORY SURGICAL CARE - GENERAL CLASSIFICATION"),
  /** 0499 - AMBULATORY SURGICAL CARE - OTHER AMBULATORY SURGICAL CARE. */
  _0499("0499", "AMBULATORY SURGICAL CARE - OTHER AMBULATORY SURGICAL CARE"),
  /** 0500 - OUTPATIENT SERVICES - GENERAL CLASSIFICATION. */
  _0500("0500", "OUTPATIENT SERVICES - GENERAL CLASSIFICATION"),
  /** 0509 - OUTPATIENT SERVICES - OTHER OUTPATIENT SERVICE. */
  _0509("0509", "OUTPATIENT SERVICES - OTHER OUTPATIENT SERVICE"),
  /** 0510 - CLINIC - GENERAL CLASSIFICATION. */
  _0510("0510", "CLINIC - GENERAL CLASSIFICATION"),
  /** 0511 - CLINIC - CHRONIC PAIN CENTER. */
  _0511("0511", "CLINIC - CHRONIC PAIN CENTER"),
  /** 0512 - CLINIC - DENTAL CLINIC. */
  _0512("0512", "CLINIC - DENTAL CLINIC"),
  /** 0513 - CLINIC - PSYCHIATRIC CLINIC. */
  _0513("0513", "CLINIC - PSYCHIATRIC CLINIC"),
  /** 0514 - CLINIC - OB-GYN CLINIC. */
  _0514("0514", "CLINIC - OB-GYN CLINIC"),
  /** 0515 - CLINIC - PEDIATRIC CLINIC. */
  _0515("0515", "CLINIC - PEDIATRIC CLINIC"),
  /** 0516 - CLINIC - URGENT CARE CLINIC. */
  _0516("0516", "CLINIC - URGENT CARE CLINIC"),
  /** 0517 - CLINIC - FAMILY PRACTICE CLINIC. */
  _0517("0517", "CLINIC - FAMILY PRACTICE CLINIC"),
  /** 0519 - CLINIC - OTHER CLINIC. */
  _0519("0519", "CLINIC - OTHER CLINIC"),
  /** 0520 - FREESTANDING CLINIC - GENERAL CLASSIFICATION. */
  _0520("0520", "FREESTANDING CLINIC - GENERAL CLASSIFICATION"),
  /** 0521 - FREESTANDING CLINIC - CLINIC VISIT BY MEMBER TO RHC/FQHC. */
  _0521("0521", "FREESTANDING CLINIC - CLINIC VISIT BY MEMBER TO RHC/FQHC"),
  /** 0522 - FREESTANDING CLINIC - HOME VISIT BY RHC/FQHC PRACTITIONER. */
  _0522("0522", "FREESTANDING CLINIC - HOME VISIT BY RHC/FQHC PRACTITIONER"),
  /** 0523 - FREESTANDING CLINIC - FAMILY PRACTICE CLINIC. */
  _0523("0523", "FREESTANDING CLINIC - FAMILY PRACTICE CLINIC"),
  /**
   * 0524 - FREESTANDING CLINIC - VISIT BY RHC/FQHC PRACTITIONER TO A MEMBER IN A SNF OR SKILLED
   * SWING BED IN A COVERED PART A STAY.
   */
  _0524(
      "0524",
      "FREESTANDING CLINIC - VISIT BY RHC/FQHC PRACTITIONER TO A MEMBER IN A SNF OR SKILLED SWING BED IN A COVERED PART A STAY"),
  /**
   * 0525 - FREESTANDING CLINIC - VISIT BY RHC/FQHC PRACTITIONER TO A MEMBER IN A SNF (NOT IN A
   * COVERED PART A STAY) OR NF OR ICF MR OR OTHER RESIDENTIAL FACILITY.
   */
  _0525(
      "0525",
      "FREESTANDING CLINIC - VISIT BY RHC/FQHC PRACTITIONER TO A MEMBER IN A SNF (NOT IN A COVERED PART A STAY) OR NF OR ICF MR OR OTHER RESIDENTIAL FACILITY"),
  /** 0526 - FREESTANDING CLINIC - URGENT CARE CLINIC. */
  _0526("0526", "FREESTANDING CLINIC - URGENT CARE CLINIC"),
  /**
   * 0527 - FREESTANDING CLINIC - VISITING NURSE SERVICE(S) TO A MEMBER&#x27;S HOME WHEN IN A HOME
   * HEALTH SHORTAGE AREA.
   */
  _0527(
      "0527",
      "FREESTANDING CLINIC - VISITING NURSE SERVICE(S) TO A MEMBER'S HOME WHEN IN A HOME HEALTH SHORTAGE AREA"),
  /**
   * 0528 - FREESTANDING CLINIC - VISIT BY RHC/FQHC PRACTITIONER TO OTHER NON-RHC/FQHC SITE (E.G.
   * SCENE OF ACCIDENT).
   */
  _0528(
      "0528",
      "FREESTANDING CLINIC - VISIT BY RHC/FQHC PRACTITIONER TO OTHER NON-RHC/FQHC SITE (E.G. SCENE OF ACCIDENT)"),
  /** 0529 - FREESTANDING CLINIC - OTHER FREESTANDING CLINIC. */
  _0529("0529", "FREESTANDING CLINIC - OTHER FREESTANDING CLINIC"),
  /** 0530 - OSTEOPATHIC SERVICES - GENERAL CLASSIFICATION. */
  _0530("0530", "OSTEOPATHIC SERVICES - GENERAL CLASSIFICATION"),
  /** 0531 - OSTEOPATHIC SERVICES - OSTEOPATHIC THERAPY. */
  _0531("0531", "OSTEOPATHIC SERVICES - OSTEOPATHIC THERAPY"),
  /** 0539 - OSTEOPATHIC SERVICES - OTHER OSTEOPATHIC SERVICES. */
  _0539("0539", "OSTEOPATHIC SERVICES - OTHER OSTEOPATHIC SERVICES"),
  /** 0540 - AMBULANCE - GENERAL CLASSIFICATION. */
  _0540("0540", "AMBULANCE - GENERAL CLASSIFICATION"),
  /** 0541 - AMBULANCE - SUPPLIES. */
  _0541("0541", "AMBULANCE - SUPPLIES"),
  /** 0542 - AMBULANCE - MEDICAL TRANSPORT. */
  _0542("0542", "AMBULANCE - MEDICAL TRANSPORT"),
  /** 0543 - AMBULANCE - HEART MOBILE. */
  _0543("0543", "AMBULANCE - HEART MOBILE"),
  /** 0544 - AMBULANCE - OXYGEN. */
  _0544("0544", "AMBULANCE - OXYGEN"),
  /** 0545 - AMBULANCE - AIR AMBULANCE. */
  _0545("0545", "AMBULANCE - AIR AMBULANCE"),
  /** 0546 - AMBULANCE - NEONATAL AMBULANCE SERVICES. */
  _0546("0546", "AMBULANCE - NEONATAL AMBULANCE SERVICES"),
  /** 0547 - AMBULANCE - PHARMACY. */
  _0547("0547", "AMBULANCE - PHARMACY"),
  /** 0548 - AMBULANCE - EKG TRANSMISSION. */
  _0548("0548", "AMBULANCE - EKG TRANSMISSION"),
  /** 0549 - AMBULANCE - OTHER AMBULANCE. */
  _0549("0549", "AMBULANCE - OTHER AMBULANCE"),
  /** 0550 - SKILLED NURSING - GENERAL CLASSIFICATION. */
  _0550("0550", "SKILLED NURSING - GENERAL CLASSIFICATION"),
  /** 0551 - SKILLED NURSING - VISIT CHARGE. */
  _0551("0551", "SKILLED NURSING - VISIT CHARGE"),
  /** 0552 - SKILLED NURSING - HOURLY CHARGE. */
  _0552("0552", "SKILLED NURSING - HOURLY CHARGE"),
  /** 0559 - SKILLED NURSING - OTHER SKILLED NURSING. */
  _0559("0559", "SKILLED NURSING - OTHER SKILLED NURSING"),
  /** 0560 - HOME HEALTH (HH) MEDICAL SOCIAL SERVICES - GENERAL CLASSIFICATION. */
  _0560("0560", "HOME HEALTH (HH) MEDICAL SOCIAL SERVICES - GENERAL CLASSIFICATION"),
  /** 0561 - HOME HEALTH (HH) MEDICAL SOCIAL SERVICES - VISIT CHARGE. */
  _0561("0561", "HOME HEALTH (HH) MEDICAL SOCIAL SERVICES - VISIT CHARGE"),
  /** 0562 - HOME HEALTH (HH) MEDICAL SOCIAL SERVICES - HOURLY CHARGE. */
  _0562("0562", "HOME HEALTH (HH) MEDICAL SOCIAL SERVICES  - HOURLY CHARGE"),
  /** 0569 - HOME HEALTH (HH) MEDICAL SOCIAL SERVICES - OTHER MED. SOCIAL SERVICE. */
  _0569("0569", "HOME HEALTH (HH) MEDICAL SOCIAL SERVICES - OTHER MED. SOCIAL SERVICE"),
  /** 0570 - HOME HEALTH (HH) AIDE - GENERAL CLASSIFICATION. */
  _0570("0570", "HOME HEALTH (HH) AIDE - GENERAL CLASSIFICATION"),
  /** 0571 - HOME HEALTH (HH) AIDE - VISIT CHARGE. */
  _0571("0571", "HOME HEALTH (HH) AIDE - VISIT CHARGE"),
  /** 0572 - HOME HEALTH (HH) AIDE - HOURLY CHARGE. */
  _0572("0572", "HOME HEALTH (HH) AIDE - HOURLY CHARGE"),
  /** 0579 - HOME HEALTH (HH) - OTHER HH AIDE. */
  _0579("0579", "HOME HEALTH (HH) - OTHER HH AIDE"),
  /** 0580 - HOME HEALTH (HH) - OTHER VISITS - GENERAL CLASSIFICATION. */
  _0580("0580", "HOME HEALTH (HH) - OTHER VISITS - GENERAL CLASSIFICATION"),
  /** 0581 - HOME HEALTH (HH) - OTHER VISITS - VISIT CHARGE. */
  _0581("0581", "HOME HEALTH (HH) - OTHER VISITS - VISIT CHARGE"),
  /** 0582 - HOME HEALTH (HH) - OTHER VISITS - HOURLY CHARGE. */
  _0582("0582", "HOME HEALTH (HH) - OTHER VISITS - HOURLY CHARGE"),
  /** 0583 - HOME HEALTH (HH) - OTHER VISITS - ASSESSMENT. */
  _0583("0583", "HOME HEALTH (HH) - OTHER VISITS - ASSESSMENT"),
  /** 0589 - HOME HEALTH (HH) - OTHER VISITS - OTHER HOME HEALTH VISIT. */
  _0589("0589", "HOME HEALTH (HH) - OTHER VISITS - OTHER HOME HEALTH VISIT"),
  /** 0590 - HOME HEALTH (HH) - UNITS OF SERVICE - GENERAL CLASSIFICATION. */
  _0590("0590", "HOME HEALTH (HH) - UNITS OF SERVICE - GENERAL CLASSIFICATION"),
  /** 0600 - HOME HEALTH (HH) - OXYGEN - GENERAL CLASSIFICATION. */
  _0600("0600", "HOME HEALTH (HH) - OXYGEN - GENERAL CLASSIFICATION"),
  /** 0601 - HOME HEALTH (HH) - OXYGEN - OXYGEN - STAT EQUIP/SUPPLY/CONTENT. */
  _0601("0601", "HOME HEALTH (HH) - OXYGEN - OXYGEN - STAT EQUIP/SUPPLY/CONTENT"),
  /** 0602 - HOME HEALTH (HH) - OXYGEN - OXYGEN - STAT EQUIP/SUPPLY &lt; 1 LPM. */
  _0602("0602", "HOME HEALTH (HH) - OXYGEN - OXYGEN - STAT EQUIP/SUPPLY < 1 LPM"),
  /** 0603 - HOME HEALTH (HH) - OXYGEN - OXYGEN - STAT EQUIP/SUPPLY &gt; 4 LPM. */
  _0603("0603", "HOME HEALTH (HH) - OXYGEN - OXYGEN - STAT EQUIP/SUPPLY > 4 LPM"),
  /** 0604 - HOME HEALTH (HH) - OXYGEN - OXYGEN - PORT ADD-ON. */
  _0604("0604", "HOME HEALTH (HH) - OXYGEN - OXYGEN - PORT ADD-ON"),
  /** 0609 - HOME HEALTH (HH) - OXYGEN - OXYGEN - OTHER. */
  _0609("0609", "HOME HEALTH (HH) - OXYGEN - OXYGEN - OTHER"),
  /** 0610 - MAGNETIC RESONANCE TECHNOLOGY (MRT) - GENERAL CLASSIFICATION. */
  _0610("0610", "MAGNETIC RESONANCE TECHNOLOGY (MRT) - GENERAL CLASSIFICATION"),
  /** 0611 - MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRI - BRAIN/BRAINSTEM. */
  _0611("0611", "MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRI - BRAIN/BRAINSTEM"),
  /** 0612 - MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRI - SPINAL CORD/SPINE. */
  _0612("0612", "MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRI - SPINAL CORD/SPINE"),
  /** 0614 - MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRI - OTHER. */
  _0614("0614", "MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRI - OTHER"),
  /** 0615 - MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRA - HEAD AND NECK. */
  _0615("0615", "MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRA - HEAD AND NECK"),
  /** 0616 - MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRA - LOWER EXTREMITIES. */
  _0616("0616", "MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRA - LOWER EXTREMITIES"),
  /** 0618 - MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRA - OTHER. */
  _0618("0618", "MAGNETIC RESONANCE TECHNOLOGY (MRT) - MRA - OTHER"),
  /** 0619 - MAGNETIC RESONANCE TECHNOLOGY (MRT) - OTHER MRT. */
  _0619("0619", "MAGNETIC RESONANCE TECHNOLOGY (MRT) - OTHER MRT"),
  /**
   * 0621 - MEDICAL/SURGICAL SUPPLIES AND DEVICES - EXTENSION OF 027X - SUPPLIES INCIDENT TO
   * RADIOLOGY.
   */
  _0621(
      "0621",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES - EXTENSION OF 027X - SUPPLIES INCIDENT TO RADIOLOGY"),
  /**
   * 0622 - MEDICAL/SURGICAL SUPPLIES AND DEVICES - EXTENSION OF 027X - SUPPLIES INCIDENT TO OTHER
   * DX SERVICES.
   */
  _0622(
      "0622",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES - EXTENSION OF 027X - SUPPLIES INCIDENT TO OTHER DX SERVICES"),
  /** 0623 - MEDICAL/SURGICAL SUPPLIES AND DEVICES - EXTENSION OF 027X - SURGICAL DRESSINGS. */
  _0623("0623", "MEDICAL/SURGICAL SUPPLIES AND DEVICES - EXTENSION OF 027X - SURGICAL DRESSINGS"),
  /**
   * 0624 - MEDICAL/SURGICAL SUPPLIES AND DEVICES - EXTENSION OF 027X - FDA INVESTIGATIONAL DEVICES.
   */
  _0624(
      "0624",
      "MEDICAL/SURGICAL SUPPLIES AND DEVICES - EXTENSION OF 027X - FDA INVESTIGATIONAL DEVICES"),
  /** 0631 - PHARMACY - EXTENSION OF 025X - SINGLE SOURCE DRUG. */
  _0631("0631", "PHARMACY - EXTENSION OF 025X - SINGLE SOURCE DRUG"),
  /** 0632 - PHARMACY - EXTENSION OF 025X - MULTIPLE SOURCE DRUG. */
  _0632("0632", "PHARMACY - EXTENSION OF 025X - MULTIPLE SOURCE DRUG"),
  /** 0633 - PHARMACY - EXTENSION OF 025X - RESTRICTIVE PRESCRIPTION. */
  _0633("0633", "PHARMACY - EXTENSION OF 025X - RESTRICTIVE PRESCRIPTION"),
  /** 0634 - PHARMACY - EXTENSION OF 025X - ERYTHROPOIETIN (EPO) &lt;10,000 UNITS. */
  _0634("0634", "PHARMACY - EXTENSION OF 025X - ERYTHROPOIETIN (EPO) <10,000 UNITS"),
  /** 0635 - PHARMACY - EXTENSION OF 025X - ERYTHROPOIETIN (EPO) &gt;=10,000 UNITS. */
  _0635("0635", "PHARMACY - EXTENSION OF 025X - ERYTHROPOIETIN (EPO) >=10,000 UNITS"),
  /** 0636 - PHARMACY - EXTENSION OF 025X - DRUGS REQUIRING DETAILED CODING. */
  _0636("0636", "PHARMACY - EXTENSION OF 025X - DRUGS REQUIRING DETAILED CODING"),
  /** 0637 - PHARMACY - EXTENSION OF 025X - SELF-ADMINISTRABLE DRUGS. */
  _0637("0637", "PHARMACY - EXTENSION OF 025X - SELF-ADMINISTRABLE DRUGS"),
  /** 0640 - HOME IV THERAPY SERVICES - GENERAL CLASSIFICATION. */
  _0640("0640", "HOME IV THERAPY SERVICES - GENERAL CLASSIFICATION"),
  /** 0641 - HOME IV THERAPY SERVICES - NON-ROUTINE NURSING, CENTRAL LINE. */
  _0641("0641", "HOME IV THERAPY SERVICES - NON-ROUTINE NURSING, CENTRAL LINE"),
  /** 0642 - HOME IV THERAPY SERVICES - IV SITE CARE, CENTRAL LINE. */
  _0642("0642", "HOME IV THERAPY SERVICES - IV SITE CARE, CENTRAL LINE"),
  /** 0643 - HOME IV THERAPY SERVICES - IV START/CHANGE, PERIPHERAL LINE. */
  _0643("0643", "HOME IV THERAPY SERVICES - IV START/CHANGE,  PERIPHERAL LINE"),
  /** 0644 - HOME IV THERAPY SERVICES - NON-ROUTINE NURSING, PERIPHERAL LINE. */
  _0644("0644", "HOME IV THERAPY SERVICES - NON-ROUTINE NURSING,  PERIPHERAL LINE"),
  /** 0645 - HOME IV THERAPY SERVICES - TRAINING PATIENT/CAREGIVER, CENTRAL LINE. */
  _0645("0645", "HOME IV THERAPY SERVICES - TRAINING PATIENT/CAREGIVER,  CENTRAL LINE"),
  /** 0646 - HOME IV THERAPY SERVICES - TRAINING DISABLED PATIENT, CENTRAL LINE. */
  _0646("0646", "HOME IV THERAPY SERVICES - TRAINING  DISABLED PATIENT,  CENTRAL LINE"),
  /** 0647 - HOME IV THERAPY SERVICES - TRAINING PATIENT/ CAREGIVER, PERIPHERAL LINE. */
  _0647("0647", "HOME IV THERAPY SERVICES - TRAINING  PATIENT/ CAREGIVER, PERIPHERAL LINE"),
  /** 0648 - HOME IV THERAPY SERVICES - TRAINING DISABLED PATIENT, PERIPHERAL LINE. */
  _0648("0648", "HOME IV THERAPY SERVICES - TRAINING DISABLED PATIENT,  PERIPHERAL LINE"),
  /** 0649 - HOME IV THERAPY SERVICES - OTHER IV THERAPY SERVICES. */
  _0649("0649", "HOME IV THERAPY SERVICES - OTHER IV THERAPY SERVICES"),
  /** 0650 - HOSPICE SERVICE - GENERAL CLASSIFICATION. */
  _0650("0650", "HOSPICE SERVICE - GENERAL CLASSIFICATION"),
  /** 0651 - HOSPICE SERVICE - ROUTINE HOME CARE. */
  _0651("0651", "HOSPICE SERVICE - ROUTINE HOME CARE"),
  /** 0652 - HOSPICE SERVICE - CONTINUOUS HOME CARE. */
  _0652("0652", "HOSPICE SERVICE - CONTINUOUS HOME CARE"),
  /** 0655 - HOSPICE SERVICE - INPATIENT RESPITE CARE. */
  _0655("0655", "HOSPICE SERVICE - INPATIENT RESPITE CARE"),
  /** 0656 - HOSPICE SERVICE - GENERAL INPATIENT CARE NON-RESPITE. */
  _0656("0656", "HOSPICE SERVICE - GENERAL INPATIENT CARE NON-RESPITE"),
  /** 0657 - HOSPICE SERVICE - PHYSICIAN SERVICES. */
  _0657("0657", "HOSPICE SERVICE - PHYSICIAN SERVICES"),
  /** 0658 - HOSPICE SERVICE - HOSPICE ROOM &amp; BOARD - NURSING FACILITY. */
  _0658("0658", "HOSPICE SERVICE - HOSPICE ROOM & BOARD - NURSING FACILITY"),
  /** 0659 - HOSPICE SERVICE - OTHER HOSPICE SERVICE. */
  _0659("0659", "HOSPICE SERVICE - OTHER HOSPICE SERVICE"),
  /** 0660 - RESPITE CARE - GENERAL CLASSIFICATION. */
  _0660("0660", "RESPITE CARE - GENERAL CLASSIFICATION"),
  /** 0661 - RESPITE CARE - HOURLY CHARGE - NURSING. */
  _0661("0661", "RESPITE CARE - HOURLY CHARGE - NURSING"),
  /** 0662 - RESPITE CARE - HOURLY CHARGE - AIDE/HOMEMAKER/COMPANION. */
  _0662("0662", "RESPITE CARE - HOURLY CHARGE - AIDE/HOMEMAKER/COMPANION"),
  /** 0663 - RESPITE CARE - DAILY RESPITE CHARGE. */
  _0663("0663", "RESPITE CARE - DAILY RESPITE CHARGE"),
  /** 0669 - RESPITE CARE - OTHER RESPITE CARE. */
  _0669("0669", "RESPITE CARE - OTHER RESPITE CARE"),
  /** 0670 - OUTPATIENT SPECIAL RESIDENCE CHARGES - GENERAL CLASSIFICATION. */
  _0670("0670", "OUTPATIENT SPECIAL RESIDENCE CHARGES - GENERAL CLASSIFICATION"),
  /** 0671 - OUTPATIENT SPECIAL RESIDENCE CHARGES - HOSPITAL OWNED. */
  _0671("0671", "OUTPATIENT SPECIAL RESIDENCE CHARGES - HOSPITAL OWNED"),
  /** 0672 - OUTPATIENT SPECIAL RESIDENCE CHARGES - CONTRACTED. */
  _0672("0672", "OUTPATIENT SPECIAL RESIDENCE CHARGES - CONTRACTED"),
  /** 0679 - OUTPATIENT SPECIAL RESIDENCE CHARGES - OTHER SPECIAL RESIDENCE CHARGE. */
  _0679("0679", "OUTPATIENT SPECIAL RESIDENCE CHARGES - OTHER SPECIAL RESIDENCE CHARGE"),
  /** 0680 - TRAUMA RESPONSE - NOT USED. */
  _0680("0680", "TRAUMA RESPONSE - NOT USED"),
  /** 0681 - TRAUMA RESPONSE - LEVEL I TRAUMA. */
  _0681("0681", "TRAUMA RESPONSE - LEVEL I TRAUMA"),
  /** 0682 - TRAUMA RESPONSE - LEVEL II TRAUMA. */
  _0682("0682", "TRAUMA RESPONSE - LEVEL II TRAUMA"),
  /** 0683 - TRAUMA RESPONSE - LEVEL III TRAUMA. */
  _0683("0683", "TRAUMA RESPONSE - LEVEL III TRAUMA"),
  /** 0684 - TRAUMA RESPONSE - LEVEL IV TRAUMA. */
  _0684("0684", "TRAUMA RESPONSE - LEVEL IV TRAUMA"),
  /** 0689 - TRAUMA RESPONSE - OTHER TRAUMA RESPONSE. */
  _0689("0689", "TRAUMA RESPONSE - OTHER TRAUMA RESPONSE"),
  /** 0690 - PRE-HOSPICE/PALLIATIVE CARE SERVICES - GENERAL CLASSIFICATION (EFFECTIVE 1/1/14). */
  _0690("0690", "PRE-HOSPICE/PALLIATIVE CARE SERVICES - GENERAL CLASSIFICATION (EFFECTIVE 1/1/14)"),
  /** 0691 - PRE-HOSPICE/PALLIATIVE CARE SERVICES - VISIT CHARGE (EFFECTIVE 1/1/14). */
  _0691("0691", "PRE-HOSPICE/PALLIATIVE CARE SERVICES - VISIT CHARGE (EFFECTIVE 1/1/14)"),
  /** 0692 - PRE-HOSPICE/PALLIATIVE CARE SERVICES - HOURLY CHARGE (EFFECTIVE 1/1/14). */
  _0692("0692", "PRE-HOSPICE/PALLIATIVE CARE SERVICES - HOURLY CHARGE (EFFECTIVE 1/1/14)"),
  /** 0693 - PRE-HOSPICE/PALLIATIVE CARE SERVICES - EVALUATION (EFFECTIVE 1/1/14). */
  _0693("0693", "PRE-HOSPICE/PALLIATIVE CARE SERVICES - EVALUATION (EFFECTIVE 1/1/14)"),
  /**
   * 0694 - PRE-HOSPICE/PALLIATIVE CARE SERVICES - CONSULTATION AND EDUCATION (EFFECTIVE 1/1/14).
   */
  _0694(
      "0694",
      "PRE-HOSPICE/PALLIATIVE CARE SERVICES - CONSULTATION AND EDUCATION (EFFECTIVE 1/1/14)"),
  /** 0695 - PRE-HOSPICE/PALLIATIVE CARE SERVICES - INPATIENT CARE (EFFECTIVE 1/1/14). */
  _0695("0695", "PRE-HOSPICE/PALLIATIVE CARE SERVICES - INPATIENT CARE (EFFECTIVE 1/1/14)"),
  /** 0696 - PRE-HOSPICE/PALLIATIVE CARE SERVICES - PHYSICIAN SERVICES (EFFECTIVE 1/1/14). */
  _0696("0696", "PRE-HOSPICE/PALLIATIVE CARE SERVICES - PHYSICIAN SERVICES (EFFECTIVE 1/1/14)"),
  /**
   * 0699 - PRE-HOSPICE/PALLIATIVE CARE SERVICES - OTHER PRE-HOSPICE/PALLIATIVE CARE SERVICES
   * (EFFECTIVE 1/1/14).
   */
  _0699(
      "0699",
      "PRE-HOSPICE/PALLIATIVE CARE SERVICES - OTHER PRE-HOSPICE/PALLIATIVE CARE SERVICES (EFFECTIVE 1/1/14)"),
  /** 0700 - CAST ROOM - GENERAL CLASSIFICATION. */
  _0700("0700", "CAST ROOM - GENERAL CLASSIFICATION"),
  /** 0710 - RECOVERY ROOM - GENERAL CLASSIFICATION. */
  _0710("0710", "RECOVERY ROOM - GENERAL CLASSIFICATION"),
  /** 0720 - LABOR ROOM/DELIVERY - GENERAL CLASSIFICATION. */
  _0720("0720", "LABOR ROOM/DELIVERY - GENERAL CLASSIFICATION"),
  /** 0721 - LABOR ROOM/DELIVERY - LABOR. */
  _0721("0721", "LABOR ROOM/DELIVERY - LABOR"),
  /** 0722 - LABOR ROOM/DELIVERY - DELIVERY ROOM. */
  _0722("0722", "LABOR ROOM/DELIVERY - DELIVERY ROOM"),
  /** 0723 - LABOR ROOM/DELIVERY - CIRCUMCISION. */
  _0723("0723", "LABOR ROOM/DELIVERY - CIRCUMCISION"),
  /** 0724 - LABOR ROOM/DELIVERY - BIRTHING CENTER. */
  _0724("0724", "LABOR ROOM/DELIVERY - BIRTHING CENTER"),
  /** 0729 - LABOR ROOM/DELIVERY - OTHER LABOR ROOM/DELIVERY. */
  _0729("0729", "LABOR ROOM/DELIVERY - OTHER LABOR ROOM/DELIVERY"),
  /** 0730 - EKG/ECG (ELECTROCARDIOGRAM) - GENERAL CLASSIFICATION. */
  _0730("0730", "EKG/ECG (ELECTROCARDIOGRAM) - GENERAL CLASSIFICATION"),
  /** 0731 - EKG/ECG (ELECTROCARDIOGRAM) - HOLTER MONITOR. */
  _0731("0731", "EKG/ECG (ELECTROCARDIOGRAM) - HOLTER MONITOR"),
  /** 0732 - EKG/ECG (ELECTROCARDIOGRAM) - TELEMETRY. */
  _0732("0732", "EKG/ECG (ELECTROCARDIOGRAM) - TELEMETRY"),
  /** 0739 - EKG/ECG (ELECTROCARDIOGRAM) - OTHER EKG/ECG. */
  _0739("0739", "EKG/ECG (ELECTROCARDIOGRAM) - OTHER EKG/ECG"),
  /** 0740 - EEG (ELECTROENCEPHALOGRAM) - GENERAL CLASSIFICATION. */
  _0740("0740", "EEG (ELECTROENCEPHALOGRAM) - GENERAL CLASSIFICATION"),
  /** 0750 - GASTRO - INTESTINAL (GI) SERVICES - GENERAL CLASSIFICATION. */
  _0750("0750", "GASTRO - INTESTINAL (GI) SERVICES - GENERAL CLASSIFICATION"),
  /** 0760 - SPECIALTY SERVICES - GENERAL CLASSIFICATION. */
  _0760("0760", "SPECIALTY SERVICES - GENERAL CLASSIFICATION"),
  /** 0761 - SPECIALTY SERVICES - TREATMENT ROOM. */
  _0761("0761", "SPECIALTY SERVICES - TREATMENT ROOM"),
  /** 0762 - SPECIALTY SERVICES - OBSERVATION HOURS. */
  _0762("0762", "SPECIALTY SERVICES - OBSERVATION HOURS"),
  /** 0769 - SPECIALTY SERVICES - OTHER SPECIALTY SERVICES. */
  _0769("0769", "SPECIALTY SERVICES - OTHER SPECIALTY SERVICES"),
  /** 0770 - PREVENTIVE CARE SERVICES - GENERAL CLASSIFICATION. */
  _0770("0770", "PREVENTIVE CARE SERVICES - GENERAL CLASSIFICATION"),
  /** 0771 - PREVENTIVE CARE SERVICES - VACCINE ADMINISTRATION. */
  _0771("0771", "PREVENTIVE CARE SERVICES - VACCINE ADMINISTRATION"),
  /** 0780 - TELEMEDICINE - GENERAL CLASSIFICATION. */
  _0780("0780", "TELEMEDICINE - GENERAL CLASSIFICATION"),
  /** 0790 - EXTRA-CORPOREAL SHOCK WAVE THERAPY (FORMERLY LITHOTRIPSY) - GENERAL CLASSIFICATION. */
  _0790(
      "0790", "EXTRA-CORPOREAL SHOCK WAVE THERAPY (FORMERLY LITHOTRIPSY) - GENERAL CLASSIFICATION"),
  /** 0800 - INPATIENT RENAL DIALYSIS - GENERAL CLASSIFICATION. */
  _0800("0800", "INPATIENT RENAL DIALYSIS - GENERAL CLASSIFICATION"),
  /** 0801 - INPATIENT RENAL DIALYSIS - INPATIENT HEMODIALYSIS. */
  _0801("0801", "INPATIENT RENAL DIALYSIS - INPATIENT HEMODIALYSIS"),
  /** 0802 - INPATIENT RENAL DIALYSIS - INPATIENT PERITONEAL (NON-CAPD). */
  _0802("0802", "INPATIENT RENAL DIALYSIS - INPATIENT PERITONEAL (NON-CAPD)"),
  /**
   * 0803 - INPATIENT RENAL DIALYSIS - INPATIENT CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD).
   */
  _0803(
      "0803",
      "INPATIENT RENAL DIALYSIS - INPATIENT CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD)"),
  /** 0804 - INPATIENT RENAL DIALYSIS - INPATIENT CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD). */
  _0804(
      "0804", "INPATIENT RENAL DIALYSIS - INPATIENT CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD)"),
  /** 0809 - INPATIENT RENAL DIALYSIS - OTHER INPATIENT DIALYSIS. */
  _0809("0809", "INPATIENT RENAL DIALYSIS - OTHER INPATIENT DIALYSIS"),
  /** 0810 - ACQUISITION OF BODY COMPONENTS - GENERAL CLASSIFICATION. */
  _0810("0810", "ACQUISITION OF BODY COMPONENTS - GENERAL CLASSIFICATION"),
  /** 0811 - ACQUISITION OF BODY COMPONENTS - LIVING DONOR. */
  _0811("0811", "ACQUISITION OF BODY COMPONENTS - LIVING DONOR"),
  /** 0812 - ACQUISITION OF BODY COMPONENTS - CADAVER DONOR. */
  _0812("0812", "ACQUISITION OF BODY COMPONENTS - CADAVER DONOR"),
  /** 0813 - ACQUISITION OF BODY COMPONENTS - UNKNOWN DONOR. */
  _0813("0813", "ACQUISITION OF BODY COMPONENTS - UNKNOWN DONOR"),
  /** 0814 - ACQUISITION OF BODY COMPONENTS - UNSUCCESSFUL ORGAN SEARCH - DONOR BANK CHARGES. */
  _0814("0814", "ACQUISITION OF BODY COMPONENTS - UNSUCCESSFUL ORGAN SEARCH - DONOR BANK CHARGES"),
  /** 0815 - ACQUISITION OF BODY COMPONENTS - ALLOGENEIC (EFFECTIVE 1/1/17). */
  _0815("0815", "ACQUISITION OF BODY COMPONENTS - ALLOGENEIC (EFFECTIVE 1/1/17)"),
  /** 0819 - ACQUISITION OF BODY COMPONENTS - OTHER DONOR. */
  _0819("0819", "ACQUISITION OF BODY COMPONENTS - OTHER DONOR"),
  /** 0820 - HEMODIALYSIS - OUTPATIENT OR HOME - GENERAL CLASSIFICATION. */
  _0820("0820", "HEMODIALYSIS - OUTPATIENT OR HOME - GENERAL CLASSIFICATION"),
  /** 0821 - HEMODIALYSIS - OUTPATIENT OR HOME - HEMODIALYSIS COMPOSITE OR OTHER RATE. */
  _0821("0821", "HEMODIALYSIS - OUTPATIENT OR HOME - HEMODIALYSIS COMPOSITE OR OTHER RATE"),
  /** 0822 - HEMODIALYSIS - OUTPATIENT OR HOME - HOME SUPPLIES. */
  _0822("0822", "HEMODIALYSIS - OUTPATIENT OR HOME - HOME SUPPLIES"),
  /** 0823 - HEMODIALYSIS - OUTPATIENT OR HOME - HOME EQUIPMENT. */
  _0823("0823", "HEMODIALYSIS - OUTPATIENT OR HOME - HOME EQUIPMENT"),
  /** 0824 - HEMODIALYSIS - OUTPATIENT OR HOME - MAINTENANCE - 100%. */
  _0824("0824", "HEMODIALYSIS - OUTPATIENT OR HOME - MAINTENANCE - 100%"),
  /** 0825 - HEMODIALYSIS - OUTPATIENT OR HOME - SUPPORT SERVICES. */
  _0825("0825", "HEMODIALYSIS - OUTPATIENT OR HOME - SUPPORT SERVICES"),
  /** 0826 - HEMODIALYSIS - SHORTER DURATION. */
  _0826("0826", "HEMODIALYSIS - SHORTER DURATION"),
  /** 0829 - HEMODIALYSIS - OUTPATIENT OR HOME - OTHER OP HEMODIALYSIS. */
  _0829("0829", "HEMODIALYSIS - OUTPATIENT OR HOME - OTHER OP HEMODIALYSIS"),
  /** 0830 - PERITONEAL DIALYSIS - OUTPATIENT OR HOME - GENERAL CLASSIFICATION. */
  _0830("0830", "PERITONEAL DIALYSIS - OUTPATIENT OR HOME - GENERAL CLASSIFICATION"),
  /** 0831 - PERITONEAL DIALYSIS - OUTPATIENT OR HOME - PERITONEAL/COMPOSITE OR OTHER RATE. */
  _0831("0831", "PERITONEAL DIALYSIS - OUTPATIENT OR HOME - PERITONEAL/COMPOSITE OR OTHER RATE"),
  /** 0832 - PERITONEAL DIALYSIS - OUTPATIENT OR HOME - HOME SUPPLIES. */
  _0832("0832", "PERITONEAL DIALYSIS - OUTPATIENT OR HOME - HOME SUPPLIES"),
  /** 0833 - PERITONEAL DIALYSIS - OUTPATIENT OR HOME - HOME EQUIPMENT. */
  _0833("0833", "PERITONEAL DIALYSIS - OUTPATIENT OR HOME - HOME EQUIPMENT"),
  /** 0834 - PERITONEAL DIALYSIS - OUTPATIENT OR HOME - MAINTENANCE - 100%. */
  _0834("0834", "PERITONEAL DIALYSIS - OUTPATIENT OR HOME - MAINTENANCE - 100%"),
  /** 0835 - PERITONEAL DIALYSIS - OUTPATIENT OR HOME - SUPPORT SERVICES. */
  _0835("0835", "PERITONEAL DIALYSIS - OUTPATIENT OR HOME - SUPPORT SERVICES"),
  /** 0839 - PERITONEAL DIALYSIS - OUTPATIENT OR HOME - OTHER OUTPATIENT PERITONEAL DIALYSIS. */
  _0839("0839", "PERITONEAL DIALYSIS - OUTPATIENT OR HOME - OTHER OUTPATIENT PERITONEAL DIALYSIS"),
  /**
   * 0840 - CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - GENERAL
   * CLASSIFICATION.
   */
  _0840(
      "0840",
      "CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - GENERAL CLASSIFICATION"),
  /**
   * 0841 - CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - CAPD/COMPOSITE
   * OR OTHER RATE.
   */
  _0841(
      "0841",
      "CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - CAPD/COMPOSITE OR OTHER RATE"),
  /**
   * 0842 - CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - HOME SUPPLIES.
   */
  _0842(
      "0842",
      "CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - HOME SUPPLIES"),
  /**
   * 0843 - CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - HOME EQUIPMENT.
   */
  _0843(
      "0843",
      "CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - HOME EQUIPMENT"),
  /**
   * 0844 - CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - MAINTENANCE -
   * 100%.
   */
  _0844(
      "0844",
      "CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - MAINTENANCE - 100%"),
  /**
   * 0845 - CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - SUPPORT
   * SERVICES.
   */
  _0845(
      "0845",
      "CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - SUPPORT SERVICES"),
  /**
   * 0849 - CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - OTHER OUTPATIENT
   * CAPD.
   */
  _0849(
      "0849",
      "CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD) - OUTPATIENT OR HOME - OTHER OUTPATIENT CAPD"),
  /**
   * 0850 - CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - GENERAL
   * CLASSIFICATION.
   */
  _0850(
      "0850",
      "CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - GENERAL CLASSIFICATION"),
  /**
   * 0851 - CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - CCPD/COMPOSITE OR
   * OTHER RATE.
   */
  _0851(
      "0851",
      "CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - CCPD/COMPOSITE OR OTHER RATE"),
  /** 0852 - CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - HOME SUPPLIES. */
  _0852(
      "0852", "CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - HOME SUPPLIES"),
  /** 0853 - CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - HOME EQUIPMENT. */
  _0853(
      "0853",
      "CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - HOME EQUIPMENT"),
  /**
   * 0854 - CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - MAINTENANCE - 100%.
   */
  _0854(
      "0854",
      "CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - MAINTENANCE - 100%"),
  /**
   * 0855 - CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - SUPPORT SERVICES.
   */
  _0855(
      "0855",
      "CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - SUPPORT SERVICES"),
  /**
   * 0859 - CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - OTHER OUTPATIENT
   * CCPD.
   */
  _0859(
      "0859",
      "CONTINUOUS CYCLING PERITONEAL DIALYSIS (CCPD) - OUTPATIENT OR HOME - OTHER OUTPATIENT CCPD"),
  /** 0860 - MAGNETOENCEPHALOGRAPHY (MEG) - GENERAL CLASSIFICATION. */
  _0860("0860", "MAGNETOENCEPHALOGRAPHY (MEG) - GENERAL CLASSIFICATION"),
  /** 0861 - MAGNETOENCEPHALOGRAPHY (MEG) - MEG. */
  _0861("0861", "MAGNETOENCEPHALOGRAPHY (MEG) - MEG"),
  /** 0870 - CELL/GENE THERAPY - GENERAL CLASSIFICATION. */
  _0870("0870", "CELL/GENE THERAPY - GENERAL CLASSIFICATION"),
  /** 0871 - CELL/GENE THERAPY - CELL COLLECTION (EFFECTIVE 4/1/19). */
  _0871("0871", "CELL/GENE THERAPY - CELL COLLECTION (EFFECTIVE 4/1/19)"),
  /**
   * 0872 - CELL/GENE THERAPY - SPECIALIZED BIOLOGIC PROCESSING AND STORAGE - PRIOR TO TRANSPORT
   * (EFFECTIVE 4/1/19).
   */
  _0872(
      "0872",
      "CELL/GENE THERAPY - SPECIALIZED BIOLOGIC PROCESSING AND STORAGE - PRIOR TO TRANSPORT (EFFECTIVE 4/1/19)"),
  /**
   * 0873 - CELL/GENE THERAPY - STORAGE AND PROCESSING AFTER RECEIPT OF CELLS FROM MANUFACTURER
   * (EFFECTIVE 4/1/19).
   */
  _0873(
      "0873",
      "CELL/GENE THERAPY - STORAGE AND PROCESSING AFTER RECEIPT OF CELLS FROM MANUFACTURER (EFFECTIVE 4/1/19)"),
  /** 0874 - CELL/GENE THERAPY - INFUSION OF MODIFIED CELLS (EFFECTIVE 4/1/19). */
  _0874("0874", "CELL/GENE THERAPY - INFUSION OF MODIFIED CELLS (EFFECTIVE 4/1/19)"),
  /** 0875 - CELL/GENE THERAPY - INJECTION OF MODIFIED CELLS (EFFECTIVE 4/1/19). */
  _0875("0875", "CELL/GENE THERAPY - INJECTION OF MODIFIED CELLS (EFFECTIVE 4/1/19)"),
  /** 0880 - MISCELLANEOUS DIALYSIS - GENERAL CLASSIFICATION. */
  _0880("0880", "MISCELLANEOUS DIALYSIS - GENERAL CLASSIFICATION"),
  /** 0881 - MISCELLANEOUS DIALYSIS - ULTRAFILTRATION. */
  _0881("0881", "MISCELLANEOUS DIALYSIS - ULTRAFILTRATION"),
  /** 0882 - MISCELLANEOUS DIALYSIS - HOME DIALYSIS AID VISIT. */
  _0882("0882", "MISCELLANEOUS DIALYSIS - HOME DIALYSIS AID VISIT"),
  /** 0889 - MISCELLANEOUS DIALYSIS - OTHER MISCELLANEOUS DIALYSIS. */
  _0889("0889", "MISCELLANEOUS DIALYSIS - OTHER MISCELLANEOUS DIALYSIS"),
  /**
   * 0891 - PHARMACY - EXTENSION OF 025X AND 063X - SPECIAL PROCESSED DRUGS - FDA APPROVED CELL
   * THERAPY (EFFECTIVE 4/1/19).
   */
  _0891(
      "0891",
      "PHARMACY - EXTENSION OF 025X AND 063X - SPECIAL PROCESSED DRUGS - FDA APPROVED CELL THERAPY (EFFECTIVE 4/1/19)"),
  /**
   * 0892 - PHARMACY - EXTENSION OF 025X AND 063X - SSPECIAL PROCESSED DRUGS - FDA APPROVED GENE
   * THERAPY (EFFECTIVE 4/1/2020).
   */
  _0892(
      "0892",
      "PHARMACY - EXTENSION OF 025X AND 063X - SSPECIAL PROCESSED DRUGS - FDA APPROVED GENE THERAPY (EFFECTIVE 4/1/2020)"),
  /**
   * 0900 - BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - GENERAL
   * CLASSIFICATION.
   */
  _0900(
      "0900",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - GENERAL CLASSIFICATION"),
  /**
   * 0901 - BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) -
   * ELECTROSHOCK TREATMENT.
   */
  _0901(
      "0901",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - ELECTROSHOCK TREATMENT"),
  /**
   * 0902 - BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - MILIEU
   * THERAPY.
   */
  _0902(
      "0902",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - MILIEU THERAPY"),
  /**
   * 0903 - BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - PLAY
   * THERAPY.
   */
  _0903(
      "0903",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - PLAY THERAPY"),
  /**
   * 0904 - BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - ACTIVITY
   * THERAPY.
   */
  _0904(
      "0904",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - ACTIVITY THERAPY"),
  /**
   * 0905 - BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - INTENSIVE
   * OUTPATIENT SERVICES - PSYCHIATRIC.
   */
  _0905(
      "0905",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - INTENSIVE OUTPATIENT SERVICES - PSYCHIATRIC"),
  /**
   * 0906 - BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - INTENSIVE
   * OUTPATIENT SERVICES - CHEMICAL DEPENDENCY.
   */
  _0906(
      "0906",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - INTENSIVE OUTPATIENT SERVICES - CHEMICAL DEPENDENCY"),
  /**
   * 0907 - BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - COMMUNITY
   * BEHAVIORAL HEALTH PROGRAM (DAY TREATMENT).
   */
  _0907(
      "0907",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES (ALSO SEE 091X, AN EXTENSION OF 090X) - COMMUNITY BEHAVIORAL HEALTH PROGRAM (DAY TREATMENT)"),
  /** 0911 - BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - REHABILITATION. */
  _0911("0911", "BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - REHABILITATION"),
  /**
   * 0912 - BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - PARTIAL HOSPITALIZATION -
   * LESS INTENSIVE.
   */
  _0912(
      "0912",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - PARTIAL HOSPITALIZATION - LESS INTENSIVE"),
  /**
   * 0913 - BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - PARTIAL HOSPITALIZATION -
   * INTENSIVE.
   */
  _0913(
      "0913",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - PARTIAL HOSPITALIZATION - INTENSIVE"),
  /** 0914 - BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - INDIVIDUAL THERAPY. */
  _0914("0914", "BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - INDIVIDUAL THERAPY"),
  /** 0915 - BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - GROUP THERAPY. */
  _0915("0915", "BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - GROUP THERAPY"),
  /** 0916 - BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - FAMILY THERAPY. */
  _0916("0916", "BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - FAMILY THERAPY"),
  /** 0917 - BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - BIO FEEDBACK. */
  _0917("0917", "BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - BIO FEEDBACK"),
  /** 0918 - BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - TESTING. */
  _0918("0918", "BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - TESTING"),
  /**
   * 0919 - BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - OTHER BEHAVIORAL HEALTH
   * TREATMENTS.
   */
  _0919(
      "0919",
      "BEHAVIORAL HEALTH TREATMENT/SERVICES - EXTENSION OF 090X - OTHER BEHAVIORAL HEALTH TREATMENTS"),
  /** 0920 - OTHER DIAGNOSTIC SERVICES - GENERAL CLASSIFICATION. */
  _0920("0920", "OTHER DIAGNOSTIC SERVICES - GENERAL CLASSIFICATION"),
  /** 0921 - OTHER DIAGNOSTIC SERVICES - PERIPHERAL VASCULAR LAB. */
  _0921("0921", "OTHER DIAGNOSTIC SERVICES - PERIPHERAL VASCULAR LAB"),
  /** 0922 - OTHER DIAGNOSTIC SERVICES - ELECTROMYOGRAM. */
  _0922("0922", "OTHER DIAGNOSTIC SERVICES - ELECTROMYOGRAM"),
  /** 0923 - OTHER DIAGNOSTIC SERVICES - PAP SMEAR. */
  _0923("0923", "OTHER DIAGNOSTIC SERVICES - PAP SMEAR"),
  /** 0924 - OTHER DIAGNOSTIC SERVICES - ALLERGY TEST. */
  _0924("0924", "OTHER DIAGNOSTIC SERVICES - ALLERGY TEST"),
  /** 0925 - OTHER DIAGNOSTIC SERVICES - PREGNANCY TEST. */
  _0925("0925", "OTHER DIAGNOSTIC SERVICES - PREGNANCY TEST"),
  /** 0929 - OTHER DIAGNOSTIC SERVICES - OTHER DIAGNOSTIC SERVICE. */
  _0929("0929", "OTHER DIAGNOSTIC SERVICES - OTHER DIAGNOSTIC SERVICE"),
  /** 0931 - MEDICAL REHABILITATION DAY PROGRAM - HALF DAY. */
  _0931("0931", "MEDICAL REHABILITATION DAY PROGRAM - HALF DAY"),
  /** 0932 - MEDICAL REHABILITATION DAY PROGRAM - FULL DAY. */
  _0932("0932", "MEDICAL REHABILITATION DAY PROGRAM - FULL DAY"),
  /**
   * 0940 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - GENERAL
   * CLASSIFICATION.
   */
  _0940(
      "0940",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X,  AN EXTENSION OF 094X) - GENERAL CLASSIFICATION"),
  /**
   * 0941 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - RECREATIONAL THERAPY.
   */
  _0941(
      "0941",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X,  AN EXTENSION OF 094X) - RECREATIONAL THERAPY"),
  /**
   * 0942 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - EDUCATION/TRAINING.
   */
  _0942(
      "0942",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X,  AN EXTENSION OF 094X) - EDUCATION/TRAINING"),
  /**
   * 0943 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - CARDIAC
   * REHABILITATION.
   */
  _0943(
      "0943",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X,  AN EXTENSION OF 094X) - CARDIAC REHABILITATION"),
  /**
   * 0944 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - DRUG REHABILITATION.
   */
  _0944(
      "0944",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X,  AN EXTENSION OF 094X) - DRUG REHABILITATION"),
  /**
   * 0945 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - ALCOHOL
   * REHABILITATION.
   */
  _0945(
      "0945",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X,  AN EXTENSION OF 094X) - ALCOHOL REHABILITATION"),
  /**
   * 0946 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - COMPLEX MEDICAL
   * EQUIPMENT - ROUTINE.
   */
  _0946(
      "0946",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - COMPLEX MEDICAL EQUIPMENT - ROUTINE"),
  /**
   * 0947 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - COMPLEX MEDICAL
   * EQUIPMENT - ANCILLARY.
   */
  _0947(
      "0947",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - COMPLEX MEDICAL EQUIPMENT - ANCILLARY"),
  /**
   * 0948 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - PULMONARY
   * REHABILITATION.
   */
  _0948(
      "0948",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - PULMONARY REHABILITATION"),
  /**
   * 0949 - OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - OTHER THERAPEUTIC
   * SERVICE.
   */
  _0949(
      "0949",
      "OTHER THERAPEUTIC SERVICES (ALSO SEE 095X, AN EXTENSION OF 094X) - OTHER THERAPEUTIC SERVICE"),
  /** 0951 - OTHER THERAPEUTIC SERVICES (EXTENSION OF 094X) - ATHLETIC TRAINING. */
  _0951("0951", "OTHER THERAPEUTIC SERVICES (EXTENSION OF 094X) - ATHLETIC TRAINING"),
  /** 0952 - OTHER THERAPEUTIC SERVICES (EXTENSION OF 094X) - KINESIOTHERAPY. */
  _0952("0952", "OTHER THERAPEUTIC SERVICES (EXTENSION OF 094X) - KINESIOTHERAPY"),
  /**
   * 0953 - OTHER THERAPEUTIC SERVICES (EXTENSION OF 094X) - CHEMICAL DEPENDENCY (DRUG AND ALCOHOL).
   */
  _0953(
      "0953",
      "OTHER THERAPEUTIC SERVICES (EXTENSION OF 094X) - CHEMICAL DEPENDENCY (DRUG AND ALCOHOL)"),
  /** 0960 - PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - GENERAL CLASSIFICATION. */
  _0960("0960", "PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - GENERAL CLASSIFICATION"),
  /** 0961 - PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - PSYCHIATRIC. */
  _0961("0961", "PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - PSYCHIATRIC"),
  /** 0962 - PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - OPHTHALMOLOGY. */
  _0962("0962", "PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - OPHTHALMOLOGY"),
  /** 0963 - PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - ANESTHESIOLOGIST (MD). */
  _0963("0963", "PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - ANESTHESIOLOGIST (MD)"),
  /** 0964 - PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - ANESTHETIST (CRNA). */
  _0964("0964", "PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - ANESTHETIST (CRNA)"),
  /** 0969 - PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - OTHER PROFESSIONAL FEE. */
  _0969("0969", "PROFESSIONAL FEES (ALSO SEE 097X AND 098X) - OTHER PROFESSIONAL FEE"),
  /** 0971 - PROFESSIONAL FEES (EXTENSION OF 096X) - LABORATORY. */
  _0971("0971", "PROFESSIONAL FEES (EXTENSION OF 096X) - LABORATORY"),
  /** 0972 - PROFESSIONAL FEES (EXTENSION OF 096X) - RADIOLOGY - DIAGNOSTIC. */
  _0972("0972", "PROFESSIONAL FEES (EXTENSION OF 096X) - RADIOLOGY - DIAGNOSTIC"),
  /** 0973 - PROFESSIONAL FEES (EXTENSION OF 096X) - RADIOLOGY - THERAPEUTIC. */
  _0973("0973", "PROFESSIONAL FEES (EXTENSION OF 096X) - RADIOLOGY - THERAPEUTIC"),
  /** 0974 - PROFESSIONAL FEES (EXTENSION OF 096X) - RADIOLOGY - NUCLEAR. */
  _0974("0974", "PROFESSIONAL FEES (EXTENSION OF 096X) - RADIOLOGY - NUCLEAR"),
  /** 0975 - PROFESSIONAL FEES (EXTENSION OF 096X) - OPERATING ROOM. */
  _0975("0975", "PROFESSIONAL FEES (EXTENSION OF 096X) - OPERATING ROOM"),
  /** 0976 - PROFESSIONAL FEES (EXTENSION OF 096X) - RESPIRATORY THERAPY. */
  _0976("0976", "PROFESSIONAL FEES (EXTENSION OF 096X) - RESPIRATORY THERAPY"),
  /** 0977 - PROFESSIONAL FEES (EXTENSION OF 096X) - PHYSICAL THERAPY. */
  _0977("0977", "PROFESSIONAL FEES (EXTENSION OF 096X) - PHYSICAL THERAPY"),
  /** 0978 - PROFESSIONAL FEES (EXTENSION OF 096X) - OCCUPATIONAL THERAPY. */
  _0978("0978", "PROFESSIONAL FEES (EXTENSION OF 096X) - OCCUPATIONAL THERAPY"),
  /** 0979 - PROFESSIONAL FEES (EXTENSION OF 096X) - SPEECH PATHOLOGY. */
  _0979("0979", "PROFESSIONAL FEES (EXTENSION OF 096X) - SPEECH PATHOLOGY"),
  /** 0981 - PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - EMERGENCY ROOM SERVICES. */
  _0981("0981", "PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - EMERGENCY ROOM SERVICES"),
  /** 0982 - PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - OUTPATIENT SERVICES. */
  _0982("0982", "PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - OUTPATIENT SERVICES"),
  /** 0983 - PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - CLINIC. */
  _0983("0983", "PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - CLINIC"),
  /** 0984 - PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - MEDICAL SOCIAL SERVICES. */
  _0984("0984", "PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - MEDICAL SOCIAL SERVICES"),
  /** 0985 - PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - EKG. */
  _0985("0985", "PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - EKG"),
  /** 0986 - PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - EEG. */
  _0986("0986", "PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - EEG"),
  /** 0987 - PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - HOSPITAL VISIT. */
  _0987("0987", "PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - HOSPITAL VISIT"),
  /** 0988 - PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - CONSULTATION. */
  _0988("0988", "PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - CONSULTATION"),
  /** 0989 - PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - PRIVATE DUTY NURSE. */
  _0989("0989", "PROFESSIONAL FEES (EXTENSION OF 096X AND 097X) - PRIVATE DUTY NURSE"),
  /** 0990 - PATIENT CONVENIENCE ITEMS - GENERAL CLASSIFICATION. */
  _0990("0990", "PATIENT CONVENIENCE ITEMS - GENERAL CLASSIFICATION"),
  /** 0991 - PATIENT CONVENIENCE ITEMS - CAFETERIA/GUEST TRAY. */
  _0991("0991", "PATIENT CONVENIENCE ITEMS - CAFETERIA/GUEST TRAY"),
  /** 0992 - PATIENT CONVENIENCE ITEMS - PRIVATE LINEN SERVICE. */
  _0992("0992", "PATIENT CONVENIENCE ITEMS - PRIVATE LINEN SERVICE"),
  /** 0993 - PATIENT CONVENIENCE ITEMS - TELEPHONE/TELECOM. */
  _0993("0993", "PATIENT CONVENIENCE ITEMS - TELEPHONE/TELECOM"),
  /** 0994 - PATIENT CONVENIENCE ITEMS - TV/RADIO. */
  _0994("0994", "PATIENT CONVENIENCE ITEMS - TV/RADIO"),
  /** 0995 - PATIENT CONVENIENCE ITEMS - NON-PATIENT ROOM RENTALS. */
  _0995("0995", "PATIENT CONVENIENCE ITEMS - NON-PATIENT ROOM RENTALS"),
  /** 0996 - PATIENT CONVENIENCE ITEMS - LATE DISCHARGE. */
  _0996("0996", "PATIENT CONVENIENCE ITEMS - LATE DISCHARGE"),
  /** 0997 - PATIENT CONVENIENCE ITEMS - ADMISSION KITS. */
  _0997("0997", "PATIENT CONVENIENCE ITEMS - ADMISSION KITS"),
  /** 0998 - PATIENT CONVENIENCE ITEMS - BEAUTY SHOP/BARBER. */
  _0998("0998", "PATIENT CONVENIENCE ITEMS - BEAUTY SHOP/BARBER"),
  /** 0999 - PATIENT CONVENIENCE ITEMS - OTHER CONVENIENCE ITEMS. */
  _0999("0999", "PATIENT CONVENIENCE ITEMS - OTHER CONVENIENCE ITEMS"),
  /** 1000 - BEHAVIORAL HEALTH ACCOMMODATIONS - GENERAL CLASSIFICATION. */
  _1000("1000", "BEHAVIORAL HEALTH ACCOMMODATIONS - GENERAL CLASSIFICATION"),
  /**
   * 1001 - BEHAVIORAL HEALTH ACCOMMODATIONS - RESIDENTIAL - PSYCHIATRIC (TITLE EFFECTIVE 10/1/13).
   */
  _1001(
      "1001",
      "BEHAVIORAL HEALTH ACCOMMODATIONS - RESIDENTIAL  - PSYCHIATRIC (TITLE EFFECTIVE 10/1/13)"),
  /**
   * 1002 - BEHAVIORAL HEALTH ACCOMMODATIONS - RESIDENTIAL - CHEMICAL DEPENDENCY (TITLE EFFECTIVE
   * 10/1/13).
   */
  _1002(
      "1002",
      "BEHAVIORAL HEALTH ACCOMMODATIONS - RESIDENTIAL  - CHEMICAL DEPENDENCY (TITLE EFFECTIVE 10/1/13)"),
  /** 1003 - BEHAVIORAL HEALTH ACCOMMODATIONS - SUPERVISED LIVING. */
  _1003("1003", "BEHAVIORAL HEALTH ACCOMMODATIONS - SUPERVISED LIVING"),
  /** 1004 - BEHAVIORAL HEALTH ACCOMMODATIONS - HALFWAY HOUSE. */
  _1004("1004", "BEHAVIORAL HEALTH ACCOMMODATIONS - HALFWAY HOUSE"),
  /** 1005 - BEHAVIORAL HEALTH ACCOMMODATIONS - GROUP HOME. */
  _1005("1005", "BEHAVIORAL HEALTH ACCOMMODATIONS - GROUP HOME"),
  /**
   * 1006 - BEHAVIORAL HEALTH ACCOMMODATIONS - OUTDOOR/WILDERNESS BEHAVIORAL HEALTH (EFFECTIVE
   * 7/1/17).
   */
  _1006(
      "1006",
      "BEHAVIORAL HEALTH ACCOMMODATIONS - OUTDOOR/WILDERNESS BEHAVIORAL HEALTH (EFFECTIVE 7/1/17)"),
  /** 2100 - ALTERNATIVE THERAPY SERVICES - GENERAL CLASSIFICATION. */
  _2100("2100", "ALTERNATIVE THERAPY SERVICES - GENERAL CLASSIFICATION"),
  /** 2101 - ALTERNATIVE THERAPY SERVICES - ACUPUNCTURE. */
  _2101("2101", "ALTERNATIVE THERAPY SERVICES - ACUPUNCTURE"),
  /** 2102 - ALTERNATIVE THERAPY SERVICES - ACUPRESSURE. */
  _2102("2102", "ALTERNATIVE THERAPY SERVICES - ACUPRESSURE"),
  /** 2103 - ALTERNATIVE THERAPY SERVICES - MASSAGE. */
  _2103("2103", "ALTERNATIVE THERAPY SERVICES - MASSAGE"),
  /** 2104 - ALTERNATIVE THERAPY SERVICES - REFLEXOLOGY. */
  _2104("2104", "ALTERNATIVE THERAPY SERVICES - REFLEXOLOGY"),
  /** 2105 - ALTERNATIVE THERAPY SERVICES - BIOFEEDBACK. */
  _2105("2105", "ALTERNATIVE THERAPY SERVICES - BIOFEEDBACK"),
  /** 2106 - ALTERNATIVE THERAPY SERVICES - HYPNOSIS. */
  _2106("2106", "ALTERNATIVE THERAPY SERVICES - HYPNOSIS"),
  /** 2109 - ALTERNATIVE THERAPY SERVICES - OTHER ALTERNATIVE THERAPY SERVICES. */
  _2109("2109", "ALTERNATIVE THERAPY SERVICES - OTHER ALTERNATIVE THERAPY SERVICES"),
  /** 3101 - ADULT CARE - ADULT DAY CARE, MEDICAL AND SOCIAL - HOURLY. */
  _3101("3101", "ADULT CARE - ADULT DAY CARE, MEDICAL AND SOCIAL - HOURLY"),
  /** 3102 - ADULT CARE - ADULT DAY CARE, SOCIAL - HOURLY. */
  _3102("3102", "ADULT CARE - ADULT DAY CARE,  SOCIAL - HOURLY"),
  /** 3103 - ADULT CARE - ADULT DAY CARE, MEDICAL AND SOCIAL - DAILY. */
  _3103("3103", "ADULT CARE - ADULT DAY CARE,  MEDICAL AND SOCIAL - DAILY"),
  /** 3104 - ADULT CARE - ADULT DAY CARE, SOCIAL - DAILY. */
  _3104("3104", "ADULT CARE - ADULT DAY CARE,  SOCIAL - DAILY"),
  /** 3105 - ADULT CARE - ADULT FOSTER CARE - DAILY. */
  _3105("3105", "ADULT CARE - ADULT FOSTER CARE - DAILY"),
  /** 3109 - ADULT CARE - OTHER ADULT CARE. */
  _3109("3109", "ADULT CARE - OTHER ADULT CARE");

  private final String code;
  private final String display;

  /**
   * Converts from a database code.
   *
   * @param code database code
   * @return revenue center code
   */
  public static Optional<ClaimLineRevenueCenterCode> tryFromCode(String code) {
    return Arrays.stream(values()).filter(v -> v.code.equals(code)).findFirst();
  }

  CodeableConcept toFhir(Optional<ClaimLineDeductibleCoinsuranceCode> deductibleCoinsuranceCode) {
    var codeableConcept =
        new CodeableConcept()
            .addCoding(
                new Coding()
                    .setSystem(SystemUrls.BLUE_BUTTON_CODE_SYSTEM_REVENUE_CENTER_CODE)
                    .setCode(code)
                    .setDisplay(display))
            .addCoding(new Coding().setSystem(SystemUrls.NUBC_REVENUE_CODES).setCode(code));
    deductibleCoinsuranceCode.ifPresent(
        c -> {
          codeableConcept.addCoding(c.toFhir());
        });
    return codeableConcept;
  }
}
