package gov.cms.bfd.server.ng.claim.model;

import gov.cms.bfd.server.ng.util.SystemUrls;
import java.util.Arrays;
import java.util.Optional;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.hl7.fhir.r4.model.Coding;
import org.hl7.fhir.r4.model.Extension;

/** Claim Payment denial code enum. * */
@AllArgsConstructor
@Getter
@SuppressWarnings("java:S115")
public enum ClaimPaymentDenialCode {
  /** ! - MSP COST AVOIDED - COB CONTRACTOR (&#x27;00&#x27; 2-BYTE CODE). */
  EXCLAMATION("!", "MSP COST AVOIDED - COB CONTRACTOR ('00' 2-BYTE CODE)"),
  /** # - MSP COST AVOIDED - OFFICE OF PERSONNEL MANAGEMENT (&#x27;13&#x27; 2-BYTE CODE). */
  HASHTAG("#", "MSP COST AVOIDED - OFFICE OF PERSONNEL MANAGEMENT ('13' 2-BYTE CODE)"),
  /**
   * $ - MSP COST AVOIDED - WORKMAN&#x27;S COMPENSATION (WC) DATA MATCH (&#x27;14&#x27; 2-BYTE
   * CODE).
   */
  DOLLAR("$", "MSP COST AVOIDED - WORKMAN'S COMPENSATION (WC) DATA MATCH ('14' 2-BYTE CODE)"),
  /** % - MSP COST AVOIDED - RAC - CALIFORNIA (&#x27;25&#x27; 2-BYTE CODE) (EFF. 10/2005). */
  PERCENT("%", "MSP COST AVOIDED - RAC - CALIFORNIA ('25' 2-BYTE CODE) (EFF. 10/2005)"),
  /** &amp; - MSP COST AVOIDED - RAC - FLORIDA (&#x27;26&#x27; 2-BYTE CODE) (EFF. 10/2005). */
  AMPERSAND("&", "MSP COST AVOIDED - RAC - FLORIDA ('26' 2-BYTE CODE) (EFF. 10/2005)"),
  /** ( - MSP COST AVOIDED - LIABILITY INSURER VDSA (&#x27;16&#x27; 2-BYTE CODE) (EFF. 4/2006). */
  LEFT_PARENTHESIS(
      "(", "MSP COST AVOIDED - LIABILITY INSURER VDSA ('16' 2-BYTE CODE) (EFF. 4/2006)"),
  /** ) - MSP COST AVOIDED - NO-FAULT INSURER VDSA (&#x27;17&#x27; 2-BYTE CODE) (EFF. 4/2006). */
  RIGHT_PARENTHESIS(
      ")", "MSP COST AVOIDED - NO-FAULT INSURER VDSA ('17' 2-BYTE CODE) (EFF. 4/2006)"),
  /**
   * - MSP COST AVOIDED - WORKMAN&#x27;S COMPENSATION INSURER VOLUNTARY DATA SHARING AGREEMENTS (WC
   * VDSA) (&#x27;15&#x27; 2-BYTE CODE) (EFF. 4/2006).
   */
  STAR(
      "*",
      "MSP COST AVOIDED - WORKMAN'S COMPENSATION INSURER VOLUNTARY DATA SHARING AGREEMENTS (WC VDSA)   ('15' 2-BYTE CODE) (EFF. 4/2006)"),
  /**
   * + - MSP COST AVOIDED - PHARMACY BENEFIT MANAGER DATA SHARING AGREEMENT (&#x27;18&#x27; 2 -BYTE
   * CODE) (EFF. 4/2006).
   */
  PLUS(
      "+",
      "MSP COST AVOIDED - PHARMACY BENEFIT MANAGER DATA SHARING AGREEMENT ('18' 2 -BYTE CODE) (EFF. 4/2006)"),
  /** 0 - DENIED. */
  _0("0", "DENIED"),
  /**
   * 00 - MEDICARE SECONDARY PAYER (MSP) COST AVOIDED - COORDINATOR OF BENEFITS (COB) CONTRACTOR
   * 11100.
   */
  _00(
      "00",
      "MEDICARE SECONDARY PAYER (MSP) COST AVOIDED - COORDINATOR OF BENEFITS (COB) CONTRACTOR 11100"),
  /** 1 - PHYSICIAN/SUPPLIER. */
  _1("1", "PHYSICIAN/SUPPLIER"),
  /**
   * 12 - MSP COST AVOIDED - BLUE CROSS (BC)/ BLUE SHIELD (BS) VOLUNTARY AGREEMENTS COB CONTRACTOR
   * 11112.
   */
  _12(
      "12",
      "MSP COST AVOIDED - BLUE CROSS (BC)/ BLUE SHIELD (BS) VOLUNTARY AGREEMENTS COB CONTRACTOR 11112"),
  /** 13 - MSP COST AVOIDED - OFFICE OF PERSONNEL MANAGEMENT COB CONTRACTOR 11113. */
  _13("13", "MSP COST AVOIDED - OFFICE OF PERSONNEL MANAGEMENT COB CONTRACTOR 11113"),
  /** 14 - MSP COST AVOIDED - WORKMAN&#x27;S COMPENSATION (WC) DATA MATCH COB CONTRACTOR 11114. */
  _14("14", "MSP COST AVOIDED - WORKMAN'S COMPENSATION (WC) DATA MATCH COB CONTRACTOR 11114"),
  /**
   * 15 - MSP COST AVOIDED - WORKMAN&#x27;S COMPENSATION INSURER VOLUNTARY DATA SHARING AGREEMENTS
   * (WC VDSA) (EFF. 4/2006) COB CONTRACTOR 11115.
   */
  _15(
      "15",
      "MSP COST AVOIDED - WORKMAN'S COMPENSATION INSURER VOLUNTARY DATA SHARING AGREEMENTS (WC VDSA) (EFF. 4/2006) COB CONTRACTOR 11115"),
  /** 16 - MSP COST AVOIDED - LIABILITY INSURER VDSA (EFF.4/2006) COB CONTRACTOR 11116. */
  _16("16", "MSP COST AVOIDED - LIABILITY INSURER VDSA (EFF.4/2006) COB CONTRACTOR 11116"),
  /** 17 - MSP COST AVOIDED - NO-FAULT INSURER VDSA (EFF.4/2006) COB CONTRACTOR 11117. */
  _17("17", "MSP COST AVOIDED - NO-FAULT INSURER VDSA (EFF.4/2006) COB CONTRACTOR 11117"),
  /**
   * 18 - MSP COST AVOIDED - PHARMACY BENEFIT MANAGER DATA SHARING AGREEMENT (EFF.4/2006) COB
   * CONTRACTOR 11118.
   */
  _18(
      "18",
      "MSP COST AVOIDED - PHARMACY BENEFIT MANAGER DATA SHARING AGREEMENT (EFF.4/2006) COB CONTRACTOR 11118"),
  /** 19 - MSP COST AVOIDED - WC MEDICARE SET-ASIDE ARRANGEMENT COB CONTRACTOR 11119. */
  _19("19", "MSP COST AVOIDED - WC MEDICARE SET-ASIDE ARRANGEMENT COB CONTRACTOR 11119"),
  /** 2 - BENEFICIARY. */
  _2("2", "BENEFICIARY"),
  /**
   * 21 - MSP COST AVOIDED - MANDATORY INSURER REPORTING (MIR) GROUP HEALTH PLAN (EFF.1/2009) COB
   * CONTRACTOR 11121.
   */
  _21(
      "21",
      "MSP COST AVOIDED - MANDATORY INSURER REPORTING (MIR) GROUP HEALTH PLAN (EFF.1/2009) COB CONTRACTOR 11121"),
  /** 22 - MSP COST AVOIDED - MIR NON-GROUP HEALTH PLAN (EFF.1/2009) COB CONTRACTOR 11122. */
  _22("22", "MSP COST AVOIDED - MIR NON-GROUP HEALTH PLAN (EFF.1/2009) COB CONTRACTOR 11122"),
  /**
   * 25 - MSP COST AVOIDED - RECOVERY AUDIT CONTRACTOR (RAC)- CALIFORNIA (EFF.10/2005) COB
   * CONTRACTOR 11125.
   */
  _25(
      "25",
      "MSP COST AVOIDED - RECOVERY AUDIT CONTRACTOR (RAC)- CALIFORNIA  (EFF.10/2005) COB CONTRACTOR 11125"),
  /** 26 - MSP COST AVOIDED - RAC- FLORIDA (EFF.10/2005) COB CONTRACTOR 11126. */
  _26("26", "MSP COST AVOIDED - RAC- FLORIDA (EFF.10/2005) COB CONTRACTOR 11126"),
  /** 3 - BOTH PHYSICIAN/SUPPLIER AND BENEFICIARY. */
  _3("3", "BOTH PHYSICIAN/SUPPLIER AND BENEFICIARY"),
  /** 39 - MSP COST AVOIDED - GROUP HEALTH PLAN (GHP) RECOVERY COB CONTRACTOR 11139. */
  _39("39", "MSP COST AVOIDED - GROUP HEALTH PLAN (GHP) RECOVERY COB CONTRACTOR 11139"),
  /** 4 - HOSPITAL (HOSPITAL BASED PHYSICIANS). */
  _4("4", "HOSPITAL (HOSPITAL BASED PHYSICIANS)"),
  /**
   * 41 - MSP COST AVOIDED - NON-GROUP HEALTH PLAN (NGHP) NON-ONGOING RESPONSIBILITY FOR MEDICALS
   * (ORM) COB CONTRACTOR 11141.
   */
  _41(
      "41",
      "MSP COST AVOIDED - NON-GROUP HEALTH PLAN (NGHP) NON-ONGOING RESPONSIBILITY FOR MEDICALS (ORM) COB CONTRACTOR 11141"),
  /** 42 - MSP COST AVOIDED - NGHP ORM RECOVERY COB CONTRACTOR 11142. */
  _42("42", "MSP COST AVOIDED - NGHP ORM RECOVERY COB CONTRACTOR 11142"),
  /** 43 - MEDICARE PART C/ MEDICARE ADVANTAGE/ COB CONTRACTOR 11143. */
  _43("43", "MEDICARE PART C/ MEDICARE ADVANTAGE/ COB CONTRACTOR 11143"),
  /** 5 - BOTH HOSPITAL AND BENEFICIARY. */
  _5("5", "BOTH HOSPITAL AND BENEFICIARY"),
  /** 6 - GROUP PRACTICE PREPAYMENT PLAN. */
  _6("6", "GROUP PRACTICE PREPAYMENT PLAN"),
  /** 7 - OTHER ENTRIES (E.G. EMPLOYER , UNION). */
  _7("7", "OTHER ENTRIES (E.G. EMPLOYER , UNION)"),
  /** 8 - FEDERALLY FUNDED. */
  _8("8", "FEDERALLY FUNDED"),
  /** 9 - PA SERVICE. */
  _9("9", "PA SERVICE"),
  /** &lt; - MSP COST AVOIDED - MIR GROUP HEALTH PLAN (&#x27;21&#x27; 2-BYTE CODE) (EFF. 1/2009). */
  LESS_THAN("<", "MSP COST AVOIDED - MIR GROUP HEALTH PLAN ('21' 2-BYTE CODE) (EFF. 1/2009)"),
  /**
   * &gt; - MSP COST AVOIDED - MIR NON-GROUP HEALTH PLAN (&#x27;22&#x27; 2-BYTE CODE) (EFF. 1/2009).
   */
  GREATER_THAN(
      ">", "MSP COST AVOIDED - MIR NON-GROUP HEALTH PLAN ('22' 2-BYTE CODE) (EFF. 1/2009)"),
  /** &#64; - MSP COST AVOIDED - BC/BS VOLUNTARY AGREEMENTS (&#x27;12&#x27; 2-BYTE CODE). */
  AT("@", "MSP COST AVOIDED - BC/BS VOLUNTARY AGREEMENTS ('12' 2-BYTE CODE)"),
  /** A - ALLOWED. */
  A("A", "ALLOWED"),
  /** B - BENEFITS EXHAUSTED. */
  B("B", "BENEFITS EXHAUSTED"),
  /** C - NON-COVERED CARE. */
  C("C", "NON-COVERED CARE"),
  /** D - DENIED DUE TO DEMONSTRATION INVOLVEMENT (EFF. 5/97). */
  D("D", "DENIED DUE TO DEMONSTRATION INVOLVEMENT (EFF. 5/97)"),
  /** E - FIRST CLAIM DEVELOPMENT. */
  E("E", "FIRST CLAIM DEVELOPMENT"),
  /** F - TRAUMA CODE DEVELOPMENT. */
  F("F", "TRAUMA CODE DEVELOPMENT"),
  /** G - SECONDARY CLAIMS INVESTIGATION. */
  G("G", "SECONDARY CLAIMS INVESTIGATION"),
  /** H - SELF REPORTS. */
  H("H", "SELF REPORTS"),
  /** J - 411.25. */
  J("J", "411.25"),
  /** K - INSURER VOLUNTARY REPORTING. */
  K("K", "INSURER VOLUNTARY REPORTING"),
  /** L - CLINICAL LAB IMPROVEMENT AMENDMENT (CLIA). */
  L("L", "CLINICAL LAB IMPROVEMENT AMENDMENT (CLIA)"),
  /** M - MULTIPLE SUBMITTAL (I.E. DUPLICATE LINE ITEM). */
  M("M", "MULTIPLE SUBMITTAL (I.E. DUPLICATE LINE ITEM)"),
  /** N - MEDICAL NECESSITY. */
  N("N", "MEDICAL NECESSITY"),
  /** O - OTHER. */
  O("O", "OTHER"),
  /** P - PHYSICIAN OWNERSHIP DENIAL (EFF 3/92). */
  P("P", "PHYSICIAN OWNERSHIP DENIAL (EFF 3/92)"),
  /** Q - EMPLOYER VOLUNTARY REPORTING. */
  Q("Q", "EMPLOYER VOLUNTARY REPORTING"),
  /** R - REPROCESSED ADJUSTMENT BASED ON SUBSEQUENT REPROCESSING OF CLAIM. */
  R("R", "REPROCESSED ADJUSTMENT BASED ON SUBSEQUENT REPROCESSING OF CLAIM"),
  /** S - SECONDARY PAYER. */
  S("S", "SECONDARY PAYER"),
  /** T - MSP COST AVOIDED - INITIAL ENROLLMENT QUESTIONNAIRE (IEQ) CONTRACTOR (EFF. 7/96). */
  T("T", "MSP COST AVOIDED - INITIAL ENROLLMENT QUESTIONNAIRE (IEQ) CONTRACTOR  (EFF. 7/96)"),
  /**
   * U - MSP COST AVOIDED - HEALTH MAINTENANCE ORGANIZATION (HMO) RATE CELL ADJUSTMENT (EFF. 7/96).
   */
  U(
      "U",
      "MSP COST AVOIDED - HEALTH MAINTENANCE ORGANIZATION (HMO) RATE CELL ADJUSTMENT (EFF. 7/96)"),
  /** V - MSP COST AVOIDED - LITIGATION SETTLEMENT (EFF. 7/96). */
  V("V", "MSP COST AVOIDED - LITIGATION SETTLEMENT (EFF. 7/96)"),
  /** X - MSP COST AVOIDED - GENERIC. */
  X("X", "MSP COST AVOIDED - GENERIC"),
  /** Y - MSP COST AVOIDED - IRS/SSA DATA MATCH PROJECT. */
  Y("Y", "MSP COST AVOIDED - IRS/SSA DATA MATCH PROJECT"),
  /** Z - ZERO PAYMENT , ALLOWED TEST. */
  Z("Z", "ZERO PAYMENT , ALLOWED TEST"),
  /** NA. */
  NA("", "NO DESCRIPTION AVAILABLE");

  private final String code;
  private final String display;

  /**
   * Convert from a database code.
   *
   * @param code database code
   * @return claim payment denial code
   */
  public static Optional<ClaimPaymentDenialCode> tryFromCode(String code) {
    return Arrays.stream(values()).filter(v -> v.code.equals(code)).findFirst();
  }

  Extension toFhir() {
    return new Extension()
        .setUrl(SystemUrls.BLUE_BUTTON_STRUCTURE_DEFINITION_CLAIM_PAYMENT_DENIAL_CODE)
        .setValue(
            new Coding(
                SystemUrls.BLUE_BUTTON_STRUCTURE_DEFINITION_CLAIM_PAYMENT_DENIAL_CODE,
                code,
                display));
  }
}
