package gov.cms.bfd.server.ng.claim.model;

import gov.cms.bfd.server.ng.util.SystemUrls;
import java.util.Arrays;
import java.util.Optional;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.hl7.fhir.r4.model.CodeableConcept;
import org.hl7.fhir.r4.model.Coding;
import org.hl7.fhir.r4.model.ExplanationOfBenefit;

/**
 * Claim nonpayment reason codes. Suppress SonarQube warning that constant names should comply with
 * naming conventions.
 */
@AllArgsConstructor
@Getter
@SuppressWarnings("java:S115")
public enum ClaimNonpaymentReasonCode {
  /** ! - MSP COST AVOIDED - COB CONTRACTOR (00 2-BYTE CODE). */
  EXCLAMATION("!", "MSP COST AVOIDED - COB CONTRACTOR (00 2-BYTE CODE)"),
  /** # - MSP COST AVOIDED - OFFICE OF PERSONNEL MANAGEMENT (13 2-BYTE CODE). */
  HASHTAG("#", "MSP COST AVOIDED - OFFICE OF PERSONNEL MANAGEMENT (13 2-BYTE CODE)"),
  /** $ - MSP COST AVOIDED - WORKMAN'S COMPENSATION (WC) DATA MATCH (14 2-BYTE CODE). */
  DOLLAR("$", "MSP COST AVOIDED - WORKMAN'S COMPENSATION (WC) DATA MATCH (14 2-BYTE CODE)"),
  /**
   * % - MSP COST AVOIDED - RECOVERY AUDIT CONTRACTOR - CALIFORNIA (25 2-BYTE CODE) (EFF. 10/2005).
   */
  PERCENT(
      "%",
      "MSP COST AVOIDED - RECOVERY AUDIT CONTRACTOR - CALIFORNIA (25 2-BYTE CODE) (EFF. 10/2005)"),
  /**
   * &amp; - MSP COST AVOIDED - RECOVERY AUDIT CONTRACTOR - FLORIDA (26 2-BYTE CODE) (EFF. 10/2005).
   */
  AMPERSAND(
      "&",
      "MSP COST AVOIDED - RECOVERY AUDIT CONTRACTOR - FLORIDA (26 2-BYTE CODE) (EFF. 10/2005)"),
  /** ( - MSP COST AVOIDED - LIABILITY INSURER VDSA (16 2-BYTE CODE) (EFF. 4/2006). */
  LEFT_PARENTHESIS("(", "MSP COST AVOIDED - LIABILITY INSURER VDSA (16 2-BYTE CODE) (EFF. 4/2006)"),
  /** ) - MSP COST AVOIDED - NO-FAULT INSURER VDSA (17 2-BYTE CODE) (EFF. 4/2006). */
  RIGHT_PARENTHESIS(")", "MSP COST AVOIDED - NO-FAULT INSURER VDSA (17 2-BYTE CODE) (EFF. 4/2006)"),
  /**
   * - MSP COST AVOIDED - WORKMAN'S COMPENSATION INSURER VOLUNTARY DATA SHARING AGREEMENTS (WC VDSA)
   * ('15' 2-BYTE CODE) (EFF. 4/2006).
   */
  STAR(
      "*",
      "MSP COST AVOIDED - WORKMAN'S COMPENSATION INSURER VOLUNTARY DATA SHARING AGREEMENTS (WC VDSA) ('15' 2-BYTE CODE) (EFF. 4/2006)"),
  /**
   * + - MSP COST AVOIDED - PHARMACY BENEFIT MANAGER DATA SHARING AGREEMENT (18 2 -BYTE CODE) (EFF.
   * 4/2006).
   */
  PLUS(
      "+",
      "MSP COST AVOIDED - PHARMACY BENEFIT MANAGER DATA SHARING AGREEMENT (18 2 -BYTE CODE) (EFF. 4/2006)"),
  /**
   * 00 - MEDICARE SECONDARY PAYER (MSP) COST AVOIDED - COORDINATOR OF BENEFITS (COB) CONTRACTOR
   * 11100.
   */
  _00(
      "00",
      "MEDICARE SECONDARY PAYER (MSP) COST AVOIDED - COORDINATOR OF BENEFITS (COB) CONTRACTOR 11100"),
  /** 12 - MSP COST AVOIDED - BLUE CROSS - BLUE SHIELD VOLUNTARY AGREEMENTS COB CONTRACTOR 11112. */
  _12(
      "12",
      "MSP COST AVOIDED - BLUE CROSS - BLUE SHIELD VOLUNTARY AGREEMENTS COB CONTRACTOR 11112"),
  /**
   * 13 - MSP COST AVOIDED - OFFICE OF PERSONNEL MANAGEMENT (OPM) DATA MATCH COB CONTRACTOR 11113.
   */
  _13(
      "13",
      "MSP COST AVOIDED - OFFICE OF PERSONNEL MANAGEMENT (OPM) DATA MATCH COB CONTRACTOR 11113"),
  /** 14 - MSP COST AVOIDED - WORKERS COMPENSATION (WC) DATA MATCH COB CONTRACTOR 11114. */
  _14("14", "MSP COST AVOIDED - WORKERS COMPENSATION (WC) DATA MATCH COB CONTRACTOR 11114"),
  /**
   * 15 - MSP COST AVOIDED - WORKERS COMPENSATION INSURER VOLUNTARY DATA SHARING AGREEMENTS (WC
   * VDSA) COB CONTRACTOR 11115.
   */
  _15(
      "15",
      "MSP COST AVOIDED - WORKERS COMPENSATION INSURER VOLUNTARY DATA SHARING AGREEMENTS (WC VDSA) COB CONTRACTOR 11115"),
  /** 16 - MSP COST AVOIDED - LIABILITY INSURER VDSA COB CONTRACTOR 11116. */
  _16("16", "MSP COST AVOIDED - LIABILITY INSURER VDSA COB CONTRACTOR 11116"),
  /** 17 - MSP COST AVOIDED - NO-FAULT INSURER VDSA COB CONTRACTOR 11117. */
  _17("17", "MSP COST AVOIDED - NO-FAULT INSURER VDSA COB CONTRACTOR 11117"),
  /**
   * 18 - MSP COST AVOIDED - PHARMACY BENEFIT MANAGER DATA SHARING AGREEMENT COB CONTRACTOR 11118.
   */
  _18(
      "18",
      "MSP COST AVOIDED - PHARMACY BENEFIT MANAGER DATA SHARING AGREEMENT COB CONTRACTOR 11118"),
  /** 19 - MSP COST AVOIDED - WC MEDICARE SET-ASIDE ARRANGEMENT COB CONTRACTOR 11119. */
  _19("19", "MSP COST AVOIDED - WC MEDICARE SET-ASIDE ARRANGEMENT COB CONTRACTOR 11119"),
  /**
   * 21 - MSP COST AVOIDED - MANDATORY INSURER REPORTING (MIR) GROUP HEALTH PLAN (EFF. 1/2009) COB
   * CONTRACTOR 11121.
   */
  _21(
      "21",
      "MSP COST AVOIDED - MANDATORY INSURER REPORTING (MIR) GROUP HEALTH PLAN (EFF. 1/2009) COB CONTRACTOR 11121"),
  /** 22 - MSP COST AVOIDED - MIR NON-GROUP HEALTH PLAN (EFF. 1/2009) COB CONTRACTOR 11122. */
  _22("22", "MSP COST AVOIDED - MIR NON-GROUP HEALTH PLAN (EFF. 1/2009) COB CONTRACTOR 11122"),
  /**
   * 25 - MSP COST AVOIDED - RECOVERY AUDIT CONTRACTOR (RAC) CALIFORNIA (EFF. 10/2005) COB
   * CONTRACTOR 11125.
   */
  _25(
      "25",
      "MSP COST AVOIDED - RECOVERY AUDIT CONTRACTOR (RAC)  CALIFORNIA (EFF. 10/2005) COB CONTRACTOR 11125"),
  /** 26 - MSP COST AVOIDED - RAC MSP FLORIDA (EFF. 10/2005) COB CONTRACTOR 11126. */
  _26("26", "MSP COST AVOIDED - RAC MSP FLORIDA (EFF. 10/2005) COB CONTRACTOR 11126"),
  /** 39 - MSP COST AVOIDED - GROUP HEALTH PLAN (GHP) RECOVERY COB CONTRACTOR 11139. */
  _39("39", "MSP COST AVOIDED - GROUP HEALTH PLAN (GHP) RECOVERY COB CONTRACTOR 11139"),
  /**
   * 41 - MSP COST AVOIDED - NON-GROUP HEALTH PLAN (NGHP) NON-ONGOING RESPONSIBILITY FOR MEDICALS
   * (ORM) COB CONTRACTOR 11141.
   */
  _41(
      "41",
      "MSP COST AVOIDED - NON-GROUP HEALTH PLAN (NGHP) NON-ONGOING RESPONSIBILITY FOR MEDICALS (ORM) COB CONTRACTOR 11141"),
  /** 42 - MSP COST AVOIDED - NGHP ORM RECOVERY COB CONTRACTOR 11142. */
  _42("42", "MSP COST AVOIDED - NGHP ORM RECOVERY COB CONTRACTOR 11142"),
  /** 43 - MEDICARE PART C/MEDICARE ADVANTAGE/ COB CONTRACTOR 11143. */
  _43("43", "MEDICARE PART C/MEDICARE ADVANTAGE/ COB CONTRACTOR 11143"),
  /** &lt; - MSP COST AVOIDED - MIR GROUP HEALTH PLAN ('21' 2-BYTE CODE) (EFF. 1/2009). */
  LESS_THAN("<", "MSP COST AVOIDED - MIR GROUP HEALTH PLAN ('21' 2-BYTE CODE) (EFF. 1/2009)"),
  /** &gt; - MSP COST AVOIDED - MIR NON-GROUP HEALTH PLAN ('22' 2-BYTE CODE) (EFF. 1/2009). */
  GREATER_THAN(
      ">", "MSP COST AVOIDED - MIR NON-GROUP HEALTH PLAN ('22' 2-BYTE CODE) (EFF. 1/2009)"),
  /** AT - MSP COST AVOIDED - BC/BS VOLUNTARY AGREEMENTS (12 2-BYTE CODE). */
  AT("@", "MSP COST AVOIDED - BC/BS VOLUNTARY AGREEMENTS (12 2-BYTE CODE)"),
  /** A - COVERED WORKERS COMPENSATION (OBSOLETE). */
  A("A", "COVERED WORKERS COMPENSATION (OBSOLETE)"),
  /** B - BENEFITS EXHAUSTED. */
  B("B", "BENEFITS EXHAUSTED"),
  /**
   * C - CUSTODIAL CARE- NON-COVERED CARE (INCLUDES ALL 'BENEFICIARY AT FAULT' WAIVER CASES)
   * (OBSOLETE).
   */
  C(
      "C",
      "CUSTODIAL CARE- NON-COVERED CARE  (INCLUDES ALL 'BENEFICIARY AT FAULT' WAIVER CASES) (OBSOLETE)"),
  /**
   * E - MSP COST AVOIDED - INTERNAL REVENUE SERVICE (IRS)/ SOCIAL SECURITY ADMINISTRATION (SSA)/
   * HEALTH CARE FINANCING ADMINISTRATION (HCFA) DATA MATCH (EFF. 7/00).
   */
  E(
      "E",
      "MSP COST AVOIDED - INTERNAL REVENUE SERVICE (IRS)/ SOCIAL SECURITY ADMINISTRATION (SSA)/ HEALTH CARE FINANCING ADMINISTRATION (HCFA) DATA MATCH (EFF. 7/00)"),
  /** F - MSP COST AVOIDED - HEALTH MAINTENANCE ORGANIZATION (HMO) RATE CELL (EFF. 7/00). */
  F("F", "MSP COST AVOIDED - HEALTH MAINTENANCE ORGANIZATION (HMO) RATE CELL (EFF. 7/00)"),
  /** G - MSP COST AVOIDED - LITIGATION SETTLEMENT (EFF. 7/00). */
  G("G", "MSP COST AVOIDED - LITIGATION SETTLEMENT (EFF. 7/00)"),
  /** H - MSP COST AVOIDED - EMPLOYER VOLUNTARY REPORTING (EFF. 7/00). */
  H("H", "MSP COST AVOIDED - EMPLOYER VOLUNTARY REPORTING (EFF. 7/00)"),
  /** J - MSP COST AVOIDED - INSURER VOLUNTARY REPORTING (EFF. 7/00). */
  J("J", "MSP COST AVOIDED - INSURER VOLUNTARY REPORTING (EFF. 7/00)"),
  /** K - MSP COST AVOIDED - INITIAL ENROLLMENT QUESTIONNAIRE (IEQ) (EFF. 7/00). */
  K("K", "MSP COST AVOIDED - INITIAL ENROLLMENT QUESTIONNAIRE (IEQ) (EFF. 7/00)"),
  /** N - ALL OTHER REASONS FOR NONPAYMENT. */
  N("N", "ALL OTHER REASONS FOR NONPAYMENT"),
  /** P - PAYMENT REQUESTED. */
  P("P", "PAYMENT REQUESTED"),
  /** Q - MSP COST AVOIDED - VOLUNTARY AGREEMENT (EFF. 7/00). */
  Q("Q", "MSP COST AVOIDED - VOLUNTARY AGREEMENT (EFF. 7/00)"),
  /** R - BENEFITS REFUSED, OR EVIDENCE NOT SUBMITTED. */
  R("R", "BENEFITS REFUSED, OR EVIDENCE NOT SUBMITTED"),
  /** T - MSP COST AVOIDED - IEQ CONTRACTOR (EFF. 9/76) (OBSOLETE 6/30/00). */
  T("T", "MSP COST AVOIDED - IEQ CONTRACTOR (EFF. 9/76) (OBSOLETE 6/30/00)"),
  /** U - MSP COST AVOIDED - HMO RATE CELL ADJUSTMENT (EFF. 9/76) (OBSOLETE 6/30/00). */
  U("U", "MSP COST AVOIDED - HMO RATE CELL ADJUSTMENT (EFF. 9/76) (OBSOLETE 6/30/00)"),
  /** V - MSP COST AVOIDED - LITIGATION SETTLEMENT (EFF. 9/76) (OBSOLETE 6/30/00). */
  V("V", "MSP COST AVOIDED - LITIGATION SETTLEMENT (EFF. 9/76) (OBSOLETE 6/30/00)"),
  /** W - WORKER'S COMPENSATION (OBSOLETE). */
  W("W", "WORKER'S COMPENSATION (OBSOLETE)"),
  /** X - MSP COST AVOIDED - GENERIC. */
  X("X", "MSP COST AVOIDED - GENERIC"),
  /** Y - MSP COST AVOIDED - IRS/SSA DATA MATCH PROJECT (OBSOLETE 6/30/00). */
  Y("Y", "MSP COST AVOIDED - IRS/SSA DATA MATCH PROJECT (OBSOLETE 6/30/00)"),
  /**
   * Z - ZERO REIMBURSEMENT REQUEST FOR ANTICIPATED PAYMENTS (RAPS) - ZERO REIMBURSEMENT MADE DUE TO
   * MEDICAL REVIEW INTERVENTION OR WHERE PROVIDER SPECIFIC ZERO PAYMENT HAS BEEN DETERMINED.
   * (EFFECTIVE WITH HHPPS - 10/00).
   */
  Z(
      "Z",
      "ZERO REIMBURSEMENT REQUEST FOR ANTICIPATED PAYMENTS (RAPS) - ZERO REIMBURSEMENT MADE DUE TO MEDICAL REVIEW INTERVENTION OR WHERE PROVIDER SPECIFIC ZERO PAYMENT HAS BEEN DETERMINED. (EFFECTIVE WITH HHPPS - 10/00)"),
  /** INVALID - Represents an invalid code that we still want to capture. */
  INVALID("", "");

  private String code;
  private final String display;

  /**
   * Convert from a database code.
   *
   * @param code database code
   * @return claim nonpayment reason code
   */
  public static Optional<ClaimNonpaymentReasonCode> tryFromCode(String code) {
    if (code == null || code.isBlank()) {
      return Optional.empty();
    }
    return Optional.of(
        Arrays.stream(values())
            .filter(v -> v.code.equals(code))
            .findFirst()
            .orElse(handleInvalidValue(code)));
  }

  /**
   * Handles scenarios where code could not be mapped to a valid value.
   *
   * @param invalidValue the invalid value to capture
   * @return claim nonpayment reason code
   */
  public static ClaimNonpaymentReasonCode handleInvalidValue(String invalidValue) {
    var invalidClaimNonpaymentReasonCode = ClaimNonpaymentReasonCode.INVALID;
    invalidClaimNonpaymentReasonCode.code = invalidValue;
    return invalidClaimNonpaymentReasonCode;
  }

  ExplanationOfBenefit.SupportingInformationComponent toFhir(
      SupportingInfoFactory supportingInfoFactory) {
    var supportingInfo = supportingInfoFactory.createSupportingInfo();
    supportingInfo.setCategory(BlueButtonSupportingInfoCategory.CLM_MDCR_NPMT_RSN_CD.toFhir());
    supportingInfo.setCode(
        new CodeableConcept(
            new Coding()
                .setSystem(SystemUrls.BLUE_BUTTON_CODE_SYSTEM_NONPAYMENT_REASON_CODE)
                .setCode(code)
                .setDisplay(display)));
    return supportingInfo;
  }
}
