FROM public.ecr.aws/aws-observability/aws-for-fluent-bit:init-arm64-3.2.5@sha256:4243ea8ce7766ab87260b94fae725c886a5b0299aa2b57e5b5b9b997931883fd
COPY ./parsers.conf /parsers.conf
COPY ./server-fluentbit.conf /server-fluentbit.conf
COPY ./server-ng-fluentbit.conf /server-ng-fluentbit.conf
