#!/usr/bin/env groovy

pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccount: bfd
  volumes:
  - name: docker-socket
    emptyDir: {}
  containers:
  - name: docker
    image: docker:20.10-git
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    tty: true
  - name: docker-daemon
    image: docker:20.10-dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
"""
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '15', daysToKeepStr: '30'))
    }
    stages {
        stage('Docker Build') {
            steps {
                script {
                    container('docker') {
                        // checkout scm
                        // Install prerequisites
                        sh 'apk add --no-cache aws-cli bash'

                        // Address limitations resulting from CVE-2022-24767
                        sh 'git config --global --add safe.directory "$WORKSPACE"'

                        // Setup AWS Credentials
                        withEnv(['AWS_ACCESS_KEY_ID=','AWS_SECRET_ACCESS_KEY=','AWS_SESSION_TOKEN=']) {
                            withCredentials([string(credentialsId: 'bfd-aws-assume-role', variable: 'ROLE')]) {
                                    env.SESSION_NAME = env.JOB_NAME
                                    awsCredentials = sh(
                                        returnStdout: true,
                                        script: 'aws sts assume-role --role-arn "$ROLE" \
                                                --role-session-name "$SESSION_NAME" \
                                                --output text --query Credentials'
                                    ).trim().split(/\s+/)
                                env.AWS_DEFAULT_REGION = 'us-east-1'
                                env.AWS_ACCESS_KEY_ID = awsCredentials[0]
                                env.AWS_SECRET_ACCESS_KEY = awsCredentials[2]
                                env.AWS_SESSION_TOKEN = awsCredentials[3]
                            }
                        }

                        // Execute the existing build-push script
                        dir('ops/jenkins/bfd-cbc-build') {
                            sh 'bash ./build-push.sh'
                        }

                    }
                }
            }
        }
    }
}
