package gov.cms.bfd.pipeline.rda.grpc.server;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;
import gov.cms.mpsm.rda.v1.mcs.McsClaim;
import gov.cms.mpsm.rda.v1.mcs.McsDiagnosisCode;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.jupiter.api.Test;

public class RandomMcsClaimGeneratorTest {
  @Test
  public void randomClaim() throws InvalidProtocolBufferException {
    final Clock july1 = Clock.fixed(Instant.ofEpochMilli(1625172944844L), ZoneOffset.UTC);
    final RandomMcsClaimGenerator generator = new RandomMcsClaimGenerator(1, true, july1);
    final McsClaim claim = generator.randomClaim();
    final String json = JsonFormat.printer().print(claim);
    assertEquals(claim.getIdrDtlCnt(), claim.getMcsDetailsList().size());
    for (McsDiagnosisCode diagnosisCode : claim.getMcsDiagnosisCodesList()) {
      assertEquals(claim.getIdrClmHdIcn(), diagnosisCode.getIdrClmHdIcn());
    }
    assertEquals(
        "{\n"
            + "  \"idrClmHdIcn\": \"2908504\",\n"
            + "  \"idrContrId\": \"380\",\n"
            + "  \"idrHic\": \"08446326339\",\n"
            + "  \"idrClaimTypeEnum\": \"CLAIM_TYPE_ADJUSTMENT\",\n"
            + "  \"idrDtlCnt\": 2,\n"
            + "  \"idrBeneLast16\": \"vmvktf\",\n"
            + "  \"idrBeneFirstInit\": \"p\",\n"
            + "  \"idrBeneMidInit\": \"r\",\n"
            + "  \"idrBeneSexEnum\": \"BENEFICIARY_SEX_MALE\",\n"
            + "  \"idrStatusCodeEnum\": \"STATUS_CODE_APPROVED_AND_PAID_M\",\n"
            + "  \"idrStatusDate\": \"2021-06-16\",\n"
            + "  \"idrBillProvNpi\": \"czwn\",\n"
            + "  \"idrBillProvNum\": \"417057273\",\n"
            + "  \"idrBillProvEin\": \"f2d\",\n"
            + "  \"idrBillProvType\": \"ws\",\n"
            + "  \"idrBillProvSpec\": \"9\",\n"
            + "  \"idrBillProvPriceSpec\": \"kd\",\n"
            + "  \"idrBillProvCounty\": \"n0\",\n"
            + "  \"idrBillProvLoc\": \"s\",\n"
            + "  \"idrTotAllowed\": \"30585.28\",\n"
            + "  \"idrCoinsurance\": \"33.08\",\n"
            + "  \"idrDeductible\": \"6.38\",\n"
            + "  \"idrBillProvStatusCdEnum\": \"BILLING_PROVIDER_STATUS_CODE_PARTICIPATING\",\n"
            + "  \"idrTotBilledAmt\": \"58.35\",\n"
            + "  \"idrClaimReceiptDate\": \"2021-02-24\",\n"
            + "  \"idrClaimMbi\": \"m5cddvk2zkd\",\n"
            + "  \"mcsDiagnosisCodes\": [{\n"
            + "    \"idrClmHdIcn\": \"2908504\",\n"
            + "    \"idrDiagIcdTypeEnum\": \"DIAGNOSIS_ICD_TYPE_ICD9\",\n"
            + "    \"idrDiagCode\": \"gh\",\n"
            + "    \"rdaPosition\": 1\n"
            + "  }, {\n"
            + "    \"idrClmHdIcn\": \"2908504\",\n"
            + "    \"idrDiagCode\": \"qqdfhg\",\n"
            + "    \"idrDiagIcdTypeUnrecognized\": \"s\",\n"
            + "    \"rdaPosition\": 2\n"
            + "  }, {\n"
            + "    \"idrClmHdIcn\": \"2908504\",\n"
            + "    \"idrDiagCode\": \"x6\",\n"
            + "    \"idrDiagIcdTypeUnrecognized\": \"w\",\n"
            + "    \"rdaPosition\": 3\n"
            + "  }, {\n"
            + "    \"idrClmHdIcn\": \"2908504\",\n"
            + "    \"idrDiagCode\": \"ptd66\",\n"
            + "    \"idrDiagIcdTypeUnrecognized\": \"n\",\n"
            + "    \"rdaPosition\": 4\n"
            + "  }, {\n"
            + "    \"idrClmHdIcn\": \"2908504\",\n"
            + "    \"idrDiagIcdTypeEnum\": \"DIAGNOSIS_ICD_TYPE_ICD9\",\n"
            + "    \"idrDiagCode\": \"zf\",\n"
            + "    \"rdaPosition\": 5\n"
            + "  }],\n"
            + "  \"mcsDetails\": [{\n"
            + "    \"idrDtlFromDate\": \"2021-01-16\",\n"
            + "    \"idrDtlToDate\": \"2021-02-26\",\n"
            + "    \"idrProcCode\": \"hq27\",\n"
            + "    \"idrModOne\": \"n0\",\n"
            + "    \"idrModTwo\": \"5f\",\n"
            + "    \"idrModThree\": \"j\",\n"
            + "    \"idrModFour\": \"bk\",\n"
            + "    \"idrDtlDiagIcdTypeEnum\": \"DIAGNOSIS_ICD_TYPE_ICD9\",\n"
            + "    \"idrDtlPrimaryDiagCode\": \"mqt6jn\",\n"
            + "    \"idrKPosLnameOrg\": \"hgxhggqwkwvbkcptcdvdxkrntbtchxdjsfrpfprbsnfxgnxmzrxbpqwp\",\n"
            + "    \"idrKPosFname\": \"pfbvpvb\",\n"
            + "    \"idrKPosMname\": \"fhkzngxbmsvnpvszfxjwd\",\n"
            + "    \"idrKPosAddr1\": \"p4wjx3g2b3xbddg84qm\",\n"
            + "    \"idrKPosAddr21st\": \"z4hfdtc5vd88cp432hprqss1\",\n"
            + "    \"idrKPosAddr22nd\": \"6z62m2c50xj1qzr2\",\n"
            + "    \"idrKPosCity\": \"hgnmrfzqfjqcxkdwj\",\n"
            + "    \"idrKPosState\": \"r\",\n"
            + "    \"idrKPosZip\": \"391\",\n"
            + "    \"idrDtlStatusUnrecognized\": \"z\",\n"
            + "    \"idrTosUnrecognized\": \"9\",\n"
            + "    \"idrTwoDigitPosUnrecognized\": \"84\",\n"
            + "    \"idrDtlRendType\": \"1w\",\n"
            + "    \"idrDtlRendSpec\": \"2p\",\n"
            + "    \"idrDtlRendNpi\": \"w31jvnfc4\",\n"
            + "    \"idrDtlRendProv\": \"8wh1d6\",\n"
            + "    \"idrKDtlFacProvNpi\": \"851\",\n"
            + "    \"idrDtlAmbPickupAddres1\": \"bcpk3m4rv9ph1cpddw8mmqs7\",\n"
            + "    \"idrDtlAmbPickupAddres2\": \"n\",\n"
            + "    \"idrDtlAmbPickupCity\": \"8k48ppqsb00j5shm4\",\n"
            + "    \"idrDtlAmbPickupState\": \"w5\",\n"
            + "    \"idrDtlAmbPickupZipcode\": \"p2\",\n"
            + "    \"idrDtlAmbDropoffName\": \"290g0qcr00wr3s173x\",\n"
            + "    \"idrDtlAmbDropoffAddrL1\": \"mwr1h5zdvp70zd372r98j2c\",\n"
            + "    \"idrDtlAmbDropoffAddrL2\": \"5484d9t5m8sxf9992g\",\n"
            + "    \"idrDtlAmbDropoffCity\": \"fq4xsnbb8q951stk\",\n"
            + "    \"idrDtlAmbDropoffState\": \"c2\",\n"
            + "    \"idrDtlAmbDropoffZipcode\": \"3vcwvcg\",\n"
            + "    \"idrDtlNumber\": 1\n"
            + "  }, {\n"
            + "    \"idrDtlFromDate\": \"2021-01-18\",\n"
            + "    \"idrDtlToDate\": \"2021-04-26\",\n"
            + "    \"idrProcCode\": \"k\",\n"
            + "    \"idrModOne\": \"1\",\n"
            + "    \"idrModTwo\": \"xn\",\n"
            + "    \"idrModThree\": \"gw\",\n"
            + "    \"idrModFour\": \"w6\",\n"
            + "    \"idrDtlDiagIcdTypeEnum\": \"DIAGNOSIS_ICD_TYPE_ICD9\",\n"
            + "    \"idrDtlPrimaryDiagCode\": \"p6m\",\n"
            + "    \"idrKPosLnameOrg\": \"skhdzktxwskmkcdrjbnjkthjxztjnnnx\",\n"
            + "    \"idrKPosFname\": \"jzffkcr\",\n"
            + "    \"idrKPosMname\": \"qngsjt\",\n"
            + "    \"idrKPosAddr1\": \"xhw2798nsjvbw7mcc69mxv2707xwr9dkmk5m7qpxjkg0cb1rrd65q\",\n"
            + "    \"idrKPosAddr21st\": \"9g2d3rstrgh5bx2\",\n"
            + "    \"idrKPosAddr22nd\": \"cb2c80dm08k22b05\",\n"
            + "    \"idrKPosCity\": \"twwxdrmtjrhmhqtfcsgsr\",\n"
            + "    \"idrKPosState\": \"p\",\n"
            + "    \"idrKPosZip\": \"823134883570075\",\n"
            + "    \"idrDtlStatusUnrecognized\": \"t\",\n"
            + "    \"idrTosUnrecognized\": \"h\",\n"
            + "    \"idrTwoDigitPosUnrecognized\": \"0k\",\n"
            + "    \"idrDtlRendType\": \"0r\",\n"
            + "    \"idrDtlRendSpec\": \"zt\",\n"
            + "    \"idrDtlRendNpi\": \"3v0t\",\n"
            + "    \"idrDtlRendProv\": \"fsv\",\n"
            + "    \"idrKDtlFacProvNpi\": \"7dt\",\n"
            + "    \"idrDtlAmbPickupAddres1\": \"g59v\",\n"
            + "    \"idrDtlAmbPickupAddres2\": \"scfc1nb3h6r\",\n"
            + "    \"idrDtlAmbPickupCity\": \"8htv\",\n"
            + "    \"idrDtlAmbPickupState\": \"7\",\n"
            + "    \"idrDtlAmbPickupZipcode\": \"m232ff\",\n"
            + "    \"idrDtlAmbDropoffName\": \"2bthr0spfrqbr7xpcj3f77mf\",\n"
            + "    \"idrDtlAmbDropoffAddrL1\": \"ghqvq0thcxxt2m3qfp26cmsp\",\n"
            + "    \"idrDtlAmbDropoffAddrL2\": \"pgnqzfpg0\",\n"
            + "    \"idrDtlAmbDropoffCity\": \"4p3\",\n"
            + "    \"idrDtlAmbDropoffState\": \"s\",\n"
            + "    \"idrDtlAmbDropoffZipcode\": \"4j\",\n"
            + "    \"idrDtlNumber\": 2\n"
            + "  }],\n"
            + "  \"idrBillProvGroupIndUnrecognized\": \"p\",\n"
            + "  \"idrHdrFromDos\": \"2021-01-16\",\n"
            + "  \"idrHdrToDos\": \"2021-04-26\",\n"
            + "  \"idrAssignmentEnum\": \"CLAIM_ASSIGNMENT_NON_ASSIGNED\",\n"
            + "  \"idrClmLevelIndEnum\": \"CLAIM_LEVEL_INDICATOR_ADJUSTED\",\n"
            + "  \"idrHdrAudit\": 868,\n"
            + "  \"idrHdrAuditIndUnrecognized\": \"m\",\n"
            + "  \"idrUSplitReasonUnrecognized\": \"p\",\n"
            + "  \"idrJReferringProvNpi\": \"4z792fv\",\n"
            + "  \"idrJFacProvNpi\": \"10vtm2bq4\",\n"
            + "  \"idrUDemoProvNpi\": \"fxr\",\n"
            + "  \"idrUSuperNpi\": \"hk7x0f1\",\n"
            + "  \"idrUFcadjBilNpi\": \"2m\",\n"
            + "  \"idrAmbPickupAddresLine1\": \"x4446qjt9g872rk\",\n"
            + "  \"idrAmbPickupAddresLine2\": \"cd91tbhfjqk3q\",\n"
            + "  \"idrAmbPickupCity\": \"j0640\",\n"
            + "  \"idrAmbPickupState\": \"9b\",\n"
            + "  \"idrAmbPickupZipcode\": \"mc1\",\n"
            + "  \"idrAmbDropoffName\": \"kd8gjq\",\n"
            + "  \"idrAmbDropoffAddrLine1\": \"xpz\",\n"
            + "  \"idrAmbDropoffAddrLine2\": \"vzw1nc3853kc1xvs\",\n"
            + "  \"idrAmbDropoffCity\": \"b5\",\n"
            + "  \"idrAmbDropoffState\": \"h\",\n"
            + "  \"idrAmbDropoffZipcode\": \"5\",\n"
            + "  \"mcsAudits\": [{\n"
            + "    \"idrJAuditNum\": 12851,\n"
            + "    \"idrJAuditIndEnum\": \"CUTBACK_AUDIT_INDICATOR__AUDIT_NUM_IS_ZEROES\",\n"
            + "    \"idrJAuditDispUnrecognized\": \"9\",\n"
            + "    \"rdaPosition\": 1\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 27913,\n"
            + "    \"idrJAuditIndUnrecognized\": \"c\",\n"
            + "    \"idrJAuditDispUnrecognized\": \"s\",\n"
            + "    \"rdaPosition\": 2\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 24319,\n"
            + "    \"idrJAuditIndEnum\": \"CUTBACK_AUDIT_INDICATOR_AUDIT_NUMBER\",\n"
            + "    \"idrJAuditDispEnum\": \"CUTBACK_AUDIT_DISPOSITION_DENY\",\n"
            + "    \"rdaPosition\": 3\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 26370,\n"
            + "    \"idrJAuditIndEnum\": \"CUTBACK_AUDIT_INDICATOR_HEADER_EDIT_NUMBER\",\n"
            + "    \"idrJAuditDispUnrecognized\": \"9\",\n"
            + "    \"rdaPosition\": 4\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 1850,\n"
            + "    \"idrJAuditIndEnum\": \"CUTBACK_AUDIT_INDICATOR_HEADER_EDIT_NUMBER\",\n"
            + "    \"idrJAuditDispUnrecognized\": \"5\",\n"
            + "    \"rdaPosition\": 5\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 9612,\n"
            + "    \"idrJAuditIndUnrecognized\": \"t\",\n"
            + "    \"idrJAuditDispUnrecognized\": \"4\",\n"
            + "    \"rdaPosition\": 6\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 16012,\n"
            + "    \"idrJAuditIndEnum\": \"CUTBACK_AUDIT_INDICATOR_HEADER_EDIT_NUMBER\",\n"
            + "    \"idrJAuditDispEnum\": \"CUTBACK_AUDIT_DISPOSITION_CUTBACK_TO_LIMIT\",\n"
            + "    \"rdaPosition\": 7\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 4307,\n"
            + "    \"idrJAuditIndEnum\": \"CUTBACK_AUDIT_INDICATOR_HEADER_EDIT_NUMBER\",\n"
            + "    \"idrJAuditDispEnum\": \"CUTBACK_AUDIT_DISPOSITION_AUDIT_OVERRIDDEN\",\n"
            + "    \"rdaPosition\": 8\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 23107,\n"
            + "    \"idrJAuditIndEnum\": \"CUTBACK_AUDIT_INDICATOR__AUDIT_NUM_IS_ZEROES\",\n"
            + "    \"idrJAuditDispEnum\": \"CUTBACK_AUDIT_DISPOSITION_AUTO_DENY_WITHOUT_TRANSMIT_TO_CWF\",\n"
            + "    \"rdaPosition\": 9\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 14296,\n"
            + "    \"idrJAuditIndEnum\": \"CUTBACK_AUDIT_INDICATOR__AUDIT_NUM_IS_ZEROES\",\n"
            + "    \"idrJAuditDispUnrecognized\": \"5\",\n"
            + "    \"rdaPosition\": 10\n"
            + "  }],\n"
            + "  \"mcsAdjustments\": [{\n"
            + "    \"idrAdjDate\": \"2021-02-24\",\n"
            + "    \"idrXrefIcn\": \"8dnb7\",\n"
            + "    \"idrAdjClerk\": \"10\",\n"
            + "    \"idrInitCcn\": \"r6rrbmktg7gj0\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-04-26\",\n"
            + "    \"idrAdjBEombAmt\": \"8.28\",\n"
            + "    \"idrAdjPEombAmt\": \"34.32\",\n"
            + "    \"rdaPosition\": 1\n"
            + "  }, {\n"
            + "    \"idrAdjDate\": \"2021-06-08\",\n"
            + "    \"idrXrefIcn\": \"1\",\n"
            + "    \"idrAdjClerk\": \"j\",\n"
            + "    \"idrInitCcn\": \"pn0xw\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-01-29\",\n"
            + "    \"idrAdjBEombAmt\": \"67.26\",\n"
            + "    \"idrAdjPEombAmt\": \"62.64\",\n"
            + "    \"rdaPosition\": 2\n"
            + "  }, {\n"
            + "    \"idrAdjDate\": \"2021-02-03\",\n"
            + "    \"idrXrefIcn\": \"1sm2b\",\n"
            + "    \"idrAdjClerk\": \"c6v5\",\n"
            + "    \"idrInitCcn\": \"jjsmqcm0\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-04-07\",\n"
            + "    \"idrAdjBEombAmt\": \"139.30\",\n"
            + "    \"idrAdjPEombAmt\": \"246.11\",\n"
            + "    \"rdaPosition\": 3\n"
            + "  }, {\n"
            + "    \"idrAdjDate\": \"2021-02-14\",\n"
            + "    \"idrXrefIcn\": \"65k01d2xp4sb06s\",\n"
            + "    \"idrAdjClerk\": \"hqj\",\n"
            + "    \"idrInitCcn\": \"zd03cn\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-01-29\",\n"
            + "    \"idrAdjBEombAmt\": \"299.69\",\n"
            + "    \"idrAdjPEombAmt\": \"189.15\",\n"
            + "    \"rdaPosition\": 4\n"
            + "  }, {\n"
            + "    \"idrAdjDate\": \"2021-06-29\",\n"
            + "    \"idrXrefIcn\": \"99sgb\",\n"
            + "    \"idrAdjClerk\": \"1m\",\n"
            + "    \"idrInitCcn\": \"0bg216b\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-04-20\",\n"
            + "    \"idrAdjBEombAmt\": \"60427.40\",\n"
            + "    \"idrAdjPEombAmt\": \"25.84\",\n"
            + "    \"rdaPosition\": 5\n"
            + "  }]\n"
            + "}",
        json);
  }
}
