package gov.cms.bfd.pipeline.rda.grpc.server;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;
import gov.cms.mpsm.rda.v1.fiss.FissClaim;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.jupiter.api.Test;

public class RandomFissClaimGeneratorTest {
  @Test
  public void randomClaim() throws InvalidProtocolBufferException {
    final Clock july1 = Clock.fixed(Instant.ofEpochMilli(1625172944844L), ZoneOffset.UTC);
    final RandomFissClaimGenerator generator = new RandomFissClaimGenerator(1, true, july1);
    final FissClaim claim = generator.randomClaim();
    final String json = JsonFormat.printer().print(claim);
    assertEquals(
        "{\n"
            + "  \"dcn\": \"962289\",\n"
            + "  \"hicNo\": \"290850477419\",\n"
            + "  \"currStatusEnum\": \"CLAIM_STATUS_PAID\",\n"
            + "  \"currLoc2Enum\": \"CURRENT_LOCATION_2_POST_PAY_7518\",\n"
            + "  \"provStateCd\": \"w2\",\n"
            + "  \"provTypFacilCd\": \"n\",\n"
            + "  \"provEmerInd\": \"m\",\n"
            + "  \"provDeptId\": \"jvz\",\n"
            + "  \"totalChargeAmount\": \"0.68\",\n"
            + "  \"recdDtCymd\": \"2021-02-18\",\n"
            + "  \"currTranDtCymd\": \"2021-03-15\",\n"
            + "  \"admDiagCode\": \"htrmjgj\",\n"
            + "  \"principleDiag\": \"pcfkzkv\",\n"
            + "  \"npiNumber\": \"8759509183\",\n"
            + "  \"mbi\": \"9dt7s6qr19q\",\n"
            + "  \"fedTaxNb\": \"7805810238\",\n"
            + "  \"fissProcCodes\": [{\n"
            + "    \"procCd\": \"pcfkzkv\",\n"
            + "    \"rdaPosition\": 1,\n"
            + "    \"procFlag\": \"v\",\n"
            + "    \"procDt\": \"2021-06-09\"\n"
            + "  }, {\n"
            + "    \"procCd\": \"rb\",\n"
            + "    \"rdaPosition\": 2,\n"
            + "    \"procFlag\": \"gz\",\n"
            + "    \"procDt\": \"2021-01-28\"\n"
            + "  }, {\n"
            + "    \"procCd\": \"tbbjqc\",\n"
            + "    \"rdaPosition\": 3,\n"
            + "    \"procFlag\": \"x\",\n"
            + "    \"procDt\": \"2021-03-16\"\n"
            + "  }, {\n"
            + "    \"procCd\": \"tnqvrfx\",\n"
            + "    \"rdaPosition\": 4,\n"
            + "    \"procFlag\": \"bnt\",\n"
            + "    \"procDt\": \"2021-01-13\"\n"
            + "  }, {\n"
            + "    \"procCd\": \"jsr\",\n"
            + "    \"rdaPosition\": 5,\n"
            + "    \"procFlag\": \"vft\",\n"
            + "    \"procDt\": \"2021-04-20\"\n"
            + "  }],\n"
            + "  \"medaProvId\": \"w5sp0fr9tf9wq\",\n"
            + "  \"pracLocAddr1\": \"kd925nvjcrvr\",\n"
            + "  \"pracLocAddr2\": \"n0j6mjqmhxz4p3dgx11g3mzjs6q9m42c672zkjrcw4zhgsjfzrsgvg08gjgxz7cnwffwqc659cx75qv3\",\n"
            + "  \"pracLocCity\": \"s2143xcvkn0jh399b20406whrtc3gqq71zfd2mstc1fj54r\",\n"
            + "  \"pracLocState\": \"pj\",\n"
            + "  \"pracLocZip\": \"73\",\n"
            + "  \"fissDiagCodes\": [{\n"
            + "    \"diagCd2\": \"mf\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_NO\",\n"
            + "    \"bitFlags\": \"b\",\n"
            + "    \"rdaPosition\": 1\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"zb\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_CLINICALLY_UNDETERMINED\",\n"
            + "    \"bitFlags\": \"ww\",\n"
            + "    \"rdaPosition\": 2\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"rzdjkrk\",\n"
            + "    \"bitFlags\": \"dkfp\",\n"
            + "    \"diagPoaIndUnrecognized\": \"t\",\n"
            + "    \"rdaPosition\": 3\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"mkxgkbn\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_CLINICALLY_UNDETERMINED\",\n"
            + "    \"bitFlags\": \"gzcd\",\n"
            + "    \"rdaPosition\": 4\n"
            + "  }],\n"
            + "  \"currLoc1Unrecognized\": \"d\",\n"
            + "  \"stmtCovFromCymd\": \"2021-02-21\",\n"
            + "  \"stmtCovToCymd\": \"2021-01-31\",\n"
            + "  \"lobCdUnrecognized\": \"h\",\n"
            + "  \"servTypeCdForClinicsEnum\": \"BILL_CLASSIFICATION_FOR_CLINICS_HOSPITAL_BASED_OR_INDEPENDENT_RENAL_DIALYSIS_FACILITY\",\n"
            + "  \"freqCdEnum\": \"BILL_FREQUENCY_REPLACEMENT_OF_PRIOR_CLAIM\",\n"
            + "  \"billTypCd\": \"d86\",\n"
            + "  \"fissPayers\": [{\n"
            + "    \"insuredPayer\": {\n"
            + "      \"rdaPosition\": 1,\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_WORKERS_COMPENSATION\",\n"
            + "      \"payersName\": \"zmmdhgmqxwbpvhkhwsjnntbmrbpc\",\n"
            + "      \"relIndUnrecognized\": \"p\",\n"
            + "      \"assignIndEnum\": \"ASSIGNMENT_OF_BENEFITS_INDICATOR_NO_BENEFITS_ASSIGNED\",\n"
            + "      \"providerNumber\": \"vwbqcrppsftjj\",\n"
            + "      \"adjDcnIcn\": \"qgssqgbtwmgtsmrvcsjqrxq\",\n"
            + "      \"priorPmt\": \"752.76\",\n"
            + "      \"estAmtDue\": \"7481.13\",\n"
            + "      \"insuredRelUnrecognized\": \"50\",\n"
            + "      \"insuredName\": \"grnqhshtznkcrwbnmhxxrgqwr\",\n"
            + "      \"insuredSsnHic\": \"m\",\n"
            + "      \"insuredGroupName\": \"hdbvccm\",\n"
            + "      \"insuredGroupNbr\": \"qpdttcdhdqcfxjvrtkcq\",\n"
            + "      \"treatAuthCd\": \"j\",\n"
            + "      \"insuredSexUnrecognized\": \"s\",\n"
            + "      \"insuredRelX12Unrecognized\": \"47\",\n"
            + "      \"insuredDob\": \"2021-04-18\",\n"
            + "      \"insuredDobText\": \"04182021\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"beneZPayer\": {\n"
            + "      \"rdaPosition\": 2,\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_MEDICARE\",\n"
            + "      \"payersName\": \"5xn1\",\n"
            + "      \"relIndEnum\": \"RELEASE_OF_INFORMATION_SIGNED_STATEMENT_WAS_OBTAINED\",\n"
            + "      \"assignIndUnrecognized\": \"x\",\n"
            + "      \"providerNumber\": \"ghcz\",\n"
            + "      \"adjDcnIcn\": \"4sbtcbj0pvsnnt29d\",\n"
            + "      \"priorPmt\": \"75.77\",\n"
            + "      \"estAmtDue\": \"719.73\",\n"
            + "      \"beneRelUnrecognized\": \"06\",\n"
            + "      \"beneLastName\": \"nchxs\",\n"
            + "      \"beneFirstName\": \"jbhpwz\",\n"
            + "      \"beneMidInit\": \"x\",\n"
            + "      \"beneSsnHic\": \"zfdt2\",\n"
            + "      \"insuredGroupName\": \"zsvppjqkfrshvmms\",\n"
            + "      \"beneDob\": \"2021-01-16\",\n"
            + "      \"beneSexEnum\": \"BENEFICIARY_SEX_FEMALE\",\n"
            + "      \"treatAuthCd\": \"v\",\n"
            + "      \"insuredSexEnum\": \"BENEFICIARY_SEX_UNKNOWN\",\n"
            + "      \"insuredRelX12Enum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_36\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"beneZPayer\": {\n"
            + "      \"rdaPosition\": 3,\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_LIABILITY\",\n"
            + "      \"payersName\": \"jqxvjfxp4j\",\n"
            + "      \"relIndEnum\": \"RELEASE_OF_INFORMATION_SIGNED_STATEMENT_WAS_OBTAINED\",\n"
            + "      \"assignIndUnrecognized\": \"h\",\n"
            + "      \"providerNumber\": \"x39cgtxwh\",\n"
            + "      \"adjDcnIcn\": \"gb9r84z1nd\",\n"
            + "      \"priorPmt\": \"9156.85\",\n"
            + "      \"estAmtDue\": \"9361.30\",\n"
            + "      \"beneRelEnum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_40\",\n"
            + "      \"beneLastName\": \"hg\",\n"
            + "      \"beneFirstName\": \"rtczmks\",\n"
            + "      \"beneMidInit\": \"m\",\n"
            + "      \"beneSsnHic\": \"9ww0p1bqz9xq65\",\n"
            + "      \"insuredGroupName\": \"wgsgxrgtqt\",\n"
            + "      \"beneDob\": \"2021-01-25\",\n"
            + "      \"beneSexEnum\": \"BENEFICIARY_SEX_UNKNOWN\",\n"
            + "      \"treatAuthCd\": \"x\",\n"
            + "      \"insuredSexUnrecognized\": \"w\",\n"
            + "      \"insuredRelX12Unrecognized\": \"22\"\n"
            + "    }\n"
            + "  }],\n"
            + "  \"fissAuditTrail\": [{\n"
            + "    \"badtStatusUnrecognized\": \"n\",\n"
            + "    \"badtLoc\": \"8k\",\n"
            + "    \"badtOperId\": \"w\",\n"
            + "    \"badtReas\": \"p2nz\",\n"
            + "    \"badtCurrDateCymd\": \"2021-02-14\",\n"
            + "    \"rdaPosition\": 1\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_DENIED\",\n"
            + "    \"badtLoc\": \"548\",\n"
            + "    \"badtOperId\": \"fq4xs\",\n"
            + "    \"badtReas\": \"c29\",\n"
            + "    \"badtCurrDateCymd\": \"2021-03-18\",\n"
            + "    \"rdaPosition\": 2\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"5\",\n"
            + "    \"badtLoc\": \"1b\",\n"
            + "    \"badtOperId\": \"khz8\",\n"
            + "    \"badtReas\": \"17238\",\n"
            + "    \"badtCurrDateCymd\": \"2021-05-25\",\n"
            + "    \"rdaPosition\": 3\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"g\",\n"
            + "    \"badtLoc\": \"w605r\",\n"
            + "    \"badtOperId\": \"9b7tk\",\n"
            + "    \"badtReas\": \"p\",\n"
            + "    \"badtCurrDateCymd\": \"2021-05-31\",\n"
            + "    \"rdaPosition\": 4\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_RETURN_TO_PRO\",\n"
            + "    \"badtLoc\": \"m\",\n"
            + "    \"badtOperId\": \"xhw27\",\n"
            + "    \"badtReas\": \"9g2d3\",\n"
            + "    \"badtCurrDateCymd\": \"2021-06-01\",\n"
            + "    \"rdaPosition\": 5\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_REJECT\",\n"
            + "    \"badtLoc\": \"4\",\n"
            + "    \"badtOperId\": \"fjkt2nfcz\",\n"
            + "    \"badtReas\": \"h\",\n"
            + "    \"badtCurrDateCymd\": \"2021-01-14\",\n"
            + "    \"rdaPosition\": 6\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"0\",\n"
            + "    \"badtLoc\": \"zt\",\n"
            + "    \"badtOperId\": \"3\",\n"
            + "    \"badtReas\": \"fsv\",\n"
            + "    \"badtCurrDateCymd\": \"2021-06-09\",\n"
            + "    \"rdaPosition\": 7\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"g\",\n"
            + "    \"badtLoc\": \"s\",\n"
            + "    \"badtOperId\": \"8htvg\",\n"
            + "    \"badtReas\": \"7\",\n"
            + "    \"badtCurrDateCymd\": \"2021-05-30\",\n"
            + "    \"rdaPosition\": 8\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"2\",\n"
            + "    \"badtLoc\": \"ghqv\",\n"
            + "    \"badtOperId\": \"pgnqzfpg\",\n"
            + "    \"badtReas\": \"4p3\",\n"
            + "    \"badtCurrDateCymd\": \"2021-03-20\",\n"
            + "    \"rdaPosition\": 9\n"
            + "  }],\n"
            + "  \"rejectCd\": \"43\",\n"
            + "  \"fullPartDenInd\": \"h\",\n"
            + "  \"nonPayInd\": \"m\",\n"
            + "  \"xrefDcnNbr\": \"pc9jbzhcbf\",\n"
            + "  \"adjReqCdUnrecognized\": \"4\",\n"
            + "  \"adjReasCd\": \"1\",\n"
            + "  \"cancelXrefDcn\": \"fx\",\n"
            + "  \"cancelDateCymd\": \"2021-05-16\",\n"
            + "  \"cancAdjCdEnum\": \"CANCEL_ADJUSTMENT_CODE_SCRAMBLE_HIC\",\n"
            + "  \"originalXrefDcn\": \"x4446qjt9g872rkjm7\",\n"
            + "  \"paidDtCymd\": \"2021-02-19\",\n"
            + "  \"admDateCymd\": \"2021-06-27\",\n"
            + "  \"admSourceUnrecognized\": \"9\",\n"
            + "  \"primaryPayerCodeEnum\": \"PAYERS_CODE_OTHER\",\n"
            + "  \"attendPhysId\": \"kd8gjq252v7k8mh\",\n"
            + "  \"attendPhysLname\": \"xpznftd\",\n"
            + "  \"attendPhysFname\": \"vzw1nc3853kc\",\n"
            + "  \"attendPhysMint\": \"b\",\n"
            + "  \"attendPhysFlagEnum\": \"PHYSICIAN_FLAG_NO\",\n"
            + "  \"operatingPhysId\": \"5\",\n"
            + "  \"operPhysLname\": \"wztqr4pxv4m03s44\",\n"
            + "  \"operPhysFname\": \"5v\",\n"
            + "  \"operPhysMint\": \"8\",\n"
            + "  \"operPhysFlagUnrecognized\": \"1\",\n"
            + "  \"othPhysId\": \"r6r\",\n"
            + "  \"othPhysLname\": \"9s957dw8\",\n"
            + "  \"othPhysFname\": \"f5zghtnjb4t75\",\n"
            + "  \"othPhysMint\": \"d\",\n"
            + "  \"othPhysFlagEnum\": \"PHYSICIAN_FLAG_NO\",\n"
            + "  \"xrefHicNbr\": \"1q7s6r30rs\",\n"
            + "  \"procNewHicIndUnrecognized\": \"j\",\n"
            + "  \"newHic\": \"pn0xw\",\n"
            + "  \"reposIndUnrecognized\": \"9\",\n"
            + "  \"reposHic\": \"kbrdt24\",\n"
            + "  \"mbiSubmBeneIndEnum\": \"FISS_HIC_OR_MBI_IS_MBI\",\n"
            + "  \"adjMbiIndUnrecognized\": \"d\",\n"
            + "  \"adjMbi\": \"1s\",\n"
            + "  \"medicalRecordNo\": \"c6v\"\n"
            + "}",
        json);
  }
}
