package gov.cms.bfd.pipeline.rda.grpc.server;

import static junit.framework.TestCase.assertEquals;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;
import gov.cms.mpsm.rda.v1.fiss.FissClaim;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.Test;

public class RandomFissClaimGeneratorTest {
  @Test
  public void randomClaim() throws InvalidProtocolBufferException {
    final Clock july1 = Clock.fixed(Instant.ofEpochMilli(1625172944844L), ZoneOffset.UTC);
    final RandomFissClaimGenerator generator = new RandomFissClaimGenerator(1, true, july1);
    final FissClaim claim = generator.randomClaim();
    final String json = JsonFormat.printer().print(claim);
    assertEquals(
        "{\n"
            + "  \"dcn\": \"9845557\",\n"
            + "  \"hicNo\": \"904843533707\",\n"
            + "  \"currStatusEnum\": \"CLAIM_STATUS_MOVE\",\n"
            + "  \"currLoc1Enum\": \"PROCESSING_TYPE_OFFLINE\",\n"
            + "  \"currLoc2Enum\": \"CURRENT_LOCATION_2_POST_PAY_7563\",\n"
            + "  \"totalChargeAmount\": \"8.83\",\n"
            + "  \"recdDtCymd\": \"2021-03-03\",\n"
            + "  \"currTranDtCymd\": \"2021-05-14\",\n"
            + "  \"admDiagCode\": \"mszx\",\n"
            + "  \"principleDiag\": \"hgr\",\n"
            + "  \"npiNumber\": \"7690551274\",\n"
            + "  \"mbi\": \"8f242z2sssv46\",\n"
            + "  \"fedTaxNb\": \"8932960060\",\n"
            + "  \"fissProcCodes\": [{\n"
            + "    \"procCd\": \"hgr\",\n"
            + "    \"procFlag\": \"djsr\",\n"
            + "    \"procDt\": \"2021-04-18\"\n"
            + "  }, {\n"
            + "    \"procCd\": \"zzm\",\n"
            + "    \"procFlag\": \"gg\",\n"
            + "    \"procDt\": \"2021-05-25\"\n"
            + "  }],\n"
            + "  \"medaProvId\": \"c6vcs2xqbzp5w\",\n"
            + "  \"pracLocAddr1\": \"fz5qbm7h08g\",\n"
            + "  \"pracLocAddr2\": \"sb9b66k2v3fs2wf24p5mxp3k0bth5s2vg\",\n"
            + "  \"pracLocCity\": \"x1njn3q6ftzx2266s0g4rqqx9qp24pb3rhw165ttc3cdnq42s3tkjz1hg\",\n"
            + "  \"pracLocState\": \"zg\",\n"
            + "  \"pracLocZip\": \"60\",\n"
            + "  \"fissDiagCodes\": [{\n"
            + "    \"diagCd2\": \"skfw\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_NO\",\n"
            + "    \"bitFlags\": \"kjc\"\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"dfz\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_UNKNOWN\",\n"
            + "    \"bitFlags\": \"m\"\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"phjhpc\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_YES\",\n"
            + "    \"bitFlags\": \"xdt\"\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"h\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_UNREPORTED\",\n"
            + "    \"bitFlags\": \"m\"\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"gjzxbnb\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_UNREPORTED\",\n"
            + "    \"bitFlags\": \"bwrg\"\n"
            + "  }],\n"
            + "  \"stmtCovFromCymd\": \"2021-01-16\",\n"
            + "  \"stmtCovToCymd\": \"2021-03-27\",\n"
            + "  \"lobCdUnrecognized\": \"h\",\n"
            + "  \"servTypeCdForSpecialFacilitiesEnum\": \"BILL_CLASSIFICATION_FOR_SPECIAL_FACILITIES_HOSPICE_HOSPITAL_BASED\",\n"
            + "  \"freqCdUnrecognized\": \"v\",\n"
            + "  \"billTypCd\": \"6fr\",\n"
            + "  \"fissPayers\": [{\n"
            + "    \"insuredPayer\": {\n"
            + "      \"payersIdUnrecognized\": \"6\",\n"
            + "      \"payersName\": \"g\",\n"
            + "      \"relIndEnum\": \"RELEASE_OF_INFORMATION_NO_RELEASE_ON_FILE\",\n"
            + "      \"assignIndEnum\": \"ASSIGNMENT_OF_BENEFITS_INDICATOR_NO_BENEFITS_ASSIGNED\",\n"
            + "      \"providerNumber\": \"d\",\n"
            + "      \"adjDcnIcn\": \"m\",\n"
            + "      \"priorPmt\": \"76.17\",\n"
            + "      \"estAmtDue\": \"95720.08\",\n"
            + "      \"insuredRelUnrecognized\": \"m\",\n"
            + "      \"insuredName\": \"z\",\n"
            + "      \"insuredSsnHic\": \"h\",\n"
            + "      \"insuredGroupName\": \"d\",\n"
            + "      \"insuredGroupNbr\": \"f\",\n"
            + "      \"treatAuthCd\": \"2021-04-11\",\n"
            + "      \"insuredSexUnrecognized\": \"n\",\n"
            + "      \"insuredRelX12Enum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_34\",\n"
            + "      \"insuredDob\": \"2021-02-05\",\n"
            + "      \"insuredDobText\": \"26987043124\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"beneZPayer\": {\n"
            + "      \"payersIdUnrecognized\": \"g\",\n"
            + "      \"payersName\": \"v\",\n"
            + "      \"relIndUnrecognized\": \"g\",\n"
            + "      \"assignIndUnrecognized\": \"m\",\n"
            + "      \"providerNumber\": \"c\",\n"
            + "      \"adjDcnIcn\": \"d\",\n"
            + "      \"priorPmt\": \"9727.42\",\n"
            + "      \"estAmtDue\": \"65862.54\",\n"
            + "      \"beneRelUnrecognized\": \"k\",\n"
            + "      \"beneLastName\": \"k\",\n"
            + "      \"beneFirstName\": \"f\",\n"
            + "      \"beneMidInit\": \"j\",\n"
            + "      \"beneSsnHic\": \"r\",\n"
            + "      \"insuredGroupName\": \"j\",\n"
            + "      \"beneDob\": \"2021-06-20\",\n"
            + "      \"beneSexEnum\": \"BENEFICIARY_SEX_UNKNOWN\",\n"
            + "      \"treatAuthCd\": \"x\",\n"
            + "      \"insuredSexUnrecognized\": \"n\",\n"
            + "      \"insuredRelX12Enum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_63\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"insuredPayer\": {\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_MEDICARE\",\n"
            + "      \"payersName\": \"f\",\n"
            + "      \"relIndEnum\": \"RELEASE_OF_INFORMATION_SIGNED_STATEMENT_IS_RESTRICTED_OR_LIMITED\",\n"
            + "      \"assignIndEnum\": \"ASSIGNMENT_OF_BENEFITS_INDICATOR_BENEFITS_ASSIGNED\",\n"
            + "      \"providerNumber\": \"b\",\n"
            + "      \"adjDcnIcn\": \"h\",\n"
            + "      \"priorPmt\": \"93.84\",\n"
            + "      \"estAmtDue\": \"0.80\",\n"
            + "      \"insuredRelUnrecognized\": \"v\",\n"
            + "      \"insuredName\": \"x\",\n"
            + "      \"insuredSsnHic\": \"n\",\n"
            + "      \"insuredGroupName\": \"s\",\n"
            + "      \"insuredGroupNbr\": \"m\",\n"
            + "      \"treatAuthCd\": \"2021-02-02\",\n"
            + "      \"insuredSexUnrecognized\": \"p\",\n"
            + "      \"insuredRelX12Enum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_72\",\n"
            + "      \"insuredDob\": \"2021-05-07\",\n"
            + "      \"insuredDobText\": \"8227450709\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"insuredPayer\": {\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_AUTO_NO_FAULT\",\n"
            + "      \"payersName\": \"r\",\n"
            + "      \"relIndEnum\": \"RELEASE_OF_INFORMATION_NO_RELEASE_ON_FILE\",\n"
            + "      \"assignIndEnum\": \"ASSIGNMENT_OF_BENEFITS_INDICATOR_BENEFITS_ASSIGNED\",\n"
            + "      \"providerNumber\": \"x\",\n"
            + "      \"adjDcnIcn\": \"r\",\n"
            + "      \"priorPmt\": \"40.24\",\n"
            + "      \"estAmtDue\": \"9581.14\",\n"
            + "      \"insuredRelEnum\": \"PATIENT_RELATIONSHIP_CODE_ORGAN_DONOR\",\n"
            + "      \"insuredName\": \"b\",\n"
            + "      \"insuredSsnHic\": \"q\",\n"
            + "      \"insuredGroupName\": \"k\",\n"
            + "      \"insuredGroupNbr\": \"k\",\n"
            + "      \"treatAuthCd\": \"2021-05-28\",\n"
            + "      \"insuredSexUnrecognized\": \"m\",\n"
            + "      \"insuredRelX12Enum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_78\",\n"
            + "      \"insuredDob\": \"2021-02-22\",\n"
            + "      \"insuredDobText\": \"566694594489\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"insuredPayer\": {\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_OTHER\",\n"
            + "      \"payersName\": \"p\",\n"
            + "      \"relIndUnrecognized\": \"x\",\n"
            + "      \"assignIndUnrecognized\": \"c\",\n"
            + "      \"providerNumber\": \"n\",\n"
            + "      \"adjDcnIcn\": \"z\",\n"
            + "      \"priorPmt\": \"81.65\",\n"
            + "      \"estAmtDue\": \"16.18\",\n"
            + "      \"insuredRelUnrecognized\": \"t\",\n"
            + "      \"insuredName\": \"f\",\n"
            + "      \"insuredSsnHic\": \"f\",\n"
            + "      \"insuredGroupName\": \"s\",\n"
            + "      \"insuredGroupNbr\": \"f\",\n"
            + "      \"treatAuthCd\": \"2021-04-07\",\n"
            + "      \"insuredSexEnum\": \"BENEFIXIARY_SEX_FEMALE\",\n"
            + "      \"insuredRelX12Unrecognized\": \"r\",\n"
            + "      \"insuredDob\": \"2021-06-07\",\n"
            + "      \"insuredDobText\": \"54386085963\"\n"
            + "    }\n"
            + "  }]\n"
            + "}",
        json);
  }
}
