package gov.cms.bfd.pipeline.rda.grpc.server;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;
import gov.cms.mpsm.rda.v1.fiss.FissClaim;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.jupiter.api.Test;

public class RandomFissClaimGeneratorTest {
  @Test
  public void randomClaim() throws InvalidProtocolBufferException {
    final Clock july1 = Clock.fixed(Instant.ofEpochMilli(1625172944844L), ZoneOffset.UTC);
    final RandomFissClaimGenerator generator = new RandomFissClaimGenerator(1, true, july1);
    final FissClaim claim = generator.randomClaim();
    final String json = JsonFormat.printer().print(claim);
    assertEquals(
        "{\n"
            + "  \"dcn\": \"9845557\",\n"
            + "  \"hicNo\": \"904843533707\",\n"
            + "  \"currStatusEnum\": \"CLAIM_STATUS_ROUTING\",\n"
            + "  \"currLoc1Enum\": \"PROCESSING_TYPE_OFFLINE\",\n"
            + "  \"currLoc2Enum\": \"CURRENT_LOCATION_2_POST_PAY_7563\",\n"
            + "  \"provStateCd\": \"c6\",\n"
            + "  \"provTypFacilCd\": \"c\",\n"
            + "  \"provEmerInd\": \"2\",\n"
            + "  \"provDeptId\": \"qbz\",\n"
            + "  \"totalChargeAmount\": \"6769.55\",\n"
            + "  \"recdDtCymd\": \"2021-07-01\",\n"
            + "  \"currTranDtCymd\": \"2021-01-31\",\n"
            + "  \"admDiagCode\": \"vmpf\",\n"
            + "  \"npiNumber\": \"6907693832\",\n"
            + "  \"mbi\": \"x9vxmpjb3b2\",\n"
            + "  \"fedTaxNb\": \"7514622715\",\n"
            + "  \"medaProvId\": \"5w0h948kjd5rz\",\n"
            + "  \"pracLocAddr1\": \"sb9b66k2v3fs2wf24p5mxp3k0bth5s2vg\",\n"
            + "  \"pracLocAddr2\": \"x1njn3q6ftzx2266s0g4rqqx9qp24pb3rhw165ttc3cdnq42s3tkjz1hg\",\n"
            + "  \"pracLocCity\": \"8hrc5p47khhhn0466frjsg26038pgrm3s4\",\n"
            + "  \"pracLocState\": \"rx\",\n"
            + "  \"pracLocZip\": \"117009\",\n"
            + "  \"fissDiagCodes\": [{\n"
            + "    \"diagCd2\": \"ckcn\",\n"
            + "    \"bitFlags\": \"nb\",\n"
            + "    \"diagPoaIndUnrecognized\": \"v\"\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"tcfrfz\",\n"
            + "    \"bitFlags\": \"sxf\",\n"
            + "    \"diagPoaIndUnrecognized\": \"f\"\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"rrthpmq\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_UNREPORTED\",\n"
            + "    \"bitFlags\": \"hk\"\n"
            + "  }],\n"
            + "  \"stmtCovFromCymd\": \"2021-04-08\",\n"
            + "  \"stmtCovToCymd\": \"2021-04-26\",\n"
            + "  \"lobCdEnum\": \"BILL_FACILITY_TYPE_INTERMEDIATE_CASE\",\n"
            + "  \"servTypCdUnrecognized\": \"v\",\n"
            + "  \"freqCdUnrecognized\": \"m\",\n"
            + "  \"billTypCd\": \"rb9\",\n"
            + "  \"fissPayers\": [{\n"
            + "    \"beneZPayer\": {\n"
            + "      \"payersIdUnrecognized\": \"f\",\n"
            + "      \"payersName\": \"kkh1bmsg1mvm\",\n"
            + "      \"relIndUnrecognized\": \"v\",\n"
            + "      \"assignIndEnum\": \"ASSIGNMENT_OF_BENEFITS_INDICATOR_BENEFITS_ASSIGNED\",\n"
            + "      \"providerNumber\": \"24p9p4tq8\",\n"
            + "      \"adjDcnIcn\": \"n6mkjqnxr52b\",\n"
            + "      \"priorPmt\": \"12907.86\",\n"
            + "      \"estAmtDue\": \"8078.36\",\n"
            + "      \"beneRelEnum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_76\",\n"
            + "      \"beneLastName\": \"kfhbwrg\",\n"
            + "      \"beneFirstName\": \"jjdrsgv\",\n"
            + "      \"beneMidInit\": \"g\",\n"
            + "      \"beneSsnHic\": \"v5g\",\n"
            + "      \"insuredGroupName\": \"tzss\",\n"
            + "      \"beneDob\": \"2021-06-05\",\n"
            + "      \"beneSexUnrecognized\": \"c\",\n"
            + "      \"treatAuthCd\": \"f\",\n"
            + "      \"insuredSexUnrecognized\": \"k\",\n"
            + "      \"insuredRelX12Enum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_71\"\n"
            + "    }\n"
            + "  }],\n"
            + "  \"fissAuditTrail\": [{\n"
            + "    \"badtStatusUnrecognized\": \"1\",\n"
            + "    \"badtLoc\": \"p\",\n"
            + "    \"badtOperId\": \"5\",\n"
            + "    \"badtReas\": \"g\",\n"
            + "    \"badtCurrDateCymd\": \"2021-06-13\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_BLANK\",\n"
            + "    \"badtLoc\": \"c\",\n"
            + "    \"badtOperId\": \"bh1xhtd\",\n"
            + "    \"badtReas\": \"p1\",\n"
            + "    \"badtCurrDateCymd\": \"2021-05-14\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_INACTIVE\",\n"
            + "    \"badtLoc\": \"1nwb\",\n"
            + "    \"badtOperId\": \"bj9\",\n"
            + "    \"badtReas\": \"w0g\",\n"
            + "    \"badtCurrDateCymd\": \"2021-01-22\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_DENIED\",\n"
            + "    \"badtLoc\": \"qvs\",\n"
            + "    \"badtOperId\": \"smg1639\",\n"
            + "    \"badtReas\": \"tf987\",\n"
            + "    \"badtCurrDateCymd\": \"2021-06-07\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_FORCE\",\n"
            + "    \"badtLoc\": \"jdfft\",\n"
            + "    \"badtOperId\": \"5h\",\n"
            + "    \"badtReas\": \"678b7\",\n"
            + "    \"badtCurrDateCymd\": \"2021-03-20\"\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"0\",\n"
            + "    \"badtLoc\": \"krpj\",\n"
            + "    \"badtOperId\": \"87q5gc\",\n"
            + "    \"badtReas\": \"w0\",\n"
            + "    \"badtCurrDateCymd\": \"2021-06-22\"\n"
            + "  }],\n"
            + "  \"rejectCd\": \"dtkrm\",\n"
            + "  \"fullPartDenInd\": \"3\",\n"
            + "  \"nonPayInd\": \"8\",\n"
            + "  \"xrefDcnNbr\": \"tsrx\",\n"
            + "  \"adjReqCdUnrecognized\": \"6\",\n"
            + "  \"adjReasCd\": \"0\",\n"
            + "  \"cancelXrefDcn\": \"xrsz5gm0xt8m1fhkgs713\",\n"
            + "  \"cancelDateCymd\": \"2021-05-06\",\n"
            + "  \"cancAdjCdEnum\": \"CANCEL_ADJUSTMENT_CODE_OTHER\",\n"
            + "  \"originalXrefDcn\": \"p5fq7s8bcsxfrcg\",\n"
            + "  \"paidDtCymd\": \"2021-01-09\",\n"
            + "  \"admDateCymd\": \"2021-04-29\",\n"
            + "  \"admSourceUnrecognized\": \"0\",\n"
            + "  \"primaryPayerCodeEnum\": \"PAYERS_CODE_BLACK_LUNG\",\n"
            + "  \"attendPhysId\": \"9fgh4d\",\n"
            + "  \"attendPhysLname\": \"tf7h188107gzznnx9\",\n"
            + "  \"attendPhysFname\": \"5vws5h\",\n"
            + "  \"attendPhysMint\": \"9\",\n"
            + "  \"attendPhysFlagUnrecognized\": \"c\",\n"
            + "  \"operatingPhysId\": \"wwgghm8qjf2ns1p4\",\n"
            + "  \"operPhysLname\": \"9hc5ft3rk49\",\n"
            + "  \"operPhysFname\": \"dhftsdx4kt02\",\n"
            + "  \"operPhysMint\": \"1\",\n"
            + "  \"operPhysFlagUnrecognized\": \"w\",\n"
            + "  \"othPhysId\": \"9k5b3\",\n"
            + "  \"othPhysLname\": \"zq84dp\",\n"
            + "  \"othPhysFname\": \"kvxb\",\n"
            + "  \"othPhysMint\": \"7\",\n"
            + "  \"othPhysFlagEnum\": \"PHYSICIAN_FLAG_NO\",\n"
            + "  \"xrefHicNbr\": \"4\",\n"
            + "  \"procNewHicIndUnrecognized\": \"7\",\n"
            + "  \"newHic\": \"j6k56gg1\",\n"
            + "  \"reposIndEnum\": \"REPOSITORY_INDICATOR_HIC_HAS_BEEN_MOVED\",\n"
            + "  \"reposHic\": \"7\",\n"
            + "  \"mbiSubmBeneIndUnrecognized\": \"z\",\n"
            + "  \"adjMbiIndUnrecognized\": \"n\",\n"
            + "  \"adjMbi\": \"0st6z50nj07\",\n"
            + "  \"medicalRecordNo\": \"j\"\n"
            + "}",
        json);
  }
}
