ALTER TABLE cms_vdm_view_mdcr_prd.v2_mdcr_clm
DROP COLUMN clm_blg_prvdr_last_name,
clm_rfrg_prvdr_last_name,
clm_prscrbng_prvdr_last_name,
clm_othr_prvdr_last_name,
clm_rndrg_prvdr_last_name,
clm_atndg_prvdr_last_name,
clm_oprtg_prvdr_last_name;
