CodeSystem: CLM_LTC_DSPNSNG_MTHD_CD
Title: "Submission clarification code"
Id: CLM-LTC-DSPNSNG-MTHD-CD
Description: "For beneficiaries living in long-term care (LTC) facilities, this variable indicates how many days' supply of the medication was dispensed by the long-term care pharmacy and provides some details about the dispensing event.

This variable is only populated when beneficiary lives in an LTC facility (i.e., when the CLM_PTNT_RSDNC_CD variable equals 03)"
* ^url = "https://bluebutton.cms.gov/fhir/CodeSystem/CLM-LTC-DSPNSNG-MTHD-CD"
* ^status = #active
* ^content = #complete

* #00 "(Unknown value – rarely populated)"
* #01 "No Override"
* #02 "Other Override"
* #03 "Vacation Supply. The pharmacist is indicating that the cardholder has requested a vacation supply of the medicine."
* #04 "Lost/Damaged Prescription. The pharmacist is indicating that the a replacement of medication that has been damaged or lost."
* #05 "Therapy change. Physician determined that a change in therapy was required – either the medication was used faster than expected, or a different dosage form is needed."
* #06 "Continuation Dose After Starter Dose. The previous medication was a starter dose and now additional medication is needed to continue treatment."
* #07 "Emergency supply of non-formulary drugs (or formulary drugs which typically require step therapy or prior authorization). Medication has been determined by the physician to be medically necessary."
* #08 "Process compound for approved ingredients"
* #09 "Encounters"
* #10 "Meets Plan Limitations. The pharmacy certifies that the transaction is in compliance with the program's policies and rules that are specific to the particular product being billed."
* #11 "Certification on File"
* #12 "DME Replacement Indicator"
* #13 "Payer-Recognized Emergency/Disaster Assistance Request"
* #14 "LTC leave of absence – short fill required for take-home use"
* #15 "Long Term Care Replacement Medication"
* #16 "LTC emergency box (e box) /automated dispensing machine"
* #17 "LTC emergency supply remainder (remainder of drug from the emergency supply)"
* #18 "LTC patient admit/readmission indicator. This status required new dispensing of medication."
* #19 "Split billing. The quantity dispensed is the remainder billed to a subsequent payer after Medicare Part A benefits expired (partial payment under Part A)."
* #20 ""340B. Purchased pursuant to rights available under Section 340B of the Public Health Act of 1992."
* #21 "LTC dispensing rule for <=14 day supply is not applicable due to CMS exclusion or the fact that the manufacturer’s packaging does not allow for special dispensing"
* #22 "LTC dispensing, 7-day supply"
* #23 "LTC dispensing, 4-day supply"
* #24 "LTC dispensing, 3-day supply"
* #25 "LTC dispensing, 2-day supply"
* #26 "LTC dispensing, 1-day supply"
* #27 "LTC dispensing, 4-day supply, then 3-day supply"
* #28 "LTC dispensing, 2-day supply, then 2-day supply, then 3-day supply"
* #29 "LTC dispensing, daily during the week then multiple days (3) for weekend"
* #30 "LTC dispensing, per shift (multiple medication passes)"
* #31 "LTC dispensing, per medication pass"
* #32 "LTC dispensing, PRN on demand"
* #33 "LTC dispensing, other <=7 day cycle"
* #34 "LTC dispensing, 14-day supply"
* #35 "LTC dispensing, other 8-14 day dispensing not listed above"
* #36 "LTC dispensing, outside short cycle, determined to be Part D after originally submitted to another payer"
* #42 "The prescriber ID submitted has been validated and is active (rarely populated)"
* #43 "For the prescriber ID submitted, the associated DEA number has been renewed or the renewal is in progress (rarely populated)"
* #44 "(Unknown value – rarely populated)"
* #45 "For the prescriber ID submitted, the associated DEA number is a valid hospital DEA number with suffix (rarely populated)"
* #46 "Prescriber has prescriptive authority for this drug DEA Schedule."
* #47 "Shortened Days Supply. Request plan benefit allowances be applied to the shortened days supply not otherwise defined in a distinct shortened days supply value."
* #48 "Dispensed Subsequent to a Shortened Days Supply Dispensing."
* #49 "Prescriber does not currently have an active Type 1 NPI."
* #50 "Prescriber's active Medicare Fee For Service enrollment status has been validated."
* #51 "Pharmacy's active Medicare Fee For Service enrollment status has been validated."
* #52 "Prescriber's state license with prescriptive authority has been validated."
* #53 "Prescriber NPI active and valid."
* #54 "CMS Other Authorized Prescriber (OAP)."
* #55 "Prescriber Enrollment in State Medicaid Program has been validated."
* #56 "Pharmacy Enrollment in State Medicaid Program has been validated."
* #57 "Discharge Medication"
* #58 "Nominal Price."
* #59 "Federal Supply Schedule"
* #60 "Long Term Care Same Drug Strength and Dosage Form with Multiple Dosing Directions"
* #61 "Synchronization Fill - Shortened Days Supply"
* #62 "Shortened Days Supply of Same Drug, Strength and Dosage Form with Multiple NDCs Dispensed"
* #63 "Mail Order Delay - Shortened Days Supply"
* #64 "Trial Fill - Shortened Days Supply"
* #65 "Individual Patient Emergency RX Fill Request"
* #66 "Patient indicated Workers' Compensation Medicare Set-Aside Arrangement (WCMSA) benefit does not apply to this claim."
* #99 "Other(Unknown)"
