CodeSystem: CLM_PRCSG_IND_CD
Title: "Processing Indicator Code"
Id: CLM-PRCSG-IND-CD
Description: "The code on a non-institutional claim indicating to whom payment was made or if the claim was denied."
* ^url = "https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PRCSG-IND-CD"
* ^status = #active
* ^content = #complete

* #A "Allowed"
* #B "Benefits exhausted"
* #C "Non-covered care"
* #D "Denied (from BMAD)"
* #G "MSP cost avoided â€” Secondary Claims Investigation"
* #H "MSP cost avoided â€” Self Reports"
* #I "Invalid data"
* #J "MSP cost avoided â€” 411.25"
* #K "MSP cost avoided â€” Insurer Voluntary Reporting"
* #L "CLIA"
* #M "Multiple submittal-duplicate line item"
* #N "Medically unnecessary"
* #O "Other"
* #P "Physician ownership denial"
* #Q "MSP cost avoided (contractor #88888) â€” voluntary agreement"
* #R "Reprocessed adjustments based on subsequent reprocessing of claim"
* #S "Secondary payer"
* #T "MSP cost avoided â€” IEQ contractor"
* #U "MSP cost avoided â€” HMO rate cell adjustment"
* #V "MSP cost avoided â€” litigation settlement"
* #X "MSP cost avoided â€” generic"
* #Y "MSP cost avoided â€” IRS/SSA data match project"
* #Z "Bundled test, no payment"
* #00 "MSP cost avoided â€” COB Contractor"
* #12 "MSP cost avoided â€” BC/BS Voluntary Agreements"
* #13 "MSP cost avoided â€” Office of Personnel Management"
* #14 "MSP cost avoided â€” Workman's Compensation (WC) Datamatch"
* #15 "MSP cost avoided â€” Workman's Compensation Insurer Voluntary Data Sharing Agreements (WC VDSA) (eff. 4/2006)"
* #16 "MSP cost avoided â€” Liability Insurer VDSA (eff.4/2006)"
* #17 "MSP cost avoided â€” No-Fault Insurer VDSA (eff.4/2006)"
* #18 "MSP cost avoided â€” Pharmacy Benefit Manager Data Sharing Agreement (eff.4/2006)"
* #21 "MSP cost avoided â€” MIR Group Health Plan (eff.1/2009)"
* #22 "MSP cost avoided â€” MIR non-Group Health Plan (eff.1/2009)"
* #25 "MSP cost avoided â€” Recovery Audit Contractor â€” California (eff.10/2005)"
* #26 "MSP cost avoided â€” Recovery Audit Contractor â€” Florida (eff.10/2005)"
