Logical: ExplanationOfBenefit-Pharmacy
Id: ExplanationOfBenefit-Pharmacy
* ^url = "https://bfd.cms.gov/fhir/StructureDefinition/ExplanationOfBenefit-Pharmacy"
* ^status = #draft
* ^type = "ExplanationOfBenefit-Pharmacy"
* . ^label = "Explanation of Benefit Pharmacy Resource for IDR. Ignore in DD Generation"
* lastUpdated 0..1 string "This field represents the last time that an ExplanationOfBenefit was updated."
* lastUpdated ^label = "Last Updated Time"
* BENE_SK 1..1 string "Beneficiary Source Key - On Claim"
* BENE_SK ^label = "Beneficiary Source Key - On Claim"
* CLM_TYPE_CD 1..1 integer "Claim Type Code"
* CLM_TYPE_CD ^label = "Claim Type Code"
  * ^definition = "A CODE IDENTIFYING THE SOURCE AND TYPE OF CLAIM SUBMITTED THROUGH THE MEDICARE OR MEDICAID PROGRAM.  FOR EXAMPLE:  60 = MEDICARE  NATIONAL CLAIMS HISTORY (NCH) INPATIENT CLAIM   8900 = MEDICAID FEE FOR SERVICE DENTAL     REFERENCE TABLE: CLM_TYPE_CD"
* CLM_UNIQ_ID 1..1 string "The claim unique ID is a unique ID for the claim within the source system."
* CLM_UNIQ_ID ^label = "Claim Unique ID"
  * ^definition = "AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED SURROGATE KEY USED TO IDENTIFY A CLAIM."
* CLM_CNTL_NUM 1..1 string "This field is an identification value assigned by a MAC. It provides a reference number for the control and monitoring of specific claims, and to differentiate between claims for the beneficiary."
* CLM_CNTL_NUM ^label = "Claim Control Number"
* CLM_ORIG_CNTL_NUM 0..1 string "This field contains the original claim control number for adjusted or corrected claims. It provides a reference to the prior claim that this claim is adjusting or correcting."
* CLM_ORIG_CNTL_NUM ^label = "Original Claim Control Number"
  * ^definition = "A NUMBER IDENTIFYING THE ORIGINAL CLAIM CONTROL NUMBER (CCN) ON AN ADJUSTED CLAIM."
* CLM_FROM_DT 1..1 string "Claim From Date"
* CLM_FROM_DT ^label = "Claim From Date"
  * ^definition = "A DATE IDENTIFYING THE FIRST DAY SERVICES ARE PROVIDED TO A BENEFICIARY."
* CLM_THRU_DT 1..1 string "Claim Thru Date"
* CLM_THRU_DT ^label = "Claim Thru Date"
  * ^definition = "A DATE IDENTIFYING THE LAST DAY SERVICES ARE PROVIDED TO A BENEFICIARY.  NOTE: FOR DRUG CLAIMS, THIS DATE IS WHEN THE PRESCRIPTION WAS FILLED."
* CLM_EFCTV_DT 1..1 string "The effective date of the claim"
* CLM_EFCTV_DT ^label = "Claim Effective Date"
  * ^definition = "A DATE CORRESPONDING TO THE NATIONAL CLAIM HISTORY (NCH) WEEKLY PROCESSING DATE AND USED IN FINAL ACTION PROCESSING TO IDENTIFY A VERSION OF A CLAIM. IT WILL ALWAYS BE A FRIDAY DATE."
* CLM_SRC_ID 1..1 string "Claim Source ID"
* CLM_SRC_ID ^label = "Claim Source ID"
  * ^definition = "AN IDENTIFIER INDICATING WHERE THE SOURCE OF THE CLAIM DATA IN THE INTEGRATED DATA REPOSITORY (IDR) ORIGINATED FROM.   VALID VALUES:  20000 = NATIONAL CLAIMS HISTORY (NCH)  21000 = FISCAL INTERMEDIARY SHARED SYSTEM (FISS)  22000 = MULTI-CARRIER SYSTEM (MCS)  23000 = VIABLE INFORMATION PROCESSING SYSTEMS (VIPS) MEDICARE SYSTEM (VMS)  24000 = ENCOUNTER DATA PROCESSING SYSTEM (EDPS)  25000 = ENCOUNTER MEDICAID DUALS 837 CLAIMS  AND DUALS MEDICAID DRUG CLAIMS (DMDC)  N/A = MEDICAID"
* META_SRC_SK 1..1 string "Meta Source SK"
* META_SRC_SK ^label = "Meta Source SK"
* PRVDR_SRVC_PRVDR_NPI_NUM 0..1 string "The NPI number of the service provider."
* PRVDR_SRVC_PRVDR_NPI_NUM ^label = "Service Provider NPI Number"
  * ^definition = "A NUMBER IDENTIFYING THE NATIONAL PROVIDER IDENTIFIER (NPI) OF A SERVICE PROVIDER AS SOURCED FROM THE NPI CROSSWALK REFERENCE INFORMATION PROVIDED BY THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES)."
* CLM_PD_DT 0..1 string "The date on which the plan originally paid the pharmacy for the prescription drug."
* CLM_PD_DT ^label = "Payment Date"
  * ^definition = "A DATE INDICATING WHEN A CLAIM WAS PAID."
* PRVDR_PRSCRBNG_PRVDR_NPI_NUM 0..1 string "The NPI number of the prescribing provider."
* PRVDR_PRSCRBNG_PRVDR_NPI_NUM ^label = "Prescribing Provider NPI Number"
  * ^definition = "A NUMBER IDENTIFYING THE NATIONAL PROVIDER IDENTIFIER (NPI) OF A PRESCRIBING PROVIDER AS SOURCED FROM THE NPI CROSSWALK REFERENCE INFORMATION PROVIDED BY THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES)."
* PRVDR_LAST_NAME 0..1 string "Last name of the prescribing provider"
* PRVDR_LAST_NAME ^label = "Prescribing Provider Last Name"
  * ^definition = "A LAST NAME OF A PROVIDER."
* CLM_LINE_RX_ORGN_CD 0..1 string "This variable indicates whether the prescription was transmitted as an electronic prescription, by phone, by fax, or as a written paper copy."
* CLM_LINE_RX_ORGN_CD ^label = "Prescription Origin Code"
* CLM_BRND_GNRC_CD 0..1 string "Plan reported value indicating whether the plan adjudicated the claim as a brand or generic drug."
* CLM_BRND_GNRC_CD ^label = "Brand Generic Code"
* CLM_PTNT_RSDNC_CD 0..1 string "This variable indicates where the beneficiary lived when the prescription was filled, as reported on the PDE record."
* CLM_PTNT_RSDNC_CD ^label = "Patient Residence Code"
* CLM_LTC_DSPNSNG_MTHD_CD 0..1 string "For beneficiaries living in long-term care (LTC) facilities, this variable indicates how many days' supply of the medication was dispensed by the long-term care pharmacy."
* CLM_LTC_DSPNSNG_MTHD_CD ^label = "Submission Clarification Code"
* CLM_CMPND_CD 0..1 string "Compound Code"
* CLM_CMPND_CD ^label = "Compound Code"
* CLM_LINE_DAYS_SUPLY_QTY 0..1 string "This field indicates the number of days' supply of medication dispensed by the pharmacy and consists of the amount the pharmacy enters for the prescription."
* CLM_LINE_DAYS_SUPLY_QTY ^label = "Days Supply"
* CLM_LINE_RX_FILL_NUM 0..1 string "This field indicates the number fill of the current dispensed supply."
* CLM_LINE_RX_FILL_NUM ^label = "Fill Number"
* CLM_DAW_PROD_SLCTN_CD 0..1 string "This field indicates the prescriber's instruction regarding substitution of generic equivalents or order to dispense the specific prescribed medication."
* CLM_DAW_PROD_SLCTN_CD ^label = "Dispense as Written Product Selection Code"
* CLM_DRUG_CVRG_STUS_CD 0..1 string "This field indicates whether or not the drug is covered by Medicare Part D."
* CLM_DRUG_CVRG_STUS_CD ^label = "Drug Coverage Status Code"
* CLM_CTSTRPHC_CVRG_IND_CD 0..1 string "This variable indicates whether the PDE occurred within the catastrophic benefit phase of the Medicare Part D benefit."
* CLM_CTSTRPHC_CVRG_IND_CD ^label = "Catastrophic Coverage Code"
* CLM_LINE_NDC_CD 0..1 string "This field identifies the dispensed drug product using a National Drug Code (NDC)."
* CLM_LINE_NDC_CD ^label = "National Drug Code"
* CLM_LINE_NDC_QTY 0..1 string "This field indicates the number of units, grams, milliliters, or other quantity dispensed in the current drug event."
* CLM_LINE_NDC_QTY ^label = "Quantity Dispensed"
* CLM_LINE_NDC_QTY_QLFYR_CD 0..1 string "The qualifier code for the quantity dispensed."
* CLM_LINE_NDC_QTY_QLFYR_CD ^label = "Quantity Qualifier Code"
* CLM_LINE_NUM 0..1 string "The line number for this item."
* CLM_LINE_NUM ^label = "Line Number"
* CNTRCT_PBP_NAME 0..1 string "This field contains the name of the plan benefit package (PBP) for the beneficiary's Part D plan of record for the year."
* CNTRCT_PBP_NAME ^label = "Contract PBP Name"
  * ^definition = "TEXT LABEL DESCRIBING THE PBP, USUALLY THE PRODUCT NAME."
* supportingInfoComponents 0..* SupportingInfoComponent "A list of supporting info"
* supportingInfoComponents ^label = "Supporting Info Components"
* supportingInfoComponents ^type.targetProfile = "https://bfd.cms.gov/fhir/StructureDefinition/SupportingInfoComponent"
* lineItemComponents 0..* LineItemComponent "A list of line items"
* lineItemComponents ^label = "Line Item Components"
* lineItemComponents ^type.targetProfile = "https://bfd.cms.gov/fhir/StructureDefinition/LineItemComponent"
* CLM_BENE_PMT_AMT 0..1 string "The amount that was paid by the beneficiary."
* CLM_BENE_PMT_AMT ^label = "Beneficiary Payment Amount"
  * ^definition = "AN AMOUNT PAID BY A BENEFICIARY FOR SERVICES RENDERED ON A CLAIM."
* CLM_OTHR_TP_PD_AMT 0..1 string "The amount that was paid by other third parties."
* CLM_OTHR_TP_PD_AMT ^label = "Other Third Party Paid Amount"
  * ^definition = "AN AMOUNT IDENTIFYING HOW MUCH WAS PAID BY A THIRD PARTY PAYER."
* providerList 0..* Provider "Provider List"
* providerList ^label = "Provider List"
* providerList ^type.targetProfile = "http://hl7.org/fhir/StructureDefinition/Provider"
* TOT_RX_CST_AMT 0..1 string "This variable is the total cost of the prescription drug event and is taken directly from the original PDE. It is the sum of the following components: the ingredient cost (INGRDNT_CST_PD_AMT), the dispensing fee (DSPNSNG_FEE_PD_AMT), the sales tax, if any (TOT_AMT_ATTR_SLS_TAX_AMT), and the vaccine administration fee, if any (VCCN_ADMIN_FEE_AMT, included starting in 2010)."
* TOT_RX_CST_AMT ^label = "Total drug cost (Part D)"
* PRVDR_SRVC_ID_QLFYR_CD 0..1 string "Indicates the type of number used to identify the pharmacy providing the services."
* PRVDR_SRVC_ID_QLFYR_CD ^label = "Provider Service Identifier Qualifier Code"
  * ^definition = "A CODE INDICATING THE TYPE OF NUMBER USED TO IDENTIFY A SERVICE PROVIDER ON A CLAIM.  FOR EXAMPLE:  01 = NPI  07 = NCPDP NUMBER  08 = STATE LICENSE NUMBER    REFERENCE TABLE: CLM_PRVDR_ID_QLFYR_CD"
* CLM_SRVC_PRVDR_GNRC_ID_NUM 0..1 string "Indicates the ID number submitted for the service provider on a claim. The type of the identifier is noted by PRVDR_SRVC_ID_QLFYR_CD."
* CLM_SRVC_PRVDR_GNRC_ID_NUM ^label = "Service Provider Generic ID Number"
  * ^definition = "A NUMBER USED TO IDENTIFY A SERVICE PROVIDER."
* CLM_PRSBNG_PRVDR_GNRC_ID_NUM 0..1 string "Indicates the ID number submitted for the prescribing provider on a claim. The type of the identifier is noted by PRVDR_PRSBNG_ID_QLFYR_CD."
* CLM_PRSBNG_PRVDR_GNRC_ID_NUM ^label = "Prescribing Provider Generic ID Number"
  * ^definition = "A NUMBER IDENTIFYING A GENERIC IDENTIFIER OF A PRESCRIBING PROVIDER SUBMITTED ON A DRUG CLAIM."
* PRVDR_PRSBNG_ID_QLFYR_CD 0..1 string "Indicates the type of number used to identify the prescriber."
* PRVDR_PRSBNG_ID_QLFYR_CD ^label = "Provider Prescribing Identifier Qualifier Code"
  * ^definition = "A CODE INDICATING THE TYPE OF NUMBER USED TO IDENTIFY A PRESCRIBING PROVIDER ON A CLAIM.  FOR EXAMPLE:  01 = NPI  07 = NCPDP NUMBER  08 = STATE LICENSE NUMBER    REFERENCE TABLE: CLM_PRVDR_ID_QLFYR_CD"
