Logical: Bene-MBI
Id: Bene-MBI
* ^url = "http://hl7.org/fhir/StructureDefinition/Bene-MBI"
* ^status = #draft
* ^type = "Bene-MBI"
* . ^label = "IDR MBI Base Resource. Ignore in DD Generation"
* BENE_MBI_ID 1..1 string "Medicare Beneficiary Identifier" "AN IDENTIFIER THAT UNIQUELY IDENTIFIES A BENEFICIARY AND REPLACES THE HEALTH INSURANCE CLAIM NUMBER (HICN) ON MEDICARE CARDS. THE FORMAT OF THE MEDICARE BENEFICIARY IDENTIFIER (MBI) IS 11-POSITIONS IN LENGTH AND CONTAINS THE FOLLOWING VALUES:  POSITION 1 Ö NUMERIC VALUES: 1 - 9  POSITION 2 Ö ALPHABETIC VALUES: A - Z (MINUS S, L, O, I, B, Z)  POSITION 3 Ö ALPHANUMERIC VALUES: 0 - 9 AND A - Z (MINUS S, L, O, I, B, Z)  POSITION 4 Ö NUMERIC VALUES: 0 - 9  POSITION 5 Ö ALPHABETIC VALUES: A - Z (MINUS S, L, O, I, B, Z)  POSITION 6 Ö ALPHANUMERIC VALUES: 0 - 9 AND A - Z (MINUS S, L, O, I, B, Z)  POSITION 7 Ö NUMERIC VALUES: 0 - 9  POSITION 8 Ö ALPHABETIC VALUES: A - Z (MINUS S, L, O, I, B, Z)  POSITION 9 Ö ALPHABETIC VALUES: A - Z (MINUS S, L, O, I, B, Z)  POSITION 10 Ö NUMERIC VALUES: 0 - 9  POSITION 11 Ö NUMERIC VALUES: 0 - 9"
* BENE_MBI_EFCTV_DT 1..1 dateTime "MBI Effective Date" "THE EFFECTIVE DATE WHEN AN MBI IS ASSIGNED TO A BENEFICIARY."
* BENE_MBI_OBSLT_DT 0..1 dateTime "MBI Obsolete Date" "THE END DATE WHEN AN MBI PERIOD IS CLOSED DUE TO BEING COMPROMISED OR INVOLVED IN A MERGE CROSS REFERENCE ACTION. (REPLACED BY A NEW MBI)."
