Logical: ExplanationOfBenefit-Pharmacy
Id: ExplanationOfBenefit-Pharmacy
* ^url = "https://bfd.cms.gov/fhir/StructureDefinition/ExplanationOfBenefit-Pharmacy"
* ^status = #draft
* ^type = "ExplanationOfBenefit-Pharmacy"
* . ^label = "Explanation of Benefit Pharmacy Resource for IDR. Ignore in DD Generation"
* lastUpdated 0..1 string "Last Updated Time" "This field represents the last time that an ExplanationOfBenefit was updated."
* BENE_SK 1..1 string "Beneficiary Source Key - On Claim" "Beneficiary Source Key - On Claim"
* CLM_TYPE_CD 1..1 integer "Claim Type Code" "A code identifying the source and type of claim submitted through the Medicare or Medicaid program. For example: 60 = Medicare National Claims History (NCH) inpatient claim. 8900 = Medicaid fee for service dental. Reference table: CLM_TYPE_CD"
* CLM_UNIQ_ID 1..1 string "Claim Unique ID" "An Integrated Data Repository (IDR) assigned surrogate key used to identify a claim."
* CLM_CNTL_NUM 1..1 string "Claim Control Number" "This field is an identification value assigned by a MAC. It provides a reference number for the control and monitoring of specific claims, and to differentiate between claims for the beneficiary."
* CLM_ORIG_CNTL_NUM 0..1 string "Original Claim Control Number" "This field contains the original claim control number for adjusted or corrected claims. It provides a reference to the prior claim that this claim is adjusting or correcting."
* CLM_FROM_DT 1..1 string "Claim From Date" "A date identifying the first day services are provided to a beneficiary."
* CLM_THRU_DT 1..1 string "Claim Thru Date" "A date identifying the last day services are provided to a beneficiary. Note: For drug claims, this date is when the prescription was filled."
* CLM_EFCTV_DT 1..1 string "Claim Effective Date" "A date corresponding to the National Claim History (NCH) weekly processing date and used in final action processing to identify a version of a claim. It will always be a Friday date."
* CLM_SRC_ID 1..1 string "Claim Source ID" "An identifier indicating where the source of the claim data in the Integrated Data Repository (IDR) originated from. Valid values: 20000 = National Claims History (NCH). 21000 = Fiscal Intermediary Shared System (FISS). 22000 = Multi-Carrier System (MCS). 23000 = Viable Information Processing Systems (VIPS) Medicare System (VMS). 24000 = Encounter Data Processing System (EDPS). 25000 = Encounter Medicaid Duals 837 claims and Duals Medicaid Drug Claims (DMDC). N/A = Medicaid"
* META_SRC_SK 1..1 string "Source ID" "Identifies the source system of the ExplanationOfBenefit data."
* PRVDR_SRVC_PRVDR_NPI_NUM 0..1 string "Service Provider NPI Number" "A number identifying the National Provider Identifier (NPI) of a service provider as sourced from the NPI crosswalk reference information provided by the National Plan and Provider Enumeration System (NPPES)."
* CLM_PD_DT 0..1 string "Payment Date" "A date indicating when a claim was paid."
* PRVDR_PRSCRBNG_PRVDR_NPI_NUM 0..1 string "Prescribing Provider NPI Number" "A number identifying the National Provider Identifier (NPI) of a prescribing provider as sourced from the NPI crosswalk reference information provided by the National Plan and Provider Enumeration System (NPPES)."
* PRVDR_LAST_NAME 0..1 string "Prescribing Provider Last Name" "Last name of the prescribing provider"
* CLM_LINE_RX_ORGN_CD 0..1 string "Prescription Origin Code" "This variable indicates whether the prescription was transmitted as an electronic prescription, by phone, by fax, or as a written paper copy."
* CLM_BRND_GNRC_CD 0..1 string "Brand Generic Code" "Plan reported value indicating whether the plan adjudicated the claim as a brand or generic drug."
* CLM_PTNT_RSDNC_CD 0..1 string "Patient Residence Code" "This variable indicates where the beneficiary lived when the prescription was filled, as reported on the PDE record."
* CLM_LTC_DSPNSNG_MTHD_CD 0..1 string "Submission Clarification Code" "For beneficiaries living in long-term care (LTC) facilities, this variable indicates how many days' supply of the medication was dispensed by the long-term care pharmacy."
* CLM_CMPND_CD 0..1 string "Compound Code" "Compound Code"
* CLM_LINE_DAYS_SUPLY_QTY 0..1 string "Days Supply" "This field indicates the number of days' supply of medication dispensed by the pharmacy and consists of the amount the pharmacy enters for the prescription."
* CLM_LINE_RX_FILL_NUM 0..1 string "Fill Number" "This field indicates the number fill of the current dispensed supply."
* CLM_DAW_PROD_SLCTN_CD 0..1 string "Dispense as Written Product Selection Code" "This field indicates the prescriber's instruction regarding substitution of generic equivalents or order to dispense the specific prescribed medication."
* CLM_DRUG_CVRG_STUS_CD 0..1 string "Drug Coverage Status Code" "This field indicates whether or not the drug is covered by Medicare Part D."
* CLM_CTSTRPHC_CVRG_IND_CD 0..1 string "Catastrophic Coverage Code" "This variable indicates whether the PDE occurred within the catastrophic benefit phase of the Medicare Part D benefit."
* CLM_LINE_NDC_CD 0..1 string "National Drug Code" "This field identifies the dispensed drug product using a National Drug Code (NDC)."
* CLM_LINE_NDC_QTY 0..1 string "Quantity Dispensed" "This field indicates the number of units, grams, milliliters, or other quantity dispensed in the current drug event."
* CLM_LINE_NDC_QTY_QLFYR_CD 0..1 string "Quantity Qualifier Code" "The qualifier code for the quantity dispensed."
* CLM_LINE_NUM 0..1 string "Line Number" "The line number for this item."
* CNTRCT_PBP_NAME 0..1 string "Contract PBP Name" "This field contains the name of the plan benefit package (PBP) for the beneficiary's Part D plan of record for the year."
* supportingInfoComponents 0..* SupportingInfoComponent "Supporting Info Components" "A list of supporting info"
  * ^type.targetProfile = "https://bfd.cms.gov/fhir/StructureDefinition/SupportingInfoComponent"
* lineItemComponents 0..* LineItemComponent "Line Item Components" "A list of line items"
  * ^type.targetProfile = "https://bfd.cms.gov/fhir/StructureDefinition/LineItemComponent"
* CLM_BENE_PMT_AMT 0..1 string "Beneficiary Payment Amount" "An amount paid by a beneficiary for services rendered on a claim."
* CLM_OTHR_TP_PD_AMT 0..1 string "Other Third Party Paid Amount" "An amount identifying how much was paid by a third party payer."
* providerList 0..* Provider "Provider List"
  * ^type.targetProfile = "http://hl7.org/fhir/StructureDefinition/Provider"
* TOT_RX_CST_AMT 0..1 string "Total drug cost (Part D)" "This variable is the total cost of the prescription drug event and is taken directly from the original PDE. It is the sum of the following components: the ingredient cost (INGRDNT_CST_PD_AMT), the dispensing fee (DSPNSNG_FEE_PD_AMT), the sales tax, if any (TOT_AMT_ATTR_SLS_TAX_AMT), and the vaccine administration fee, if any (VCCN_ADMIN_FEE_AMT, included starting in 2010)."
* PRVDR_SRVC_ID_QLFYR_CD 0..1 string "Provider Service Identifier Qualifier Code" "A code indicating the type of number used to identify a service provider on a claim. For example: 01 = NPI. 07 = NCPDP number. 08 = State license number. Reference table: CLM_PRVDR_ID_QLFYR_CD"
* CLM_SRVC_PRVDR_GNRC_ID_NUM 0..1 string "Service Provider Generic ID Number" "A number used to identify a service provider."
* CLM_PRSBNG_PRVDR_GNRC_ID_NUM 0..1 string "Prescribing Provider Generic ID Number" "A number identifying a generic identifier of a prescribing provider submitted on a drug claim."
* CLM_CMS_PROC_DT 0..1 date "Claim Process Date" "Date a claim or prescription drug event was processed by a CMS front end system, such as the DDPS operational data store."
* CLM_SBMT_FRMT_CD 0..1 string "Claim Submission Format Code" "A code identifying the format of the claim as submitted."
* CLM_SBMTR_CNTRCT_NUM 0..1 string "Submitter Contract Number" "The contract number of the plan that submitted the claim."
* CLM_SBMTR_CNTRCT_PBP_NUM 0..1 string "Submitter PBP Number" "The Plan Benefit Package (PBP) number of the plan that submitted the claim."
* CLM_ADJSTMT_TYPE_CD 0..1 string "Claim Adjustment Type Code" "A code identifying the type of adjustment record represented on a claim or encounter. Reference table: CLM_ADJSTMT_TYPE_CD"
* CLM_DISP_CD 0..1 string "Claim Disposition Code" "A code indicating the disposition or outcome of a processed claim record. Reference table: CLM_DISP_CD"
* CLM_IDR_LD_DT 1..1 date "Claim IDR Load Date" "A date identifying when Part A and Part B data are loaded into the Integrated Data Repository (IDR)."
* PRVDR_PRSBNG_ID_QLFYR_CD 0..1 string "Provider Prescribing Identifier Qualifier Code" "A code indicating the type of number used to identify a prescribing provider on a claim. For example: 01 = NPI. 07 = NCPDP number. 08 = State license number. Reference table: CLM_PRVDR_ID_QLFYR_CD"
* profileType 0..1 string "Profile Type" "Identifies which profile this resource conforms to."
