*
!pyproject.toml
!uv.lock
!apps/bfd-pipeline-idr/pyproject.toml
!apps/bfd-pipeline-idr/.python-version
!apps/bfd-pipeline-idr/src/idr_pipeline/model/*.py
!apps/bfd-pipeline-idr/src/idr_pipeline/matching/*.py
!apps/bfd-pipeline-idr/src/idr_pipeline/*.py
