[project]
name = "idr-pipeline"
version = "0.1.0"
description = "ETL Pipeline to load data from the IDR into BFD's database"
requires-python = ">=3.14.3"
dependencies = [
  "cryptography>=50.0.0",
  "psycopg[binary,pool]>=3.3.3",
  "snowflake-connector-python>=4.7.2",
  "snowflake-snowpark-python>=1.54.0",
  "python-dateutil>=2.9.0",
  "pydantic>=2.13.3",
  "usaddress>=0.5.16",
  "unidecode>=1.4.0",
  "click>=8.4.2",
  "anyio",
  "loguru",
  "tblib>=3.2.2",
]


[project.scripts]
idr-pipeline = "idr_pipeline:main"


[tool.uv]
exclude-newer = "7 days"

[tool.uv.build-backend]
module-name = "idr_pipeline"

[build-system]
requires = ["uv_build<=0.12"]
build-backend = "uv_build"


# [[tool.mypy.overrides]]
# module = ["testcontainers.*"]
# follow_untyped_imports = true
