name: 'CI - Java'
on:
  push: #FIXME: Remove
  pull_request:
  merge_group:

env:
  # workflow file matchers - workflow jobs will only run if matching files are found
  # please see https://github.com/CMSgov/beneficiary-fhir-data/pull/773 for why we
  # are using this workflow logic
  # NOTE: The expression below can be extended to multi-line
  # using a '\' as a continuation character.
  # https://stackoverflow.com/questions/6268391/is-there-a-way-to-represent-a-long-string-that-doesnt-have-any-whitespace-on-mul
  workflow_files_re: "^apps/(?!bfd-pipeline/bfd-pipeline-idr|bfd-model/bfd-model-idr|utils).+$|^.github/workflows/ci-java.yml$"
  SONAR_PROJECT_KEY: 'bfd-parent'
  SONAR_HOST_URL: 'https://sonarqube.cloud.cms.gov'
permissions:
  id-token: write # This is required for requesting the AWS IAM OIDC JWT
  contents: write # This is required for actions/checkout

jobs:
  workflow:
    name: Checking workflow
    runs-on: ubuntu-24.04
    outputs:
      files: ${{ steps.workflow_files.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: workflow_files
        name: Set output
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$(git diff --name-only --diff-filter=ACMRTD HEAD^ HEAD | grep -P '${{ env.workflow_files_re }}')" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  mvn-fmt-maven-plugin:
    runs-on: ubuntu-24.04
    needs: workflow
    if: needs.workflow.outputs.files
    steps:
      - uses: actions/checkout@v4
      - name: 'Setup JDK'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: 'Run maven ${{ matrix.mvn_commmand }}'
        run: mvn com.spotify.fmt:fmt-maven-plugin:check
        working-directory: ./apps

  mvn-verify:
    runs-on: ubuntu-24.04
    needs: workflow
    if: needs.workflow.outputs.files
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4
      - name: 'Setup JDK'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: 'Run Maven Build'
        run: |
          mvn install \
          --threads 1C \
          --no-transfer-progress \
          -Dmaven.javadoc.skip=true \
          -Dcheckstyle.skip \
          -Dmaven.build.cache.enabled=true \
          -Dmaven.jacoco.skip=false
        working-directory: ./apps

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-reports
          path: |
            **/target/coverage-reports/jacoco-[iu]t/jacoco.xml
            **/pom.xml

  Upload-SonarQube-Artifacts:
    needs: mvn-verify
    runs-on:
      - codebuild-bfd-mgmt-ci-small-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Download Reports
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-reports

      - name: 'Setup JDK'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GHA_AWS_IAM_ROLE_ARN }}
          role-session-name: ci-java-upload-sonarqube-artifacts
          aws-region: us-east-1 #FIXME

      - name: Mask sensitive AWS data
        run: |
          caller_id="$(aws sts get-caller-identity)"
          account_num="$(jq -r '.Account' <<<$caller_id)"
          role_arn="$(jq -r '.Arn' <<<$caller_id)"
          user_id="$(jq -r '.UserId' <<<$caller_id)"

          echo "::add-mask::$account_num"
          echo "::add-mask::$role_arn"
          echo "::add-mask::$user_id"

      - name: Fetch SonarQube Access Key
        run: |
          SONAR_TOKEN="$(aws ssm get-parameter \
          --name '/bfd/mgmt/common/sensitive/service_accounts/sonar/service_account_access_key' \
          --with-decryption --query Parameter.Value --output text)"
          echo "::add-mask::$SONAR_TOKEN"
          echo $SONAR_TOKEN >> $GITHUB_ENV

      - name: Upload SonarQube Coverage Reports
        # This will expand into ./apps
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.host.url="$SONAR_HOST_URL" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dmaven.build.cache.enabled=false \
            -DskipITs \
            -DskipTests \
            -Dsonar.exclusions='*.java' \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/coverage-reports/jacoco-it/jacoco.xml,target/coverage-reports/jacoco-ut/jacoco.xml
        working-directory: ./apps

# TODO: Conformance testing is currently missing from mvn-verify. BFD-3245 will re-examine conformance regression testing in BFD.
