name: CI - Synthetic Pipeline

on:
  pull_request:
    paths:
      - "apps/bfd-model-idr/*"
      - "apps/bfd-pipeline/bfd-pipeline-idr/*"
      - ".github/workflows/ci-pipeline-synthetic.yml"
  merge_group:

jobs:
  run-synthetic:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        id: code-checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.10"
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
      # Maven is needed to run the migrator
      - name: "Setup JDK"
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "corretto"
      - name: Install dependencies
        run: npm install -g fsh-sushi
      - name: Build sushi
        run: |
          cd ${{ github.workspace }}/apps/bfd-model-idr
          sushi build ./sushi
      - name: Ensure synthetic data pipeline runs
        run: |
          cd ${{ github.workspace }}/apps/bfd-model-idr
          uv run patient_generator.py --claims --patients 100

          # TODO: Remove the below in BFD-4585
          # This constructs the IDR_TABLES environment variable for the IDR Pipeline such that only
          # existing tables post BFD-4502 are loaded into as the models for the old tables have not
          # yet been removed.
          idr_tables=(
            "idr.beneficiary"
            "idr.beneficiary_dual_eligibility"
            "idr.beneficiary_entitlement"
            "idr.beneficiary_entitlement_reason"
            "idr.beneficiary_low_income_subsidy"
            "idr.beneficiary_ma_part_d_enrollment"
            "idr.beneficiary_ma_part_d_enrollment_rx"
            "idr.beneficiary_mbi_id"
            "idr.beneficiary_overshare_mbi"
            "idr.beneficiary_status"
            "idr.beneficiary_third_party"
            "idr.claim_date_signature"
            "idr.claim_institutional_nch"
            "idr.claim_institutional_ss"
            "idr.claim_item_institutional_nch"
            "idr.claim_item_institutional_ss"
            "idr.claim_item_professional_nch"
            "idr.claim_item_professional_ss"
            "idr.claim_professional_nch"
            "idr.claim_professional_ss"
            "idr.claim_rx"
            "idr.contract_pbp_contact"
            "idr.contract_pbp_number"
            "idr.load_progress"
            "idr.provider_history"
          )

          export IDR_TABLES="$(echo "${idr_tables[@]}" | tr ' ' ',')"
          # TODO: Remove above in BFD-4585

          cd ../bfd-pipeline-idr
          ./run-db.sh
      # TODO: This takes too long after BFD-4502 (~1 hour); re-enable when this is fast enough
      # - name: Ensure synthetic data pipeline runs with existing synthetic data
      #   run: |
      #     cd ${{ github.workspace }}/apps/bfd-model-idr
      #     uv run patient_generator.py --claims ./synthetic-data
      #     # Split claims output into batches of 5000 CLMs to avoid timeouts with new claims schema
      #     uv run load_splitter.py -c 5000
      #     cd ../bfd-pipeline-idr
      #     # Load from batched_out instead of out due to splitting load
      #     ./run-db.sh ../bfd-model-idr/batched_out
