name: CI - Synthetic Pipeline

on:
  pull_request:
    paths:
      - "apps/bfd-model-idr/**"
      - "apps/bfd-pipeline-idr/**"
      - ".github/workflows/ci-pipeline-synthetic.yml"
  merge_group:

jobs:
  run-synthetic:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        id: code-checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.11.2"
      - name: Install node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"
      # Maven is needed to run the migrator
      - name: "Setup JDK"
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: "25"
          distribution: "corretto"
      - name: Sync UV in bfd-model-idr
        run: uv sync
        working-directory: apps/bfd-model-idr
      - name: Generate v3 Data Dictionary
        run: uv run gen_dd.py
        working-directory: apps/bfd-model-idr
      - name: Ensure synthetic data pipeline runs
        run: |
          cd ${{ github.workspace }}/apps/bfd-model-idr
          uv run patient_generator.py --claims --patients 100
          cd ../bfd-pipeline-idr
          ./run-db.sh
      - name: Ensure synthetic data pipeline runs with existing synthetic data
        run: |
          cd ${{ github.workspace }}/apps/bfd-model-idr
          uv run patient_generator.py --claims ./synthetic-data
          # Split claims output into 1000 CLMs batches
          uv run load_splitter.py -c 1000
          cd ../bfd-pipeline-idr
          # Load from batched_out/0 to load _just_ the first batch to validate that the structure
          # of data is OK and the data was regenerated properly without taking a significant amount
          # of time to load the full dataset
          ./run-db.sh ../bfd-model-idr/batched_out/0
