name: CI - Prek (Pre-commit) Checks
on: [pull_request]

jobs:
  prek:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: corretto
      - name: Install uv
        uses: astral-sh/setup-uv@v8
      - name: Run Prek pre-commit hooks
        uses: j178/prek-action@v1
        with:
          extra-args: --hook-stage pre-commit --from-ref origin/${{github.base_ref}} --to-ref HEAD
      - name: Run Prek pre-push hooks
        uses: j178/prek-action@v1
        with:
          extra-args: --hook-stage pre-push --from-ref origin/${{github.base_ref}} --to-ref HEAD
