name: CI - Prek (Pre-commit) Checks
on: [pull_request]

jobs:
  prek:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: j178/prek-action@v1
        with:
          extra-args: --hook-stage pre-commit --from-ref ${{github.base_ref}} --to-ref HEAD
      - uses: j178/prek-action@v1
        with:
          extra-args: --hook-stage pre-push --from-ref ${{github.base_ref}} --to-ref HEAD
