name: CI - Pre-commit Checks
on: [push, pull_request]

jobs:
  prek:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: j178/prek-action@v1
        with:
          extra-args: --hook-stage pre-commit # this is default hook-stage, but we want to override the default extra-args of --all-files
      - uses: j178/prek-action@v1
        with:
          extra-args: --hook-stage pre-push
