name: CI - Synthetic Pipeline

on:
  pull_request:
    paths:
      - "apps/bfd-model-idr/**"
      - "apps/bfd-pipeline-idr/**"
      - ".github/workflows/ci-pipeline-synthetic.yml"
  merge_group:

jobs:
  run-synthetic:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        id: code-checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          version: "0.11.2"
      - name: Install node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"
      # Maven is needed to run the migrator
      - name: "Setup JDK"
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version: "25"
          distribution: "corretto"
      - uses: taiki-e/install-action@9983c65e42da123ff25d1f78505eb6de315aa172 # v2.87.20
        with:
          tool: just
      - name: Generate v3 Data Dictionary
        run: just generate-data-dictionary
      - name: Ensure synthetic data pipeline runs
        run: |
          just patient-generator --patients 100
          just claims-generator ./apps/bfd-model-idr/out
          just pipeline --env local --seed-from ../bfd-model-idr/out
