name: "Deploy Platform Services"
on:
  workflow_dispatch:
    inputs:
      account-type:
        description: The BFD account type to deploy services to
        default: non-prod
        required: true
        type: choice
        options:
          - non-prod
          - prod
      services:
        description: Comma-separated list of services to deploy
        default: >-
          bootstrap,
          config,
          alerting,
          backup,
          ecr,
          network
        required: true
      per-service-vars-json:
        description: >-
          Tofu plan variables per-service in JSON; see Workflow for format
        required: false
      aws-region:
        description: >-
          Override the AWS Region
        default: us-east-1
        type: choice
        options:
          - us-east-1
          - us-west-2
        required: true
      skip-applies:
        description: >-
          If true, skips the apply step for each Terraservice such that only the plans are generated
        default: false
        required: false
        type: boolean
      git-ref:
        description: >-
          The Git reference (branch, tag, commit, etc.) to use for deploy.
          Defaults to the selected branch/tag
        default: ""
        required: false
  workflow_call:
    inputs:
      account-type:
        type: string
        description: The BFD account type to deploy services to
        required: true
      services:
        type: string
        description: Comma-separated list of services to deploy
        default: >-
          bootstrap,
          config,
          alerting,
          backup,
          ecr,
          network
        required: false
      per-service-vars-json:
        type: string
        description: >-
          Tofu plan variables per-service in JSON; see Workflow for format
        required: false
      aws-region:
        type: string
        description: >-
          Override the AWS Region
        default: us-east-1
        required: false
      skip-applies:
        type: boolean
        description: >-
          If true, skips the apply step for each Terraservice such that only the plans are generated
        default: false
        required: false
      git-ref:
        type: string
        description: >-
          The Git reference (branch, tag, commit, etc.) to use for deploy.
          Defaults to the selected branch/tag
        default: ""
        required: false

permissions:
  id-token: write # This is required for requesting the AWS IAM OIDC JWT
  contents: write # This is required for actions/checkout

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-tofuservices.yml
    with:
      service-type: PLATFORM
      env-or-account: ${{ inputs.account-type }}
      services: ${{ inputs.services }}
      per-service-vars-json: ${{ inputs.per-service-vars-json }}
      aws-region: ${{ inputs.aws-region }}
      skip-applies: ${{ inputs.skip-applies }}
      git-ref: ${{ inputs.git-ref }}
    secrets: inherit
