name: "Deploy Environment Services"
on:
  workflow_dispatch:
    inputs:
      bfd-env:
        description: The BFD environment to deploy services to
        required: true
      services:
        description: Comma-separated list of services to deploy
        default: >-
          config,
          bene-prefs,
          cluster,
          database,
          locust,
          migrator,
          ccw-pipeline,
          npi-pipeline,
          rda-pipeline,
          server,
          ccw-pipeline-metrics,
          rda-pipeline-metrics,
          server-metrics,
          ccw-pipeline-alarms,
          rda-pipeline-alarms,
          server-alarms
        required: true
      per-service-vars-json:
        description: >-
          Tofu plan variables per-service in JSON; see Workflow for format
        required: false
      aws-region:
        description: >-
          Override the AWS Region
        default: us-east-1
        type: choice
        options:
          - us-east-1
          - us-west-2
        required: true
      skip-applies:
        description: >-
          If true, skips the apply step for each Terraservice such that only the plans are generated
        default: false
        required: false
        type: boolean
      git-ref:
        description: >-
          The Git reference (branch, tag, commit, etc.) to use for deploy.
          Defaults to the selected branch/tag
        default: ""
        required: false
  workflow_call:
    inputs:
      bfd-env:
        type: string
        description: The BFD environment to deploy services to
        required: true
      services:
        type: string
        description: Comma-separated list of services to deploy
        default: >-
          config,
          bene-prefs,
          cluster,
          database,
          locust,
          migrator,
          ccw-pipeline,
          npi-pipeline,
          rda-pipeline,
          server,
          ccw-pipeline-metrics,
          rda-pipeline-metrics,
          server-metrics,
          ccw-pipeline-alarms,
          rda-pipeline-alarms,
          server-alarms
        required: false
      per-service-vars-json:
        type: string
        description: >-
          Tofu plan variables per-service in JSON; see Workflow for format
        required: false
      aws-region:
        type: string
        description: >-
          Override the AWS Region
        default: us-east-1
        required: false
      skip-applies:
        type: boolean
        description: >-
          If true, skips the apply step for each Terraservice such that only the plans are generated
        default: false
        required: false
      git-ref:
        type: string
        description: >-
          The Git reference (branch, tag, commit, etc.) to use for deploy.
          Defaults to the selected branch/tag
        default: ""
        required: false

permissions:
  id-token: write # This is required for requesting the AWS IAM OIDC JWT
  contents: write # This is required for actions/checkout

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-tofuservices.yml
    with:
      service-type: ENVIRONMENT
      env-or-account: ${{ inputs.bfd-env }}
      services: ${{ inputs.services }}
      per-service-vars-json: ${{ inputs.per-service-vars-json }}
      aws-region: ${{ inputs.aws-region }}
      skip-applies: ${{ inputs.skip-applies }}
      git-ref: ${{ inputs.git-ref }}
    secrets: inherit
