name: SonarQube
on: [push]
jobs:
  SonarQube:
    runs-on:
      - codebuild-bfd-mgmt-gha-sonarqube-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: curl https://sonarqube.cloud.cms.gov
